// Year 7 Mathematics Trivia Questions
// Based on UK Year 7 Maths Curriculum Framework (KS3)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_7_MATHS_QUESTIONS = [
  // NUMBER (40 questions)
  // Integers and place value
  { id: 'y7_math_1', question: 'What is -15 + 23?', options: ['8', '-8', '38', '-38'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_2', question: 'What is -7 - 9?', options: ['-16', '16', '-2', '2'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_3', question: 'What is -6 × -4?', options: ['-24', '24', '-10', '10'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_4', question: 'What is -20 ÷ 4?', options: ['-5', '5', '-16', '16'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_5', question: 'What is -3 × 5?', options: ['-15', '15', '-8', '8'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_6', question: 'Order from smallest: -8, 3, -2, 5, -10', options: ['-10, -8, -2, 3, 5', '-2, -8, -10, 3, 5', '5, 3, -2, -8, -10', '-10, -2, -8, 3, 5'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_7', question: 'What is the value of 2⁴?', options: ['6', '8', '16', '32'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_8', question: 'What is the value of 3³?', options: ['6', '9', '27', '81'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_9', question: 'What is √49?', options: ['6', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_10', question: 'What is √100?', options: ['5', '10', '50', '20'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Factors, multiples, primes
  { id: 'y7_math_11', question: 'What is the Highest Common Factor (HCF) of 24 and 36?', options: ['6', '12', '4', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_12', question: 'What is the Lowest Common Multiple (LCM) of 4 and 6?', options: ['12', '24', '8', '10'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_13', question: 'Is 29 a prime number?', options: ['Yes', 'No', 'Sometimes', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_14', question: 'What are the prime factors of 30?', options: ['2 × 3 × 5', '2 × 15', '3 × 10', '5 × 6'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_15', question: 'Express 60 as a product of prime factors:', options: ['2² × 3 × 5', '2 × 3² × 5', '2 × 3 × 10', '4 × 15'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },

  // Fractions, decimals, percentages
  { id: 'y7_math_16', question: 'Simplify 18/24:', options: ['2/3', '3/4', '9/12', '6/8'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_17', question: 'What is 3/5 + 1/4?', options: ['4/9', '17/20', '7/10', '13/20'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_18', question: 'What is 2/3 × 3/4?', options: ['1/2', '5/7', '6/12', '5/12'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_19', question: 'What is 1/2 ÷ 1/3?', options: ['1/6', '3/2', '2/3', '1/5'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_20', question: 'Convert 0.625 to a fraction:', options: ['5/8', '3/5', '2/3', '7/10'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_21', question: 'Convert 7/20 to a decimal:', options: ['0.35', '0.7', '0.35', '0.75'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_22', question: 'What is 15% of 200?', options: ['15', '20', '30', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_23', question: 'Increase ₦500 by 20%:', options: ['₦520', '₦600', '₦700', '₦100'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_24', question: 'Decrease ₦800 by 25%:', options: ['₦600', '₦700', '₦750', '₦200'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_25', question: 'Express 0.45 as a percentage:', options: ['4.5%', '45%', '450%', '0.45%'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Approximation and estimation
  { id: 'y7_math_26', question: 'Round 4.567 to 1 decimal place:', options: ['4.5', '4.6', '4.57', '5.0'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_27', question: 'Round 3,456 to the nearest 100:', options: ['3,400', '3,450', '3,500', '3,000'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_28', question: 'Estimate 49 × 21:', options: ['500', '1,000', '1,500', '2,000'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_29', question: 'Round 67.89 to 2 significant figures:', options: ['67', '68', '67.9', '70'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_30', question: 'Express 4,567 to 1 significant figure:', options: ['4', '4,000', '5,000', '4,500'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },

  // Standard form
  { id: 'y7_math_31', question: 'Write 3,000 in standard form:', options: ['3 × 10²', '3 × 10³', '30 × 10²', '0.3 × 10⁴'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_32', question: 'Write 0.005 in standard form:', options: ['5 × 10⁻²', '5 × 10⁻³', '5 × 10³', '0.5 × 10⁻²'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_33', question: 'What is 2.5 × 10⁴ in ordinary form?', options: ['250', '2,500', '25,000', '250,000'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_34', question: 'What is 3.2 × 10⁻² in ordinary form?', options: ['0.032', '0.32', '3.2', '32'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },

  // Sequences
  { id: 'y7_math_35', question: 'What is the next term: 3, 7, 11, 15, ___?', options: ['17', '18', '19', '20'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_36', question: 'What is the term-to-term rule: 2, 6, 18, 54?', options: ['Add 4', 'Multiply by 3', 'Add then multiply', 'Square'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_37', question: 'What is the nth term of: 5, 8, 11, 14?', options: ['3n + 2', '2n + 3', '5n', 'n + 5'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_38', question: 'Find the 10th term in sequence: 4, 7, 10, 13...', options: ['30', '31', '32', '33'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_39', question: 'What type of sequence: 1, 2, 4, 8, 16?', options: ['Arithmetic', 'Geometric', 'Fibonacci', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_40', question: 'What is the common difference in: 12, 17, 22, 27?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },

  // ALGEBRA (40 questions)
  { id: 'y7_math_41', question: 'Simplify: 5x + 3x', options: ['8x', '15x', '8x²', '5x + 3'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_42', question: 'Simplify: 7a - 2a', options: ['5', '5a', '9a', '5a²'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_43', question: 'Simplify: 4b × 3', options: ['7b', '12b', '4b + 3', '12b²'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_44', question: 'Expand: 3(x + 5)', options: ['3x + 5', '3x + 15', 'x + 15', '3x + 8'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_45', question: 'Expand: 4(2x - 3)', options: ['8x - 12', '8x - 3', '6x - 7', '8x + 12'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_46', question: 'Solve: x + 7 = 15', options: ['x = 7', 'x = 8', 'x = 22', 'x = 15'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_47', question: 'Solve: 3x = 21', options: ['x = 6', 'x = 7', 'x = 18', 'x = 24'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_48', question: 'Solve: x - 5 = 12', options: ['x = 7', 'x = 17', 'x = 60', 'x = 2.4'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_49', question: 'Solve: x/4 = 6', options: ['x = 2', 'x = 10', 'x = 24', 'x = 1.5'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_50', question: 'Solve: 2x + 3 = 11', options: ['x = 4', 'x = 7', 'x = 14', 'x = 5'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_51', question: 'Solve: 5x - 7 = 18', options: ['x = 3', 'x = 4', 'x = 5', 'x = 11'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_52', question: 'Solve: 3(x + 2) = 15', options: ['x = 3', 'x = 5', 'x = 7', 'x = 9'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_53', question: 'If n = 4, find 3n + 5:', options: ['12', '14', '17', '20'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_54', question: 'If a = 6, find 2a - 3:', options: ['6', '9', '12', '15'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_55', question: 'Simplify: 2x + 3y + 4x - y', options: ['6x + 2y', '6x + 4y', '5x + 2y', '6xy'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_56', question: 'Simplify: 5a + 2b - 3a + 4b', options: ['2a + 6b', '8a + 6b', '2a + 2b', '8ab'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_57', question: 'Expand and simplify: 2(x + 3) + 4', options: ['2x + 7', '2x + 10', '2x + 6', '6x + 4'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_58', question: 'Factorise: 6x + 9', options: ['3(2x + 3)', '2(3x + 9)', '3(2x + 9)', '6(x + 9)'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_59', question: 'Factorise: 4x + 12', options: ['2(2x + 6)', '4(x + 3)', '4(x + 12)', '2(2x + 12)'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_60', question: 'What is 5² - 3²?', options: ['4', '8', '16', '25'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_61', question: 'Simplify: x × x', options: ['2x', 'x²', 'x + x', 'x/2'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_62', question: 'Simplify: 3x × 2x', options: ['5x', '6x', '5x²', '6x²'], correctAnswer: 3, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_63', question: 'Simplify: x⁴ ÷ x²', options: ['x²', 'x⁶', 'x', 'x³'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_64', question: 'What is (x³)²?', options: ['x⁵', 'x⁶', 'x⁹', '2x³'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_65', question: 'Write an expression for: 5 more than x', options: ['5x', 'x + 5', 'x - 5', '5 - x'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_66', question: 'Write an expression for: the product of 3 and y', options: ['3 + y', '3y', 'y/3', 'y - 3'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_67', question: 'Form an equation: A number doubled plus 5 equals 17', options: ['2x + 5 = 17', 'x + 5 = 17', '2(x + 5) = 17', 'x/2 + 5 = 17'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_68', question: 'Solve: 4x + 5 = 3x + 9', options: ['x = 2', 'x = 4', 'x = 6', 'x = 14'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_69', question: 'Solve: 5x - 3 = 2x + 9', options: ['x = 2', 'x = 3', 'x = 4', 'x = 6'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_70', question: 'Substitute a = 3 into 2a² + 1:', options: ['13', '17', '19', '37'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_71', question: 'Simplify: 3a + 4b - a + 2b', options: ['2a + 6b', '4a + 6b', '3ab + 6', '2a + 2b'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_72', question: 'Expand: 5(2x - 1)', options: ['10x - 1', '10x - 5', '7x - 4', '10x + 5'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_73', question: 'Factorise: 3x + 6y', options: ['3(x + 2y)', 'x(3 + 6y)', '3(x + 6y)', '6(x + y)'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_74', question: 'Solve: 2(x + 3) = 14', options: ['x = 4', 'x = 5', 'x = 7', 'x = 8'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_75', question: 'If y = 5, find y² - 2y:', options: ['10', '15', '20', '25'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_76', question: 'Simplify: 4x² + 3x²', options: ['7x²', '7x⁴', '12x²', '12x⁴'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_77', question: 'What is x⁰?', options: ['0', '1', 'x', 'undefined'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_78', question: 'Solve: x/3 + 2 = 5', options: ['x = 3', 'x = 6', 'x = 9', 'x = 15'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_79', question: 'Form equation: Triple a number minus 4 equals 11', options: ['3x - 4 = 11', 'x/3 - 4 = 11', '3(x - 4) = 11', 'x - 4 = 11'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_80', question: 'Expand: -2(x - 3)', options: ['-2x - 6', '-2x + 6', '2x - 6', '-2x - 3'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // RATIO & PROPORTION (20 questions)
  { id: 'y7_math_81', question: 'Simplify ratio 15:20', options: ['3:4', '5:10', '1:2', '15:20'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_82', question: 'Share ₦120 in ratio 2:3. Larger share?', options: ['₦48', '₦60', '₦72', '₦80'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_83', question: 'Ratio of boys:girls is 3:5. There are 15 boys. How many girls?', options: ['20', '25', '30', '35'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_84', question: 'Express 2:5 as a fraction:', options: ['2/5', '5/2', '2/7', '5/7'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_85', question: 'If 4:6 = x:15, find x:', options: ['8', '10', '12', '18'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_86', question: '5 pens cost ₦250. Cost of 8 pens?', options: ['₦350', '₦400', '₦450', '₦500'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_87', question: 'Map scale 1:50,000. 4cm represents?', options: ['2km', '2.5km', '3km', '4km'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_88', question: 'Divide ₦300 in ratio 1:2:3. Smallest share?', options: ['₦50', '₦75', '₦100', '₦150'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_89', question: 'Simplify 12:18:24', options: ['2:3:4', '4:6:8', '3:6:9', '6:9:12'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_90', question: 'Recipe for 4: 200g flour. For 10 people?', options: ['400g', '500g', '600g', '800g'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_91', question: 'Best buy: 500ml for ₦200 or 750ml for ₦285?', options: ['500ml', '750ml', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_92', question: 'Write ratio 0.5:2 in simplest form:', options: ['1:4', '1:2', '5:20', '0.5:2'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_93', question: 'If a:b = 2:3 and b:c = 4:5, find a:b:c:', options: ['2:3:5', '8:12:15', '2:4:5', '6:12:15'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_94', question: 'Speed = distance ÷ time. Find speed: 100km in 2 hours', options: ['50 km/h', '100 km/h', '200 km/h', '25 km/h'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_95', question: 'Distance = speed × time. Find distance: 60 km/h for 3 hours', options: ['20km', '63km', '180km', '240km'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_96', question: 'Density = mass ÷ volume. Find mass: density 8g/cm³, volume 5cm³', options: ['1.6g', '13g', '40g', '3g'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_97', question: '3 workers take 10 days. How long for 5 workers (same work)?', options: ['4 days', '6 days', '8 days', '16 days'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_98', question: 'Convert 2.5m to cm:', options: ['25cm', '250cm', '2,500cm', '0.025cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_99', question: 'Convert 3.2kg to g:', options: ['32g', '320g', '3,200g', '32,000g'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_100', question: 'Currency: £1 = ₦950. Convert £5 to Naira:', options: ['₦4,500', '₦4,750', '₦4,950', '₦5,000'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // GEOMETRY & MEASURES (50 questions)
  { id: 'y7_math_101', question: 'Angles in a triangle add to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_102', question: 'Angles in a quadrilateral add to:', options: ['180°', '270°', '360°', '540°'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_103', question: 'Angles on a straight line add to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_104', question: 'Angles around a point add to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 3, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_105', question: 'Two angles in triangle: 60° and 70°. Find third:', options: ['40°', '50°', '60°', '70°'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_106', question: 'Angles on straight line: one is 115°. Find other:', options: ['65°', '75°', '85°', '115°'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_107', question: 'What are vertically opposite angles?', options: ['Different', 'Equal', 'Add to 90°', 'Add to 180°'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_108', question: 'Alternate angles on parallel lines are:', options: ['Different', 'Equal', 'Add to 90°', 'Add to 180°'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_109', question: 'Corresponding angles on parallel lines are:', options: ['Different', 'Equal', 'Add to 90°', 'Add to 180°'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_110', question: 'Co-interior angles on parallel lines add to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_111', question: 'An equilateral triangle has angles:', options: ['All different', 'All 60°', 'All 90°', 'Two equal'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_112', question: 'An isosceles triangle has:', options: ['No equal sides', 'Two equal sides', 'Three equal sides', 'All different angles'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_113', question: 'Sum of interior angles of pentagon:', options: ['360°', '450°', '540°', '720°'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_114', question: 'Sum of interior angles of hexagon:', options: ['540°', '720°', '900°', '1080°'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_115', question: 'Each interior angle of regular hexagon:', options: ['108°', '120°', '135°', '150°'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_116', question: 'Perimeter of rectangle: length 12cm, width 8cm', options: ['20cm', '40cm', '96cm', '48cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_117', question: 'Area of rectangle: length 15m, width 9m', options: ['24m²', '48m²', '135m²', '270m²'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_118', question: 'Area of triangle = ½ × base × height. Base 10cm, height 8cm:', options: ['18cm²', '40cm²', '80cm²', '160cm²'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_119', question: 'Circumference = 2πr. Find C when r = 7cm (π ≈ 3.14):', options: ['22cm', '44cm', '154cm', '88cm'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_120', question: 'Area of circle = πr². Find A when r = 5cm (π ≈ 3.14):', options: ['15.7cm²', '31.4cm²', '78.5cm²', '157cm²'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_121', question: 'Area of parallelogram = base × height. Base 10cm, height 6cm:', options: ['16cm²', '32cm²', '60cm²', '120cm²'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_122', question: 'Area of trapezium = ½(a+b)h. a=8, b=12, h=5:', options: ['50cm²', '100cm²', '200cm²', '25cm²'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_123', question: 'Volume of cuboid: length 5cm, width 3cm, height 4cm', options: ['12cm³', '24cm³', '60cm³', '120cm³'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_124', question: 'Volume of cube with sides 4cm:', options: ['16cm³', '24cm³', '48cm³', '64cm³'], correctAnswer: 3, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_125', question: 'Surface area of cube with sides 3cm:', options: ['9cm²', '18cm²', '27cm²', '54cm²'], correctAnswer: 3, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_126', question: 'What is π (pi) approximately?', options: ['3.12', '3.14', '3.16', '3.18'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_127', question: 'Diameter = 2 × radius. Find d when r = 9cm:', options: ['4.5cm', '18cm', '27cm', '36cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_128', question: 'What is a prism?', options: ['3D shape with constant cross-section', 'Any 3D shape', 'Only triangular', 'Only rectangular'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_129', question: 'Volume of prism = cross-sectional area × length. Area 20cm², length 5cm:', options: ['25cm³', '100cm³', '200cm³', '400cm³'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_130', question: 'A regular polygon has:', options: ['No equal sides', 'All sides and angles equal', 'Two equal sides', 'Random angles'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_131', question: 'Convert 2.5 hours to minutes:', options: ['120 mins', '130 mins', '150 mins', '160 mins'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_132', question: 'Convert 3 days to hours:', options: ['48 hours', '60 hours', '72 hours', '84 hours'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_133', question: 'Film starts 14:35, lasts 2h 40min. End time?', options: ['16:75', '17:05', '17:15', '17:25'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_134', question: 'Time from 08:45 to 15:20:', options: ['6h 15min', '6h 35min', '7h 15min', '7h 35min'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_135', question: 'What is a net?', options: ['3D shape', '2D pattern folding to 3D', 'Measurement', 'Angle'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_136', question: 'Cube has how many faces?', options: ['4', '6', '8', '12'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_137', question: 'Cube has how many vertices?', options: ['4', '6', '8', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_138', question: 'Cube has how many edges?', options: ['6', '8', '10', '12'], correctAnswer: 3, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_139', question: 'A cuboid is:', options: ['A cube only', 'A rectangular 3D box', 'A cylinder', 'A sphere'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_140', question: 'Pythagoras: a² + b² = c². Find c when a=3, b=4:', options: ['5', '7', '25', '√7'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_141', question: 'What type of triangle has one 90° angle?', options: ['Equilateral', 'Isosceles', 'Right-angled', 'Scalene'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_142', question: 'Lines that never meet are:', options: ['Perpendicular', 'Parallel', 'Intersecting', 'Vertical'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_143', question: 'Lines meeting at 90° are:', options: ['Parallel', 'Perpendicular', 'Alternate', 'Corresponding'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_144', question: 'Convert 5km to metres:', options: ['50m', '500m', '5,000m', '50,000m'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_145', question: 'Convert 1.5L to ml:', options: ['15ml', '150ml', '1,500ml', '15,000ml'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_146', question: 'Convert 2.8kg to g:', options: ['28g', '280g', '2,800g', '28,000g'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_147', question: 'Reflection creates:', options: ['Different shape', 'Mirror image', 'Rotation', 'Enlargement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_148', question: 'Translation means:', options: ['Flipping', 'Sliding', 'Turning', 'Enlarging'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_149', question: 'Rotation turns shape around:', options: ['A line', 'A point', 'An edge', 'A face'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_150', question: 'Coordinates (5, -3): x-coordinate is:', options: ['-3', '5', '2', '-2'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // STATISTICS & PROBABILITY (30 questions)
  { id: 'y7_math_151', question: 'Mean of 4, 6, 8, 10, 12:', options: ['6', '7', '8', '10'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_152', question: 'Median of 3, 7, 9, 11, 15:', options: ['7', '9', '11', '8'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_153', question: 'Mode of 2, 5, 5, 7, 8, 5, 10:', options: ['2', '5', '7', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_154', question: 'Range of 12, 18, 25, 30, 33:', options: ['18', '21', '25', '33'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_155', question: 'Mean of 10, 20, 30:', options: ['15', '20', '25', '30'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_156', question: 'Find median of 2, 5, 8, 12:', options: ['5', '6.5', '7', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_157', question: 'What type of average is most affected by outliers?', options: ['Mean', 'Median', 'Mode', 'Range'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_158', question: 'Bar chart is best for:', options: ['Continuous data', 'Comparing categories', 'Showing proportions', 'Time series'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_159', question: 'Line graph is best for:', options: ['Categories', 'Data over time', 'One value', 'Proportions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_160', question: 'Pie chart shows:', options: ['Time', 'Proportions of whole', 'Frequency', 'Correlation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_161', question: 'Probability of certain event:', options: ['0', '0.5', '1', '2'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_162', question: 'Probability of impossible event:', options: ['0', '0.5', '1', '-1'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_163', question: 'Probability is between:', options: ['0 and 1', '0 and 10', '1 and 10', '-1 and 1'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_164', question: 'Fair coin toss: P(heads) =', options: ['0', '0.5', '1', '0.25'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_165', question: 'Fair dice: P(rolling 3) =', options: ['1/2', '1/3', '1/6', '1/12'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_166', question: 'Bag has 3 red, 7 blue balls. P(red) =', options: ['3/10', '3/7', '7/10', '1/2'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_167', question: 'If P(event) = 0.3, P(not event) =', options: ['0.3', '0.5', '0.7', '1'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_168', question: 'Sum of all probabilities:', options: ['0', '0.5', '1', '10'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_169', question: 'Experimental probability uses:', options: ['Theory', 'Actual results', 'Guesses', 'Formula only'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_170', question: 'Theoretical probability uses:', options: ['Experiments', 'Logic and equally likely outcomes', 'Past results', 'Random guesses'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_171', question: 'What is frequency?', options: ['Probability', 'How many times something happens', 'Average', 'Range'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_172', question: 'Relative frequency = frequency ÷', options: ['Total', 'Mean', 'Mode', 'Range'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_173', question: 'Dice rolled 60 times, 6 appears 12 times. Relative frequency:', options: ['1/6', '1/5', '1/4', '1/12'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_174', question: 'Sample space is:', options: ['One outcome', 'All possible outcomes', 'Most likely outcome', 'Average'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_175', question: 'Spinner with 4 equal sections: P(any section) =', options: ['1/2', '1/4', '1/8', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_176', question: 'What is an outlier?', options: ['Normal value', 'Value far from others', 'The mode', 'The mean'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_177', question: 'Scatter graph shows:', options: ['One variable', 'Relationship between two variables', 'Categories', 'Probability'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_178', question: 'Positive correlation means:', options: ['No pattern', 'As one increases, other increases', 'As one increases, other decreases', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_179', question: 'Negative correlation means:', options: ['No pattern', 'As one increases, other decreases', 'As one increases, other increases', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_180', question: 'No correlation means:', options: ['Strong pattern', 'No clear relationship', 'Perfect match', 'Always increasing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // PROBLEM SOLVING & REASONING (20 questions)
  { id: 'y7_math_181', question: 'Bus fare ₦450 each way. Return journey for 2 people?', options: ['₦900', '₦1,350', '₦1,800', '₦2,250'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_182', question: 'Rectangle area 48cm², length 8cm. Width?', options: ['4cm', '5cm', '6cm', '7cm'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_183', question: 'Train travels 180km in 3 hours. Speed?', options: ['50 km/h', '60 km/h', '90 km/h', '540 km/h'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_184', question: 'Class of 30: 40% are boys. How many girls?', options: ['12', '15', '18', '20'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_185', question: 'Book costs ₦2,400. 15% discount. Final price?', options: ['₦2,040', '₦2,100', '₦2,160', '₦360'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_186', question: 'Multi-step: Buy 4 books at ₦350 each, get ₦200 off total. Pay?', options: ['₦1,200', '₦1,400', '₦1,600', '₦1,800'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_187', question: 'Pattern: 2, 6, 12, 20, 30... What comes next?', options: ['38', '40', '42', '44'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_188', question: 'Perimeter of square is 36cm. Side length?', options: ['6cm', '9cm', '12cm', '18cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_189', question: 'Tank holds 150L. 2/5 full. How much water?', options: ['50L', '60L', '75L', '90L'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_190', question: 'Number thought of, doubled, add 5, result 23. Number?', options: ['7', '9', '11', '14'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_191', question: 'Phone costs ₦45,000. Pay 30% deposit. Deposit amount?', options: ['₦10,500', '₦13,500', '₦15,000', '₦31,500'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_192', question: 'Temperature at 8am: -3°C. Rises 12°C by noon. Noon temperature?', options: ['-15°C', '-9°C', '9°C', '15°C'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_193', question: 'Cinema: 8 rows, 15 seats per row. Total seats?', options: ['23', '60', '120', '240'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_194', question: 'Journey: 45 min by car, 2h 15min by bus. How much longer by bus?', options: ['1h 30min', '1h 45min', '2h 15min', '3h'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_195', question: 'If 1€ = ₦850, convert €10 to Naira:', options: ['₦8,000', '₦8,500', '₦9,000', '₦9,500'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_196', question: 'School day: 8:30am-3:15pm with 1h lunch. Teaching time?', options: ['5h 45min', '6h 15min', '6h 45min', '7h 15min'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_197', question: 'Pattern: 1, 4, 9, 16, 25... These are:', options: ['Even numbers', 'Square numbers', 'Prime numbers', 'Multiples of 3'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_math_198', question: 'Sharing: Dad gets twice what son gets. Total ₦900. Son gets?', options: ['₦300', '₦450', '₦600', '₦200'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_math_199', question: 'Shop: 20% profit on ₦5,000 cost. Selling price?', options: ['₦5,200', '₦5,500', '₦6,000', '₦7,000'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_math_200', question: 'Two consecutive numbers sum to 35. Larger number?', options: ['17', '18', '19', '20'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 }
];
