// Year 8 Science Trivia Questions
// Based on UK Year 8 Science Curriculum Framework (KS3)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_8_SCIENCE_QUESTIONS = [
  // ORGANISMS & HEALTH (40 questions)
  // Body systems and health
  { id: 'y8_sci_1', question: 'What is the function of red blood cells?', options: ['Fight infection', 'Transport oxygen', 'Clot blood', 'Make hormones'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_2', question: 'What is the function of white blood cells?', options: ['Transport oxygen', 'Fight infection and disease', 'Clot blood', 'Transport food'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_3', question: 'What is the function of platelets?', options: ['Transport oxygen', 'Fight infection', 'Help blood clot', 'Transport food'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_4', question: 'Plasma is:', options: ['A cell', 'Liquid part of blood', 'An organ', 'A bone'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_5', question: 'What connects muscles to bones?', options: ['Cartilage', 'Ligaments', 'Tendons', 'Nerves'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_6', question: 'What connects bones to bones?', options: ['Cartilage', 'Ligaments', 'Tendons', 'Muscles'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_7', question: 'What is cartilage?', options: ['Hard bone', 'Flexible connective tissue', 'Muscle', 'Nerve'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_8', question: 'What is a joint?', options: ['Bone end', 'Where two bones meet', 'Muscle', 'Tendon'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_9', question: 'What is respiration?', options: ['Breathing', 'Process of releasing energy from food', 'Eating', 'Circulation'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_10', question: 'Aerobic respiration needs:', options: ['No oxygen', 'Oxygen', 'Only food', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_11', question: 'Aerobic respiration equation:', options: ['Food → Energy', 'Glucose + Oxygen → CO₂ + Water + Energy', 'Oxygen → Energy', 'Food + Water → Energy'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_12', question: 'Anaerobic respiration occurs:', options: ['With lots of oxygen', 'Without oxygen', 'Only in plants', 'Never'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_13', question: 'What is the diaphragm?', options: ['Lung', 'Muscle below lungs for breathing', 'Rib', 'Windpipe'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_14', question: 'Trachea is:', options: ['Lung', 'Windpipe', 'Diaphragm', 'Heart'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_15', question: 'Bronchi are:', options: ['Air sacs', 'Tubes branching from trachea', 'Muscles', 'Blood vessels'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_16', question: 'Alveoli are:', options: ['Tubes', 'Tiny air sacs for gas exchange', 'Muscles', 'Bones'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_17', question: 'Gas exchange in lungs:', options: ['No exchange', 'O₂ in, CO₂ out', 'Only O₂', 'Only CO₂'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_18', question: 'What is digestion?', options: ['Breathing', 'Breaking down food', 'Circulation', 'Growth'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_19', question: 'Enzymes are:', options: ['Foods', 'Biological catalysts', 'Vitamins', 'Minerals'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_20', question: 'Amylase breaks down:', options: ['Protein', 'Fats', 'Carbohydrates', 'Vitamins'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_21', question: 'Protease breaks down:', options: ['Protein', 'Fats', 'Carbohydrates', 'Sugars'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_22', question: 'Lipase breaks down:', options: ['Protein', 'Fats/lipids', 'Carbohydrates', 'Sugars'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_23', question: 'Small intestine function:', options: ['Stores bile', 'Absorbs nutrients', 'Produces enzymes only', 'Stores waste'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_24', question: 'Large intestine function:', options: ['Absorbs nutrients', 'Absorbs water', 'Produces bile', 'Breaks down protein'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_25', question: 'Stomach produces:', options: ['Bile', 'Acid and enzymes', 'Only water', 'Saliva'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_26', question: 'What is photosynthesis?', options: ['Plant respiration', 'Plant making food using light', 'Plant reproduction', 'Plant movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_27', question: 'Photosynthesis equation:', options: ['CO₂ + H₂O → Glucose + O₂', 'Glucose → Energy', 'O₂ → CO₂', 'H₂O → O₂'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_28', question: 'Chlorophyll:', options: ['Is yellow', 'Green pigment absorbing light', 'Is red', 'Produces oxygen only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_29', question: 'Photosynthesis occurs in:', options: ['Roots', 'Chloroplasts', 'Nucleus', 'Mitochondria'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_30', question: 'Factors affecting photosynthesis:', options: ['Only light', 'Light, CO₂, temperature, water', 'Only CO₂', 'Only temperature'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_31', question: 'What do plants need water for?', options: ['Nothing', 'Photosynthesis, transport, support', 'Only photosynthesis', 'Only transport'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_32', question: 'Stomata are:', options: ['Roots', 'Pores for gas exchange', 'Flowers', 'Seeds'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_33', question: 'Transpiration is:', options: ['Photosynthesis', 'Water loss from leaves', 'Respiration', 'Growth'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_34', question: 'Xylem transports:', options: ['Food', 'Water and minerals up', 'Only minerals', 'Oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_35', question: 'Phloem transports:', options: ['Water', 'Food/sugars', 'Only oxygen', 'Only CO₂'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_36', question: 'What are drug classes?', options: ['Only medicine', 'Stimulants, depressants, hallucinogens', 'Only illegal', 'Food groups'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_37', question: 'Alcohol is a:', options: ['Stimulant', 'Depressant', 'Hallucinogen', 'Vitamin'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_38', question: 'Caffeine is a:', options: ['Stimulant', 'Depressant', 'Hallucinogen', 'Sedative'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_39', question: 'Balanced diet includes:', options: ['Only protein', 'Carbs, protein, fats, vitamins, minerals', 'Only carbs', 'Only vitamins'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_40', question: 'What are pathogens?', options: ['Nutrients', 'Disease-causing microorganisms', 'Vitamins', 'Cells'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // CHEMICAL REACTIONS & MATERIALS (40 questions)
  { id: 'y8_sci_41', question: 'What is a chemical reaction?', options: ['Physical change', 'New substances formed', 'No change', 'Only mixing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_42', question: 'Signs of chemical reaction:', options: ['No change', 'Color change, gas, heat, precipitate', 'Only mixing', 'Dissolving'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_43', question: 'Exothermic reaction:', options: ['Takes in heat', 'Gives out heat', 'No heat change', 'Absorbs light'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_44', question: 'Endothermic reaction:', options: ['Gives out heat', 'Takes in heat', 'No heat change', 'Gives out light'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_45', question: 'Combustion is:', options: ['Cooling', 'Burning (reaction with oxygen)', 'Freezing', 'Condensing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_46', question: 'Complete combustion of hydrocarbons produces:', options: ['CO + H₂O', 'CO₂ + H₂O', 'Only CO₂', 'Only smoke'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_47', question: 'Incomplete combustion produces:', options: ['CO₂ + H₂O', 'CO + H₂O + C (soot)', 'Only O₂', 'No products'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_48', question: 'Oxidation is:', options: ['Losing oxygen', 'Gaining oxygen', 'No change', 'Reduction'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_49', question: 'Reduction is:', options: ['Gaining oxygen', 'Losing oxygen', 'Oxidation', 'No change'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_50', question: 'Thermal decomposition:', options: ['Joining', 'Breaking down with heat', 'Mixing', 'Dissolving'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_51', question: 'What is a catalyst?', options: ['Slows reaction', 'Speeds reaction without being used up', 'Is reactant', 'Is product'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_52', question: 'Reactivity series orders metals by:', options: ['Size', 'How reactive they are', 'Color', 'Weight'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_53', question: 'More reactive metal displaces:', options: ['Nothing', 'Less reactive metal from compound', 'More reactive', 'All metals'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_54', question: 'Metal + Acid →', options: ['Salt + water', 'Salt + hydrogen', 'Only salt', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_55', question: 'Metal + Oxygen →', options: ['Salt', 'Metal oxide', 'Hydroxide', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_56', question: 'Acid + Alkali →', options: ['Salt + hydrogen', 'Salt + water', 'Only salt', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_57', question: 'Acid + Carbonate →', options: ['Salt + water', 'Salt + water + CO₂', 'Only CO₂', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_58', question: 'pH 1-3:', options: ['Weak acid', 'Strong acid', 'Neutral', 'Alkali'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_59', question: 'pH 4-6:', options: ['Strong acid', 'Weak acid', 'Neutral', 'Alkali'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_60', question: 'pH 11-14:', options: ['Acid', 'Neutral', 'Strong alkali', 'Weak alkali'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_61', question: 'Neutralisation:', options: ['Making acid', 'Acid + alkali → salt + water', 'Making alkali', 'Combustion'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_62', question: 'What is corrosion?', options: ['Strengthening', 'Metal reacting with oxygen/water', 'Painting', 'Cleaning'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_63', question: 'Rusting needs:', options: ['Only water', 'Iron, oxygen, water', 'Only oxygen', 'Only iron'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_64', question: 'Prevent rusting by:', options: ['Adding water', 'Painting, oiling, galvanizing', 'Heating', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_65', question: 'Conservation of mass:', options: ['Mass changes', 'Mass is conserved in reactions', 'Mass increases', 'Mass decreases'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_66', question: 'In sealed reaction, mass:', options: ['Increases', 'Stays same', 'Decreases', 'Varies'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_67', question: 'Word equation shows:', options: ['Nothing', 'Reactants → Products', 'Only reactants', 'Only products'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_68', question: 'Chemical equation uses:', options: ['Words only', 'Formulas and symbols', 'Pictures', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_69', question: 'Balanced equation has:', options: ['Random atoms', 'Same atoms each side', 'More reactants', 'More products'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_70', question: 'Physical change:', options: ['New substance', 'No new substance, reversible', 'Irreversible', 'Chemical'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_71', question: 'Chemical change:', options: ['Reversible easily', 'New substances, often irreversible', 'No change', 'Physical only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_72', question: 'What is a polymer?', options: ['Small molecule', 'Large molecule made of repeating units', 'Element', 'Compound'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_73', question: 'Examples of polymers:', options: ['Iron, copper', 'Plastics, proteins', 'Oxygen, nitrogen', 'Water, salt'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_74', question: 'Metals are:', options: ['Non-conductors', 'Good conductors of heat and electricity', 'Brittle', 'Transparent'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_75', question: 'Non-metals are:', options: ['Conductors', 'Poor conductors, often brittle', 'Shiny', 'Malleable'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_76', question: 'Alloy is:', options: ['Pure metal', 'Mixture of metals', 'Non-metal', 'Element'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_77', question: 'Steel is alloy of:', options: ['Only iron', 'Iron and carbon', 'Only carbon', 'Copper and zinc'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_78', question: 'Brass is alloy of:', options: ['Iron and carbon', 'Copper and zinc', 'Iron and zinc', 'Copper and iron'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_79', question: 'Why make alloys?', options: ['No reason', 'Improve properties', 'Make weaker', 'Make heavier'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_80', question: 'Rate of reaction increased by:', options: ['Cooling', 'Temperature, concentration, surface area, catalyst', 'Diluting', 'Removing catalyst'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // ENERGY & FORCES (60 questions)
  { id: 'y8_sci_81', question: 'Energy stores include:', options: ['Only kinetic', 'Kinetic, potential, chemical, thermal, etc', 'Only heat', 'Only light'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_82', question: 'Kinetic energy is:', options: ['Stored energy', 'Energy of movement', 'Chemical', 'Nuclear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_83', question: 'Gravitational potential energy depends on:', options: ['Speed', 'Mass and height', 'Temperature', 'Color'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_84', question: 'Elastic potential energy is:', options: ['Movement', 'Stored in stretched/compressed objects', 'Heat', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_85', question: 'Chemical energy stored in:', options: ['Height', 'Food, fuels, batteries', 'Motion', 'Sound'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_86', question: 'Energy cannot be:', options: ['Transferred', 'Created or destroyed', 'Stored', 'Changed'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_87', question: 'Energy is measured in:', options: ['Watts', 'Joules', 'Newtons', 'Meters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_88', question: 'Power is measured in:', options: ['Joules', 'Watts', 'Newtons', 'Meters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_89', question: 'Power = energy ÷ ___:', options: ['Mass', 'Time', 'Distance', 'Force'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_90', question: 'Conduction:', options: ['Heat through liquid', 'Heat through solid by particles', 'Heat by waves', 'No transfer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_91', question: 'Convection:', options: ['Heat through solid', 'Heat through fluids by circulation', 'Heat by waves', 'No transfer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_92', question: 'Radiation:', options: ['Heat through solid', 'Heat by waves, no medium needed', 'Only through liquid', 'No transfer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_93', question: 'Vacuum is:', options: ['Full of air', 'Empty space', 'Only liquid', 'Only solid'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_94', question: 'Heat can travel through vacuum by:', options: ['Conduction', 'Convection', 'Radiation', 'Cannot'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_95', question: 'Good conductors:', options: ['Wood, plastic', 'Metals', 'Air', 'Vacuum'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_96', question: 'Good insulators:', options: ['Metals', 'Wood, plastic, air', 'Only copper', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_97', question: 'Dark surfaces:', options: ['Reflect heat', 'Absorb and emit heat well', 'Are cold', 'Insulate'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_98', question: 'Shiny surfaces:', options: ['Absorb heat well', 'Reflect heat well', 'Are hot', 'Conduct poorly'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_99', question: 'Work done = force × ___:', options: ['Time', 'Distance', 'Mass', 'Energy'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_100', question: 'Work is measured in:', options: ['Watts', 'Joules', 'Newtons', 'Meters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_101', question: 'Force measured in:', options: ['Joules', 'Watts', 'Newtons', 'Meters'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_102', question: 'Balanced forces:', options: ['Object accelerates', 'Object stays at rest or constant speed', 'Object stops', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_103', question: 'Unbalanced forces:', options: ['No change', 'Object accelerates/decelerates', 'Object steady', 'No movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_104', question: 'Gravity:', options: ['Pushes objects apart', 'Pulls objects towards Earth', 'Only affects big objects', 'Is magnetic'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_105', question: 'Weight = mass × ___:', options: ['Speed', 'Gravitational field strength', 'Distance', 'Time'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_106', question: 'Mass is:', options: ['Force', 'Amount of matter', 'Weight', 'Energy'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_107', question: 'Weight is:', options: ['Amount of matter', 'Force of gravity', 'Volume', 'Distance'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_108', question: 'Mass measured in:', options: ['Newtons', 'Kilograms', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_109', question: 'Weight measured in:', options: ['Kilograms', 'Newtons', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_110', question: 'Friction:', options: ['Helps movement', 'Opposes movement', 'Is gravity', 'Is weight'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_111', question: 'Air resistance is:', options: ['Gravity', 'Friction from air', 'Magnetism', 'Weight'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_112', question: 'Streamlined shapes:', options: ['Increase air resistance', 'Reduce air resistance', 'Have no effect', 'Stop movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_113', question: 'Speed = distance ÷ ___:', options: ['Mass', 'Time', 'Force', 'Energy'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_114', question: 'Velocity includes:', options: ['Only speed', 'Speed and direction', 'Only direction', 'Only distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_115', question: 'Acceleration is:', options: ['Constant speed', 'Change in velocity', 'No change', 'Distance'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_116', question: 'Distance-time graph: horizontal line means:', options: ['Moving', 'Stationary', 'Accelerating', 'Slowing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_117', question: 'Distance-time graph: gradient shows:', options: ['Distance', 'Speed', 'Time', 'Mass'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_118', question: 'Steeper gradient on distance-time graph:', options: ['Slower', 'Faster', 'Stopped', 'Backwards'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_119', question: 'Pressure = force ÷ ___:', options: ['Distance', 'Area', 'Mass', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_120', question: 'Pressure measured in:', options: ['Newtons', 'Pascals', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_121', question: 'Smaller area means:', options: ['Less pressure', 'More pressure', 'Same pressure', 'No pressure'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_122', question: 'Atmospheric pressure caused by:', options: ['Nothing', 'Weight of air', 'Wind', 'Temperature'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_123', question: 'Pressure in liquids:', options: ['Stays same', 'Increases with depth', 'Decreases with depth', 'Is zero'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_124', question: 'Turning effect of force:', options: ['Pressure', 'Moment', 'Weight', 'Friction'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_125', question: 'Moment = force × ___:', options: ['Area', 'Distance from pivot', 'Time', 'Mass'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_126', question: 'Balanced moments:', options: ['Turn', 'No turning/equilibrium', 'Accelerate', 'Fall'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_127', question: 'Lever:', options: ['Is complex', 'Simple machine using pivot', 'Has no pivot', 'Cannot turn'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_128', question: 'Principle of moments:', options: ['Random', 'Clockwise moments = anticlockwise moments', 'All clockwise', 'All anticlockwise'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_129', question: 'Centre of mass is:', options: ['Top of object', 'Point where mass is concentrated', 'Bottom', 'Edge'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_130', question: 'Stable object has centre of mass:', options: ['High', 'Low and over base', 'Outside base', 'At top'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_131', question: 'Newton\'s First Law:', options: ['F = ma', 'Object stays at rest or constant velocity unless acted on', 'Action = reaction', 'E = mc²'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_132', question: 'Newton\'s Second Law:', options: ['Object stays at rest', 'F = ma (force = mass × acceleration)', 'Action = reaction', 'E = mc²'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_133', question: 'Newton\'s Third Law:', options: ['F = ma', 'Objects stay at rest', 'Every action has equal opposite reaction', 'E = mc²'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_134', question: 'When you push wall, wall:', options: ['Doesn\'t push back', 'Pushes back equally', 'Pushes more', 'Pushes less'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_135', question: 'Stopping distance = reaction distance + ___:', options: ['Speed distance', 'Braking distance', 'Starting distance', 'Thinking time'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_136', question: 'Reaction time affected by:', options: ['Nothing', 'Tiredness, drugs, distractions', 'Weather only', 'Road only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_137', question: 'Braking distance affected by:', options: ['Only speed', 'Speed, road conditions, brakes, tyres', 'Nothing', 'Only weather'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_138', question: 'Elastic deformation:', options: ['Permanent', 'Returns to original shape', 'Breaks', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_139', question: 'Plastic deformation:', options: ['Returns to shape', 'Permanent deformation', 'Elastic', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_140', question: 'Hooke\'s Law:', options: ['Random', 'Extension proportional to force (within limit)', 'No relationship', 'Inverse relationship'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },

  // WAVES, MAGNETISM & ELECTRICITY (40 questions)
  { id: 'y8_sci_141', question: 'Sound travels as:', options: ['Light', 'Vibrations/waves', 'Electricity', 'Heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_142', question: 'Sound cannot travel through:', options: ['Air', 'Water', 'Vacuum', 'Solids'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_143', question: 'Sound travels fastest in:', options: ['Air', 'Water', 'Solids', 'Vacuum'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_144', question: 'Pitch depends on:', options: ['Amplitude', 'Frequency', 'Volume', 'Speed'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_145', question: 'Loudness depends on:', options: ['Frequency', 'Amplitude', 'Pitch', 'Wavelength'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_146', question: 'Frequency measured in:', options: ['Meters', 'Hertz', 'Decibels', 'Joules'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_147', question: 'High frequency =', options: ['Low pitch', 'High pitch', 'Loud', 'Quiet'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_148', question: 'Large amplitude =', options: ['High pitch', 'Loud sound', 'Low pitch', 'Quiet'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_149', question: 'Ultrasound:', options: ['Low frequency', 'Frequency above human hearing', 'Below hearing', 'Audible'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_150', question: 'Uses of ultrasound:', options: ['Nothing', 'Medical scans, cleaning', 'Only music', 'Only communication'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_151', question: 'Echo is:', options: ['New sound', 'Reflected sound', 'Absorbed sound', 'No sound'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_152', question: 'Light travels in:', options: ['Curves', 'Straight lines', 'Circles', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_153', question: 'Light travels ___ than sound:', options: ['Slower', 'Faster', 'Same speed', 'Not at all'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_154', question: 'Reflection:', options: ['Light passing through', 'Light bouncing off', 'Light absorbed', 'Light stopped'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_155', question: 'Law of reflection:', options: ['Random', 'Angle of incidence = angle of reflection', 'Always 90°', 'No pattern'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_156', question: 'Refraction:', options: ['Light bouncing', 'Light bending when changing medium', 'Light stopping', 'Light glowing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_157', question: 'Dispersion:', options: ['Light bouncing', 'White light splitting into colors', 'Light stopping', 'Light absorbing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_158', question: 'Primary colors of light:', options: ['Red, yellow, blue', 'Red, green, blue', 'Red, orange, yellow', 'Only red'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_159', question: 'White light contains:', options: ['One color', 'All colors', 'No colors', 'Only white'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_160', question: 'Objects appear colored because:', options: ['They glow', 'They reflect certain colors', 'They are magic', 'They absorb all'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_161', question: 'Translucent:', options: ['Blocks all light', 'Allows some light through (blurry)', 'Transparent', 'Opaque'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_162', question: 'Transparent:', options: ['Blocks light', 'Lets light through clearly', 'Reflects all', 'Absorbs all'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_163', question: 'Opaque:', options: ['Lets light through', 'Blocks light', 'Is transparent', 'Is translucent'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_164', question: 'Electromagnetic spectrum includes:', options: ['Only light', 'Radio, micro, IR, visible, UV, X-ray, gamma', 'Only UV', 'Only X-rays'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_sci_165', question: 'Visible light is part of:', options: ['Sound spectrum', 'Electromagnetic spectrum', 'Nothing', 'Magnetic field'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_166', question: 'Infrared is:', options: ['Visible', 'Heat radiation', 'Sound', 'Magnetic'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_167', question: 'Ultraviolet:', options: ['Is visible', 'Beyond violet, can damage skin', 'Is sound', 'Is safe always'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_168', question: 'X-rays used for:', options: ['Cooking', 'Medical imaging', 'Communication', 'Heating'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_169', question: 'Magnet has ___ poles:', options: ['One', 'Two (North and South)', 'Three', 'Four'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_170', question: 'Like poles:', options: ['Attract', 'Repel', 'No effect', 'Stick'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_171', question: 'Unlike poles:', options: ['Repel', 'Attract', 'No effect', 'Break'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_172', question: 'Magnetic field is:', options: ['Physical object', 'Region where magnetic force acts', 'Only at poles', 'Visible'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_173', question: 'Magnetic materials:', options: ['Wood, plastic', 'Iron, nickel, cobalt', 'Copper, gold', 'Glass, rubber'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_174', question: 'Electromagnet needs:', options: ['Permanent magnet only', 'Current in coil', 'No current', 'No wire'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_175', question: 'Electromagnet strength increased by:', options: ['Less current', 'More coils, more current, iron core', 'Fewer coils', 'No core'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_176', question: 'Series circuit:', options: ['Multiple paths', 'One path for current', 'No path', 'Random paths'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_177', question: 'Parallel circuit:', options: ['One path', 'Multiple paths for current', 'No path', 'Series only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_178', question: 'In series, if one bulb breaks:', options: ['Others stay on', 'All go out', 'Get brighter', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_179', question: 'In parallel, if one bulb breaks:', options: ['All go out', 'Others stay on', 'Get dimmer', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_180', question: 'Current same throughout:', options: ['Parallel', 'Series', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // ECOSYSTEMS & THE EARTH (20 questions)
  { id: 'y8_sci_181', question: 'Ecosystem includes:', options: ['Only animals', 'Living organisms and environment', 'Only plants', 'Only climate'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_182', question: 'Producer:', options: ['Eats other organisms', 'Makes own food (plants)', 'Decomposes', 'Hunts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_183', question: 'Primary consumer:', options: ['Eats plants', 'Eats consumers', 'Is plant', 'Decomposes'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_184', question: 'Secondary consumer:', options: ['Eats plants', 'Eats primary consumers', 'Is plant', 'Decomposes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_185', question: 'Decomposer:', options: ['Producer', 'Consumer', 'Breaks down dead matter', 'Hunter'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_186', question: 'Food chain shows:', options: ['Random organisms', 'Energy flow through organisms', 'Only plants', 'Only animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_187', question: 'Food web shows:', options: ['One chain', 'Many interconnected food chains', 'No connections', 'Only producers'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_188', question: 'Predator:', options: ['Is hunted', 'Hunts other animals', 'Is plant', 'Decomposes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_189', question: 'Prey:', options: ['Hunts', 'Is hunted', 'Is plant', 'Decomposes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_190', question: 'Competition for:', options: ['Nothing', 'Resources like food, water, space', 'Only food', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_191', question: 'Adaptation helps organisms:', options: ['Die', 'Survive in environment', 'Compete less', 'Fail'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_192', question: 'Seasons caused by:', options: ['Distance from sun', 'Earth\'s tilt', 'Moon', 'Stars'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_193', question: 'Day/night caused by:', options: ['Earth orbiting sun', 'Earth rotating on axis', 'Moon', 'Stars'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_194', question: 'Year is time for:', options: ['Moon orbit', 'Earth to orbit sun', 'Earth rotation', 'Sun movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_195', question: 'Moon phases caused by:', options: ['Moon\'s shape changing', 'Different amounts illuminated', 'Earth\'s shadow', 'Sun changing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_196', question: 'Solar eclipse:', options: ['Earth blocks sun', 'Moon blocks sun', 'Sun disappears', 'Moon disappears'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_197', question: 'Lunar eclipse:', options: ['Sun blocks moon', 'Earth\'s shadow on moon', 'Moon blocks sun', 'Moon disappears'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_sci_198', question: 'Gravity keeps:', options: ['Nothing', 'Planets in orbit', 'Everything still', 'Sun moving'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_199', question: 'Solar system consists of:', options: ['Only Earth', 'Sun, planets, moons, asteroids, comets', 'Only sun', 'Only planets'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_sci_200', question: 'Rock cycle involves:', options: ['One rock type', 'Igneous, sedimentary, metamorphic transforming', 'Only igneous', 'No changes'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 }
];
