// Year 6 Science Trivia Questions
// Based on UK Year 6 Science Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_6_SCIENCE_QUESTIONS = [
  // LIVING THINGS & THEIR HABITATS - Classification (35 questions)
  { id: 'y6_sci_1', question: 'What is classification?', options: ['Naming animals', 'Grouping organisms by shared characteristics', 'Counting species', 'Feeding animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_2', question: 'Who developed the classification system we use today?', options: ['Darwin', 'Carl Linnaeus', 'Newton', 'Einstein'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_3', question: 'What are the two main groups of organisms?', options: ['Big and small', 'Vertebrates and invertebrates', 'Land and water', 'Fast and slow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_4', question: 'Vertebrates have:', options: ['No bones', 'A backbone/spine', 'Feathers', 'Scales'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_5', question: 'Invertebrates have:', options: ['A backbone', 'No backbone', 'Fur', 'Lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_6', question: 'The five vertebrate groups are:', options: ['Only mammals', 'Mammals, birds, fish, amphibians, reptiles', 'Only fish', 'Insects and mammals'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_7', question: 'Which are invertebrates?', options: ['Dogs and cats', 'Insects, spiders, worms, snails', 'Only birds', 'Only mammals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_8', question: 'What is a mammal?', options: ['Lays eggs', 'Has fur, feeds milk to young, warm-blooded', 'Has scales', 'Lives in water'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_9', question: 'What are birds characterized by?', options: ['Fur', 'Feathers, lay eggs, beaks, wings', 'Scales', 'Gills'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_10', question: 'What are fish characterized by?', options: ['Lungs', 'Gills, scales, fins, live in water', 'Fur', 'Feathers'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_11', question: 'Amphibians:', options: ['Only live on land', 'Start in water, can live on land (metamorphosis)', 'Only live in water', 'Have fur'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_12', question: 'Reptiles have:', options: ['Wet skin', 'Dry scaly skin, lay eggs on land', 'Fur', 'Feathers'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_13', question: 'What are the main invertebrate groups?', options: ['Only insects', 'Insects, arachnids, molluscs, worms', 'Only mammals', 'Only birds'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_14', question: 'Insects have:', options: ['8 legs', '6 legs, 3 body parts', '4 legs', 'No legs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_15', question: 'Arachnids (spiders) have:', options: ['6 legs', '8 legs', '10 legs', '4 legs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_16', question: 'Which is an arachnid?', options: ['Ant', 'Spider', 'Worm', 'Snail'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_17', question: 'Molluscs include:', options: ['Ants', 'Snails, slugs, octopuses', 'Spiders', 'Worms'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_18', question: 'What are micro-organisms?', options: ['Big animals', 'Tiny organisms visible only under microscope', 'Plants', 'Mammals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_19', question: 'Examples of micro-organisms:', options: ['Elephants', 'Bacteria, viruses, some fungi', 'Trees', 'Fish'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_20', question: 'Plants can be classified as:', options: ['Only trees', 'Flowering and non-flowering', 'Only grass', 'Big and small'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_21', question: 'Flowering plants produce:', options: ['No seeds', 'Flowers and seeds', 'Only leaves', 'Only roots'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_22', question: 'Non-flowering plants include:', options: ['Roses', 'Ferns, mosses, conifers', 'Sunflowers', 'Tulips'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_23', question: 'What is a classification key?', options: ['A door key', 'Tool using questions to identify organisms', 'A password', 'A map'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_24', question: 'Classification keys use:', options: ['Random guesses', 'Yes/No questions about features', 'Colors only', 'Size only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_25', question: 'Why classify organisms?', options: ['No reason', 'To organize and understand relationships', 'For fun', 'To confuse people'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_26', question: 'What are the 5 kingdoms?', options: ['Only animals', 'Animals, plants, fungi, protists, bacteria', 'Only plants', 'Only mammals'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_27', question: 'Warm-blooded animals:', options: ['Cannot control temperature', 'Maintain constant body temperature', 'Are always cold', 'Only reptiles'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_28', question: 'Cold-blooded animals:', options: ['Maintain constant temperature', 'Body temperature changes with environment', 'Are always warm', 'Only mammals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_29', question: 'Which are warm-blooded?', options: ['Fish', 'Mammals and birds', 'Reptiles', 'Amphibians'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_30', question: 'Which are cold-blooded?', options: ['Mammals', 'Fish, reptiles, amphibians', 'Birds', 'Only humans'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_31', question: 'Fungi include:', options: ['Animals', 'Mushrooms, molds, yeast', 'Only plants', 'Fish'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_32', question: 'What do fungi feed on?', options: ['Sunlight', 'Dead or living organic matter', 'Rocks', 'Air'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_33', question: 'Characteristics shared by a group are called:', options: ['Random traits', 'Common characteristics', 'Differences', 'Unique features'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_34', question: 'Scientific names use:', options: ['English only', 'Latin', 'Numbers only', 'Pictures'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_35', question: 'Why use scientific names?', options: ['Confuse people', 'Universal names recognized globally', 'Make it harder', 'No reason'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // EVOLUTION & INHERITANCE (35 questions)
  { id: 'y6_sci_36', question: 'What is evolution?', options: ['Staying the same', 'Change in species over time', 'Only growth', 'Death'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_37', question: 'Who developed the theory of evolution?', options: ['Newton', 'Einstein', 'Charles Darwin', 'Galileo'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_38', question: 'What is natural selection?', options: ['Humans choosing', 'Organisms best suited survive and reproduce', 'Random selection', 'All die'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_39', question: 'What are fossils?', options: ['Living organisms', 'Remains/traces of ancient organisms', 'Rocks', 'Modern bones'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_40', question: 'Fossils provide evidence for:', options: ['Nothing', 'Evolution and past life', 'Current weather', 'Future'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_41', question: 'What is adaptation?', options: ['Staying same', 'Features helping organisms survive in environment', 'Death', 'Random changes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_42', question: 'Why do polar bears have white fur?', options: ['Random', 'Camouflage in snow (adaptation)', 'Fashion', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_43', question: 'Why do cacti have spines?', options: ['Decoration', 'Reduce water loss, protection (adaptation)', 'No reason', 'To hurt'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_44', question: 'What is inheritance?', options: ['Buying things', 'Passing traits from parents to offspring', 'Growing', 'Eating'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_45', question: 'Inherited characteristics include:', options: ['Learned skills', 'Eye color, hair color, height', 'Riding a bike', 'Reading'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_46', question: 'Which is inherited?', options: ['Speaking English', 'Eye color', 'Playing piano', 'Writing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_47', question: 'Which is NOT inherited?', options: ['Blood type', 'Hair color', 'Language', 'Eye color'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_48', question: 'Offspring look like parents because:', options: ['Magic', 'They inherit genes/DNA', 'Coincidence', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_49', question: 'Variation means:', options: ['All same', 'Differences between individuals', 'Only one type', 'No change'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_50', question: 'Variation can be caused by:', options: ['Nothing', 'Genetics and environment', 'Only genetics', 'Only environment'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_51', question: 'Example of environmental variation:', options: ['Eye color', 'Scars from injury', 'Blood type', 'Natural hair color'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_52', question: 'What is selective breeding?', options: ['Natural selection', 'Humans choosing which organisms breed', 'Random breeding', 'No breeding'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_53', question: 'Selective breeding is used to:', options: ['Make organisms worse', 'Develop desirable traits', 'Random results', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_54', question: 'Examples of selective breeding:', options: ['Random animals', 'Crop plants, farm animals, dogs', 'Only wild animals', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_55', question: 'What is extinction?', options: ['New species', 'When all members of species die out', 'Growth', 'Evolution'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_56', question: 'Dinosaurs are:', options: ['Still alive', 'Extinct', 'Hiding', 'Invisible'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_57', question: 'Species can become extinct due to:', options: ['Being too successful', 'Habitat loss, climate change, competition', 'Nothing', 'Magic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_58', question: 'What helps species survive?', options: ['Staying same', 'Useful adaptations', 'Being large only', 'No features'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_59', question: 'Organisms compete for:', options: ['Nothing', 'Food, water, space, mates', 'Only food', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_60', question: 'Better adapted organisms:', options: ['Die first', 'More likely to survive and reproduce', 'Are weaker', 'Avoid competition'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_61', question: 'Evolution happens:', options: ['Overnight', 'Over many generations/long time', 'In one day', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_62', question: 'What is a species?', options: ['Random group', 'Group of similar organisms that can breed together', 'Any animal', 'Only mammals'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_63', question: 'Humans belong to species:', options: ['Homo erectus', 'Homo sapiens', 'Homo habilis', 'Neanderthals'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_64', question: 'Evidence for evolution includes:', options: ['Nothing', 'Fossils, DNA, anatomy similarities', 'Only fossils', 'Guesses'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_65', question: 'Why do giraffes have long necks?', options: ['Random', 'Adaptation to reach high leaves', 'Fashion', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_66', question: 'Camouflage helps organisms:', options: ['Be seen', 'Hide from predators or prey', 'Look pretty', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_67', question: 'What is DNA?', options: ['A disease', 'Genetic material carrying instructions', 'A food', 'A plant'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_68', question: 'Offspring inherit DNA from:', options: ['No one', 'Both parents', 'Only mother', 'Only father'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_69', question: 'Mutations are:', options: ['Always harmful', 'Changes in DNA', 'Always helpful', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_70', question: 'Advantageous traits become more common because:', options: ['Luck', 'Organisms with them survive and reproduce more', 'Magic', 'No reason'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // ANIMALS INCLUDING HUMANS - Circulatory System (30 questions)
  { id: 'y6_sci_71', question: 'What is the circulatory system?', options: ['Breathing system', 'System transporting blood around body', 'Digestive system', 'Skeletal system'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_72', question: 'Main parts of circulatory system:', options: ['Only heart', 'Heart, blood vessels, blood', 'Only blood', 'Only lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_73', question: 'What does the heart do?', options: ['Digests food', 'Pumps blood around body', 'Breathes', 'Thinks'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_74', question: 'The heart is a:', options: ['Bone', 'Muscle that pumps', 'Vein', 'Artery'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_75', question: 'How many chambers does human heart have?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_76', question: 'What are blood vessels?', options: ['Organs', 'Tubes carrying blood', 'Cells', 'Bones'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_77', question: 'Three types of blood vessels:', options: ['Only veins', 'Arteries, veins, capillaries', 'Only arteries', 'Heart only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_78', question: 'Arteries carry blood:', options: ['To the heart', 'Away from heart', 'Nowhere', 'Only to lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_79', question: 'Veins carry blood:', options: ['Away from heart', 'To the heart', 'Nowhere', 'Only to lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_80', question: 'Capillaries are:', options: ['Large vessels', 'Tiny vessels connecting arteries and veins', 'Organs', 'Bones'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_81', question: 'What does blood carry?', options: ['Nothing', 'Oxygen, nutrients, waste', 'Only water', 'Only air'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_82', question: 'Red blood cells carry:', options: ['Water', 'Oxygen', 'Food', 'Waste'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_83', question: 'White blood cells:', options: ['Carry oxygen', 'Fight infection', 'Pump blood', 'Digest food'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_84', question: 'Platelets help:', options: ['Fight infection', 'Blood clotting', 'Carry oxygen', 'Pump blood'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_85', question: 'Plasma is:', options: ['A cell', 'Liquid part of blood', 'An organ', 'A bone'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_86', question: 'What is your pulse?', options: ['Breathing rate', 'Heart beating felt in arteries', 'Digestion', 'Thinking'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_87', question: 'Where can you feel pulse?', options: ['Nowhere', 'Wrist, neck', 'Only feet', 'Only head'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_88', question: 'Heart rate increases when:', options: ['Resting', 'Exercising', 'Sleeping', 'Sitting'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_89', question: 'Why does heart rate increase during exercise?', options: ['Random', 'Muscles need more oxygen', 'No reason', 'It doesn\'t'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_90', question: 'Blood picks up oxygen in:', options: ['Stomach', 'Lungs', 'Feet', 'Brain'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_91', question: 'Blood delivers oxygen to:', options: ['Nowhere', 'All body cells', 'Only heart', 'Only lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_92', question: 'Blood removes what from cells?', options: ['Oxygen', 'Carbon dioxide (waste)', 'Nothing', 'Food'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_93', question: 'A healthy circulatory system needs:', options: ['Junk food', 'Exercise, balanced diet, no smoking', 'No exercise', 'Lots of sugar'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_94', question: 'Exercise helps heart by:', options: ['Weakening it', 'Making it stronger', 'Stopping it', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_95', question: 'Smoking damages:', options: ['Nothing', 'Heart and blood vessels', 'Only lungs', 'Only skin'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_96', question: 'The heart beats about ___ times per day:', options: ['1,000', '10,000', '100,000', '1,000,000'], correctAnswer: 2, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_97', question: 'Blood travels through body in:', options: ['Random paths', 'A circular route', 'One direction only', 'No pattern'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_98', question: 'What is the aorta?', options: ['A vein', 'Main artery from heart', 'A lung', 'A chamber'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_99', question: 'The right side of heart pumps blood to:', options: ['Body', 'Lungs', 'Brain', 'Stomach'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_100', question: 'The left side of heart pumps blood to:', options: ['Lungs only', 'Rest of body', 'Nowhere', 'Brain only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // LIGHT (40 questions)
  { id: 'y6_sci_101', question: 'What is light?', options: ['A liquid', 'A form of energy', 'A solid', 'A gas'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_102', question: 'Light travels in:', options: ['Curves', 'Straight lines', 'Circles', 'Spirals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_103', question: 'We see objects because:', options: ['They glow', 'Light reflects off them into our eyes', 'Magic', 'They are bright'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_104', question: 'What is a light source?', options: ['Anything we see', 'Something that produces light', 'A mirror', 'A shadow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_105', question: 'Which is a light source?', options: ['Moon', 'Sun', 'Book', 'Wall'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_106', question: 'The Moon:', options: ['Produces light', 'Reflects sunlight', 'Is a star', 'Glows'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_107', question: 'What is reflection?', options: ['Light passing through', 'Light bouncing off a surface', 'Light being absorbed', 'Light stopping'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_108', question: 'Smooth shiny surfaces (mirrors):', options: ['Absorb all light', 'Reflect light well', 'Let light through', 'Stop light'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_109', question: 'Rough surfaces:', options: ['Reflect light in all directions (scattered)', 'Reflect perfectly', 'Absorb all light', 'Glow'], correctAnswer: 0, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_110', question: 'What is refraction?', options: ['Light bouncing', 'Light bending when entering different material', 'Light stopping', 'Light glowing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_111', question: 'A straw in water looks bent because:', options: ['It is bent', 'Refraction of light', 'Magic', 'Water pressure'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_112', question: 'What is a shadow?', options: ['Light source', 'Dark area where light is blocked', 'Reflection', 'Refraction'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_113', question: 'Shadows form when:', options: ['Light passes through', 'Opaque object blocks light', 'Light bends', 'Light reflects'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_114', question: 'Transparent materials:', options: ['Block all light', 'Let light through', 'Reflect light', 'Absorb light'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_115', question: 'Opaque materials:', options: ['Let light through', 'Block light', 'Are invisible', 'Glow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_116', question: 'Translucent materials:', options: ['Block all light', 'Let some light through (blurry)', 'Are transparent', 'Are opaque'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_117', question: 'Which is transparent?', options: ['Wood', 'Clear glass', 'Metal', 'Brick'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_118', question: 'Which is opaque?', options: ['Glass', 'Water', 'Wood', 'Air'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_119', question: 'How do we see?', options: ['Eyes produce light', 'Light enters eyes from objects', 'Magic', 'Eyes glow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_120', question: 'The pupil is:', options: ['Colored part', 'Black opening letting light in', 'White part', 'Eyelid'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_121', question: 'The iris:', options: ['Lets light in', 'Colored part controlling pupil size', 'White part', 'Lens'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_122', question: 'The retina:', options: ['Controls pupil', 'Detects light at back of eye', 'Is colored', 'Focuses light'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_123', question: 'The lens:', options: ['Colors the eye', 'Focuses light onto retina', 'Lets light in', 'Protects eye'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_124', question: 'In bright light, pupil:', options: ['Gets bigger', 'Gets smaller', 'Stays same', 'Closes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_125', question: 'In dim light, pupil:', options: ['Gets smaller', 'Gets bigger', 'Stays same', 'Closes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_126', question: 'White light is made of:', options: ['One color', 'All colors of rainbow', 'No colors', 'Only red'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_127', question: 'A prism can:', options: ['Block light', 'Split white light into colors', 'Make light', 'Stop light'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_128', question: 'Rainbow colors in order:', options: ['Random', 'Red, Orange, Yellow, Green, Blue, Indigo, Violet', 'Only red and blue', 'Only green'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_129', question: 'How do rainbows form?', options: ['Magic', 'Sunlight refracted by water droplets', 'Painted', 'Clouds'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_130', question: 'Objects appear colored because:', options: ['They produce light', 'They reflect certain colors, absorb others', 'Magic', 'They glow'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_131', question: 'A red apple appears red because:', options: ['It absorbs red', 'It reflects red light', 'It glows', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_132', question: 'Black objects:', options: ['Reflect all light', 'Absorb all light', 'Are transparent', 'Glow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_133', question: 'White objects:', options: ['Absorb all light', 'Reflect all light', 'Are opaque', 'Glow'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_134', question: 'Light travels at:', options: ['Slow speed', 'Very fast speed (fastest thing)', 'Medium speed', 'No speed'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_135', question: 'We see things almost instantly because:', options: ['Light is slow', 'Light travels very fast', 'Eyes are fast', 'Magic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_136', question: 'A periscope uses:', options: ['Lenses only', 'Mirrors to reflect light', 'Prisms only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_137', question: 'Mirrors are used in:', options: ['Nothing', 'Telescopes, periscopes, car mirrors', 'Only bathrooms', 'Only shops'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_138', question: 'Shadow size depends on:', options: ['Nothing', 'Distance from light source and object', 'Color', 'Temperature'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_139', question: 'Object closer to light source makes shadow:', options: ['Smaller', 'Larger', 'Same size', 'Disappear'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_140', question: 'Why can\'t we see in complete darkness?', options: ['Eyes don\'t work', 'No light to reflect into eyes', 'Too tired', 'Magic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // ELECTRICITY (Advanced) (30 questions)
  { id: 'y6_sci_141', question: 'What is voltage?', options: ['Current', 'Push of electricity', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_142', question: 'Voltage is measured in:', options: ['Amps', 'Volts', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_143', question: 'What is current?', options: ['Voltage', 'Flow of electricity', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_144', question: 'Current is measured in:', options: ['Volts', 'Amperes (Amps)', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_145', question: 'Circuit symbol for a cell:', options: ['Circle', 'Long and short lines', 'Cross', 'Square'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_146', question: 'Circuit symbol for a bulb:', options: ['X in circle', 'Circle with cross', 'Rectangle', 'Triangle'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_147', question: 'Circuit symbol for a switch:', options: ['Line', 'Gap with line', 'Circle', 'Cross'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_148', question: 'Circuit symbol for a motor:', options: ['M in circle', 'Circle only', 'Square', 'Triangle'], correctAnswer: 0, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_149', question: 'Circuit symbol for a buzzer:', options: ['Speaker shape', 'Circle', 'Square', 'Line'], correctAnswer: 0, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_150', question: 'Circuit symbol for a resistor:', options: ['Circle', 'Rectangle', 'Triangle', 'Cross'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_151', question: 'What is a series circuit?', options: ['Multiple paths', 'Single path for current', 'No path', 'Random paths'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_152', question: 'In series circuit, if one bulb breaks:', options: ['Others stay lit', 'All go out', 'Nothing happens', 'They get brighter'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_153', question: 'Adding more cells in series:', options: ['Decreases brightness', 'Increases brightness', 'No change', 'Bulbs break'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_154', question: 'Adding more bulbs in series:', options: ['Increases brightness', 'Decreases brightness of each', 'No change', 'Breaks circuit'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_155', question: 'What affects brightness of bulb?', options: ['Color', 'Voltage and number of bulbs', 'Size', 'Shape'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_156', question: 'More cells (voltage) means:', options: ['Dimmer bulbs', 'Brighter bulbs', 'No change', 'Bulbs break'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_157', question: 'What is a variable resistor?', options: ['Fixed resistance', 'Adjustable resistance', 'No resistance', 'Infinite resistance'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_158', question: 'Increasing resistance in circuit:', options: ['Increases current', 'Decreases current', 'No effect', 'Breaks circuit'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_159', question: 'What is a fuse?', options: ['Wire that glows', 'Safety device that melts if current too high', 'Resistor', 'Switch'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_160', question: 'Why use fuses?', options: ['Decoration', 'Protect from dangerous currents/fires', 'Make light', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_161', question: 'What do batteries store?', options: ['Water', 'Chemical energy converted to electrical', 'Light', 'Heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_162', question: 'Batteries eventually:', options: ['Last forever', 'Run out of energy', 'Get bigger', 'Explode'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_163', question: 'Direction of current in circuit:', options: ['Random', 'From positive to negative terminal', 'No direction', 'Backwards'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_164', question: 'What is an ammeter?', options: ['Measures voltage', 'Measures current', 'Measures resistance', 'Measures power'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_165', question: 'What is a voltmeter?', options: ['Measures current', 'Measures voltage', 'Measures resistance', 'Measures power'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_166', question: 'Electricity safety rules include:', options: ['Touch wires', 'Never use near water, don\'t overload sockets', 'Ignore warnings', 'Use damaged wires'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_167', question: 'Static electricity is:', options: ['Moving charge', 'Build-up of charge', 'No charge', 'Current'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_168', question: 'Example of static electricity:', options: ['Battery', 'Rubbing balloon on hair', 'Mains power', 'Bulb'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_169', question: 'Current electricity:', options: ['Static charge', 'Flowing charge', 'No movement', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_170', question: 'Renewable energy sources include:', options: ['Coal, oil', 'Solar, wind, hydro', 'Only gas', 'Only nuclear'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // WORKING SCIENTIFICALLY (25 questions)
  { id: 'y6_sci_171', question: 'What is a hypothesis?', options: ['A fact', 'Testable prediction', 'Random guess', 'Conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_172', question: 'What is a variable?', options: ['Fixed value', 'Something that can change', 'Result', 'Equipment'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_173', question: 'Independent variable is:', options: ['What you measure', 'What you change', 'What stays same', 'The result'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_174', question: 'Dependent variable is:', options: ['What you change', 'What you measure', 'What stays same', 'Equipment'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_175', question: 'Control variables are:', options: ['What you change', 'What you measure', 'What you keep the same', 'Random'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_176', question: 'A fair test:', options: ['Changes everything', 'Changes one variable only', 'Changes nothing', 'Is random'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_177', question: 'Why repeat experiments?', options: ['Waste time', 'Improve reliability and accuracy', 'No reason', 'Make work longer'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_178', question: 'Accurate measurements are:', options: ['Random', 'Close to true value', 'Far from truth', 'Quick'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_179', question: 'Precise measurements are:', options: ['Spread out', 'Close together when repeated', 'Random', 'Different each time'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_180', question: 'Anomalous results are:', options: ['Normal', 'Results that don\'t fit pattern', 'Average', 'Expected'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_181', question: 'What should you do with anomalous results?', options: ['Ignore always', 'Identify, check, possibly repeat', 'Always keep', 'Always remove'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_182', question: 'A line graph shows:', options: ['Categories', 'Continuous data/trends over time', 'One value', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_183', question: 'A bar chart shows:', options: ['Continuous data', 'Comparing categories', 'Time only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_184', question: 'A scatter graph shows:', options: ['One variable', 'Relationship between two variables', 'Categories', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_sci_185', question: 'What is a conclusion?', options: ['The hypothesis', 'Summary based on results', 'Random statement', 'The question'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_186', question: 'Conclusions should be:', options: ['Random', 'Based on evidence', 'Guesses', 'Opinions'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_187', question: 'What is evaluation?', options: ['First step', 'Reviewing method and results', 'Random', 'Starting experiment'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_188', question: 'Why evaluate?', options: ['Waste time', 'Identify improvements', 'No reason', 'Avoid work'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_189', question: 'Scientific diagrams should:', options: ['Be messy', 'Be clear, labeled, titled', 'Have no labels', 'Be colorful only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_190', question: 'Why use tables?', options: ['Decoration', 'Organize data clearly', 'Waste space', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_191', question: 'A prediction should be:', options: ['Random', 'Based on scientific knowledge', 'A guess', 'Unrelated'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_192', question: 'What makes evidence reliable?', options: ['One test', 'Repeated tests with consistent results', 'Random results', 'No tests'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_193', question: 'Scientific reports should include:', options: ['Only results', 'Question, method, results, conclusion', 'Only pictures', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_194', question: 'Why is peer review important?', options: ['No reason', 'Others check your work for errors', 'Waste time', 'Confuse'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_sci_195', question: 'Scientific knowledge:', options: ['Never changes', 'Develops with new evidence', 'Is random', 'Is opinion'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // ASSESSMENT (5 questions)
  { id: 'y6_sci_196', question: 'End-of-unit assessments test:', options: ['Nothing', 'Your understanding of the topic', 'Only memory', 'Only speed'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_197', question: 'Scientific investigations assess:', options: ['Only knowledge', 'Practical skills and enquiry', 'Only reading', 'Only writing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_198', question: 'SATs Science tests check:', options: ['Only one topic', 'Understanding across all topics', 'Nothing', 'Only practicals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_199', question: 'Good revision includes:', options: ['Last-minute cramming', 'Regular practice, notes, questions', 'Only reading', 'Avoiding weaknesses'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_sci_200', question: 'Year 6 Science mastery means:', options: ['Knowing everything', 'Demonstrating understanding and skills', 'Passing one test', 'Guessing well'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 }
];
