// Year 8 English Trivia Questions
// Based on UK Year 8 English Curriculum Framework (KS3)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_8_ENGLISH_QUESTIONS = [
  // READING & COMPREHENSION (70 questions)
  // Literary Analysis
  { id: 'y8_eng_1', question: 'What is a theme?', options: ['The title', 'Central idea or underlying message', 'The plot', 'The setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_2', question: 'What is mood in literature?', options: ['Author attitude', 'Atmosphere/feeling created', 'Plot', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_3', question: 'What is tone?', options: ['Volume', 'Author\'s attitude toward subject', 'Character', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_4', question: 'What is symbolism?', options: ['Math symbols', 'Objects/elements representing deeper meanings', 'Letters', 'Punctuation'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_5', question: 'What is foreshadowing?', options: ['Past events', 'Hints about future events', 'Current events', 'No events'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_6', question: 'What is irony?', options: ['Expected outcome', 'Opposite of expected', 'Sarcasm only', 'Humor'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_7', question: 'What is dramatic irony?', options: ['Audience knows more than characters', 'Characters know everything', 'No irony', 'Sarcasm'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_8', question: 'What is situational irony?', options: ['Verbal statement', 'Outcome opposite of expected', 'Dramatic scene', 'Metaphor'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_9', question: 'What is verbal irony?', options: ['Saying opposite of what\'s meant', 'Physical action', 'True statement', 'Question'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_10', question: 'What is juxtaposition?', options: ['Same elements together', 'Contrasting elements placed together', 'Repetition', 'Rhyme'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  
  // Shakespeare
  { id: 'y8_eng_11', question: 'Shakespeare lived during which period?', options: ['Medieval', 'Elizabethan/Jacobean', 'Victorian', 'Modern'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_12', question: 'What is blank verse?', options: ['No words', 'Unrhymed iambic pentameter', 'Free verse', 'Rhyming couplets'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_13', question: 'What is iambic pentameter?', options: ['5 syllables', '10 syllables with unstressed/stressed pattern', '8 lines', 'Rhyme scheme'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_14', question: 'A soliloquy is:', options: ['Two characters talking', 'Character revealing thoughts alone on stage', 'Group speech', 'Narration'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_15', question: 'An aside is:', options: ['Exit', 'Comment to audience, not other characters', 'Main speech', 'Song'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_16', question: 'What is a sonnet?', options: ['5-line poem', '14-line poem', '20-line poem', 'Play'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_17', question: 'Shakespearean sonnet rhyme scheme:', options: ['ABAB CDCD EFEF GG', 'ABBAABBA CDECDE', 'ABCABC', 'No rhyme'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_18', question: 'What is a tragedy?', options: ['Happy ending', 'Serious play with downfall/death', 'Comedy', 'Mystery'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_19', question: 'Tragic flaw is:', options: ['Perfect quality', 'Character weakness leading to downfall', 'Happy trait', 'Minor issue'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_20', question: 'Hamartia means:', options: ['Perfection', 'Tragic flaw', 'Victory', 'Beginning'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },

  // Poetry
  { id: 'y8_eng_21', question: 'What is enjambment?', options: ['End-stopped line', 'Line running onto next without pause', 'Rhyme', 'Stanza break'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_22', question: 'What is a caesura?', options: ['Line ending', 'Pause within line', 'Rhyme scheme', 'Metaphor'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_23', question: 'What is assonance?', options: ['Consonant repetition', 'Vowel sound repetition', 'Rhyming', 'No sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_24', question: 'What is consonance?', options: ['Vowel repetition', 'Consonant sound repetition', 'Full rhyme', 'No pattern'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_25', question: 'What is sibilance?', options: ['S sound repetition', 'B sound repetition', 'Any alliteration', 'Rhyme'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_26', question: 'What is plosive?', options: ['Soft sounds', 'Hard consonant sounds (b, p, t, d)', 'Vowels', 'Silence'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_27', question: 'Volta in sonnet is:', options: ['First line', 'Turn/shift in argument', 'Last line', 'Title'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_28', question: 'Octave in sonnet:', options: ['8 lines', '14 lines', '6 lines', '4 lines'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_29', question: 'Sestet in sonnet:', options: ['8 lines', '14 lines', '6 lines', '4 lines'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_30', question: 'Extended metaphor:', options: ['One line metaphor', 'Metaphor developed throughout text', 'No metaphor', 'Simile'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // Prose and Novel Study
  { id: 'y8_eng_31', question: 'What is a protagonist?', options: ['Villain', 'Main character', 'Minor character', 'Narrator'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_32', question: 'What is an antagonist?', options: ['Hero', 'Character opposing protagonist', 'Narrator', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_33', question: 'What is characterization?', options: ['Plot', 'How author presents characters', 'Setting', 'Theme'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_34', question: 'Direct characterization:', options: ['Showing through actions', 'Author explicitly describes', 'Implied', 'No description'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_35', question: 'Indirect characterization:', options: ['Explicit description', 'Revealed through actions/dialogue', 'No characterization', 'Title only'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_36', question: 'Round character is:', options: ['Flat', 'Complex and developed', 'Unchanging', 'Minor'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_37', question: 'Flat character is:', options: ['Complex', 'One-dimensional, stereotypical', 'Main character', 'Dynamic'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_38', question: 'Dynamic character:', options: ['Never changes', 'Changes throughout story', 'Is static', 'Minor role'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_39', question: 'Static character:', options: ['Changes constantly', 'Remains unchanged', 'Is dynamic', 'Main character'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_40', question: 'What is exposition?', options: ['Climax', 'Background information/introduction', 'Resolution', 'Ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_41', question: 'What is rising action?', options: ['Falling', 'Events building to climax', 'Resolution', 'Introduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_42', question: 'What is climax?', options: ['Beginning', 'Turning point/highest tension', 'Ending', 'Introduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_43', question: 'What is falling action?', options: ['Building tension', 'Events after climax', 'Introduction', 'Climax'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_44', question: 'What is resolution/denouement?', options: ['Introduction', 'Climax', 'Conclusion/outcome', 'Rising action'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_45', question: 'First-person narrator:', options: ['Uses he/she', 'Uses I/we', 'Omniscient', 'Third person'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_46', question: 'Third-person limited:', options: ['Knows everything', 'Follows one character\'s perspective', 'Uses I', 'Omniscient'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_47', question: 'Third-person omniscient:', options: ['One perspective', 'Knows all characters\' thoughts', 'Uses I', 'Limited view'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_48', question: 'Unreliable narrator:', options: ['Trustworthy', 'Cannot be fully trusted', 'Omniscient', 'Always truthful'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_49', question: 'What is flashback?', options: ['Future scene', 'Scene from past', 'Present scene', 'No time shift'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_50', question: 'What is a cliffhanger?', options: ['Clear ending', 'Suspenseful unresolved ending', 'Happy ending', 'Boring ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Non-Fiction
  { id: 'y8_eng_51', question: 'What is bias?', options: ['Fairness', 'Prejudice for/against', 'Balance', 'Neutrality'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_52', question: 'What is a fact?', options: ['Opinion', 'Verifiable information', 'Belief', 'Guess'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_53', question: 'What is an opinion?', options: ['Proven truth', 'Personal belief/judgment', 'Fact', 'Data'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_54', question: 'Emotive language:', options: ['Factual', 'Appeals to emotions', 'Neutral', 'Scientific'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_55', question: 'Rhetorical question:', options: ['Needs answer', 'Asked for effect, not answer', 'Simple question', 'Statement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_56', question: 'Rule of three:', options: ['Three words', 'Things grouped in threes for effect', 'Three paragraphs', 'Three pages'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_57', question: 'Anecdote:', options: ['Statistic', 'Personal story/example', 'Fact', 'Argument'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_58', question: 'Statistics in persuasion:', options: ['Emotional only', 'Provide factual evidence', 'Are opinions', 'Unimportant'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_59', question: 'Counter-argument:', options: ['Agreement', 'Opposing viewpoint', 'Repeat same point', 'Conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_60', question: 'Rebuttal:', options: ['Agreement', 'Response disproving counter-argument', 'Ignoring', 'First point'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_61', question: 'Expert opinion provides:', options: ['No value', 'Authority/credibility', 'Bias only', 'Entertainment'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_62', question: 'Hyperbole in persuasion:', options: ['Understatement', 'Exaggeration for emphasis', 'Fact', 'Question'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_63', question: 'Imperative verbs:', options: ['Describe', 'Command/instruct', 'Question', 'State'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_64', question: 'Register means:', options: ['Name list', 'Level of formality', 'Topic', 'Length'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_65', question: 'Allusion:', options: ['Direct reference', 'Indirect reference to another work', 'Metaphor', 'Simile'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_66', question: 'Analogy:', options: ['Different things', 'Comparison showing similarity', 'Contrast', 'Definition'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_67', question: 'What is ethos?', options: ['Logic', 'Credibility/authority', 'Emotion', 'Time'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_68', question: 'What is pathos?', options: ['Logic', 'Credibility', 'Emotional appeal', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_69', question: 'What is logos?', options: ['Logical reasoning/facts', 'Emotion', 'Credibility', 'Time'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_70', question: 'Inference means:', options: ['Direct statement', 'Reading between lines', 'Copying', 'Guessing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // WRITING (70 questions)
  // Creative Writing
  { id: 'y8_eng_71', question: 'Show don\'t tell means:', options: ['State emotions directly', 'Use actions/descriptions to reveal', 'Be vague', 'Tell everything'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_72', question: 'Varied sentence structure creates:', options: ['Boredom', 'Interest and flow', 'Confusion', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_73', question: 'Sensory details include:', options: ['Only sight', 'All five senses', 'Only sound', 'Only touch'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_74', question: 'Pathetic fallacy:', options: ['No connection', 'Weather/nature reflecting mood', 'Character flaw', 'Plot device'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_75', question: 'Cyclical structure:', options: ['Linear', 'Ends where it begins', 'Random', 'No structure'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_76', question: 'In medias res means:', options: ['Start at beginning', 'Start in middle of action', 'Start at end', 'No beginning'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_77', question: 'Building tension use:', options: ['Reveal everything', 'Short sentences, cliffhangers, delay info', 'Long exposition', 'No suspense'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_78', question: 'Narrative voice consistency means:', options: ['Change perspectives', 'Maintain same perspective throughout', 'Mix tenses', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_79', question: 'Effective dialogue:', options: ['Is unnecessary', 'Reveals character, advances plot', 'Is very long', 'Is boring'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_80', question: 'Setting establishes:', options: ['Nothing', 'Time, place, atmosphere', 'Only location', 'Only time'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Non-fiction Writing
  { id: 'y8_eng_81', question: 'Article purpose:', options: ['Entertain only', 'Inform/persuade readers', 'Confuse', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_82', question: 'Article headline should:', options: ['Be long', 'Be catchy and informative', 'Be vague', 'Have no caps'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_83', question: 'Article lead paragraph:', options: ['Least important', 'Hooks reader, key information', 'Only conclusion', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_84', question: 'Letter format includes:', options: ['No address', 'Address, greeting, body, closing, signature', 'Only body', 'Only greeting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_85', question: 'Formal letter greeting:', options: ['Hi', 'Dear Sir/Madam', 'Hey', 'Yo'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_86', question: 'Informal letter greeting:', options: ['Dear Sir', 'Hi/Dear [name]', 'To whom it may concern', 'Formal only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_87', question: 'Formal letter ending:', options: ['Cheers', 'Yours sincerely/faithfully', 'Love', 'See ya'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_88', question: 'Speech structure:', options: ['No structure', 'Opening, main points, closing', 'Only jokes', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_89', question: 'Speech techniques:', options: ['Mumble', 'Rhetorical questions, repetition, address audience', 'Be boring', 'No techniques'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_90', question: 'Review evaluates:', options: ['Nothing', 'Quality/worth of something', 'Only negatives', 'Only positives'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_91', question: 'Report is:', options: ['Fiction', 'Factual account of event/topic', 'Opinion only', 'Story'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_92', question: 'Essay structure:', options: ['No structure', 'Introduction, body paragraphs, conclusion', 'Only intro', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_93', question: 'Introduction should:', options: ['Conclude', 'Introduce topic, thesis', 'Be last', 'Be random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_94', question: 'Body paragraphs should:', options: ['Be random', 'Each develop one point with evidence', 'Be very short', 'Have no structure'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_95', question: 'Conclusion should:', options: ['Introduce new ideas', 'Summarize, provide closure', 'Be first', 'Be incomplete'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_96', question: 'Topic sentence:', options: ['Ends paragraph', 'Introduces main idea of paragraph', 'Is random', 'Not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_97', question: 'PEE paragraph structure:', options: ['Random', 'Point, Evidence, Explain', 'Only point', 'No structure'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_98', question: 'Linking words/phrases:', options: ['Disconnect ideas', 'Connect ideas smoothly', 'Are unnecessary', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_99', question: 'Paragraphs should have:', options: ['Random ideas', 'One main idea', 'Many unrelated ideas', 'No focus'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_100', question: 'Audience awareness means:', options: ['Ignore reader', 'Adapt writing to reader', 'Same for everyone', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_101', question: 'Purpose awareness means:', options: ['No goal', 'Clear reason for writing', 'Random', 'Confusing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_102', question: 'Editing checks:', options: ['Nothing', 'Grammar, spelling, punctuation, clarity', 'Only spelling', 'Only grammar'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_103', question: 'Proofreading checks:', options: ['Content only', 'Final errors in spelling/punctuation', 'Ideas only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_104', question: 'Drafting means:', options: ['Final version', 'Creating initial version', 'No writing', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_105', question: 'Planning helps:', options: ['Waste time', 'Organize ideas before writing', 'Confuse', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_106', question: 'Thesis statement:', options: ['Conclusion', 'Main argument stated upfront', 'Evidence', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_107', question: 'Coherence means:', options: ['Random ideas', 'Ideas flow logically', 'Confusion', 'No connection'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_108', question: 'Cohesion achieved through:', options: ['Random words', 'Linking words, pronouns, repetition', 'Long sentences', 'No connection'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_109', question: 'Formal writing avoids:', options: ['Proper grammar', 'Contractions, slang, colloquialisms', 'Structure', 'Clarity'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_110', question: 'Active voice preferred because:', options: ['Weaker', 'Clearer, more direct', 'Confusing', 'Passive'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // GRAMMAR & LANGUAGE (60 questions)
  { id: 'y8_eng_111', question: 'Simple sentence has:', options: ['Two clauses', 'One independent clause', 'Three clauses', 'No clause'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_112', question: 'Compound sentence has:', options: ['One clause', 'Two+ independent clauses', 'Only subordinate', 'No clauses'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_113', question: 'Complex sentence has:', options: ['Only independent', 'Independent + subordinate clause(s)', 'No clauses', 'Only subordinate'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_114', question: 'Independent clause:', options: ['Cannot stand alone', 'Can stand alone as sentence', 'Depends on another', 'Fragment'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_115', question: 'Subordinate clause:', options: ['Stands alone', 'Cannot stand alone', 'Is complete', 'Independent'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_116', question: 'Coordinating conjunctions (FANBOYS):', options: ['Because, although', 'For, and, nor, but, or, yet, so', 'Who, which', 'In, on, at'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_117', question: 'Subordinating conjunctions:', options: ['And, but, or', 'Because, although, when, if, since', 'For, nor', 'In, on'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_118', question: 'Relative pronoun:', options: ['I, you, he', 'Who, which, that, whose', 'And, but', 'In, on'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_119', question: 'Relative clause gives:', options: ['Main idea', 'Extra information about noun', 'No information', 'Command'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_120', question: 'Use "who" for:', options: ['Things', 'People', 'Places', 'Times'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_121', question: 'Use "which" for:', options: ['People', 'Things', 'Only animals', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_122', question: 'Modal verb shows:', options: ['Past only', 'Possibility, necessity, ability', 'Present only', 'Future only'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_123', question: 'Modal verbs:', options: ['Walk, run', 'Can, must, should, might', 'Happy, sad', 'Quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_124', question: 'Active voice:', options: ['Subject receives action', 'Subject performs action', 'No subject', 'Passive'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_125', question: 'Passive voice:', options: ['Subject performs', 'Subject receives action', 'Active', 'No verb'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_126', question: 'Active example:', options: ['The ball was kicked', 'Tom kicked the ball', 'It was done', 'Was seen'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_127', question: 'Passive example:', options: ['She wrote it', 'It was written by her', 'They write', 'I write'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_128', question: 'Subject-verb agreement:', options: ['Don\'t need to match', 'Subject and verb must agree', 'Only use singular', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_129', question: 'Correct agreement:', options: ['She walk', 'She walks', 'They walks', 'I walks'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_130', question: 'Past perfect tense:', options: ['I walk', 'I walked', 'I had walked', 'I will walk'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_131', question: 'Future perfect tense:', options: ['I walk', 'I will walk', 'I will have walked', 'I walked'], correctAnswer: 2, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_132', question: 'Present progressive:', options: ['I walk', 'I am walking', 'I walked', 'I will walk'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_133', question: 'Semi-colon used to:', options: ['End sentence', 'Link related clauses', 'Show question', 'Show excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_134', question: 'Colon used to:', options: ['End sentence', 'Introduce list/explanation', 'Show question', 'Show excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_135', question: 'Dash used for:', options: ['Same as hyphen', 'Sudden break/parenthesis', 'Question', 'Full stop'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_136', question: 'Hyphen used to:', options: ['End sentence', 'Join words (twenty-one)', 'Show question', 'Introduce list'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_137', question: 'Ellipsis shows:', options: ['Full stop', 'Omission or trailing off', 'Question', 'Comma'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_138', question: 'Parenthesis adds:', options: ['Main info', 'Extra/aside information', 'Title', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_139', question: 'Parenthesis uses:', options: ['Only full stops', 'Brackets, dashes, or commas', 'Only capitals', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_140', question: 'Apostrophe for possession:', options: ['Shows plural', 'Shows ownership', 'Shows question', 'Shows excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_141', question: 'Apostrophe for contraction:', options: ['Shows ownership', 'Shows missing letters', 'Shows plural', 'Shows past'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_142', question: 'Correct: "It\'s raining" means:', options: ['Its raining', 'It is raining', 'It was raining', 'Its rain'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_143', question: 'Correct: "The cat\'s toy" means:', options: ['Many cats', 'Toy belongs to cat', 'Cats are toys', 'Many toys'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_144', question: 'Plural possession: "dogs\' toys":', options: ['One dog', 'Many dogs', 'One toy', 'No dogs'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_145', question: 'Abstract noun:', options: ['Physical object', 'Idea, concept, feeling', 'Person', 'Place'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_146', question: 'Concrete noun:', options: ['Idea', 'Physical, tangible thing', 'Feeling', 'Concept'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_147', question: 'Collective noun:', options: ['One item', 'Group (team, flock)', 'Verb', 'Adjective'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_148', question: 'Proper noun:', options: ['Common name', 'Specific name (capitals)', 'Verb', 'Adjective'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_149', question: 'Synonym:', options: ['Opposite', 'Similar meaning', 'Rhyme', 'Homophone'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_150', question: 'Antonym:', options: ['Similar', 'Opposite meaning', 'Rhyme', 'Homophone'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_151', question: 'Homophone:', options: ['Same spelling', 'Sound same, different meanings', 'Opposite', 'Synonym'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_152', question: 'Homonym:', options: ['Different spelling', 'Same spelling/sound, different meanings', 'Opposite', 'Synonym'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_153', question: 'Prefix "dis-" means:', options: ['Again', 'Not/opposite', 'Before', 'After'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_154', question: 'Prefix "pre-" means:', options: ['After', 'Before', 'Not', 'Again'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_155', question: 'Suffix "-ness" creates:', options: ['Verb', 'Noun', 'Adjective', 'Adverb'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_156', question: 'Suffix "-ful" creates:', options: ['Noun', 'Verb', 'Adjective', 'Adverb'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_157', question: 'Connotation:', options: ['Literal meaning', 'Associated feelings/meanings', 'Definition', 'Spelling'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_158', question: 'Denotation:', options: ['Associated feelings', 'Literal dictionary meaning', 'Slang', 'Spelling'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_159', question: 'Standard English:', options: ['Slang', 'Formal, grammatically correct', 'Dialect', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_160', question: 'Dialect:', options: ['Standard English', 'Regional variation of language', 'Formal only', 'No variation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_161', question: 'Colloquialism:', options: ['Formal', 'Informal, everyday expression', 'Technical term', 'Foreign word'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_162', question: 'Idiom:', options: ['Literal phrase', 'Expression with non-literal meaning', 'Scientific term', 'Foreign phrase'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_163', question: 'Etymology studies:', options: ['Insects', 'Word origins and history', 'Grammar', 'Punctuation'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_164', question: 'Morphology studies:', options: ['Shapes', 'Word structure and formation', 'Sounds', 'Meaning'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_165', question: 'Semantics studies:', options: ['Grammar', 'Meaning', 'Pronunciation', 'Spelling'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_166', question: 'Syntax:', options: ['Meaning', 'Sentence structure', 'Spelling', 'Pronunciation'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_167', question: 'Ambiguity:', options: ['Clear meaning', 'Multiple possible meanings', 'One meaning', 'No meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_168', question: 'Context clues help:', options: ['Nothing', 'Determine word meaning', 'Grammar only', 'Spelling'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_169', question: 'Register varies based on:', options: ['Nothing', 'Audience and purpose', 'Only age', 'Only topic'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_170', question: 'Formal register uses:', options: ['Slang', 'Proper grammar, formal vocabulary', 'Casual language', 'Contractions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // SPELLING & VOCABULARY (30 questions)
  { id: 'y8_eng_171', question: 'Correct spelling:', options: ['Accomodate', 'Accommodate', 'Acommodate', 'Acomodate'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_172', question: 'Correct spelling:', options: ['Embarass', 'Embarras', 'Embarrass', 'Embaress'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_173', question: 'Correct spelling:', options: ['Occured', 'Occurred', 'Occured', 'Ocurred'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_174', question: 'Correct spelling:', options: ['Mischievous', 'Mischievious', 'Mischevious', 'Mischeivous'], correctAnswer: 0, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_175', question: 'Correct spelling:', options: ['Concious', 'Conscious', 'Consious', 'Concience'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_176', question: 'Correct: "___ very happy."', options: ['There', 'Their', 'They\'re', 'Thare'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_177', question: 'Correct: "___ book is this?"', options: ['Whose', 'Who\'s', 'Whos', 'Who\'se'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_178', question: 'Correct: "The decision is ___."', options: ['your\'s', 'yours', 'yours\'', 'your'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_179', question: 'Silent letter in "psychology":', options: ['p', 's', 'y', 'o'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_180', question: 'Silent letter in "debt":', options: ['d', 'b', 'e', 't'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_181', question: 'Silent letter in "receipt":', options: ['r', 'c', 'e', 'p'], correctAnswer: 3, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_182', question: 'I before E rule: "believe" uses:', options: ['ei', 'ie', 'no rule', 'random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_183', question: 'Exception to I before E: "receive" uses:', options: ['ie', 'ei', 'no rule', 'random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_184', question: 'Double consonant when adding suffix: "running" from:', options: ['run', 'rune', 'runn', 'runnin'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_185', question: 'Drop E when adding -ing: "hoping" from:', options: ['hop', 'hopping', 'hope', 'hopi'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_186', question: 'Y to I rule: "happiness" from:', options: ['happy', 'happyness', 'happi', 'happines'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_187', question: 'Plural of "journey":', options: ['journies', 'journeys', 'journey\'s', 'journeies'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_188', question: 'Plural of "knife":', options: ['knifes', 'knives', 'knife\'s', 'knive'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_189', question: 'Plural of "criterion":', options: ['criterions', 'criteria', 'criterion\'s', 'criterias'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y8_eng_190', question: 'Word root "bio" means:', options: ['Life', 'Earth', 'Water', 'Air'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_191', question: 'Word root "geo" means:', options: ['Life', 'Earth', 'Water', 'Air'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_192', question: 'Word root "graph" means:', options: ['Speak', 'Write', 'See', 'Hear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_193', question: 'Word root "tele" means:', options: ['Near', 'Far/distant', 'Above', 'Below'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_194', question: 'Word root "auto" means:', options: ['Other', 'Self', 'Many', 'Few'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_195', question: 'Word family of "joy":', options: ['Jump, just', 'Joyful, enjoy, joyous', 'Join, joint', 'Judge, jury'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_196', question: 'Correct: "___ going to the park."', options: ['Were', 'Where', 'We\'re', 'Wear'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_197', question: 'Correct: "The ___ was rough."', options: ['see', 'sea', 'c', 'seat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y8_eng_198', question: 'Affect vs Effect: "This will ___ you."', options: ['affect', 'effect', 'both', 'neither'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_199', question: 'Affect vs Effect: "The ___was dramatic."', options: ['affect', 'effect', 'both', 'neither'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y8_eng_200', question: 'Correct: "She was ___ to go."', options: ['aloud', 'allowed', 'allow', 'a loud'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 }
];
