// Year 1 Mathematics Trivia Questions
// Based on UK Year 1 Maths Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_1_MATHS_QUESTIONS = [
  // NUMBER AND PLACE VALUE - Counting (25 questions)
  { id: 'y1_math_1', question: 'Count the apples: 🍎🍎🍎🍎', options: ['3', '4', '5', '6'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_2', question: 'Count the stars: ⭐⭐⭐⭐⭐⭐', options: ['5', '6', '7', '8'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_3', question: 'How many fingers do you have on one hand?', options: ['4', '5', '6', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_4', question: 'Count the balloons: 🎈🎈🎈🎈🎈🎈🎈🎈', options: ['7', '8', '9', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_5', question: 'What number comes after 5?', options: ['4', '6', '7', '8'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_6', question: 'What number comes before 10?', options: ['8', '9', '11', '12'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_7', question: 'Count backwards: 5, 4, 3, 2, ___', options: ['0', '1', '6', '3'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_8', question: 'How many is 10?', options: ['🔟', '⑤', '⑮', '⑳'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_9', question: 'Count the dots: • • • • • • • • • •', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_10', question: 'What number is between 7 and 9?', options: ['6', '8', '10', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_11', question: 'Count: 1, 2, 3, 4, ___', options: ['3', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_12', question: 'How many days in a week?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_13', question: 'Count to 20: Which comes after 15?', options: ['14', '16', '17', '20'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_14', question: 'What is 1 more than 12?', options: ['11', '12', '13', '14'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_15', question: 'What is 1 less than 8?', options: ['6', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_16', question: 'How many fingers on two hands?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_17', question: 'Count in 2s: 2, 4, 6, ___', options: ['7', '8', '9', '10'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_18', question: 'Count in 5s: 5, 10, ___', options: ['11', '12', '15', '20'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_19', question: 'Count in 10s: 10, 20, ___', options: ['25', '30', '35', '40'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_20', question: 'Which is the smallest number?', options: ['9', '3', '7', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_21', question: 'Which is the biggest number?', options: ['4', '12', '8', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_22', question: 'Put in order: 3, 1, 2. What comes first?', options: ['1', '2', '3', '0'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_23', question: 'What number is missing? 8, 9, ___, 11', options: ['7', '10', '12', '13'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_24', question: 'How do you write the number "seven"?', options: ['6', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_25', question: 'Which number is equal to 10 + 10?', options: ['10', '15', '20', '25'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },

  // ADDITION (25 questions)
  { id: 'y1_math_26', question: 'What is 1 + 1?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_27', question: 'What is 2 + 2?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_28', question: 'What is 3 + 1?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_29', question: 'What is 5 + 2?', options: ['6', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_30', question: 'What is 4 + 3?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_31', question: 'What is 6 + 2?', options: ['7', '8', '9', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_32', question: 'What is 5 + 5?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_33', question: 'What is 7 + 3?', options: ['9', '10', '11', '12'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_34', question: 'What is 8 + 2?', options: ['9', '10', '11', '12'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_35', question: 'What is 9 + 1?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_36', question: 'What is 6 + 4?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_37', question: 'If you have 3 apples and get 2 more, how many do you have?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_38', question: 'What is 10 + 5?', options: ['12', '13', '14', '15'], correctAnswer: 3, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_39', question: 'What is 8 + 4?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_40', question: 'What is 7 + 5?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_41', question: 'What is 9 + 3?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_42', question: 'What is 6 + 6?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_43', question: 'If I have 4 toys and my friend gives me 4 more, how many do I have?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_44', question: 'What is 10 + 10?', options: ['15', '18', '20', '25'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_45', question: 'What is 0 + 7?', options: ['0', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_46', question: 'What is 5 + 4?', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_47', question: 'What is 3 + 3 + 3?', options: ['6', '7', '8', '9'], correctAnswer: 3, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_48', question: 'What is 2 + 3 + 4?', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_49', question: 'What is 1 + 2 + 3?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_50', question: 'What is 11 + 9?', options: ['18', '19', '20', '21'], correctAnswer: 2, difficulty: 'hard', xpReward: 20 },

  // SUBTRACTION (25 questions)
  { id: 'y1_math_51', question: 'What is 2 - 1?', options: ['0', '1', '2', '3'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_52', question: 'What is 5 - 2?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_53', question: 'What is 4 - 1?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_54', question: 'What is 6 - 3?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_55', question: 'What is 7 - 4?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_56', question: 'What is 8 - 3?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_57', question: 'What is 9 - 4?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_58', question: 'What is 10 - 5?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_59', question: 'What is 10 - 3?', options: ['6', '7', '8', '9'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_60', question: 'What is 8 - 8?', options: ['0', '1', '8', '16'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_61', question: 'If you have 7 sweets and eat 2, how many are left?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_62', question: 'What is 12 - 5?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_63', question: 'What is 15 - 10?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_64', question: 'What is 11 - 6?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_65', question: 'What is 13 - 7?', options: ['5', '6', '7', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_66', question: 'What is 14 - 8?', options: ['5', '6', '7', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_67', question: 'If I have 10 pencils and give away 4, how many are left?', options: ['5', '6', '7', '8'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_68', question: 'What is 20 - 10?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_69', question: 'What is 9 - 9?', options: ['0', '1', '9', '18'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_70', question: 'What is 16 - 9?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_71', question: 'What is 18 - 9?', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_72', question: 'What is 17 - 8?', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_73', question: 'There are 12 birds. 5 fly away. How many are left?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_74', question: 'What is 19 - 10?', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_75', question: 'What is 20 - 15?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },

  // MULTIPLICATION & DIVISION BASICS (15 questions)
  { id: 'y1_math_76', question: 'What is double 2?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_77', question: 'What is double 5?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_78', question: 'What is double 3?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_79', question: 'What is double 4?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_80', question: 'What is half of 10?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_81', question: 'What is half of 6?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_82', question: 'What is half of 8?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_83', question: 'If you have 2 groups of 3 apples, how many apples in total?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_84', question: 'If you have 3 groups of 2 bananas, how many bananas in total?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_85', question: 'Share 6 sweets equally between 2 children. How many each?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_86', question: 'Share 8 crayons equally between 2 children. How many each?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_87', question: 'What is double 10?', options: ['15', '18', '20', '25'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_88', question: 'What is half of 20?', options: ['8', '9', '10', '11'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_89', question: '2 + 2 + 2 is the same as:', options: ['2 × 2', '2 × 3', '3 × 2', '3 + 2'], correctAnswer: 2, difficulty: 'hard', xpReward: 20 },
  { id: 'y1_math_90', question: 'How many 2s make 10?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },

  // FRACTIONS (10 questions)
  { id: 'y1_math_91', question: 'If you cut a pizza into 2 equal parts, each part is:', options: ['A whole', 'A half', 'A quarter', 'A third'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_92', question: 'If you cut a cake into 4 equal parts, each part is:', options: ['A whole', 'A half', 'A quarter', 'A third'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_93', question: 'How many halves make a whole?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_94', question: 'How many quarters make a whole?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_95', question: 'Which is bigger: a half or a quarter?', options: ['Half', 'Quarter', 'Same size', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_96', question: 'If I eat half of 4 cookies, how many did I eat?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_97', question: 'If I eat a quarter of 8 sweets, how many did I eat?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_98', question: 'Two halves are equal to:', options: ['A quarter', 'A half', 'A whole', 'Two wholes'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_99', question: 'One half of 10 is:', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_100', question: 'One quarter of 12 is:', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'hard', xpReward: 20 },

  // MEASUREMENT - Length & Height (12 questions)
  { id: 'y1_math_101', question: 'Which is longer: a ruler or a pencil?', options: ['Ruler', 'Pencil', 'Same length', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_102', question: 'Which is taller: a house or a person?', options: ['House', 'Person', 'Same height', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_103', question: 'Which is shorter: a car or a bus?', options: ['Car', 'Bus', 'Same length', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_104', question: 'We measure length using:', options: ['Kilograms', 'Centimetres', 'Litres', 'Hours'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_105', question: 'What tool do we use to measure length?', options: ['Scales', 'Ruler', 'Clock', 'Thermometer'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_106', question: 'Which unit measures length?', options: ['Metre', 'Litre', 'Kilogram', 'Hour'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_107', question: 'Is a giraffe tall or short?', options: ['Tall', 'Short', 'Medium', 'Small'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_108', question: 'If pencil A is 10cm and pencil B is 15cm, which is longer?', options: ['Pencil A', 'Pencil B', 'Same length', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_109', question: 'What does "cm" stand for?', options: ['Centimetre', 'Cubic metre', 'Circle metre', 'Central metre'], correctAnswer: 0, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_110', question: 'Which is the longest?', options: ['5 cm', '10 cm', '3 cm', '7 cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_111', question: 'A mouse is shorter than:', options: ['An ant', 'A cat', 'A ladybird', 'A bee'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_112', question: '100 centimetres equals:', options: ['1 metre', '10 metres', '100 metres', '1000 metres'], correctAnswer: 0, difficulty: 'hard', xpReward: 20 },

  // MEASUREMENT - Weight (8 questions)
  { id: 'y1_math_113', question: 'Which is heavier: an elephant or a mouse?', options: ['Elephant', 'Mouse', 'Same weight', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_114', question: 'Which is lighter: a feather or a book?', options: ['Feather', 'Book', 'Same weight', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_115', question: 'We measure weight using:', options: ['Rulers', 'Scales', 'Clocks', 'Jugs'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_116', question: 'Which unit measures weight?', options: ['Metre', 'Litre', 'Kilogram', 'Hour'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_117', question: 'What do we use to weigh things?', options: ['Ruler', 'Scales', 'Thermometer', 'Clock'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_118', question: 'Which is heavier: 5kg or 2kg?', options: ['5 kg', '2 kg', 'Same weight', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_119', question: 'A bag of sugar weighs about:', options: ['1 gram', '1 kilogram', '10 kilograms', '100 kilograms'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_120', question: 'What does "kg" stand for?', options: ['Kilograme', 'Kilogram', 'Kilo-gram', 'King-gram'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // MEASUREMENT - Capacity (8 questions)
  { id: 'y1_math_121', question: 'Which holds more: a cup or a bucket?', options: ['Cup', 'Bucket', 'Same amount', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_122', question: 'Which holds less: a spoon or a jug?', options: ['Spoon', 'Jug', 'Same amount', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_123', question: 'We measure how much liquid a container holds using:', options: ['Centimetres', 'Kilograms', 'Litres', 'Hours'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_124', question: 'Which unit measures capacity?', options: ['Metre', 'Litre', 'Kilogram', 'Centimetre'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_125', question: 'If a bottle is full, it holds:', options: ['Nothing', 'Its maximum capacity', 'Half', 'A little'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_126', question: 'If a glass is empty, it holds:', options: ['Everything', 'Nothing', 'Half', 'A lot'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_127', question: 'Which holds more: 5 litres or 2 litres?', options: ['5 litres', '2 litres', 'Same amount', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_128', question: 'A bottle of water holds about:', options: ['1 litre', '10 litres', '100 litres', '1000 litres'], correctAnswer: 0, difficulty: 'medium', xpReward: 15 },

  // GEOMETRY - 2D Shapes (15 questions)
  { id: 'y1_math_129', question: 'How many sides does a triangle have?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_130', question: 'How many sides does a square have?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_131', question: 'How many sides does a rectangle have?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_132', question: 'How many sides does a circle have?', options: ['0', '1', '2', '3'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_133', question: 'Which shape has 3 corners?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_134', question: 'Which shape has 4 equal sides?', options: ['Triangle', 'Square', 'Circle', 'Pentagon'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_135', question: 'Which shape is round?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_136', question: 'What shape is a door?', options: ['Circle', 'Triangle', 'Rectangle', 'Square'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_137', question: 'What shape is a ball when you look at it from any side?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_138', question: 'A square and a rectangle both have:', options: ['3 sides', '4 sides', '5 sides', '6 sides'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_139', question: 'How many corners does a square have?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_140', question: 'Which shape has no corners?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_141', question: 'What shape is a slice of pizza?', options: ['Circle', 'Triangle', 'Square', 'Rectangle'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_142', question: 'How many sides does a pentagon have?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_143', question: 'How many sides does a hexagon have?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },

  // GEOMETRY - 3D Shapes (10 questions)
  { id: 'y1_math_144', question: 'A box is a:', options: ['Circle', 'Square', 'Cube', 'Triangle'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_145', question: 'What shape is a ball?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_146', question: 'What shape is a tin can?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_147', question: 'What shape is an ice cream cone?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 3, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_148', question: 'How many faces does a cube have?', options: ['4', '5', '6', '8'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_149', question: 'A dice is a:', options: ['Sphere', 'Cube', 'Cylinder', 'Cone'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_150', question: 'Which 3D shape can roll?', options: ['Cube only', 'Sphere only', 'Both sphere and cylinder', 'Neither'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_151', question: 'What shape is a birthday hat?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 3, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_152', question: 'A football is a:', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_153', question: 'Which shape has flat faces?', options: ['Sphere', 'Cube', 'Ball', 'Marble'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // POSITION & DIRECTION (12 questions)
  { id: 'y1_math_154', question: 'If something is above you, it is:', options: ['Below', 'Higher up', 'Behind', 'In front'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_155', question: 'If something is behind you, where is it?', options: ['In front', 'At your back', 'Above', 'Below'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_156', question: 'If you turn right, then turn right again, which way are you facing?', options: ['Forward', 'Left', 'Backward', 'Same direction'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_157', question: 'The opposite of left is:', options: ['Up', 'Down', 'Right', 'Forward'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_158', question: 'The opposite of up is:', options: ['Left', 'Right', 'Down', 'Forward'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_159', question: 'If the ball is inside the box, where is it?', options: ['Outside', 'In the box', 'Above', 'Below'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_160', question: 'If you are between two trees, you are:', options: ['In front of both', 'Behind both', 'In the middle', 'Above both'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_161', question: 'If the cat is under the table, where is it?', options: ['On top', 'Below the table', 'Beside', 'In front'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_162', question: 'A full turn is:', options: ['Half a circle', 'A quarter circle', 'A complete circle', 'Two circles'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_163', question: 'A half turn means you face:', options: ['The same way', 'The opposite way', 'Right', 'Left'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_164', question: 'A quarter turn to the right from facing forward means you face:', options: ['Backward', 'Left', 'Right', 'Forward'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_165', question: 'The book is next to the pen. They are:', options: ['Far apart', 'Side by side', 'One above the other', 'Opposite'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // TIME (15 questions)
  { id: 'y1_math_166', question: 'How many hours are in a day?', options: ['12', '20', '24', '30'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_167', question: 'How many minutes are in 1 hour?', options: ['30', '50', '60', '100'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_168', question: 'Which comes first: morning or afternoon?', options: ['Morning', 'Afternoon', 'Same time', 'Evening'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_169', question: 'When do we eat breakfast?', options: ['Evening', 'Night', 'Morning', 'Afternoon'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_170', question: 'When do we go to bed?', options: ['Morning', 'Afternoon', 'Evening', 'Night'], correctAnswer: 3, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_171', question: 'What time is shown when the hour hand points to 12 and minute hand to 12?', options: ['1 o\'clock', '11 o\'clock', '12 o\'clock', '6 o\'clock'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_172', question: 'When the hour hand points to 3 and minute hand to 12, what time is it?', options: ['2 o\'clock', '3 o\'clock', '4 o\'clock', '12 o\'clock'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_173', question: 'What comes after Wednesday?', options: ['Tuesday', 'Thursday', 'Friday', 'Monday'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_174', question: 'How many days are in a week?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_175', question: 'Which is the first day of the week?', options: ['Monday', 'Sunday', 'Saturday', 'Tuesday'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_176', question: 'How many months are in a year?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_177', question: 'Which month comes after January?', options: ['December', 'February', 'March', 'April'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_178', question: 'The short hand on a clock shows:', options: ['Minutes', 'Hours', 'Seconds', 'Days'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_179', question: 'When it is half past 2, the hour hand is:', options: ['On the 2', 'Between 2 and 3', 'On the 3', 'On the 6'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_180', question: 'How many seconds are in 1 minute?', options: ['30', '50', '60', '100'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },

  // MONEY (10 questions)
  { id: 'y1_math_181', question: 'Which coin is worth more: 1p or 2p?', options: ['1p', '2p', 'Same value', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_182', question: 'How many 1p coins equal 5p?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_183', question: 'How many 2p coins equal 10p?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_184', question: 'What coin is worth 10 pence?', options: ['1p', '5p', '10p', '20p'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_185', question: 'If you have 5p and get 5p more, how much do you have?', options: ['5p', '10p', '15p', '20p'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_186', question: 'Which is worth more: 10p or 20p?', options: ['10p', '20p', 'Same value', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_187', question: 'If a sweet costs 2p and you have 10p, how many sweets can you buy?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_188', question: 'What does "p" stand for in money?', options: ['Pound', 'Pence', 'Penny', 'Price'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_189', question: 'How many pennies make 10p?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_190', question: '100 pence equals:', options: ['50p', '£1', '£2', '£5'], correctAnswer: 1, difficulty: 'hard', xpReward: 20 },

  // DATA HANDLING (10 questions)
  { id: 'y1_math_191', question: 'A tally chart uses marks to:', options: ['Colour pictures', 'Count things', 'Tell time', 'Measure length'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_192', question: 'In a pictogram, each picture stands for:', options: ['Nothing', 'One or more items', 'A colour', 'A shape'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_193', question: 'If there are 5 pictures of apples and each stands for 1 apple, how many apples?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_194', question: 'A bar chart shows information using:', options: ['Pictures', 'Bars', 'Words only', 'Numbers only'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_195', question: 'If the bar for "cats" is taller than the bar for "dogs", there are:', options: ['More dogs', 'More cats', 'Same amount', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_196', question: 'We collect information to:', options: ['Waste time', 'Answer questions', 'Make mess', 'Sleep'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_197', question: 'Sorting objects helps us:', options: ['Make a mess', 'See patterns and count', 'Lose things', 'Break things'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_198', question: 'In a survey about favorite colours, if 8 chose blue and 5 chose red, which is more popular?', options: ['Red', 'Blue', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_math_199', question: 'A table shows information in:', options: ['Pictures only', 'Rows and columns', 'Circles', 'Lines'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_math_200', question: 'Charts and graphs help us to:', options: ['Write stories', 'See information clearly', 'Draw pictures', 'Play games'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 }
];
