// Year 3 Science Trivia Questions
// Based on UK Year 3 Science Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_3_SCIENCE_QUESTIONS = [
  // PLANTS (40 questions)
  // Functions of parts of flowering plants
  { id: 'y3_sci_1', question: 'What is the main function of roots?', options: ['Make flowers', 'Absorb water and nutrients from soil', 'Make seeds', 'Produce oxygen'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_2', question: 'What does the stem/trunk do?', options: ['Absorb sunlight', 'Support the plant and transport water', 'Make food', 'Attract insects'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_3', question: 'What is the main function of leaves?', options: ['Store water', 'Make food using sunlight', 'Attract insects', 'Anchor the plant'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_4', question: 'What is the function of flowers?', options: ['Store food', 'Support the plant', 'Reproduction (making seeds)', 'Absorb water'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_5', question: 'Which part of the plant anchors it to the ground?', options: ['Leaves', 'Stem', 'Roots', 'Flowers'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  
  // Requirements of plants
  { id: 'y3_sci_6', question: 'What do plants need to grow? (Select the most complete answer)', options: ['Only water', 'Only sunlight', 'Air, light, water, nutrients, and space', 'Only soil'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_7', question: 'Why do plants need light?', options: ['To keep warm', 'To make food through photosynthesis', 'To drink', 'To breathe'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_8', question: 'Why do plants need water?', options: ['For transportation and photosynthesis', 'Only for drinking', 'To stay heavy', 'To make flowers'], correctAnswer: 0, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_9', question: 'What nutrients do plants get from soil?', options: ['Oxygen', 'Minerals like nitrogen and phosphorus', 'Only water', 'Sunlight'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_10', question: 'Why do plants need room to grow?', options: ['To look nice', 'So roots and leaves can spread', 'To stay warm', 'To make seeds'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  
  // Transportation of water
  { id: 'y3_sci_11', question: 'How does water move up a plant?', options: ['Through the leaves', 'Through tubes in the stem', 'Through the flowers', 'Through the air'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_12', question: 'Water enters the plant through:', options: ['Leaves', 'Flowers', 'Roots', 'Seeds'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_13', question: 'Where does the water go after entering the roots?', options: ['Stays in roots', 'Moves up the stem to leaves and flowers', 'Goes to seeds', 'Stays in soil'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_14', question: 'What happens to excess water in plants?', options: ['Stays forever', 'Evaporates from leaves', 'Goes to flowers', 'Makes seeds'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  
  // Life cycle of flowering plants
  { id: 'y3_sci_15', question: 'What is pollination?', options: ['Growing leaves', 'Transfer of pollen from one flower to another', 'Making roots', 'Drinking water'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_16', question: 'What helps with pollination?', options: ['Rocks', 'Insects, wind, and animals', 'Soil only', 'Rain only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_17', question: 'What happens after pollination?', options: ['Plant dies', 'Seeds form', 'Roots grow', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_18', question: 'Where are seeds formed?', options: ['In roots', 'In leaves', 'In flowers', 'In stems'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_19', question: 'What is seed dispersal?', options: ['Seeds dying', 'Seeds spreading away from parent plant', 'Seeds staying still', 'Seeds growing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_20', question: 'How can seeds be dispersed?', options: ['Only by falling', 'By wind, water, animals, and explosion', 'They don\'t move', 'Only by humans'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_21', question: 'Why is seed dispersal important?', options: ['To waste seeds', 'So plants don\'t compete with parent plant', 'To make flowers', 'No reason'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_22', question: 'What do seeds need to germinate?', options: ['Only air', 'Water, warmth, and oxygen', 'Only light', 'Only soil'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_23', question: 'Which comes first in a flowering plant\'s life cycle?', options: ['Flowering', 'Seed germination', 'Pollination', 'Seed dispersal'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_24', question: 'Bees help plants by:', options: ['Eating them', 'Pollinating flowers', 'Breaking stems', 'Digging roots'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  
  // Investigating plant growth
  { id: 'y3_sci_25', question: 'If a plant gets no light, it will:', options: ['Grow normally', 'Become weak and yellow', 'Grow faster', 'Turn blue'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_26', question: 'A plant with no water will:', options: ['Grow better', 'Wilt and may die', 'Stay the same', 'Grow faster'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_27', question: 'Plants grow best when they have:', options: ['No light', 'No water', 'Light, water, nutrients, and space', 'Only soil'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_28', question: 'To test how light affects plant growth, you should:', options: ['Give different amounts of light', 'Change everything', 'Do nothing', 'Only water them'], correctAnswer: 0, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_29', question: 'In a fair test, you change:', options: ['Everything', 'Only one variable', 'Nothing', 'All variables'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_30', question: 'Which plant part grows toward light?', options: ['Roots', 'Stem and leaves', 'Seeds', 'Flowers only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_31', question: 'If you plant seeds in poor soil vs rich soil, what might happen?', options: ['Same growth', 'Rich soil plants grow better', 'Poor soil grows better', 'Both die'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_32', question: 'What is photosynthesis?', options: ['Drinking water', 'Making food using sunlight', 'Growing roots', 'Making flowers'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_33', question: 'During photosynthesis, plants take in:', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_34', question: 'During photosynthesis, plants release:', options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_35', question: 'Why are plants important for us?', options: ['No reason', 'They provide oxygen and food', 'Only decoration', 'They waste space'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_36', question: 'Which grows first from a seed?', options: ['Flower', 'Root', 'Leaves', 'Stem'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_37', question: 'A dandelion disperses seeds by:', options: ['Water', 'Wind', 'Animals eating', 'Explosion'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_38', question: 'Fruits help seed dispersal by:', options: ['Killing seeds', 'Attracting animals to eat and spread seeds', 'Stopping growth', 'Making seeds heavy'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_39', question: 'What color are most healthy leaves?', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_40', question: 'Chlorophyll in leaves helps plants:', options: ['Drink water', 'Capture sunlight for photosynthesis', 'Make roots', 'Attract insects'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },

  // ANIMALS, INCLUDING HUMANS (40 questions)
  // Nutrition and balanced diet
  { id: 'y3_sci_41', question: 'What is a balanced diet?', options: ['Only vegetables', 'Eating right amounts of different food groups', 'Only meat', 'Only fruits'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_42', question: 'How many main food groups are there?', options: ['3', '5', '7', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_43', question: 'Which food group gives us energy?', options: ['Vitamins', 'Carbohydrates', 'Water', 'Minerals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_44', question: 'Which food group helps build muscles?', options: ['Carbohydrates', 'Proteins', 'Fruits', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_45', question: 'Which food group includes milk and cheese?', options: ['Fruits', 'Vegetables', 'Dairy', 'Grains'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_46', question: 'Why do we need vitamins and minerals?', options: ['Only for taste', 'To keep body healthy and functioning', 'To gain weight', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_47', question: 'Which nutrient helps with digestion?', options: ['Fat', 'Fiber', 'Sugar', 'Salt'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_48', question: 'What happens if you eat too much sugar?', options: ['You become healthier', 'Tooth decay and weight gain', 'You grow taller', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_49', question: 'Why should we eat vegetables?', options: ['They taste bad', 'They provide vitamins, minerals, and fiber', 'No reason', 'Only for color'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_50', question: 'Water is important because:', options: ['It tastes good only', 'Our body needs it for all functions', 'It\'s not important', 'Only for washing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_51', question: 'Which is a healthy snack?', options: ['Candy', 'Fruit', 'Chips', 'Soda'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_52', question: 'Too much fat can lead to:', options: ['Strong bones', 'Health problems like obesity', 'Better eyesight', 'Faster running'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_53', question: 'Which food is high in protein?', options: ['Apple', 'Bread', 'Chicken', 'Candy'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_54', question: 'Which food is high in carbohydrates?', options: ['Fish', 'Rice', 'Cheese', 'Butter'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_55', question: 'Why should we limit junk food?', options: ['It\'s too healthy', 'It lacks nutrients and has too much sugar/fat', 'It\'s too expensive', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  
  // Skeletons and muscles
  { id: 'y3_sci_56', question: 'What does the skeleton do?', options: ['Only looks nice', 'Supports, protects, and helps movement', 'Makes food', 'Breathes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_57', question: 'How many bones does an adult human have?', options: ['106', '206', '306', '406'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_58', question: 'What does the skull protect?', options: ['Heart', 'Brain', 'Stomach', 'Lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_59', question: 'What do ribs protect?', options: ['Brain', 'Heart and lungs', 'Stomach only', 'Arms'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_60', question: 'Muscles help us:', options: ['Think', 'Move', 'Digest only', 'Breathe only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_61', question: 'How do muscles work?', options: ['They push only', 'They pull by contracting', 'They twist only', 'They don\'t move'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_62', question: 'Muscles work in:', options: ['Groups of 10', 'Pairs', 'Alone', 'Groups of 100'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_63', question: 'When you bend your arm, which muscle contracts?', options: ['Leg muscle', 'Bicep', 'Tricep', 'Back muscle'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_64', question: 'When you straighten your arm, which muscle contracts?', options: ['Bicep', 'Tricep', 'Shoulder', 'Neck'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_65', question: 'What are muscles attached to?', options: ['Nothing', 'Bones', 'Skin only', 'Hair'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_66', question: 'Vertebrates are animals with:', options: ['No bones', 'A backbone', 'Only soft bodies', 'No muscles'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_67', question: 'Invertebrates are animals:', options: ['With a backbone', 'Without a backbone', 'Only mammals', 'Only birds'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_68', question: 'Which is a vertebrate?', options: ['Worm', 'Snail', 'Dog', 'Butterfly'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_69', question: 'Which is an invertebrate?', options: ['Cat', 'Fish', 'Spider', 'Bird'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_70', question: 'Humans are:', options: ['Invertebrates', 'Vertebrates', 'Neither', 'Sometimes both'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_71', question: 'The backbone is also called:', options: ['Skull', 'Spine', 'Ribs', 'Pelvis'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_72', question: 'Joints are where:', options: ['Muscles end', 'Bones meet', 'Skin folds', 'Nothing happens'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_73', question: 'What is the largest bone in the human body?', options: ['Skull', 'Femur (thigh bone)', 'Spine', 'Rib'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_74', question: 'Exercise helps muscles become:', options: ['Weaker', 'Stronger', 'Smaller', 'Disappear'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_75', question: 'Bones are made strong by:', options: ['Water', 'Calcium', 'Sugar', 'Fat'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_76', question: 'An exoskeleton is:', options: ['Inside the body', 'Outside the body (like insects)', 'Not real', 'Only in humans'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_77', question: 'Which has an exoskeleton?', options: ['Dog', 'Beetle', 'Human', 'Fish'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_78', question: 'Why do we need a balanced diet for bones?', options: ['For color', 'To provide calcium and nutrients', 'For taste', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_79', question: 'The heart is a:', options: ['Bone', 'Muscle', 'Joint', 'Skeleton'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_80', question: 'When one muscle in a pair contracts, the other:', options: ['Also contracts', 'Relaxes', 'Disappears', 'Breaks'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // ROCKS (30 questions)
  { id: 'y3_sci_81', question: 'Rocks can be grouped by their:', options: ['Color and age', 'Appearance and physical properties', 'Size only', 'Weight only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_82', question: 'Which is a property of rocks?', options: ['Hardness', 'Taste', 'Smell', 'Sound'], correctAnswer: 0, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_83', question: 'Granite is:', options: ['Soft', 'Hard', 'Liquid', 'Gas'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_84', question: 'Chalk is:', options: ['Very hard', 'Soft and crumbly', 'Liquid', 'Transparent'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_85', question: 'What are the three main types of rocks?', options: ['Big, small, medium', 'Igneous, sedimentary, metamorphic', 'Hard, soft, medium', 'Old, new, ancient'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_86', question: 'Igneous rocks form from:', options: ['Water', 'Cooled lava or magma', 'Plants', 'Animals'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_87', question: 'Sedimentary rocks form from:', options: ['Lava', 'Layers of sediment pressed together', 'Air', 'Fire'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_88', question: 'Metamorphic rocks form from:', options: ['Existing rocks changed by heat and pressure', 'Water only', 'Air only', 'Nothing'], correctAnswer: 0, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_89', question: 'Fossils are usually found in:', options: ['Igneous rock', 'Sedimentary rock', 'Metamorphic rock', 'All rocks equally'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_90', question: 'How are fossils formed?', options: ['Animals turn to stone overnight', 'Remains buried and preserved over millions of years', 'Plants change color', 'Rocks melt'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_91', question: 'What are fossils?', options: ['New rocks', 'Preserved remains or traces of ancient life', 'Fresh plants', 'Modern animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_92', question: 'Soil is made from:', options: ['Only water', 'Rocks and organic matter', 'Only air', 'Only plants'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_93', question: 'Organic matter in soil includes:', options: ['Rocks only', 'Dead plants and animals', 'Water only', 'Air only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_94', question: 'Why is soil important?', options: ['For decoration', 'Plants grow in it', 'It looks nice', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_95', question: 'Permeability means:', options: ['How hard a rock is', 'How well water passes through', 'How colorful it is', 'How old it is'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_96', question: 'A permeable rock:', options: ['Blocks water', 'Lets water pass through', 'Is very hard', 'Is very colorful'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_97', question: 'An impermeable rock:', options: ['Lets water through easily', 'Blocks water', 'Is soft', 'Is transparent'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_98', question: 'Durability means:', options: ['How water passes through', 'How well a rock resists weathering', 'How colorful it is', 'How old it is'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_99', question: 'Marble is used for buildings because it is:', options: ['Soft and weak', 'Hard and durable', 'Permeable', 'Cheap only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_100', question: 'Sandstone is made of:', options: ['Mud', 'Sand grains pressed together', 'Lava', 'Ice'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_101', question: 'Why are some rocks shiny?', options: ['They\'re wet', 'They contain crystals or minerals', 'They\'re painted', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_102', question: 'Weathering means:', options: ['Rocks staying the same', 'Rocks breaking down over time', 'Rocks melting', 'Rocks flying'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_103', question: 'Erosion is:', options: ['Rocks staying still', 'Worn rock materials being moved', 'Rocks melting', 'Rocks growing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_104', question: 'Which can cause weathering?', options: ['Water, wind, ice', 'Only humans', 'Nothing', 'Only plants'], correctAnswer: 0, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_105', question: 'Layers in sedimentary rock form because:', options: ['They look nice', 'Sediment builds up over time', 'Magic', 'Temperature changes'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_106', question: 'A geologist studies:', options: ['Plants', 'Animals', 'Rocks and Earth', 'Weather only'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_107', question: 'Limestone can contain:', options: ['Lava', 'Fossils', 'Ice', 'Plastic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_108', question: 'Pumice is a rock that:', options: ['Sinks in water', 'Floats in water', 'Melts in water', 'Explodes in water'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_109', question: 'We use rocks for:', options: ['Nothing', 'Building, roads, and tools', 'Only decoration', 'Only museums'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_110', question: 'Which rock is often used for roofs?', options: ['Chalk', 'Slate', 'Sand', 'Pumice'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // LIGHT (30 questions)
  { id: 'y3_sci_111', question: 'Light helps us:', options: ['Sleep', 'See', 'Eat only', 'Smell'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_112', question: 'Darkness is:', options: ['A type of light', 'The absence of light', 'Very bright', 'A color'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_113', question: 'Light travels in:', options: ['Circles', 'Straight lines', 'Zigzags', 'Spirals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_114', question: 'Which is a light source?', options: ['Moon', 'Sun', 'Mirror', 'Book'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_115', question: 'The moon:', options: ['Makes its own light', 'Reflects light from the Sun', 'Never has light', 'Is a light bulb'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_116', question: 'Reflection is when light:', options: ['Disappears', 'Bounces off a surface', 'Goes through', 'Stops'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_117', question: 'Which surface reflects light well?', options: ['Rough wood', 'Mirror', 'Black cloth', 'Sponge'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_118', question: 'Smooth surfaces reflect light:', options: ['Poorly', 'Well', 'Not at all', 'Only at night'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_119', question: 'Rough surfaces reflect light:', options: ['In many directions (scattered)', 'In one direction', 'Not at all', 'Only upward'], correctAnswer: 0, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_120', question: 'We should never look directly at:', options: ['Books', 'The Sun', 'Mirrors', 'Windows'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_121', question: 'Why not look directly at the Sun?', options: ['It\'s boring', 'It can damage your eyes', 'It\'s too small', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_122', question: 'To protect eyes from sun, wear:', options: ['Nothing', 'Sunglasses', 'Regular glasses only', 'Hats only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_123', question: 'A shadow forms when:', options: ['Light passes through', 'An opaque object blocks light', 'It rains', 'It\'s windy'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_124', question: 'Opaque means:', options: ['See-through', 'Light cannot pass through', 'Very bright', 'Colorful'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_125', question: 'Transparent means:', options: ['Cannot see through', 'Can see through clearly', 'Colorful', 'Heavy'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_126', question: 'Translucent means:', options: ['Completely see-through', 'Some light passes through but not clear', 'No light passes', 'Very bright'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_127', question: 'Which is opaque?', options: ['Clear glass', 'Wooden door', 'Water', 'Air'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_128', question: 'Which is transparent?', options: ['Metal', 'Clear glass', 'Wood', 'Paper'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_129', question: 'If you move closer to a light source, your shadow becomes:', options: ['Smaller', 'Larger', 'Same size', 'Disappears'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_130', question: 'If you move farther from a light source, your shadow becomes:', options: ['Larger', 'Smaller', 'Same size', 'Brighter'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_131', question: 'Your shadow is longest when the sun is:', options: ['Directly overhead', 'Low in the sky', 'Behind clouds', 'Not visible'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_132', question: 'Your shadow is shortest when the sun is:', options: ['Low in sky', 'High overhead', 'Behind clouds', 'Setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_133', question: 'The shape of a shadow depends on:', options: ['Time of day only', 'The shape of the object', 'Weather only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_134', question: 'Where is the shadow in relation to the light source?', options: ['Toward the light', 'On the same side as light', 'On the opposite side from light', 'Above the light'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_135', question: 'Can you have a shadow without light?', options: ['Yes', 'No', 'Sometimes', 'Always'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_136', question: 'Light from the sun takes about ___ to reach Earth:', options: ['8 seconds', '8 minutes', '8 hours', '8 days'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_137', question: 'A rainbow is caused by:', options: ['Magic', 'Light reflecting and refracting in water droplets', 'Clouds only', 'Wind'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_138', question: 'White light is made up of:', options: ['Only one color', 'Many colors', 'No colors', 'Only black'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_139', question: 'Why do we see different colors?', options: ['Magic', 'Objects reflect certain colors and absorb others', 'All objects are naturally colored', 'Temperature'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_140', question: 'Light helps plants:', options: ['Sleep', 'Make food', 'Move', 'Sing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // FORCES AND MAGNETS (40 questions)
  { id: 'y3_sci_141', question: 'A force is:', options: ['A type of energy', 'A push or pull', 'A material', 'A color'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_142', question: 'Forces can make things:', options: ['Stay still only', 'Start moving, stop, or change direction', 'Disappear', 'Change color'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_143', question: 'Friction is:', options: ['A type of magnet', 'A force that slows moving objects', 'A color', 'A sound'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_144', question: 'Friction occurs when:', options: ['Objects don\'t touch', 'Two surfaces rub together', 'Only in water', 'Only in air'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_145', question: 'Which surface has more friction?', options: ['Smooth ice', 'Rough carpet', 'Glass', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_146', question: 'Which surface has less friction?', options: ['Sandpaper', 'Smooth ice', 'Rough wood', 'Gravel'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_147', question: 'Friction is useful because:', options: ['It makes things slippery', 'It helps us grip and stop', 'It makes things hot', 'It\'s not useful'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_148', question: 'To reduce friction, we can:', options: ['Make surfaces rougher', 'Use oil or make surfaces smooth', 'Add more weight', 'Stop moving'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_149', question: 'A toy car moves faster on:', options: ['Rough carpet', 'Smooth floor', 'Grass', 'Sand'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_150', question: 'Shoes have rough soles to:', options: ['Look nice', 'Increase friction and grip', 'Decrease friction', 'Make noise'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_151', question: 'A magnet:', options: ['Attracts all materials', 'Attracts certain metals', 'Repels all materials', 'Does nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_152', question: 'Magnets can attract:', options: ['Wood', 'Plastic', 'Iron', 'Paper'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_153', question: 'Which material is magnetic?', options: ['Copper', 'Aluminum', 'Iron', 'Plastic'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_154', question: 'Which is NOT magnetic?', options: ['Iron', 'Steel', 'Wood', 'Nickel'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_155', question: 'Magnetic forces can act:', options: ['Only by touching', 'At a distance without touching', 'Only in water', 'Only in the dark'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_156', question: 'The force of a magnet is strongest:', options: ['In the middle', 'At the poles', 'Nowhere', 'Everywhere equally'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_157', question: 'How many poles does a magnet have?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_158', question: 'The two poles of a magnet are:', options: ['East and West', 'North and South', 'Up and Down', 'Left and Right'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_159', question: 'When two north poles of magnets meet:', options: ['They attract', 'They repel', 'Nothing happens', 'They stick'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_160', question: 'When a north pole meets a south pole:', options: ['They repel', 'They attract', 'Nothing happens', 'They break'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_161', question: 'Like poles (N-N or S-S):', options: ['Attract', 'Repel', 'Do nothing', 'Stick together'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_162', question: 'Opposite poles (N-S):', options: ['Repel', 'Attract', 'Do nothing', 'Push away'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_163', question: 'A compass needle is:', options: ['Not magnetic', 'A small magnet', 'Made of wood', 'Made of plastic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_164', question: 'A compass needle points toward:', options: ['South', 'East', 'North', 'West'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_165', question: 'Magnets are used in:', options: ['Nothing', 'Compasses, speakers, and motors', 'Only toys', 'Only decorations'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_166', question: 'Can magnetic forces pass through paper?', options: ['No', 'Yes', 'Sometimes', 'Never'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_167', question: 'The Earth acts like:', options: ['A giant battery', 'A giant magnet', 'A giant mirror', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_168', question: 'Steel is magnetic because it contains:', options: ['Plastic', 'Iron', 'Wood', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_169', question: 'To test if something is magnetic:', options: ['Taste it', 'See if a magnet attracts it', 'Smell it', 'Listen to it'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_170', question: 'A magnet loses its magnetism if:', options: ['You look at it', 'You drop it hard or heat it', 'You touch it', 'You wash it'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y3_sci_171', question: 'Gravity is:', options: ['A type of magnet', 'A force that pulls objects toward Earth', 'A color', 'A sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_172', question: 'What makes things fall down?', options: ['Wind', 'Gravity', 'Magnets', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_173', question: 'Without friction, it would be hard to:', options: ['Float', 'Walk or stop', 'See', 'Breathe'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_174', question: 'Water resistance is friction in:', options: ['Air', 'Water', 'Space', 'Soil'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_175', question: 'Air resistance is friction in:', options: ['Water', 'Air', 'Soil', 'Space'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_176', question: 'A parachute works because of:', options: ['Magnets', 'Air resistance', 'Gravity only', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_177', question: 'Which force pulls a falling object down?', options: ['Friction', 'Magnetism', 'Gravity', 'Push'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_178', question: 'Magnets can work through:', options: ['Nothing', 'Some materials like paper and plastic', 'Only metal', 'Only air'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_179', question: 'A refrigerator door stays closed using:', options: ['Glue', 'Magnets', 'Tape', 'Rope'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_180', question: 'Forces are measured in:', options: ['Meters', 'Newtons', 'Liters', 'Degrees'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },

  // WORKING SCIENTIFICALLY (20 questions)
  { id: 'y3_sci_181', question: 'A scientific question is:', options: ['Random', 'One that can be tested', 'Only about space', 'Only about animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_182', question: 'An enquiry is:', options: ['Giving up', 'An investigation to find answers', 'A guess', 'A game'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_183', question: 'A fair test means:', options: ['Everyone wins', 'Only one variable changes', 'Everything changes', 'Nothing changes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_184', question: 'A variable is:', options: ['A guess', 'Something that can change', 'A tool', 'A result'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_185', question: 'Why do we repeat tests?', options: ['To waste time', 'To check results are reliable', 'For fun', 'No reason'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_186', question: 'Observations should be:', options: ['Made up', 'Careful and accurate', 'Random', 'Quick and careless'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_187', question: 'We record data to:', options: ['Waste paper', 'Remember and analyze results', 'Make it messy', 'Hide findings'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_188', question: 'Data can be recorded using:', options: ['Nothing', 'Tables, charts, and drawings', 'Only memory', 'Only words'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_189', question: 'A conclusion is:', options: ['The start', 'What you learned from the investigation', 'A guess', 'A tool'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_190', question: 'A prediction is:', options: ['Looking back', 'Saying what you think will happen', 'A result', 'A mistake'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_191', question: 'We use scientific language to:', options: ['Confuse people', 'Communicate clearly and accurately', 'Sound smart only', 'Waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_192', question: 'Classifying means:', options: ['Breaking things', 'Grouping by similar properties', 'Hiding things', 'Losing things'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_193', question: 'A pattern in results means:', options: ['Random data', 'Something that repeats or shows a trend', 'Mistakes', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_194', question: 'If results don\'t match your prediction:', options: ['Give up', 'Think about why and learn from it', 'Change data', 'Ignore it'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_195', question: 'To improve an investigation, you might:', options: ['Do nothing', 'Change methods or repeat more times', 'Give up', 'Break equipment'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_196', question: 'Safety in science means:', options: ['Being careless', 'Following rules and being careful', 'Ignoring instructions', 'Running around'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_197', question: 'A hypothesis is:', options: ['A fact', 'An educated guess to test', 'A result', 'A tool'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y3_sci_198', question: 'Measuring helps us:', options: ['Waste time', 'Be accurate and compare', 'Make things up', 'Confuse data'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_199', question: 'Why is it important to ask questions in science?', options: ['It\'s not important', 'Questions lead to investigations and learning', 'To annoy people', 'To waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y3_sci_200', question: 'Good scientists:', options: ['Never make mistakes', 'Are curious, careful, and learn from results', 'Give up easily', 'Don\'t ask questions'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 }
];
