// Year 11 English Trivia Questions
// Based on UK Year 11 English Curriculum Framework (GCSE Final Year - Advanced)
// 200 comprehensive questions for GCSE exam preparation

export const YEAR_11_ENGLISH_QUESTIONS = [
  // ADVANCED LITERATURE ANALYSIS (80 questions)
  { id: 'y11_eng_1', question: 'In "Macbeth", what do the witches represent?', options: ['Comedy', 'Evil/supernatural/fate', 'Love', 'Hope'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_2', question: 'Macbeth\'s fatal flaw (hamartia) is:', options: ['Love', 'Ambition', 'Cowardice', 'Honesty'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_3', question: 'Lady Macbeth\'s sleepwalking shows:', options: ['Happiness', 'Guilt and mental breakdown', 'Health', 'Strength'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_4', question: '"Fair is foul, and foul is fair" is example of:', options: ['Metaphor', 'Paradox', 'Simile', 'Alliteration'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_5', question: 'Blood motif in Macbeth symbolizes:', options: ['Water', 'Guilt and violence', 'Love', 'Hope'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_6', question: 'In "An Inspector Calls", who is Eva Smith?', options: ['Rich heiress', 'Working class victim', 'Inspector\'s wife', 'Sheila\'s friend'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_7', question: 'Priestley wrote "An Inspector Calls" to promote:', options: ['Capitalism', 'Social responsibility/socialism', 'War', 'Individualism'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_8', question: 'The Inspector functions as:', options: ['Comic relief', 'Priestley\'s voice/conscience', 'Villain', 'Love interest'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_9', question: '"We are members of one body" reflects:', options: ['Individualism', 'Collective responsibility', 'Capitalism', 'Isolation'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_10', question: 'Mr Birling represents:', options: ['Socialism', 'Capitalism/old generation', 'Youth', 'Inspector'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_11', question: 'Sheila\'s character arc shows:', options: ['No change', 'Growth and responsibility', 'Regression', 'Weakness'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_12', question: 'Circular structure in "An Inspector Calls" emphasizes:', options: ['Change', 'No lessons learned', 'Time', 'Place'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_13', question: 'In "A Christmas Carol", Scrooge\'s transformation represents:', options: ['Greed', 'Redemption and change', 'Death', 'Poverty'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_14', question: 'Ghost of Christmas Past symbolizes:', options: ['Future', 'Memory and reflection', 'Death', 'Greed'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_15', question: 'Tiny Tim represents:', options: ['Greed', 'Innocence and vulnerability', 'Evil', 'Wealth'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_16', question: 'Dickens wrote "A Christmas Carol" to critique:', options: ['Christmas', 'Poverty and social inequality', 'Ghosts', 'Families'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_17', question: 'In "Jekyll and Hyde", Hyde represents:', options: ['Good', 'Repressed evil desires', 'Society', 'Science'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_18', question: 'The novella explores theme of:', options: ['Love', 'Duality of human nature', 'War', 'Friendship'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_19', question: 'Victorian setting reflects:', options: ['Freedom', 'Repression and hypocrisy', 'Openness', 'Honesty'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_20', question: 'Gothic elements include:', options: ['Romance', 'Darkness, mystery, supernatural', 'Comedy', 'Realism'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_21', question: 'In "Romeo and Juliet", the feud represents:', options: ['Love', 'Destructive hatred', 'Peace', 'Joy'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_22', question: 'Romeo and Juliet\'s love is described as:', options: ['Slow and steady', 'Intense and impulsive', 'Weak', 'Platonic'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_23', question: 'Mercutio\'s death is turning point because:', options: ['Comedy continues', 'Tragedy intensifies', 'Peace achieved', 'Nothing changes'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_24', question: 'Juliet\'s maturity compared to Romeo shows in:', options: ['Her youth', 'Her practical thinking', 'Her weakness', 'Her age'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_25', question: 'Fate vs free will: which dominates the play?', options: ['Free will only', 'Both intertwine', 'Neither', 'Only fate'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_26', question: 'In "Of Mice and Men", American Dream represents:', options: ['Reality', 'Unattainable hope', 'Guarantee', 'Fact'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_27', question: 'George and Lennie\'s friendship is significant because:', options: ['Common', 'Rare in harsh migrant world', 'Weak', 'Temporary'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_28', question: 'Lennie\'s death by George is:', options: ['Murder', 'Mercy killing', 'Accident', 'Suicide'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_29', question: 'Curley\'s wife represents:', options: ['Power', 'Loneliness and victimization', 'Happiness', 'Success'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_30', question: 'Candy\'s dog foreshadows:', options: ['Joy', 'Lennie\'s death', 'Success', 'Dream achieved'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_31', question: 'Cyclical structure shows:', options: ['Progress', 'Return to lonely beginning', 'Success', 'Joy'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_32', question: 'In "Lord of the Flies", conch symbolizes:', options: ['Evil', 'Order and civilization', 'Chaos', 'Violence'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_33', question: 'Jack represents:', options: ['Democracy', 'Savagery and dictatorship', 'Intelligence', 'Peace'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_34', question: 'Ralph represents:', options: ['Savagery', 'Leadership and civilization', 'Evil', 'Chaos'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_35', question: 'Piggy represents:', options: ['Strength', 'Intellect and reason', 'Violence', 'Hunting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_36', question: 'Simon represents:', options: ['Evil', 'Goodness and spirituality', 'Violence', 'Power'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_37', question: 'Beast symbolizes:', options: ['Real animal', 'Inner human evil', 'External threat', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_38', question: 'Novel\'s message about human nature:', options: ['Inherently good', 'Capable of evil without society', 'Purely rational', 'Perfect'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_39', question: 'Context: allegory for:', options: ['School life', 'WWII/Cold War tensions', 'Sports', 'Adventure'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_40', question: 'In "Animal Farm", pigs represent:', options: ['Workers', 'Corrupt leaders', 'Victims', 'Heroes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_41', question: 'Allegory for:', options: ['American Revolution', 'Russian Revolution', 'French Revolution', 'Industrial Revolution'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_42', question: 'Napoleon represents:', options: ['Lenin', 'Stalin', 'Marx', 'Trotsky'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_43', question: 'Snowball represents:', options: ['Stalin', 'Trotsky', 'Marx', 'Lenin'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_44', question: '"All animals are equal, but some are more equal" shows:', options: ['Equality', 'Corruption/hypocrisy', 'Justice', 'Truth'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_45', question: 'In poetry, enjambment creates:', options: ['Full stop', 'Flow between lines', 'Rhyme', 'Pause'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_46', question: 'Caesura is:', options: ['End of poem', 'Pause within line', 'Rhyme scheme', 'Stanza'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_47', question: 'Volta in sonnet is:', options: ['Rhyme', 'Turn/shift in argument', 'Meter', 'Title'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_48', question: 'Extended metaphor develops:', options: ['One line', 'Throughout poem/section', 'Not at all', 'Only in title'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_49', question: 'Semantic field of war creates:', options: ['Romance', 'Conflict atmosphere', 'Peace', 'Joy'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_50', question: 'Sibilance (s sounds) can suggest:', options: ['Loudness', 'Softness/menace', 'Anger', 'Joy'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_51', question: 'Plosive sounds (b, p, d, t) suggest:', options: ['Softness', 'Harshness/aggression', 'Peace', 'Calm'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_52', question: 'Internal rhyme occurs:', options: ['Between lines', 'Within same line', 'Never', 'Only at end'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_53', question: 'Half rhyme/slant rhyme creates:', options: ['Perfect harmony', 'Dissonance/unease', 'Joy', 'Peace'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_54', question: 'Iambic pentameter has ___ syllables:', options: ['8', '10', '12', '14'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_55', question: 'Iamb is ___ followed by ___:', options: ['Stressed, unstressed', 'Unstressed, stressed', 'Two unstressed', 'Two stressed'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_56', question: 'Trochee is ___ followed by ___:', options: ['Unstressed, stressed', 'Stressed, unstressed', 'Two unstressed', 'Two stressed'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_57', question: 'Disrupting regular meter creates:', options: ['Boredom', 'Emphasis/disturbance', 'Peace', 'Sleep'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_58', question: 'Free verse lacks:', options: ['Meaning', 'Regular rhyme/meter', 'Words', 'Ideas'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_59', question: 'Dramatic monologue features:', options: ['Narrator telling story', 'Speaker revealing character', 'Dialogue', 'Description'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_60', question: 'First person plural "we" creates:', options: ['Division', 'Collective identity/unity', 'Isolation', 'Confusion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_61', question: 'In war poetry, Owen shows:', options: ['Glory of war', 'Horror and pity of war', 'Excitement', 'Adventure'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_62', question: '"Dulce et decorum est" is:', options: ['Truth', 'The old lie about war glory', 'New idea', 'Fact'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_63', question: 'Power and Conflict poems explore:', options: ['Love', 'Individual/society power dynamics', 'Nature only', 'Peace'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_64', question: 'Ozymandias shows:', options: ['Eternal power', 'Temporary nature of power', 'Love', 'Nature'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_65', question: 'In Remains, repetition of "probably" shows:', options: ['Certainty', 'Uncertainty and guilt', 'Joy', 'Peace'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_66', question: 'Storm on the Island uses:', options: ['Regular form to contrast chaos', 'No structure', 'Sonnets', 'Haiku'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_67', question: 'Tissue poem uses paper to symbolize:', options: ['Strength', 'Fragility of power/borders', 'Permanence', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_68', question: 'Kamikaze\'s structure (shifting perspective) shows:', options: ['Confusion', 'Complex family/honor conflict', 'Simplicity', 'Peace'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_69', question: 'Comparative analysis requires:', options: ['One poem', 'Comparing language/structure/themes', 'Summary only', 'Biography'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_70', question: 'Context includes:', options: ['Only plot', 'Historical/social/biographical background', 'Only summary', 'Only quotes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_71', question: 'Authorial intent means:', options: ['Reader\'s view', 'Writer\'s purpose/message', 'Plot', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_72', question: 'Interpretations can:', options: ['Only be one', 'Vary validly', 'Never differ', 'Be wrong'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_73', question: 'Alternative readings come from:', options: ['Ignoring text', 'Different perspectives (feminist, Marxist)', 'Guessing', 'Not reading'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_74', question: 'Feminist reading examines:', options: ['Only men', 'Gender roles/female representation', 'Economics', 'Nature'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_75', question: 'Marxist reading focuses on:', options: ['Love', 'Class/power/economics', 'Nature', 'Gender'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_76', question: 'Postcolonial reading explores:', options: ['Love', 'Empire/colonialism effects', 'Science', 'Sport'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_77', question: 'Reader response theory says:', options: ['One meaning', 'Reader creates meaning', 'Author controls all', 'No meaning'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_78', question: 'Intertextuality is:', options: ['Single text', 'References between texts', 'No connection', 'Same text'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_79', question: 'Subtext is:', options: ['Obvious meaning', 'Underlying/implied meaning', 'Title', 'Summary'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_80', question: 'Tension in narrative created by:', options: ['Peace', 'Conflict/uncertainty', 'Resolution', 'Happiness'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },

  // ADVANCED LANGUAGE TECHNIQUES (60 questions)
  { id: 'y11_eng_81', question: 'Rhetoric aims to:', options: ['Inform only', 'Persuade effectively', 'Entertain only', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_82', question: 'Ethos appeals to:', options: ['Emotion', 'Logic', 'Credibility/ethics', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_83', question: 'Pathos appeals to:', options: ['Credibility', 'Logic', 'Emotions', 'Statistics'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_84', question: 'Logos appeals to:', options: ['Emotion', 'Logic and reason', 'Credibility', 'Fear'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_85', question: 'Anaphora repeats words at:', options: ['End', 'Beginning of successive clauses', 'Middle', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_86', question: 'Epistrophe repeats words at:', options: ['Beginning', 'End of successive clauses', 'Middle', 'Never'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_87', question: 'Tricolon uses ___ elements:', options: ['Two', 'Three', 'Four', 'Five'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_88', question: 'Antithesis creates:', options: ['Agreement', 'Contrast of ideas', 'Similarity', 'Confusion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_89', question: 'Paradox is:', options: ['Simple truth', 'Seemingly contradictory but true', 'False', 'Boring'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_90', question: 'Irony says opposite of:', options: ['Nothing', 'What is meant', 'Everything', 'Sometimes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_91', question: 'Satire uses humor to:', options: ['Entertain only', 'Criticize/expose flaws', 'Praise', 'Inform'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_92', question: 'Hypophora asks then:', options: ['Leaves unanswered', 'Immediately answers own question', 'Changes topic', 'Confuses'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_93', question: 'Litotes is:', options: ['Exaggeration', 'Understatement using negative', 'Direct statement', 'Question'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_94', question: 'Euphemism is:', options: ['Harsh language', 'Mild/indirect expression for harsh reality', 'Direct language', 'Slang'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_95', question: 'Dysphemism is:', options: ['Polite', 'Offensive/harsh alternative', 'Neutral', 'Scientific'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_96', question: 'Colloquialism is:', options: ['Formal language', 'Informal/everyday language', 'Technical language', 'Foreign language'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_97', question: 'Jargon is:', options: ['Simple language', 'Specialized technical language', 'Slang', 'Standard English'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_98', question: 'Register refers to:', options: ['Volume', 'Level of formality', 'Font', 'Size'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_99', question: 'Discourse markers like "furthermore" indicate:', options: ['Contrast', 'Addition', 'Time', 'Conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_100', question: '"However" indicates:', options: ['Addition', 'Contrast', 'Time', 'Cause'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_101', question: '"Consequently" indicates:', options: ['Contrast', 'Time', 'Cause/effect', 'Addition'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_102', question: 'Modal verbs (might, could, should) express:', options: ['Certainty', 'Possibility/obligation', 'Past tense', 'Future only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_103', question: 'Passive voice emphasizes:', options: ['Doer of action', 'Action/recipient', 'Nothing', 'Time'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_104', question: 'Nominalisation turns verbs into:', options: ['Adjectives', 'Nouns', 'Adverbs', 'Conjunctions'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_105', question: 'Short sentences create:', options: ['Boredom', 'Impact/emphasis', 'Confusion', 'Length'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_106', question: 'Long complex sentences create:', options: ['Simplicity', 'Sophisticated detail', 'Boredom', 'Confusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_107', question: 'Minor sentences (fragments) create:', options: ['Complete thoughts', 'Emphasis/informality', 'Proper grammar', 'Formality'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_108', question: 'Listing creates sense of:', options: ['One thing', 'Accumulation/overwhelming', 'Nothing', 'Peace'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_109', question: 'Syndetic listing uses:', options: ['No connectives', 'Connectives (and, or)', 'Only commas', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_110', question: 'Asyndetic listing uses:', options: ['Many connectives', 'No connectives, just commas', 'Only "and"', 'Semicolons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_111', question: 'Polysyndeton uses:', options: ['No connectives', 'Multiple connectives', 'One connective', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_112', question: 'Parallel structure repeats:', options: ['Ideas', 'Grammatical structure', 'Words only', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_113', question: 'Imperative mode is used for:', options: ['Questions', 'Commands/instructions', 'Statements', 'Wishes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_114', question: 'Declarative mode is used for:', options: ['Commands', 'Questions', 'Statements', 'Exclamations'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_115', question: 'Interrogative mode is used for:', options: ['Statements', 'Commands', 'Questions', 'Exclamations'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_116', question: 'Exclamatory mode expresses:', options: ['Questions', 'Commands', 'Strong emotion', 'Facts'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_117', question: 'Second person "you" creates:', options: ['Distance', 'Direct address/involvement', 'Formality', 'Confusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_118', question: 'Third person creates:', options: ['Intimacy', 'Objectivity/distance', 'Subjectivity', 'Confusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_119', question: 'Connotation is:', options: ['Dictionary meaning', 'Associated meaning/feeling', 'Spelling', 'Pronunciation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_120', question: 'Denotation is:', options: ['Associated feeling', 'Literal dictionary meaning', 'Pronunciation', 'Connotation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_121', question: '"Home" has positive connotations of:', options: ['Danger', 'Safety/warmth', 'Fear', 'Sadness'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_122', question: 'Loaded language contains:', options: ['Neutrality', 'Strong emotional associations', 'Facts only', 'Statistics'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_123', question: 'Abstract nouns represent:', options: ['Physical objects', 'Ideas/concepts', 'People', 'Places'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_124', question: 'Concrete nouns represent:', options: ['Ideas', 'Physical things', 'Emotions', 'Thoughts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_125', question: 'Dynamic verbs show:', options: ['State', 'Physical action', 'Existence', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_126', question: 'Stative verbs show:', options: ['Action', 'State/feeling', 'Movement', 'Completion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_127', question: 'Intensifiers (very, extremely) are:', options: ['Nouns', 'Adverbs that strengthen', 'Verbs', 'Adjectives'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_128', question: 'Qualifiers (quite, rather) are:', options: ['Strengthening', 'Weakening/limiting adverbs', 'Nouns', 'Verbs'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_129', question: 'Determiner comes before:', options: ['Verb', 'Noun', 'Adjective only', 'Adverb'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_130', question: 'Possessive pronouns show:', options: ['Action', 'Ownership', 'Description', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_131', question: 'Demonstrative pronouns (this, that) indicate:', options: ['Ownership', 'Specific items', 'Actions', 'Feelings'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_132', question: 'Relative pronouns (who, which, that) introduce:', options: ['Questions', 'Relative clauses', 'Main clauses', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_133', question: 'Subordinating conjunctions create:', options: ['Equal clauses', 'Dependent clauses', 'Lists', 'Questions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_134', question: 'Coordinating conjunctions (FANBOYS) join:', options: ['Unequal clauses', 'Equal/independent clauses', 'Phrases only', 'Words only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_135', question: 'Correlative conjunctions work in:', options: ['Singles', 'Pairs (either...or)', 'Threes', 'Never'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_136', question: 'Ellipsis (...) suggests:', options: ['Completion', 'Omission/trailing off', 'Question', 'Exclamation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_137', question: 'Dash creates:', options: ['End', 'Abrupt break/emphasis', 'Question', 'List'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_138', question: 'Colon introduces:', options: ['Question', 'Explanation/list', 'Contrast', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_139', question: 'Semi-colon joins:', options: ['Unrelated ideas', 'Related independent clauses', 'Questions', 'Lists'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_140', question: 'Parentheses/brackets provide:', options: ['Main idea', 'Additional/aside information', 'Conclusion', 'Introduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // EXAM SKILLS & CRITICAL ANALYSIS (60 questions)
  { id: 'y11_eng_141', question: 'In GCSE essay, thesis statement should:', options: ['Be vague', 'Clearly state argument', 'Ask question', 'Be absent'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_142', question: 'Topic sentence should:', options: ['End paragraph', 'Introduce paragraph focus', 'Be in middle', 'Be absent'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_143', question: 'Evidence must be:', options: ['Irrelevant', 'Relevant and support point', 'Long', 'Absent'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_144', question: 'After quote, you must:', options: ['Move on', 'Analyze language/effect', 'Summarize', 'Ignore it'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_145', question: 'PEEL stands for:', options: ['Paragraph, Example, Evidence, Link', 'Point, Evidence, Explain, Link', 'Point, Example, End, Learn', 'Perfect, Essay, Every, Line'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_146', question: 'Embedding quotes means:', options: ['Long block quotes', 'Integrating smoothly into sentence', 'Separate lines', 'Not quoting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_147', question: 'When analyzing, focus on:', options: ['What happens', 'How language creates meaning/effect', 'Author bio', 'Summary'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_148', question: 'Writer\'s methods include:', options: ['Only plot', 'Language, structure, form', 'Only characters', 'Only setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_149', question: 'Structure analysis examines:', options: ['Only grammar', 'How text is organized for effect', 'Only plot', 'Only spelling'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_150', question: 'Form refers to:', options: ['Content', 'Type of text (sonnet, letter)', 'Plot', 'Character'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_151', question: 'Comparative analysis requires:', options: ['One text', 'Comparing similarities/differences', 'Summary', 'Biography'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_152', question: 'When comparing poems, connect using:', options: ['Similarly/conversely/whereas', 'Random words', 'Nothing', 'Only "and"'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_153', question: 'Inference requires:', options: ['Stating obvious', 'Reading between lines', 'Summarizing', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_154', question: 'Synthesis means:', options: ['Separating ideas', 'Combining information from sources', 'Copying', 'Ignoring'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_155', question: 'Evaluation requires:', options: ['Description', 'Judgment of effectiveness', 'Summary', 'Retelling'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_156', question: 'Critical perspective means:', options: ['Accepting everything', 'Questioning and analyzing', 'Summarizing', 'Copying'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_157', question: 'In creative writing, narrative voice is:', options: ['Plot', 'Perspective telling story', 'Setting', 'Character'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_158', question: 'Show don\'t tell means:', options: ['State directly', 'Use sensory details to imply', 'Tell everything', 'Summarize'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_159', question: 'Varied sentence structures create:', options: ['Boredom', 'Interest and rhythm', 'Confusion', 'Simplicity'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_160', question: 'Ambitious vocabulary should be:', options: ['Random', 'Precise and appropriate', 'Complex for sake of it', 'Simple only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_161', question: 'Narrative arc includes:', options: ['Only beginning', 'Exposition, rising action, climax, resolution', 'Only end', 'Random events'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_162', question: 'Foreshadowing creates:', options: ['Confusion', 'Anticipation for future events', 'Boredom', 'Resolution'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_163', question: 'Flashback provides:', options: ['Future', 'Background information', 'Conclusion', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_164', question: 'In medias res starts:', options: ['At beginning', 'In middle of action', 'At end', 'Nowhere'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_165', question: 'Cliffhanger creates:', options: ['Resolution', 'Suspense', 'Conclusion', 'Boredom'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_166', question: 'Pacing controls:', options: ['Character', 'Speed of narrative', 'Setting', 'Theme'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_167', question: 'Dialogue reveals:', options: ['Nothing', 'Character/advances plot', 'Only time', 'Only place'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_168', question: 'Setting can reflect:', options: ['Nothing', 'Mood/character state', 'Only location', 'Only time'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_169', question: 'Characterization can be:', options: ['Only direct', 'Direct or indirect', 'Absent', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_170', question: 'Direct characterization:', options: ['Shows through actions', 'Explicitly states traits', 'Implies only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_171', question: 'Indirect characterization shows through:', options: ['Direct statement', 'Actions, speech, thoughts', 'Nothing', 'Title'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_172', question: 'Dynamic character:', options: ['Never changes', 'Changes/develops', 'Is flat', 'Is boring'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_173', question: 'Static character:', options: ['Changes significantly', 'Remains unchanged', 'Is complex', 'Is protagonist'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_174', question: 'Round character is:', options: ['Flat', 'Complex and realistic', 'Simple', 'One-dimensional'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_175', question: 'Flat character is:', options: ['Complex', 'One-dimensional', 'Realistic', 'Detailed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_176', question: 'Motif is:', options: ['One-time image', 'Recurring element', 'Character', 'Setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_177', question: 'Theme is:', options: ['Plot', 'Central idea/message', 'Character', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_178', question: 'Universal themes are:', options: ['Specific to one culture', 'Relevant across cultures/time', 'Modern only', 'Ancient only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_179', question: 'Tone reflects writer\'s:', options: ['Height', 'Attitude toward subject', 'Age', 'Location'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_180', question: 'Mood creates reader\'s:', options: ['Confusion', 'Emotional response', 'Biography', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_181', question: 'Atmosphere is:', options: ['Weather', 'Overall feeling/environment', 'Character', 'Plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_182', question: 'Suspense builds:', options: ['Resolution', 'Tension/uncertainty', 'Boredom', 'Peace'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_183', question: 'Anticlimax is:', options: ['Exciting peak', 'Disappointing after build-up', 'Beginning', 'Introduction'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_184', question: 'Denouement is:', options: ['Introduction', 'Resolution/outcome', 'Climax', 'Rising action'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_185', question: 'Protagonist is:', options: ['Villain', 'Main character', 'Minor character', 'Narrator'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_186', question: 'Antagonist:', options: ['Supports protagonist', 'Opposes protagonist', 'Narrates', 'Observes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_eng_187', question: 'Foil character:', options: ['Is same as protagonist', 'Contrasts to highlight protagonist', 'Is villain', 'Is narrator'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_188', question: 'Archetype is:', options: ['Unique character', 'Universal character type', 'Real person', 'Modern only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_189', question: 'Tragic hero has:', options: ['No flaws', 'Fatal flaw leading to downfall', 'Perfect life', 'Happy ending'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_190', question: 'Catharsis causes audience:', options: ['Boredom', 'Emotional release', 'Confusion', 'Sleep'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_191', question: 'Hubris is excessive:', options: ['Humility', 'Pride', 'Fear', 'Sadness'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_192', question: 'Nemesis is:', options: ['Friend', 'Deserved fate/downfall', 'Beginning', 'Success'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_193', question: 'Peripeteia is:', options: ['Introduction', 'Sudden reversal of fortune', 'Rising action', 'Resolution'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_194', question: 'Anagnorisis is:', options: ['Ignorance', 'Moment of recognition/discovery', 'Beginning', 'Conflict'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_195', question: 'Deus ex machina is:', options: ['Natural resolution', 'Sudden unlikely solution', 'Gradual change', 'Introduction'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_196', question: 'Verisimilitude means:', options: ['Fantasy', 'Appearance of truth/realism', 'Impossible', 'Magical'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_197', question: 'Willing suspension of disbelief allows:', options: ['Critical thinking', 'Accepting fictional world', 'Rejection', 'Confusion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_198', question: 'Metafiction is:', options: ['Traditional narrative', 'Self-aware fiction about fiction', 'Non-fiction', 'Biography'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_eng_199', question: 'Breaking fourth wall means:', options: ['Building walls', 'Character addresses audience', 'Staying in character', 'Silence'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_eng_200', question: 'Genre conventions are:', options: ['Random elements', 'Expected features of genre', 'Unique elements', 'Breaking rules'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 }
];
