// Year 2 English Trivia Questions
// Based on UK Year 2 English Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_2_ENGLISH_QUESTIONS = [
  // PHONICS & SPELLING (40 questions)
  // Phonics Revision
  { id: 'y2_eng_1', question: 'Which letters make the "oa" sound in "boat"?', options: ['b-t', 'o-a', 'oa', 'at'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_2', question: 'What sound does "igh" make in "night"?', options: ['ig', 'eye sound', 'ih', 'ight'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_3', question: 'Which word has the "ee" sound?', options: ['read', 'red', 'road', 'rod'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_4', question: 'How many sounds in the word "cloud"?', options: ['3', '4', '5', '6'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_5', question: 'What does "ow" say in "snow"?', options: ['ow (as in cow)', 'oh', 'aw', 'ew'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_6', question: 'Which is the correct spelling?', options: ['lait', 'lite', 'light', 'liet'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_7', question: 'What sound does "ph" make in "phone"?', options: ['p', 'f', 'ph', 'h'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_8', question: 'Which word uses "ai" for the long a sound?', options: ['rain', 'ran', 'run', 'rein'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_9', question: 'Read this longer word: "sun-shine". What does it mean?', options: ['Dark sky', 'Bright light from the sun', 'Moon', 'Stars'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_10', question: 'Which letters are silent in "knight"?', options: ['k and gh', 'n and t', 'i and g', 'k and n'], correctAnswer: 0, difficulty: 'hard', xpReward: 25 },

  // Spelling Rules & Patterns
  { id: 'y2_eng_11', question: 'What is the plural of "cat"?', options: ['cat', 'cats', 'cates', 'caties'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_12', question: 'What is the plural of "box"?', options: ['boxs', 'box', 'boxes', 'boxies'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_13', question: 'What is the plural of "baby"?', options: ['babys', 'babies', 'babyes', 'baby'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_14', question: 'Add -ed to "jump":', options: ['jumped', 'jumpped', 'jumpd', 'jumpeed'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_15', question: 'Add -ing to "run":', options: ['runing', 'running', 'runming', 'runn'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_16', question: 'Add -er to "fast" (to compare):', options: ['faster', 'fasterr', 'fastor', 'fastter'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_17', question: 'Add -est to "big":', options: ['bigest', 'bigger', 'biggest', 'biggestt'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_18', question: 'Change "happy" to past tense with -er:', options: ['happyer', 'happier', 'happyier', 'happeir'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_19', question: 'What is "cry" in past tense?', options: ['cryed', 'cried', 'cryd', 'cryed'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_20', question: 'Which is a compound word?', options: ['running', 'sunshine', 'quickly', 'jumped'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_21', question: 'Join "rain" and "bow" to make:', options: ['rainbowing', 'rainbow', 'rainbow', 'rain-bow'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_22', question: 'What is the plural of "lady"?', options: ['ladys', 'ladies', 'ladyes', 'lady'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_23', question: 'Add -ing to "hope":', options: ['hopeing', 'hoping', 'hopping', 'hoppping'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_eng_24', question: 'Which is spelled correctly?', options: ['stoped', 'stopped', 'stopd', 'stopt'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_25', question: 'What is the superlative of "tall"?', options: ['taller', 'tallest', 'most tall', 'very tall'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // Common Exception Words
  { id: 'y2_eng_26', question: 'How do you spell: "I am ___" (the opposite of wrong)?', options: ['rite', 'right', 'wright', 'riet'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_27', question: 'Spell: "Can you ___ me?" (assist)', options: ['help', 'halp', 'hepl', 'hellp'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_28', question: 'Which is correct?', options: ['becuz', 'becaus', 'because', 'becuase'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_29', question: 'How do you spell "very cold"?', options: ['coold', 'cold', 'cald', 'coled'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_30', question: 'Spell: "I ___ a book" (possess):', options: ['hav', 'have', 'hev', 'haev'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_31', question: 'Which is correct?', options: ['sed', 'said', 'siad', 'sayd'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_32', question: 'Spell: "one more time"', options: ['agen', 'again', 'agane', 'agin'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_33', question: 'How do you spell: "large or huge"?', options: ['grate', 'great', 'greit', 'graat'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_34', question: 'Which is correct?', options: ['evry', 'every', 'evrey', 'everi'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_35', question: 'Spell: "not ordinary, unique"', options: ['speshul', 'speshal', 'special', 'specail'], correctAnswer: 2, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_eng_36', question: 'Which is the correct spelling?', options: ['frend', 'friend', 'freind', 'friand'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_eng_37', question: 'How do you spell "lovely, attractive"?', options: ['butiful', 'beautifull', 'beautiful', 'beutiful'], correctAnswer: 2, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_eng_38', question: 'Spell: "60 minutes"', options: ['our', 'hour', 'hower', 'ower'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_39', question: 'Which is correct?', options: ['peepul', 'peopel', 'people', 'peeple'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_40', question: 'Spell: "behind in time"', options: ['late', 'lait', 'layt', 'lat'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },

  // READING FLUENCY & DECODING (15 questions)
  { id: 'y2_eng_41', question: 'When reading aloud, a full stop (.) means:', options: ['Read faster', 'Pause and breathe', 'Read louder', 'Skip words'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_42', question: 'Reading with expression means:', options: ['Reading very fast', 'Using your voice to show feelings', 'Reading silently', 'Skipping words'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_43', question: 'When you see a question mark (?), your voice should:', options: ['Go down', 'Go up', 'Stay flat', 'Get louder'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_44', question: 'If you make a mistake while reading, you should:', options: ['Keep going', 'Self-correct and fix it', 'Stop reading', 'Skip the sentence'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_45', question: 'An exclamation mark (!) shows:', options: ['A question', 'Excitement or surprise', 'Sadness', 'The end'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_46', question: 'Fluent reading means reading:', options: ['Slowly and carefully', 'Smoothly and with understanding', 'Very loudly', 'Without stopping'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_47', question: 'When reading a character\'s speech, you should:', options: ['Read in a boring voice', 'Use expression to sound like the character', 'Skip it', 'Read very quietly'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_48', question: 'Commas (,) in a sentence tell you to:', options: ['Stop completely', 'Take a small pause', 'Read louder', 'Skip the next word'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_49', question: 'Good readers read with:', options: ['Speed only', 'Accuracy and expression', 'Eyes closed', 'No pauses'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_50', question: 'If you don\'t know a word, you should:', options: ['Give up', 'Use phonics to sound it out', 'Skip it', 'Ask someone every time'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_51', question: 'Reading accurately means:', options: ['Reading fast', 'Reading the words correctly', 'Reading loudly', 'Reading silently'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_52', question: 'When you see speech marks " ", someone is:', options: ['Thinking', 'Speaking', 'Sleeping', 'Running'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_53', question: 'Intonation means:', options: ['Reading speed', 'The rise and fall of your voice', 'Reading backwards', 'Reading silently'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_54', question: 'Why should we recognize punctuation when reading?', options: ['To read faster', 'To help us read with expression and understanding', 'To skip words', 'To make it harder'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_55', question: 'Self-correcting means:', options: ['Never making mistakes', 'Noticing and fixing your own errors', 'Reading silently', 'Reading very slowly'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // READING COMPREHENSION (35 questions)
  // Understanding Texts
  { id: 'y2_eng_56', question: 'In "Tom played football in the park," WHO played football?', options: ['Park', 'Tom', 'Football', 'Nobody'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_57', question: '"The cat slept on the sofa." WHERE did the cat sleep?', options: ['On the floor', 'On the sofa', 'On the bed', 'Outside'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_58', question: '"Mia ate her lunch at 12 o\'clock." WHEN did Mia eat?', options: ['Morning', '12 o\'clock', 'Evening', 'Night'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_59', question: '"The dog barked because it was scared." WHY did the dog bark?', options: ['It was happy', 'It was scared', 'It was hungry', 'It was tired'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_60', question: 'What does sequencing mean?', options: ['Reading backwards', 'Putting events in order', 'Mixing up the story', 'Skipping parts'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_61', question: 'Story sequence: First, Sam woke up. Next, he brushed his teeth. Then he:', options: ['Went to bed', 'Had breakfast', 'Went to sleep', 'Brushed again'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_62', question: 'Retelling a story means:', options: ['Forgetting it', 'Telling it again in your own words', 'Making up a new story', 'Reading it backwards'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_63', question: 'In "Jack climbed the beanstalk," WHAT did Jack climb?', options: ['A tree', 'A mountain', 'The beanstalk', 'A ladder'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_64', question: 'When retelling, you should include:', options: ['Only the end', 'Beginning, middle, and end', 'Only pictures', 'Random details'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_65', question: 'What happened first? 1. They went home. 2. They played. 3. They arrived.', options: ['1', '2', '3', 'All at once'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // Inference & Prediction
  { id: 'y2_eng_66', question: 'Making a prediction means:', options: ['Reading backwards', 'Guessing what might happen next', 'Finishing the book', 'Forgetting the story'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_67', question: 'If dark clouds appear in a story, what might happen next?', options: ['Sunshine', 'Rain', 'Snow in summer', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_68', question: 'Evidence from the text means:', options: ['Making things up', 'Using details from the story to support your answer', 'Drawing pictures', 'Guessing randomly'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_69', question: '"Sara smiled and jumped for joy." How does Sara feel?', options: ['Sad', 'Angry', 'Happy', 'Scared'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_70', question: '"The boy packed his suitcase." What is he probably going to do?', options: ['Stay home', 'Go on a trip', 'Sleep', 'Play'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_71', question: 'A character who helps others is probably:', options: ['Mean', 'Kind', 'Lazy', 'Angry'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_72', question: 'If a story is set in a castle, where does it take place?', options: ['A school', 'A castle', 'A shop', 'A park'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_73', question: '"The leaves were falling from the trees." What season is it likely?', options: ['Summer', 'Winter', 'Autumn', 'Spring'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_74', question: 'Inference means:', options: ['Reading the exact words', 'Working out something not directly said', 'Skipping pages', 'Guessing randomly'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_75', question: '"Tim\'s eyes were red and watery." How might Tim be feeling?', options: ['Happy', 'Sad or upset', 'Excited', 'Hungry'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },

  // Fiction, Non-Fiction & Poetry
  { id: 'y2_eng_76', question: 'Fiction means:', options: ['True stories', 'Made-up stories', 'Only poems', 'Instructions'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_77', question: 'Non-fiction means:', options: ['Made-up stories', 'True information', 'Only poems', 'Fairy tales'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_78', question: 'A book about real animals is:', options: ['Fiction', 'Non-fiction', 'A poem', 'A fairy tale'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_79', question: 'A story about a talking dragon is:', options: ['Non-fiction', 'Fiction', 'True', 'Instructions'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_80', question: 'An information text tells us:', options: ['Made-up stories', 'Facts and information', 'Jokes only', 'Nothing useful'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_81', question: 'A poem usually has:', options: ['Only numbers', 'Rhythm and sometimes rhyme', 'No words', 'Only pictures'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_82', question: 'Which is a familiar setting?', options: ['Space station', 'A school or home', 'Dragon\'s cave', 'Magic castle'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_83', question: 'Which is an unfamiliar setting?', options: ['Your bedroom', 'The park', 'An underwater kingdom', 'The playground'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_84', question: 'A rhyme is when words have:', options: ['Different meanings', 'The same ending sound', 'No connection', 'Lots of letters'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_85', question: 'Which book would be non-fiction?', options: ['Cinderella', 'How Plants Grow', 'The Three Little Pigs', 'Jack and the Beanstalk'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // WRITING (COMPOSITION) (25 questions)
  // Sentence Writing
  { id: 'y2_eng_86', question: 'A sentence must start with:', options: ['A small letter', 'A capital letter', 'A number', 'A symbol'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_87', question: 'A sentence must end with:', options: ['Nothing', 'A full stop, ? or !', 'A comma', 'A capital letter'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_88', question: 'Which is a complete sentence?', options: ['Running fast', 'The dog barked.', 'Blue sky', 'Very happy'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_89', question: 'A conjunction is a word that:', options: ['Describes', 'Joins words or ideas', 'Names things', 'Shows action'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_90', question: 'Which is a conjunction?', options: ['Dog', 'Run', 'And', 'Happy'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_91', question: 'Join these: "I like apples ___ bananas."', options: ['run', 'and', 'the', 'jump'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_92', question: 'Which conjunction shows contrast?', options: ['and', 'but', 'because', 'so'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_93', question: '"I stayed home ___ it was raining." Which conjunction?', options: ['and', 'but', 'because', 'or'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_94', question: 'Which sentence is clear and correct?', options: ['The went park dog.', 'Dog the park went.', 'The dog went to the park.', 'Park dog the went.'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_95', question: 'Why use capital letters?', options: ['To look fancy', 'To start sentences and for names', 'Randomly', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // Paragraph Writing & Writing for Purpose
  { id: 'y2_eng_96', question: 'A paragraph groups sentences about:', options: ['Different topics', 'The same topic', 'Random things', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_97', question: 'When writing a story, you need:', options: ['Only numbers', 'A beginning, middle, and end', 'Only pictures', 'No words'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_98', question: 'A description tells:', options: ['How to do something', 'What something is like', 'What happened', 'A made-up story'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_99', question: 'Instructions tell you:', options: ['A story', 'How to do something step by step', 'About the past', 'A joke'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_100', question: 'A recount is about:', options: ['The future', 'Something that already happened', 'Made-up events', 'Instructions'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_101', question: 'When writing instructions, use words like:', options: ['Once upon a time', 'First, then, next', 'The end', 'Beautiful, lovely'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_102', question: 'A story opening could be:', options: ['The end', 'Once upon a time', 'Finally', 'In conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_103', question: 'When recounting your weekend, you write about:', options: ['Made-up events', 'What you actually did', 'The future', 'Someone else\'s weekend'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_104', question: 'Descriptive writing uses:', options: ['Only verbs', 'Adjectives to describe', 'No words', 'Only numbers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_105', question: 'When writing, your ideas should:', options: ['Be mixed up', 'Make sense and be organized', 'Have no order', 'Be random'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // GRAMMAR (30 questions)
  { id: 'y2_eng_106', question: 'A noun is:', options: ['A doing word', 'A naming word', 'A describing word', 'A joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_107', question: 'Which is a noun?', options: ['run', 'happy', 'table', 'quickly'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_108', question: 'A verb is:', options: ['A naming word', 'A doing word', 'A describing word', 'A joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_109', question: 'Which is a verb?', options: ['cat', 'jump', 'red', 'beautiful'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_110', question: 'An adjective is:', options: ['A doing word', 'A naming word', 'A describing word', 'A joining word'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_111', question: 'Which is an adjective?', options: ['run', 'dog', 'beautiful', 'quickly'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_112', question: 'An adverb often tells us:', options: ['A name', 'How something is done', 'What something is', 'Who did it'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_113', question: 'Which is an adverb?', options: ['happy', 'quickly', 'table', 'run'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_114', question: 'An expanded noun phrase is:', options: ['Just a noun', 'A noun with describing words', 'A verb', 'A sentence'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_115', question: 'Expand "dog" into a phrase:', options: ['dog', 'a dog', 'the big, fluffy dog', 'dogs'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_116', question: 'Past tense means:', options: ['Now', 'Already happened', 'Will happen', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_117', question: 'Present tense means:', options: ['Already happened', 'Happening now', 'Will happen', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_118', question: 'What is the past tense of "walk"?', options: ['walking', 'walked', 'will walk', 'walks'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_119', question: 'What is the present tense of "jumped"?', options: ['jump', 'jumping', 'will jump', 'jumped'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_120', question: 'Singular means:', options: ['More than one', 'Just one', 'None', 'Many'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_121', question: 'Plural means:', options: ['Just one', 'More than one', 'None', 'Zero'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_122', question: 'Which is singular?', options: ['cats', 'dogs', 'car', 'books'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_123', question: 'Which is plural?', options: ['cat', 'dog', 'bird', 'horses'], correctAnswer: 3, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_124', question: 'Find the verb: "The cat sleeps."', options: ['The', 'cat', 'sleeps', 'None'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_125', question: 'Find the adjective: "The red car."', options: ['The', 'red', 'car', 'None'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_126', question: 'Find the noun: "A big elephant."', options: ['A', 'big', 'elephant', 'None'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_127', question: 'Which word describes HOW she ran? "She ran quickly."', options: ['She', 'ran', 'quickly', 'None'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_128', question: 'Past tense of "play":', options: ['plays', 'playing', 'played', 'will play'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_129', question: 'Present tense of "ran":', options: ['run', 'running', 'will run', 'ran'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_130', question: 'Which sentence is in past tense?', options: ['I walk to school', 'I walked to school', 'I will walk to school', 'I am walking'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // PUNCTUATION (20 questions)
  { id: 'y2_eng_131', question: 'A capital letter is used:', options: ['In the middle of words', 'At the start of sentences and names', 'At the end', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_132', question: 'A full stop goes:', options: ['At the start', 'At the end of a sentence', 'In the middle', 'Nowhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_133', question: 'A question mark is used for:', options: ['Statements', 'Questions', 'Exclamations', 'Names'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_134', question: 'Which needs a question mark? "Where is my book___"', options: ['.', '!', '?', ','], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_135', question: 'An exclamation mark shows:', options: ['A question', 'Strong feeling or surprise', 'Nothing', 'A name'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_136', question: 'Which needs an exclamation mark? "Watch out___"', options: ['.', '?', '!', ','], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_137', question: 'Commas in a list separate:', options: ['Sentences', 'Items', 'Paragraphs', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_138', question: 'Which is correct? "I have apples___ oranges___ and bananas."', options: ['no commas', 'apples, oranges,', 'apples. oranges.', 'apples! oranges!'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_139', question: 'An apostrophe for contraction shows:', options: ['Possession', 'Missing letters', 'A list', 'A question'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_140', question: '"Do not" becomes ___ with an apostrophe:', options: ['dont', 'don\'t', 'do\'nt', 'doNot'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_141', question: '"I am" becomes:', options: ['Im', 'I\'m', 'Iam', 'I,m'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_142', question: 'Which is correct?', options: ['i like cats.', 'I like cats.', 'i Like cats.', 'I Like Cats.'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_143', question: 'Names need:', options: ['Small letters', 'Capital letters', 'No letters', 'Numbers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_144', question: 'Which is correct?', options: ['tom and sara', 'Tom and Sara', 'tom And sara', 'Tom And Sara'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_145', question: '"Cannot" becomes:', options: ['cant', 'can\'t', 'ca\'nt', 'canNot'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_146', question: 'The word "I" is always:', options: ['lowercase i', 'Capital I', 'Ii', 'iI'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_147', question: 'Days of the week start with:', options: ['Small letters', 'Capital letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_148', question: 'Months of the year start with:', options: ['Small letters', 'Capital letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_149', question: 'Which is punctuated correctly?', options: ['how are you', 'How are you?', 'how are you.', 'How Are You'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_150', question: '"It is" becomes:', options: ['its', 'it\'s', 'i\'ts', 'Its'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },

  // HANDWRITING & PRESENTATION (10 questions)
  { id: 'y2_eng_151', question: 'Letters should be:', options: ['All different sizes', 'Sized correctly', 'Very tiny', 'Huge'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_152', question: 'Spacing between words should be:', options: ['No space', 'Consistent and clear', 'Very large', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_153', question: 'Joined handwriting means:', options: ['Letters are separate', 'Letters are connected', 'No writing', 'Only capitals'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_154', question: 'Neat writing helps:', options: ['Make it messy', 'Others to read your work', 'Waste time', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_155', question: 'Tall letters like "l" and "h" should:', options: ['Be very short', 'Reach above the line', 'Go below the line', 'Be any size'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_156', question: 'Letters with tails like "g" and "y" should:', options: ['Stay on the line', 'Go below the line', 'Go above the line', 'Be very small'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_157', question: 'Presentation means:', options: ['Not caring how it looks', 'Making your work look neat and clear', 'Using no spaces', 'Writing very fast'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_158', question: 'Why is neat handwriting important?', options: ['It\'s not important', 'So others can read your ideas', 'To waste time', 'To make mistakes'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_159', question: 'When forming letters, you should:', options: ['Start anywhere', 'Start at the correct place', 'Write backwards', 'Never practice'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_160', question: 'Good presentation includes:', options: ['Messy writing', 'Neat writing and clear spacing', 'No punctuation', 'Random letters'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // SPEAKING & LISTENING (10 questions)
  { id: 'y2_eng_161', question: 'When speaking, use:', options: ['Random words', 'Full sentences', 'Only gestures', 'Silence'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_162', question: 'When someone asks a question, you should:', options: ['Ignore them', 'Answer clearly', 'Run away', 'Shout'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_163', question: 'Retelling a story orally means:', options: ['Writing it down', 'Telling it using your voice', 'Drawing it', 'Forgetting it'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_164', question: 'When presenting ideas, speak:', options: ['Very quietly', 'Clearly and confidently', 'Very fast', 'Not at all'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_165', question: 'Good listeners:', options: ['Talk over others', 'Pay attention', 'Look away', 'Interrupt'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_166', question: 'When asking a question, remember to:', options: ['Shout', 'Be polite and clear', 'Look down', 'Mumble'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_167', question: 'Eye contact when speaking means:', options: ['Looking at the floor', 'Looking at the person', 'Closing your eyes', 'Looking away'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_168', question: 'Speaking in full sentences helps:', options: ['Confuse people', 'Make your ideas clear', 'Waste time', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_169', question: 'When listening, you should:', options: ['Interrupt', 'Focus on the speaker', 'Talk to others', 'Not pay attention'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_170', question: 'A clear voice is:', options: ['Mumbled', 'Easy to hear and understand', 'Very quiet', 'Very loud'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // VOCABULARY DEVELOPMENT (15 questions)
  { id: 'y2_eng_171', question: 'A synonym is a word that:', options: ['Means the opposite', 'Means the same or similar', 'Rhymes', 'Has no meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_172', question: 'A synonym for "happy" is:', options: ['sad', 'joyful', 'angry', 'tired'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_173', question: 'An antonym is a word that:', options: ['Means the same', 'Means the opposite', 'Rhymes', 'Has no meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_174', question: 'An antonym for "hot" is:', options: ['warm', 'cold', 'big', 'small'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_175', question: 'Learning new words helps you:', options: ['Forget things', 'Communicate better', 'Get confused', 'Waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_176', question: 'A dictionary helps you:', options: ['Find word meanings', 'Draw pictures', 'Play games', 'Count numbers'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_177', question: 'What does "enormous" mean?', options: ['Very small', 'Very big', 'Medium', 'Colorful'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_178', question: 'A synonym for "big" is:', options: ['small', 'tiny', 'large', 'short'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_179', question: 'An antonym for "fast" is:', options: ['quick', 'slow', 'speedy', 'rapid'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_180', question: 'What does "tiny" mean?', options: ['Very big', 'Very small', 'Very tall', 'Very fast'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_181', question: 'A synonym for "sad" is:', options: ['happy', 'unhappy', 'joyful', 'excited'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_182', question: 'An antonym for "day" is:', options: ['morning', 'afternoon', 'night', 'evening'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_183', question: 'What does "frightened" mean?', options: ['Happy', 'Scared', 'Brave', 'Excited'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_184', question: 'A synonym for "beautiful" is:', options: ['ugly', 'lovely', 'plain', 'dull'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_185', question: 'Discussing word meanings helps you:', options: ['Forget words', 'Understand and use them better', 'Get confused', 'Waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // POETRY & PERFORMANCE (10 questions)
  { id: 'y2_eng_186', question: 'When performing a poem, use:', options: ['A boring voice', 'Expression and feeling', 'No voice', 'Silence'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_187', question: 'Rhyming words have:', options: ['Different endings', 'The same ending sound', 'No connection', 'Different meanings only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_188', question: 'Which words rhyme?', options: ['cat, dog', 'sun, fun', 'big, small', 'run, walk'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_189', question: 'A simple poem can have:', options: ['No words', 'Short lines and maybe rhyme', 'Only pictures', 'Only numbers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_190', question: 'When reading a poem aloud, think about:', options: ['Reading very fast', 'Rhythm and expression', 'Skipping words', 'Being silent'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_191', question: 'Which words rhyme?', options: ['tree, bee', 'car, bus', 'house, flat', 'book, pen'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_192', question: 'Creating a poem means:', options: ['Copying exactly', 'Making your own using words creatively', 'Not writing', 'Drawing only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_193', question: 'Poems can be about:', options: ['Nothing', 'Anything you choose', 'Only animals', 'Only numbers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_194', question: 'Performing means:', options: ['Hiding', 'Presenting aloud to others', 'Staying silent', 'Sleeping'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_195', question: 'A poem\'s rhythm is:', options: ['The color', 'The beat or pattern', 'The size', 'The shape'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },

  // REASONING & LANGUAGE SKILLS (15 questions)
  { id: 'y2_eng_196', question: 'Find the error: "the dog is big"', options: ['No error', 'Should be "The"', 'Should be "doG"', 'Should be "iS"'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_197', question: 'Which is correct?', options: ['I like apples', 'i like apples.', 'I like apples.', 'i Like apples'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_198', question: 'Fix this: "she went home"', options: ['she went home', 'She went home.', 'shE Went Home', 'she Went home.'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_199', question: 'Put in order: "home went I"', options: ['home went I', 'went I home', 'I went home', 'I home went'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_200', question: 'Choose the correct word: "I ___ to school." (present)', options: ['goed', 'went', 'go', 'going'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_201', question: 'Which sentence matches the picture of a boy reading?', options: ['The boy runs', 'The boy reads', 'The boy sleeps', 'The boy eats'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_202', question: 'What\'s wrong? "He like sweets"', options: ['Nothing', 'Should be "likes"', 'Should be "liked"', 'Should be "liking"'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_203', question: 'Order these: 3. Finally 2. Then 1. First', options: ['3, 2, 1', '1, 2, 3', '2, 1, 3', '1, 3, 2'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_204', question: 'Which makes sense? "The bird ___ in the sky"', options: ['swims', 'drives', 'flies', 'walks'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_205', question: 'Find the mistake: "I has a dog"', options: ['No mistake', 'Should be "have"', 'Should be "had"', 'Should be "having"'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_206', question: 'Which is correctly punctuated?', options: ['where is my book', 'Where is my book.', 'Where is my book?', 'where is my book?'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_207', question: 'Choose the right word: "The cat ___ on the mat." (past)', options: ['sit', 'sits', 'sat', 'sitting'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_208', question: 'Fix the word order: "red big the ball"', options: ['red big the ball', 'the big red ball', 'big the red ball', 'ball red big the'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_eng_209', question: 'Which sentence is complete?', options: ['Running fast', 'The happy dog', 'She plays outside.', 'Very beautiful'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_eng_210', question: 'Understanding a text means:', options: ['Only reading words', 'Knowing what it means', 'Skipping parts', 'Guessing randomly'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 }
];
