// Year 7 Science Trivia Questions
// Based on UK Year 7 Science Curriculum Framework (KS3)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_7_SCIENCE_QUESTIONS = [
  // CELLS & ORGANIZATION (25 questions)
  { id: 'y7_sci_1', question: 'What is a cell?', options: ['A prison', 'Basic unit of life', 'An organ', 'A tissue'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_2', question: 'What controls what enters/exits a cell?', options: ['Nucleus', 'Cell membrane', 'Cytoplasm', 'Mitochondria'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_3', question: 'What is the nucleus?', options: ['Cell wall', 'Control center containing DNA', 'Outer layer', 'Energy producer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_4', question: 'Where does most chemical reactions happen in cell?', options: ['Nucleus', 'Cytoplasm', 'Membrane', 'Cell wall'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_5', question: 'What produces energy in cells?', options: ['Nucleus', 'Cytoplasm', 'Mitochondria', 'Membrane'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_6', question: 'Plant cells have ___ but animal cells don\'t:', options: ['Nucleus', 'Membrane', 'Cell wall and chloroplasts', 'Cytoplasm'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_7', question: 'What are chloroplasts for?', options: ['Energy', 'Photosynthesis', 'Storage', 'Support'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_8', question: 'What stores cell sap in plants?', options: ['Nucleus', 'Chloroplast', 'Vacuole', 'Mitochondria'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_9', question: 'Cell wall provides:', options: ['Energy', 'Support and shape', 'Food', 'Color'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_10', question: 'What is a tissue?', options: ['One cell', 'Group of similar cells', 'An organ', 'A system'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_11', question: 'What is an organ?', options: ['One cell', 'One tissue', 'Group of tissues working together', 'One system'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_12', question: 'What is an organ system?', options: ['One organ', 'Group of organs working together', 'One tissue', 'One cell'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_13', question: 'Example of organ system:', options: ['Heart', 'Blood', 'Circulatory system', 'Cell'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_14', question: 'Example of organ:', options: ['Red blood cell', 'Heart', 'Circulatory system', 'Organism'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_15', question: 'Example of tissue:', options: ['Heart', 'Muscle tissue', 'Cell', 'Organism'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_16', question: 'What is a specialized cell?', options: ['General cell', 'Cell adapted for specific function', 'Dead cell', 'Plant cell'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_17', question: 'Red blood cells transport:', options: ['Water', 'Oxygen', 'Food', 'Waste'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_18', question: 'Nerve cells transmit:', options: ['Food', 'Electrical signals', 'Oxygen', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_19', question: 'Root hair cells:', options: ['Transport water up', 'Absorb water and minerals', 'Photosynthesize', 'Support'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_20', question: 'Palisade cells are for:', options: ['Support', 'Photosynthesis', 'Transport', 'Absorption'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_21', question: 'What is a unicellular organism?', options: ['Many cells', 'One cell', 'No cells', 'Dead'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_22', question: 'What is a multicellular organism?', options: ['One cell', 'Many cells', 'No cells', 'Bacteria'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_23', question: 'Example of unicellular:', options: ['Human', 'Dog', 'Bacteria', 'Tree'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_24', question: 'Microscope magnifies:', options: ['Nothing', 'Small objects', 'Large objects', 'Far objects'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_25', question: 'Total magnification = eyepiece × ___:', options: ['Size', 'Objective lens', 'Light', 'Focus'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // REPRODUCTION (20 questions - keeping it age-appropriate)
  { id: 'y7_sci_26', question: 'What is reproduction?', options: ['Growing', 'Producing offspring', 'Eating', 'Moving'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_27', question: 'Sexual reproduction needs:', options: ['One parent', 'Two parents', 'Three parents', 'No parents'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_28', question: 'Asexual reproduction needs:', options: ['Two parents', 'One parent', 'Three parents', 'No parent'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_29', question: 'Male reproductive cell:', options: ['Egg', 'Sperm', 'Zygote', 'Embryo'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_30', question: 'Female reproductive cell:', options: ['Sperm', 'Egg/ovum', 'Zygote', 'Embryo'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_31', question: 'When sperm meets egg:', options: ['Nothing', 'Fertilization occurs', 'They separate', 'They die'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_32', question: 'Fertilized egg is called:', options: ['Sperm', 'Egg', 'Zygote', 'Tissue'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_33', question: 'Where does human baby develop?', options: ['Ovary', 'Uterus/womb', 'Stomach', 'Brain'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_34', question: 'Time for human baby development:', options: ['3 months', '6 months', '9 months', '12 months'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_35', question: 'Male flower part:', options: ['Petal', 'Stamen', 'Stigma', 'Ovary'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_36', question: 'Female flower part:', options: ['Stamen', 'Carpel/pistil', 'Sepal', 'Petal'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_37', question: 'Pollen transfer is called:', options: ['Fertilization', 'Pollination', 'Germination', 'Reproduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_38', question: 'Pollinators include:', options: ['Rain', 'Insects, birds, wind', 'Soil', 'Darkness'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_39', question: 'After pollination, flowers produce:', options: ['More petals', 'Seeds', 'Roots', 'Leaves'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_40', question: 'Seeds contain:', options: ['Nothing', 'Baby plant (embryo)', 'Water only', 'Soil'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_41', question: 'Seed germination needs:', options: ['Only light', 'Water, warmth, oxygen', 'Only soil', 'Only darkness'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_42', question: 'Advantage of sexual reproduction:', options: ['Fast', 'Genetic variation', 'Needs one parent', 'Simple'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_43', question: 'Advantage of asexual reproduction:', options: ['Variation', 'Fast, needs one parent', 'Complex', 'Slow'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_44', question: 'What is menstruation?', options: ['Male only', 'Monthly cycle in females', 'Growth', 'Digestion'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_45', question: 'What is adolescence?', options: ['Childhood', 'Transition from child to adult', 'Old age', 'Birth'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // PARTICLES (25 questions)
  { id: 'y7_sci_46', question: 'What are the three states of matter?', options: ['Hot, cold, warm', 'Solid, liquid, gas', 'Big, small, medium', 'Hard, soft, rough'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_47', question: 'Particles in solid are:', options: ['Far apart', 'Close together, vibrate', 'Moving freely', 'Not there'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_48', question: 'Particles in liquid:', options: ['Fixed', 'Can move around each other', 'Very far apart', 'Don\'t exist'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_49', question: 'Particles in gas:', options: ['Close together', 'Very far apart, move freely', 'Fixed', 'Don\'t move'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_50', question: 'Solid to liquid:', options: ['Freezing', 'Melting', 'Evaporating', 'Condensing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_51', question: 'Liquid to solid:', options: ['Melting', 'Freezing', 'Evaporating', 'Condensing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_52', question: 'Liquid to gas:', options: ['Melting', 'Freezing', 'Evaporating', 'Condensing'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_53', question: 'Gas to liquid:', options: ['Melting', 'Freezing', 'Evaporating', 'Condensing'], correctAnswer: 3, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_54', question: 'Melting point of water:', options: ['0°C', '50°C', '100°C', '25°C'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_55', question: 'Boiling point of water:', options: ['0°C', '50°C', '100°C', '25°C'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_56', question: 'Diffusion is:', options: ['No movement', 'Particles spreading from high to low concentration', 'Only in solids', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_57', question: 'Diffusion is fastest in:', options: ['Solids', 'Liquids', 'Gases', 'Same all'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_58', question: 'Temperature increase makes particles:', options: ['Stop', 'Move faster', 'Move slower', 'Disappear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_59', question: 'Pressure in gas is caused by:', options: ['Nothing', 'Particles hitting container walls', 'Magic', 'Light'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_60', question: 'Increase temperature of gas:', options: ['Decreases pressure', 'Increases pressure', 'No change', 'Makes solid'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_61', question: 'Gas expands when heated because:', options: ['Particles stop', 'Particles move faster and spread out', 'Particles die', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_62', question: 'Density = mass ÷ ___:', options: ['Temperature', 'Volume', 'Pressure', 'Size'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_63', question: 'Solids generally have ___ density than gases:', options: ['Lower', 'Higher', 'Same', 'No'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_64', question: 'What is sublimation?', options: ['Liquid to gas', 'Solid to gas directly', 'Gas to liquid', 'Liquid to solid'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_sci_65', question: 'State changes are ___ changes:', options: ['Irreversible', 'Physical/reversible', 'Chemical', 'Permanent'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_66', question: 'Conservation of mass means:', options: ['Mass changes', 'Mass stays same in state changes', 'Mass increases', 'Mass decreases'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_67', question: 'Brownian motion is:', options: ['No movement', 'Random particle movement', 'Straight lines', 'Circles'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_sci_68', question: 'Brownian motion provides evidence for:', options: ['Nothing', 'Particle theory', 'Magic', 'Light'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_sci_69', question: 'At absolute zero (-273°C) particles:', options: ['Move fastest', 'Have no energy/stop moving', 'Explode', 'Disappear'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_sci_70', question: 'Particle model explains:', options: ['Nothing', 'Properties of materials', 'Only colors', 'Only smells'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // ELEMENTS, ATOMS & COMPOUNDS (25 questions)
  { id: 'y7_sci_71', question: 'What is an element?', options: ['Mixture', 'Substance made of one type of atom', 'Compound', 'Solution'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_72', question: 'What is an atom?', options: ['Largest particle', 'Smallest particle of element', 'A molecule', 'A compound'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_73', question: 'What is a compound?', options: ['One element', 'Two+ elements chemically bonded', 'A mixture', 'An atom'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_74', question: 'What is a mixture?', options: ['One substance', 'Two+ substances not chemically bonded', 'A compound', 'An element'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_75', question: 'Chemical symbol for oxygen:', options: ['Ox', 'O', 'O₂', 'Og'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_76', question: 'Chemical symbol for carbon:', options: ['Ca', 'C', 'Cr', 'Co'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_77', question: 'Chemical symbol for hydrogen:', options: ['H', 'He', 'Hy', 'Hg'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_78', question: 'Chemical symbol for nitrogen:', options: ['Ni', 'N', 'Ne', 'Na'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_79', question: 'Water formula:', options: ['H', 'O', 'H₂O', 'HO'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_80', question: 'CO₂ is:', options: ['Carbon monoxide', 'Carbon dioxide', 'Oxygen', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_81', question: 'H₂O molecule contains:', options: ['1H, 1O', '2H, 1O', '1H, 2O', '2H, 2O'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_82', question: 'Periodic table organizes:', options: ['Compounds', 'Elements', 'Mixtures', 'Solutions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_83', question: 'Elements in same group have:', options: ['Different properties', 'Similar properties', 'No pattern', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_84', question: 'What are metals like?', options: ['Brittle, dull', 'Shiny, conduct electricity, malleable', 'Transparent', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_85', question: 'What are non-metals like?', options: ['Shiny, conduct', 'Dull, don\'t conduct well', 'Only gases', 'Only solids'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_86', question: 'Separation technique for different boiling points:', options: ['Filtration', 'Distillation', 'Chromatography', 'Magnetism'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_87', question: 'Separation technique for insoluble solid from liquid:', options: ['Distillation', 'Filtration', 'Chromatography', 'Evaporation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_88', question: 'Separation technique for dissolved solids:', options: ['Filtration', 'Evaporation/crystallization', 'Magnetism', 'Distillation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_89', question: 'Chromatography separates:', options: ['Metals', 'Mixtures like inks/dyes', 'Pure substances', 'Elements'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_90', question: 'Pure substance has:', options: ['Mixed properties', 'Fixed melting/boiling point', 'Variable properties', 'Random melting point'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_91', question: 'What is a molecule?', options: ['One atom', 'Two+ atoms bonded together', 'An element', 'A mixture'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_92', question: 'O₂ is:', options: ['One oxygen atom', 'Oxygen molecule (2 atoms)', 'A compound', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_93', question: 'Inside atom center is:', options: ['Electrons', 'Nucleus (protons & neutrons)', 'Nothing', 'Vacuole'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_94', question: 'Electrons are:', options: ['In nucleus', 'Around nucleus in shells', 'Not in atom', 'Only in compounds'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_95', question: 'Chemical reaction produces:', options: ['Same substances', 'New substances', 'Only heat', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // REACTIONS (20 questions)
  { id: 'y7_sci_96', question: 'Sign of chemical reaction:', options: ['No change', 'Color change, gas, heat, precipitate', 'Only color', 'Only heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_97', question: 'Reactants are:', options: ['Products', 'Starting substances', 'Catalysts', 'Observers'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_98', question: 'Products are:', options: ['Starting substances', 'Substances made', 'Reactants', 'Catalysts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_99', question: 'Word equation format:', options: ['Product → Reactant', 'Reactants → Products', 'Both same', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_100', question: 'Combustion needs:', options: ['No oxygen', 'Fuel, oxygen, heat', 'Only fuel', 'Only heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_101', question: 'Combustion of hydrocarbon produces:', options: ['Only smoke', 'CO₂ and H₂O', 'Only CO₂', 'Only H₂O'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_102', question: 'Thermal decomposition:', options: ['Joining', 'Breaking down with heat', 'Mixing', 'Dissolving'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_103', question: 'Oxidation is:', options: ['Losing oxygen', 'Gaining oxygen', 'No change', 'Reduction'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_104', question: 'Acid + Metal →', options: ['Salt + water', 'Salt + hydrogen', 'Only salt', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_105', question: 'Acid + Alkali →', options: ['Salt + hydrogen', 'Salt + water (neutralization)', 'Only salt', 'Only water'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_106', question: 'What is neutralization?', options: ['Making acid', 'Acid + alkali → salt + water', 'Making alkali', 'Combustion'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_107', question: 'pH less than 7:', options: ['Neutral', 'Acid', 'Alkali', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_108', question: 'pH 7:', options: ['Acid', 'Neutral', 'Alkali', 'Strong acid'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_109', question: 'pH greater than 7:', options: ['Acid', 'Neutral', 'Alkali', 'Strong acid'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_110', question: 'Universal indicator shows:', options: ['Temperature', 'pH by color', 'Pressure', 'Volume'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_111', question: 'Red litmus in alkali turns:', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_112', question: 'Blue litmus in acid turns:', options: ['Blue', 'Red', 'Green', 'Yellow'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_113', question: 'Catalyst:', options: ['Slows reaction', 'Speeds up reaction without being used up', 'Is reactant', 'Is product'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_114', question: 'Exothermic reaction:', options: ['Takes in heat', 'Releases heat', 'No heat change', 'Absorbs light'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_115', question: 'Endothermic reaction:', options: ['Releases heat', 'Takes in heat', 'No heat change', 'Releases light'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // ENERGY (25 questions)
  { id: 'y7_sci_116', question: 'Energy cannot be:', options: ['Transferred', 'Created or destroyed', 'Stored', 'Used'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_117', question: 'Energy is measured in:', options: ['Watts', 'Joules', 'Newtons', 'Meters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_118', question: 'Energy stores include:', options: ['Only heat', 'Kinetic, potential, chemical, thermal', 'Only kinetic', 'Only chemical'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_119', question: 'Kinetic energy is:', options: ['Stored', 'Energy of movement', 'Chemical', 'Nuclear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_120', question: 'Potential energy is:', options: ['Movement energy', 'Stored energy (position/height)', 'Heat', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_121', question: 'Chemical energy stored in:', options: ['Height', 'Food, fuels, batteries', 'Motion', 'Sound'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_122', question: 'Thermal energy is:', options: ['Light', 'Heat', 'Sound', 'Movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_123', question: 'Energy transfer methods:', options: ['Only heat', 'Mechanical, electrical, heating, radiation', 'Only electrical', 'Only radiation'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_124', question: 'Conduction is:', options: ['Heat through liquid/gas', 'Heat through solid by particles', 'Heat by waves', 'No heat transfer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_125', question: 'Convection is:', options: ['Heat through solid', 'Heat through liquid/gas by circulation', 'Heat by waves', 'No transfer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_126', question: 'Radiation is:', options: ['Heat through solid', 'Heat through liquid', 'Heat by waves, no medium needed', 'No transfer'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_127', question: 'Good conductors:', options: ['Wood, plastic', 'Metals', 'Air', 'Vacuum'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_128', question: 'Good insulators:', options: ['Metals', 'Wood, plastic, air', 'Only metals', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_129', question: 'Renewable energy:', options: ['Coal, oil', 'Solar, wind, hydro', 'Only fossil fuels', 'Nuclear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_130', question: 'Non-renewable energy:', options: ['Solar', 'Coal, oil, gas', 'Wind', 'Hydro'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_131', question: 'Fossil fuels formed from:', options: ['Rocks', 'Dead organisms over millions of years', 'Plants only', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_132', question: 'Burning fossil fuels produces:', options: ['Only heat', 'Heat and CO₂', 'Only CO₂', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_133', question: 'Power measured in:', options: ['Joules', 'Watts', 'Newtons', 'Meters'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_134', question: 'Power = energy ÷ ___:', options: ['Mass', 'Time', 'Distance', 'Force'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_135', question: 'Efficient means:', options: ['Wastes energy', 'Transfers energy usefully', 'No transfer', 'Uses lots energy'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_136', question: 'Wasted energy usually as:', options: ['Light', 'Heat and sound', 'Chemical', 'Nuclear'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_137', question: 'Energy resource concerns:', options: ['Unlimited', 'Running out, pollution, climate change', 'No concerns', 'Only cost'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_138', question: 'Photosynthesis stores energy as:', options: ['Heat', 'Chemical (glucose)', 'Kinetic', 'Sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_139', question: 'Temperature measures:', options: ['Energy', 'How hot/cold', 'Power', 'Force'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_140', question: 'Sankey diagram shows:', options: ['Nothing', 'Energy transfers', 'Forces', 'Distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // FORCES (20 questions)
  { id: 'y7_sci_141', question: 'Force measured in:', options: ['Joules', 'Watts', 'Newtons', 'Meters'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_142', question: 'Balanced forces mean:', options: ['Object accelerates', 'Object stays at rest or constant speed', 'Object stops', 'Object explodes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_143', question: 'Unbalanced forces mean:', options: ['No change', 'Object accelerates/decelerates', 'Object disappears', 'No movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_144', question: 'What is gravity?', options: ['Magnetism', 'Force pulling objects towards Earth', 'Push force', 'Heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_145', question: 'Weight = mass × ___:', options: ['Speed', 'Gravity', 'Distance', 'Time'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_146', question: 'Mass is:', options: ['Force', 'Amount of matter', 'Weight', 'Energy'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_147', question: 'Weight is:', options: ['Amount of matter', 'Force of gravity on object', 'Volume', 'Distance'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_148', question: 'Mass measured in:', options: ['Newtons', 'Kilograms', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_149', question: 'Weight measured in:', options: ['Kilograms', 'Newtons', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_150', question: 'Friction opposes:', options: ['Nothing', 'Motion', 'Gravity', 'Heat'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_151', question: 'Air resistance is:', options: ['Gravity', 'Friction from air', 'Magnetism', 'Weight'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_152', question: 'Water resistance is:', options: ['Gravity', 'Friction from water', 'Magnetism', 'Weight'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_153', question: 'Speed = distance ÷ ___:', options: ['Mass', 'Time', 'Force', 'Energy'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_154', question: 'Speed measured in:', options: ['m', 'm/s or km/h', 's', 'N'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_155', question: 'If 100m in 10s, speed =', options: ['5 m/s', '10 m/s', '100 m/s', '1000 m/s'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_156', question: 'Distance-time graph: flat line means:', options: ['Moving', 'Stationary', 'Accelerating', 'Slowing'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_157', question: 'Distance-time graph: steep line means:', options: ['Slow', 'Fast', 'Stopped', 'Backwards'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_158', question: 'Pressure = force ÷ ___:', options: ['Distance', 'Area', 'Mass', 'Time'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_159', question: 'Smaller area, same force means:', options: ['Less pressure', 'More pressure', 'Same pressure', 'No pressure'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_160', question: 'Pressure measured in:', options: ['Newtons', 'Pascals', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // WAVES - SOUND & LIGHT (25 questions)
  { id: 'y7_sci_161', question: 'Sound travels through:', options: ['Vacuum', 'Medium (solid, liquid, gas)', 'Only air', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_162', question: 'Sound cannot travel through:', options: ['Air', 'Water', 'Vacuum (empty space)', 'Solids'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_163', question: 'Sound travels fastest in:', options: ['Air', 'Water', 'Solids', 'Vacuum'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_164', question: 'Sound is caused by:', options: ['Light', 'Vibrations', 'Heat', 'Magnetism'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_165', question: 'Pitch is:', options: ['Loudness', 'How high/low sound is', 'Volume', 'Speed'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_166', question: 'High pitch means:', options: ['Slow vibrations', 'Fast vibrations', 'No vibrations', 'Loud'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_167', question: 'Volume/loudness is:', options: ['How high/low', 'How loud/quiet', 'How fast', 'Color'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_168', question: 'Loud sound has:', options: ['Weak vibrations', 'Strong vibrations', 'No vibrations', 'High pitch'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_169', question: 'Frequency measured in:', options: ['Meters', 'Hertz (Hz)', 'Joules', 'Newtons'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_170', question: 'High frequency = ___ pitch:', options: ['Low', 'High', 'No', 'Medium'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_171', question: 'Amplitude relates to:', options: ['Pitch', 'Loudness', 'Speed', 'Color'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_172', question: 'Echo is:', options: ['New sound', 'Reflected sound', 'No sound', 'Absorbed sound'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_173', question: 'Light travels in:', options: ['Curves', 'Straight lines', 'Circles', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_174', question: 'Light travels ___ than sound:', options: ['Slower', 'Faster', 'Same speed', 'Not at all'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_175', question: 'Reflection is:', options: ['Light passing through', 'Light bouncing off', 'Light being absorbed', 'Light stopping'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_176', question: 'Law of reflection: angle in = angle ___:', options: ['Double', 'Out', 'Half', 'Zero'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_177', question: 'Transparent materials:', options: ['Block all light', 'Let light through', 'Reflect light', 'Absorb all'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_178', question: 'Opaque materials:', options: ['Let light through', 'Block light', 'Are invisible', 'Glow'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_179', question: 'Translucent materials:', options: ['Block all light', 'Let some light through (blurry)', 'Transparent', 'Opaque'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_180', question: 'White light contains:', options: ['One color', 'All colors', 'No colors', 'Only white'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_181', question: 'Prism splits white light into:', options: ['Nothing', 'Spectrum/rainbow colors', 'Only red', 'Only blue'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_182', question: 'Objects appear colored because they:', options: ['Produce light', 'Reflect certain colors', 'Glow', 'Are magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_183', question: 'Red apple appears red because it:', options: ['Absorbs red', 'Reflects red', 'Makes red', 'Is magic'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_184', question: 'Filters:', options: ['Block all colors', 'Only let certain colors through', 'Make new colors', 'Reflect everything'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_185', question: 'Primary colors of light:', options: ['Red, yellow, blue', 'Red, green, blue', 'Red, orange, yellow', 'Only red'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // ELECTRICITY & MAGNETISM (10 questions)
  { id: 'y7_sci_186', question: 'Series circuit has:', options: ['Multiple paths', 'One path', 'No path', 'Random paths'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_187', question: 'In series, if one bulb breaks:', options: ['Others stay on', 'All go out', 'Brighter', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_188', question: 'Current measured with:', options: ['Voltmeter', 'Ammeter', 'Thermometer', 'Ruler'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_189', question: 'Current measured in:', options: ['Volts', 'Amperes/Amps', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_190', question: 'Voltage measured with:', options: ['Ammeter', 'Voltmeter', 'Thermometer', 'Ruler'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_191', question: 'Voltage measured in:', options: ['Amps', 'Volts', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_192', question: 'What attracts iron?', options: ['Plastic', 'Magnet', 'Wood', 'Glass'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_193', question: 'Magnet has ___ poles:', options: ['One', 'Two (North & South)', 'Three', 'Four'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_194', question: 'Like poles:', options: ['Attract', 'Repel', 'No effect', 'Stick'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_195', question: 'Unlike poles:', options: ['Repel', 'Attract', 'No effect', 'Break'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // ECOSYSTEMS & INTERDEPENDENCE (5 questions)
  { id: 'y7_sci_196', question: 'What is an ecosystem?', options: ['One organism', 'Community of organisms and environment', 'Only plants', 'Only animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_197', question: 'Producer in food chain:', options: ['Animal', 'Plant making own food', 'Consumer', 'Decomposer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_198', question: 'Consumer:', options: ['Makes own food', 'Eats other organisms', 'Is a plant', 'Decomposes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_sci_199', question: 'Decomposer:', options: ['Producer', 'Consumer', 'Breaks down dead matter', 'Hunter'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_sci_200', question: 'Food chain shows:', options: ['Random organisms', 'Energy flow through organisms', 'Only plants', 'Only animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 }
];
