// Year 10 English Trivia Questions
// Based on UK Year 10 English Curriculum Framework (GCSE Literature & Language)
// 200 comprehensive questions covering GCSE English specifications

export const YEAR_10_ENGLISH_QUESTIONS = [
  // LITERATURE - SHAKESPEARE (40 questions)
  { id: 'y10_eng_1', question: 'Who wrote "Macbeth"?', options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Geoffrey Chaucer'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_2', question: 'In "Macbeth", who prophesies Macbeth will be king?', options: ['Duncan', 'Lady Macbeth', 'The three witches', 'Banquo'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_3', question: '"Out, damned spot!" is said by:', options: ['Macbeth', 'Lady Macbeth', 'Duncan', 'Banquo'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_4', question: 'What does Macbeth see before murdering Duncan?', options: ['A ghost', 'A dagger', 'A crown', 'Blood'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_5', question: 'Who kills Macbeth?', options: ['Malcolm', 'Macduff', 'Banquo', 'Duncan'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_6', question: 'In "Romeo and Juliet", which families are feuding?', options: ['Smith and Jones', 'Montague and Capulet', 'Tudor and Stuart', 'York and Lancaster'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_7', question: 'How old is Juliet?', options: ['12', '13', '14', '15'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_8', question: 'Who performs Romeo and Juliet\'s marriage?', options: ['Friar Lawrence', 'Friar John', 'The Prince', 'Lord Capulet'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_9', question: 'What does Juliet take to fake her death?', options: ['Poison', 'Sleeping potion', 'Medicine', 'Wine'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_10', question: 'Who kills Tybalt?', options: ['Mercutio', 'Romeo', 'Benvolio', 'Paris'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_11', question: 'In "Much Ado About Nothing", who is tricked into thinking Hero is unfaithful?', options: ['Benedick', 'Claudio', 'Don Pedro', 'Leonato'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_12', question: 'In "The Merchant of Venice", who demands a pound of flesh?', options: ['Antonio', 'Bassanio', 'Shylock', 'Portia'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_13', question: 'Iambic pentameter has ___ syllables per line:', options: ['8', '10', '12', '14'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_14', question: 'A sonnet has ___ lines:', options: ['10', '12', '14', '16'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_15', question: 'Shakespearean sonnet rhyme scheme:', options: ['ABAB CDCD EFEF GG', 'ABBA CDDC EFFE GG', 'ABAB ABAB CDCD EE', 'AABB CCDD EEFF GG'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_16', question: 'A soliloquy is:', options: ['Dialogue between two characters', 'Speech alone revealing thoughts', 'Stage direction', 'Narrator\'s comment'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_17', question: 'Dramatic irony is when:', options: ['Something is funny', 'Audience knows something characters don\'t', 'Characters argue', 'The ending is tragic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_18', question: 'A tragedy typically ends with:', options: ['Marriage', 'Death of protagonist', 'Happy resolution', 'Comedy'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_19', question: 'Hamartia is a character\'s:', options: ['Strength', 'Fatal flaw', 'Goal', 'Background'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_20', question: 'Hubris means excessive:', options: ['Humility', 'Pride', 'Fear', 'Love'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_21', question: 'In Shakespeare, aside is spoken to:', options: ['Another character', 'The audience', 'No one', 'The entire cast'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_22', question: 'Blank verse is:', options: ['Poetry without rhyme but with meter', 'Prose', 'Free verse', 'Poetry with ABAB rhyme'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_23', question: 'Elizabethan audience mainly stood where?', options: ['Balcony', 'Pit/Groundlings', 'Boxes', 'Stage'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_24', question: 'Shakespeare\'s theatre was called:', options: ['The Globe', 'The Palace', 'The Arena', 'The Stage'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_25', question: 'Female roles in Shakespeare\'s time were played by:', options: ['Women', 'Young boys/men', 'Masked actors', 'Puppets'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_26', question: 'Foreshadowing hints at:', options: ['Past events', 'Future events', 'Character feelings', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_27', question: 'Protagonist is:', options: ['The villain', 'The main character', 'The narrator', 'A minor character'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_28', question: 'Antagonist is:', options: ['The hero', 'Character opposing protagonist', 'The narrator', 'The setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_29', question: 'Catharsis in tragedy causes audience to feel:', options: ['Boredom', 'Emotional release', 'Anger', 'Confusion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_30', question: 'Motif is:', options: ['Main character', 'Recurring element/image', 'Single event', 'Setting'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_31', question: 'Which is NOT a Shakespeare play?', options: ['Hamlet', 'Othello', 'Wuthering Heights', 'Julius Caesar'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_32', question: 'Shakespeare lived in which era?', options: ['Victorian', 'Elizabethan/Jacobean', 'Medieval', 'Modern'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_33', question: 'What is a couplet?', options: ['One line', 'Two consecutive rhyming lines', 'Three lines', 'Four lines'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_34', question: 'Enjambment is:', options: ['End-stopped line', 'Line running onto next without pause', 'Rhyme scheme', 'Metaphor'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_35', question: 'Caesura is:', options: ['A pause within a line', 'The end of a poem', 'A rhyme scheme', 'A metaphor'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_36', question: 'In five-act structure, climax usually in Act:', options: ['1', '3', '4', '5'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_37', question: 'Exposition introduces:', options: ['Climax', 'Resolution', 'Characters, setting, situation', 'Conflict only'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_38', question: 'Resolution occurs in:', options: ['Beginning', 'Middle', 'End', 'Throughout'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_39', question: 'Foil character serves to:', options: ['Be the villain', 'Contrast with main character', 'Provide comedy', 'Narrate'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_40', question: 'Which theme is common in Shakespeare?', options: ['Technology', 'Ambition and power', 'Space travel', 'Modern politics'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // MODERN TEXTS & POETRY (40 questions)
  { id: 'y10_eng_41', question: 'Who wrote "An Inspector Calls"?', options: ['Arthur Miller', 'J.B. Priestley', 'Harold Pinter', 'Tennessee Williams'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_42', question: 'In "An Inspector Calls", what is being investigated?', options: ['A robbery', 'A suicide', 'A murder', 'A fire'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_43', question: 'What does the Inspector represent?', options: ['The police', 'Social conscience/responsibility', 'The government', 'Entertainment'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_44', question: 'When is "An Inspector Calls" set?', options: ['1912', '1945', '1960', '2000'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_45', question: 'Who wrote "A Christmas Carol"?', options: ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'George Orwell'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_46', question: 'How many ghosts visit Scrooge?', options: ['One', 'Two', 'Three', 'Four'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_47', question: 'What phrase does Scrooge say about Christmas?', options: ['"Merry Christmas"', '"Bah! Humbug!"', '"Happy holidays"', '"Season\'s greetings"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_48', question: 'Who wrote "Jekyll and Hyde"?', options: ['Bram Stoker', 'Mary Shelley', 'Robert Louis Stevenson', 'Edgar Allan Poe'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_49', question: 'Main theme of "Jekyll and Hyde":', options: ['Love', 'Duality of human nature', 'War', 'Poverty'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_50', question: 'Who wrote "Animal Farm"?', options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'William Golding'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_51', question: '"Animal Farm" is an allegory of:', options: ['World War II', 'Russian Revolution', 'Industrial Revolution', 'French Revolution'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_52', question: 'Who wrote "Lord of the Flies"?', options: ['George Orwell', 'William Golding', 'J.D. Salinger', 'Harper Lee'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_53', question: 'In "Lord of the Flies", conch symbolizes:', options: ['Evil', 'Order/civilization', 'Fear', 'Hunger'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_54', question: 'Who wrote "To Kill a Mockingbird"?', options: ['Harper Lee', 'John Steinbeck', 'F. Scott Fitzgerald', 'Ernest Hemingway'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_55', question: 'Who wrote "Of Mice and Men"?', options: ['Harper Lee', 'John Steinbeck', 'F. Scott Fitzgerald', 'Mark Twain'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_56', question: 'In "Of Mice and Men", what is Lennie\'s dream?', options: ['To be rich', 'To own a farm with rabbits', 'To travel', 'To be famous'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_57', question: 'Who wrote "The Strange Case of Dr Jekyll and Mr Hyde"?', options: ['Bram Stoker', 'Robert Louis Stevenson', 'Mary Shelley', 'Oscar Wilde'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_58', question: 'Metaphor directly compares saying one thing ___ another:', options: ['is like', 'is', 'as', 'than'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_59', question: 'Simile uses which words?', options: ['"is" or "are"', '"like" or "as"', '"but" or "however"', '"because"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_60', question: 'Personification gives ___ qualities to non-human things:', options: ['Animal', 'Human', 'Plant', 'Mechanical'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_61', question: 'Alliteration repeats ___ sounds:', options: ['Vowel', 'Consonant at start of words', 'Ending', 'Middle'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_62', question: 'Sibilance repeats ___ sounds:', options: ['B sounds', 'S/sh sounds', 'T sounds', 'M sounds'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_63', question: 'Which is sibilance?', options: ['Peter Piper picked', 'She sells sea shells', 'Big bad wolf', 'Round and round'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_64', question: 'Onomatopoeia words:', options: ['Rhyme', 'Sound like their meaning', 'Are long', 'Are short'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_65', question: 'Which is onomatopoeia?', options: ['Happy', 'Crash', 'Beautiful', 'Angry'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_66', question: 'Hyperbole is:', options: ['Understatement', 'Exaggeration', 'Comparison', 'Repetition'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_67', question: 'Oxymoron combines:', options: ['Similar words', 'Contradictory words', 'Long words', 'Short words'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_68', question: 'Which is an oxymoron?', options: ['Happy birthday', 'Bittersweet', 'Red rose', 'Fast car'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_69', question: 'Imagery creates:', options: ['Plot', 'Vivid mental pictures', 'Characters', 'Dialogue'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_70', question: 'Symbolism means object represents:', options: ['Itself only', 'Deeper meaning', 'Nothing', 'The author'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_71', question: 'Juxtaposition places ___ ideas together:', options: ['Similar', 'Contrasting', 'Identical', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_72', question: 'Pathetic fallacy is:', options: ['Being emotional', 'Weather/nature reflecting mood', 'A mistake', 'A character'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_73', question: 'First person narrative uses:', options: ['"He/she"', '"I/we"', '"You"', '"They"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_74', question: 'Third person narrative uses:', options: ['"I/we"', '"You"', '"He/she/they"', 'Only names'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_75', question: 'Third person omniscient narrator knows:', options: ['Nothing', 'One character\'s thoughts', 'Everything about all characters', 'Only what\'s said aloud'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_76', question: 'Unreliable narrator:', options: ['Tells the truth', 'May distort/mislead', 'Knows everything', 'Is objective'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_77', question: 'Stanza is:', options: ['A line', 'A verse/group of lines', 'A rhyme', 'A title'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_78', question: 'Rhyme scheme ABAB means:', options: ['No rhyme', 'Lines 1&2, 3&4 rhyme', 'Lines 1&3, 2&4 rhyme', 'All lines rhyme'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_79', question: 'Free verse has:', options: ['Strict rhyme and meter', 'No set rhyme or meter', 'Only rhyme', 'Only meter'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_80', question: 'Volta in a sonnet is:', options: ['The rhyme', 'The turn/shift in argument', 'The meter', 'The title'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },

  // LANGUAGE ANALYSIS & NON-FICTION (60 questions)
  { id: 'y10_eng_81', question: 'Rhetorical question is asked to:', options: ['Get an answer', 'Make reader think (no answer expected)', 'Confuse', 'Test'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_82', question: 'Emotive language appeals to:', options: ['Logic', 'Emotions', 'Statistics', 'Facts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_83', question: 'Which uses emotive language?', options: ['"Temperature is 20°C"', '"Innocent children suffering"', '"It is Tuesday"', '"5 meters wide"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_84', question: 'Rule of three uses ___ points for impact:', options: ['Two', 'Three', 'Four', 'Five'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_85', question: 'Anecdote is:', options: ['A statistic', 'A short personal story', 'A question', 'A command'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_86', question: 'Statistics provide:', options: ['Emotions', 'Evidence/credibility', 'Entertainment', 'Confusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_87', question: 'Direct address uses ___ to engage reader:', options: ['Third person', '"You"', 'Past tense', 'No pronouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_88', question: 'Imperative verbs give:', options: ['Descriptions', 'Commands', 'Questions', 'Explanations'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_89', question: 'Which is imperative?', options: ['"Are you ready?"', '"Close the door"', '"The door is closed"', '"I closed it"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_90', question: 'Repetition emphasizes by:', options: ['Saying once', 'Repeating words/phrases', 'Using synonyms', 'Being brief'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_91', question: 'Anaphora repeats at ___ of successive clauses:', options: ['End', 'Beginning', 'Middle', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_92', question: 'Tricolon uses ___ parallel elements:', options: ['Two', 'Three', 'Four', 'Five'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_93', question: 'Counterargument:', options: ['Agrees completely', 'Presents and addresses opposing view', 'Ignores other opinions', 'Changes topic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_94', question: 'Bias means:', options: ['Fairness', 'Prejudice favoring one side', 'Objectivity', 'Multiple viewpoints'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_95', question: 'Objective writing is:', options: ['Personal and emotional', 'Unbiased, factual', 'Full of opinions', 'One-sided'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_96', question: 'Subjective writing is:', options: ['Factual only', 'Based on personal opinions/feelings', 'Scientific', 'Neutral'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_97', question: 'Fact is:', options: ['An opinion', 'Can be proven true', 'A guess', 'Always false'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_98', question: 'Opinion is:', options: ['Proven truth', 'A belief/judgment', 'Always correct', 'A fact'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_99', question: 'Which is a fact?', options: ['"Pizza is delicious"', '"Water freezes at 0°C"', '"Summer is best"', '"Red is prettier"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_100', question: 'Which is an opinion?', options: ['"Earth orbits Sun"', '"London is UK capital"', '"Chocolate tastes amazing"', '"7 days in week"'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_101', question: 'Formal language is used in:', options: ['Text messages', 'Academic essays', 'Casual chat', 'Social media'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_102', question: 'Informal language includes:', options: ['Complex vocabulary', 'Slang and contractions', 'Third person', 'No pronouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_103', question: 'Standard English is:', options: ['Slang', 'Widely accepted formal version', 'Regional dialect', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_104', question: 'Tone is the writer\'s:', options: ['Handwriting', 'Attitude toward subject', 'Name', 'Age'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_105', question: 'Mood is the ___ created for reader:', options: ['Confusion', 'Atmosphere/feeling', 'Plot', 'Character'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_106', question: 'Purpose of persuasive text:', options: ['Entertain', 'Convince reader', 'Inform only', 'Describe'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_107', question: 'Purpose of informative text:', options: ['Persuade', 'Educate/inform', 'Entertain', 'Argue'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_108', question: 'Purpose of entertaining text:', options: ['Inform', 'Persuade', 'Amuse/engage', 'Instruct'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_109', question: 'Target audience is:', options: ['The author', 'The intended readers', 'Publishers', 'Printers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_110', question: 'Audience affects:', options: ['Nothing', 'Language, tone, content choices', 'Only length', 'Only font'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_111', question: 'Formal letter starts with:', options: ['"Hi"', '"Dear Sir/Madam" or name', '"Hey"', '"Yo"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_112', question: '"Yours faithfully" when you:', options: ['Know name', 'Don\'t know name (Dear Sir/Madam)', 'Write to friend', 'Are angry'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_113', question: '"Yours sincerely" when you:', options: ['Know the name', 'Don\'t know name', 'Write to friend', 'Write informally'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_114', question: 'Headline should:', options: ['Be very long', 'Grab attention and summarize', 'Confuse', 'Be boring'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_115', question: 'Subheadings:', options: ['Make text longer', 'Organize into sections', 'Confuse', 'Replace paragraphs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_116', question: 'Topic sentence usually at ___ of paragraph:', options: ['End', 'Beginning', 'Middle', 'Not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_117', question: 'Discourse markers like "However" show:', options: ['Time', 'Contrast', 'Addition', 'Cause'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_118', question: '"Furthermore" shows:', options: ['Contrast', 'Addition', 'Time', 'Conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_119', question: '"Meanwhile" shows:', options: ['Contrast', 'Addition', 'Time', 'Cause'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_120', question: '"Therefore" shows:', options: ['Time', 'Contrast', 'Consequence', 'Addition'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_121', question: 'Inference means:', options: ['Reading stated information', 'Reading between lines', 'Summarizing', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_122', question: 'Explicit information is:', options: ['Hidden', 'Clearly stated', 'Implied', 'Guessed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_123', question: 'Implicit information is:', options: ['Clearly stated', 'Suggested/implied', 'In bold', 'In title'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_124', question: 'Context clues help:', options: ['Spell words', 'Determine unknown word meanings', 'Count words', 'Find author'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_125', question: 'Summary should be:', options: ['Longer than original', 'Brief overview of main points', 'Exact copy', 'Only opinions'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_126', question: 'When analyzing language, examine:', options: ['Page numbers', 'Word choice, techniques, effects', 'Font type', 'Paper quality'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_127', question: 'When analyzing structure, examine:', options: ['Only grammar', 'How text is organized', 'Only punctuation', 'Only spelling'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_128', question: 'Circular structure means ending:', options: ['Is different', 'Links back to beginning', 'Is unclear', 'Is long'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_129', question: 'Chronological order is:', options: ['Random', 'Time order', 'Alphabetical', 'Importance'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_130', question: 'Flashback:', options: ['Moves forward', 'Goes to earlier events', 'Stays in present', 'Predicts future'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_131', question: 'Narrative hook:', options: ['Ends story', 'Opens to engage reader', 'Is in middle', 'Concludes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_132', question: 'Cliffhanger:', options: ['Resolves clearly', 'Creates suspense at end', 'Introduces characters', 'Describes setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_133', question: 'Show don\'t tell means:', options: ['State directly', 'Use details to imply', 'Use short sentences', 'Ask questions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_134', question: 'Which "shows" anger?', options: ['"He was angry"', '"His fists clenched, face red"', '"Anger happened"', '"He felt angry"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_135', question: 'Semantic field is:', options: ['Rhyming words', 'Group of words related by meaning', 'Same-sounding words', 'Repeated phrases'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_136', question: 'Connotation is:', options: ['Dictionary meaning', 'Associated meaning/feeling', 'Pronunciation', 'Spelling'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_137', question: 'Denotation is:', options: ['Literal dictionary meaning', 'Associated meaning', 'Pronunciation', 'Spelling'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_138', question: 'Register refers to:', options: ['Volume', 'Level of formality', 'Font', 'Length'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_139', question: 'Syndetic listing uses:', options: ['No connectives', 'Connectives (and, or)', 'Only commas', 'Semicolons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_140', question: 'Asyndetic listing uses:', options: ['Many connectives', 'No connectives (only commas)', 'Semicolons', 'Colons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },

  // GRAMMAR, PUNCTUATION & SPELLING (60 questions)
  { id: 'y10_eng_141', question: 'Which word is a noun?', options: ['Run', 'Quickly', 'Freedom', 'Beautiful'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_142', question: 'Which word is a verb?', options: ['Happy', 'Quickly', 'Jump', 'Table'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_143', question: 'Which word is an adjective?', options: ['Run', 'Brilliant', 'Quickly', 'And'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_144', question: 'Which word is an adverb?', options: ['Happy', 'Happiness', 'Happily', 'Table'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_145', question: 'Abstract noun is:', options: ['Thing you can touch', 'Idea/quality you can\'t touch', 'Person', 'Place'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_146', question: 'Which is abstract?', options: ['Table', 'Dog', 'Love', 'Book'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_147', question: 'Concrete noun is:', options: ['Idea', 'Physical object', 'Emotion', 'Thought'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_148', question: 'Collective noun is:', options: ['One item', 'Group', 'Place', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_149', question: 'Which is collective?', options: ['Dog', 'Pack', 'Happy', 'Run'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_150', question: 'Modal verb expresses:', options: ['Action', 'Possibility/ability/obligation', 'Description', 'Location'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_151', question: 'Which is a modal verb?', options: ['Run', 'Can', 'Happy', 'Table'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_152', question: 'Simple sentence has:', options: ['One main clause', 'Two main clauses', 'No clause', 'Three clauses'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_153', question: 'Compound sentence has:', options: ['One clause', 'Two+ independent clauses', 'No verb', 'Only dependent clauses'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_154', question: 'Compound sentence uses:', options: ['Subordinating conjunctions', 'Coordinating conjunctions (and, but, or)', 'No conjunctions', 'Relative pronouns'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_155', question: 'Complex sentence has:', options: ['Only one clause', 'Independent and dependent clause', 'No verb', 'No subject'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_156', question: 'Subordinate clause:', options: ['Can stand alone', 'Cannot stand alone', 'Has no verb', 'Is main clause'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_157', question: 'Subordinating conjunctions include:', options: ['and, but, or', 'because, although, if, when', 'I, you, he', 'the, a, an'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_158', question: 'Active voice: subject ___ action:', options: ['Receives', 'Performs', 'Describes', 'Avoids'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_159', question: 'Passive voice: subject ___ action:', options: ['Performs', 'Receives', 'Describes', 'Creates'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_160', question: 'Which is passive?', options: ['"The cat chased mouse"', '"The mouse was chased by cat"', '"The cat is chasing"', '"Chase the mouse"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_161', question: 'Which is correct?', options: ['"Me and John went"', '"John and I went"', '"John and me went"', '"I and John went"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_162', question: 'Which is correct?', options: ['"Their going"', '"There going"', '"They\'re going"', '"Theyre going"'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_163', question: 'Which is correct?', options: ['"Its raining"', '"It\'s raining"', '"Its\' raining"', '"Its\'\' raining"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_164', question: '"The boy\'s book" means:', options: ['Many boys, one book', 'One boy, his book', 'Many boys, many books', 'No possession'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_165', question: '"The boys\' books" means:', options: ['One boy, one book', 'One boy, many books', 'Many boys, their books', 'No possession'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_166', question: 'Semi-colon (;) joins:', options: ['Word and definition', 'Closely related independent clauses', 'Questions', 'Quotes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_167', question: 'Colon (:) introduces:', options: ['Questions', 'List or explanation', 'New paragraph', 'Title'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_168', question: 'Dash (—) can:', options: ['End sentences', 'Add info or create emphasis', 'Show questions', 'Replace all punctuation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_169', question: 'Parentheses ( ) contain:', options: ['Main ideas', 'Additional/less important info', 'Questions', 'Titles'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_170', question: 'Ellipsis (...) shows:', options: ['End of sentence', 'Omission or pause', 'Question', 'Emphasis'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_171', question: 'Subject-verb agreement: "The dogs ___ barking"', options: ['is', 'are', 'was', 'be'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_172', question: 'Subject-verb agreement: "Each student ___ book"', options: ['have', 'has', 'having', 'are'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_173', question: 'Comparative form of "good":', options: ['gooder', 'better', 'best', 'more good'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_174', question: 'Superlative form of "bad":', options: ['badder', 'baddest', 'worse', 'worst'], correctAnswer: 3, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_175', question: 'Double negative is:', options: ['Correct', 'Incorrect in Standard English', 'Emphasis', 'Question form'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_176', question: 'Homophone words:', options: ['Sound same, different meanings', 'Look same', 'Mean same', 'Rhyme'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_177', question: 'Which are homophones?', options: ['big/large', 'there/their/they\'re', 'happy/sad', 'run/walk'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_178', question: 'Synonym means:', options: ['Opposite', 'Similar meaning', 'Sounds same', 'Rhymes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_179', question: 'Antonym means:', options: ['Similar', 'Opposite meaning', 'Sounds same', 'Same spelling'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_180', question: 'Prefix is added at ___ of word:', options: ['End', 'Beginning', 'Middle', 'Nowhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_181', question: 'Suffix is added at ___ of word:', options: ['Beginning', 'End', 'Middle', 'Nowhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_182', question: '"Un-" prefix means:', options: ['Again', 'Not/opposite', 'Before', 'After'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_183', question: '"-less" suffix means:', options: ['More', 'Without', 'Full of', 'Before'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_184', question: 'Proper noun should:', options: ['Be lowercase', 'Start with capital', 'Be plural', 'Be action'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_185', question: 'Pronoun replaces:', options: ['Verb', 'Noun', 'Adjective', 'Adverb'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_186', question: 'Preposition shows:', options: ['Action', 'Position/relationship', 'Description', 'Time only'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_187', question: 'Conjunction connects:', options: ['Only sentences', 'Words, phrases, clauses', 'Only nouns', 'Only verbs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_188', question: 'Past participle of "eat":', options: ['eated', 'ate', 'eaten', 'eating'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_189', question: 'Present participle of "run":', options: ['ran', 'running', 'runned', 'runs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_190', question: 'Imperative mood gives:', options: ['Questions', 'Commands', 'Statements', 'Wishes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_191', question: 'Indicative mood states:', options: ['Commands', 'Facts/questions', 'Wishes', 'Conditions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_192', question: 'Subjunctive mood expresses:', options: ['Facts', 'Wishes/hypotheticals', 'Commands', 'Questions'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_193', question: 'Which uses subjunctive?', options: ['"He is here"', '"If I were rich"', '"I am going"', '"She runs"'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_194', question: 'Transitive verb takes:', options: ['No object', 'An object', 'Only subject', 'No subject'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_195', question: 'Intransitive verb takes:', options: ['An object', 'No object', 'Two objects', 'Subject only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_eng_196', question: 'Relative clause starts with:', options: ['and, but', 'who, which, that', 'because, if', 'I, you, he'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_197', question: 'Determiner comes before:', options: ['Verb', 'Noun', 'Adverb', 'Conjunction'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_198', question: 'Which is a determiner?', options: ['Run', 'The', 'Quickly', 'Happy'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_eng_199', question: 'Infinitive form includes:', options: ['to + verb', 'verb + ing', 'verb + ed', 'Just verb'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_eng_200', question: 'Gerund is:', options: ['Past verb', 'Verb used as noun (verb+ing)', 'Adjective', 'Conjunction'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 }
];
