// Year 9 English Trivia Questions
// Based on UK Year 9 English Curriculum Framework (KS3 Level 3)
// 200 comprehensive questions covering literature, language, grammar, and comprehension

export const YEAR_9_ENGLISH_QUESTIONS = [
  // SHAKESPEARE & CLASSIC LITERATURE (40 questions)
  { id: 'y9_eng_1', question: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Geoffrey Chaucer'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_2', question: 'In "Romeo and Juliet", which families are feuding?', options: ['Smith and Jones', 'Montague and Capulet', 'Tudor and Stuart', 'York and Lancaster'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_3', question: 'What is a soliloquy?', options: ['A type of poem', 'A speech alone on stage revealing thoughts', 'A dialogue between two characters', 'A stage direction'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_4', question: 'In "Macbeth", who prophesies Macbeth will be king?', options: ['Duncan', 'Banquo', 'The three witches', 'Lady Macbeth'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_5', question: '"Out, damned spot!" is said by which character?', options: ['Lady Macbeth', 'Macbeth', 'The Porter', 'Duncan'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_6', question: 'What does iambic pentameter mean?', options: ['5 syllables per line', '10 syllables with unstressed/stressed pattern', '14 lines', 'Rhyming couplets'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_7', question: 'A sonnet has how many lines?', options: ['10', '12', '14', '16'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_8', question: 'Who wrote "A Christmas Carol"?', options: ['William Shakespeare', 'Charles Dickens', 'Robert Louis Stevenson', 'Mark Twain'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_9', question: 'In "A Christmas Carol", how many ghosts visit Scrooge?', options: ['One', 'Two', 'Three', 'Four'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_10', question: 'What does Scrooge say instead of "Merry Christmas"?', options: ['"Happy holidays"', '"Bah! Humbug!"', '"Good day"', '"Season\'s greetings"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_11', question: 'Who wrote "An Inspector Calls"?', options: ['Arthur Miller', 'J.B. Priestley', 'Harold Pinter', 'Tennessee Williams'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_12', question: 'In "An Inspector Calls", what is Inspector Goole investigating?', options: ['A robbery', 'A suicide', 'A murder', 'A kidnapping'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_13', question: 'What does the Inspector represent in "An Inspector Calls"?', options: ['Justice/Conscience', 'The police', 'The government', 'Death'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_14', question: 'A metaphor is:', options: ['A comparison using "like" or "as"', 'Direct comparison saying one thing IS another', 'Exaggeration', 'Giving human qualities to objects'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_15', question: 'A simile uses which words?', options: ['"is" or "are"', '"like" or "as"', '"very" or "really"', '"but" or "however"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_16', question: 'Personification means:', options: ['Using a person\'s name', 'Giving human qualities to non-human things', 'Describing a person', 'Writing in first person'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_17', question: 'Alliteration is:', options: ['Rhyming words', 'Repetition of consonant sounds at start of words', 'Repetition of vowel sounds', 'Using "like" or "as"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_18', question: 'Which is an example of alliteration?', options: ['The sun is like gold', 'Peter Piper picked', 'The tree swayed gently', 'It was very cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_19', question: 'Onomatopoeia is:', options: ['A type of rhyme', 'Words that sound like their meaning', 'Exaggeration', 'A comparison'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_20', question: 'Which word is onomatopoeia?', options: ['Beautiful', 'Buzz', 'Happy', 'Slow'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_21', question: 'Hyperbole means:', options: ['Understatement', 'Exaggeration for effect', 'Comparison', 'Contrast'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_22', question: 'Which is an example of hyperbole?', options: ['"I\'m so hungry I could eat a horse"', '"The cat is sleeping"', '"It\'s quite warm today"', '"She is tall"'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_23', question: 'Oxymoron is:', options: ['Two words that contradict each other', 'Two words that rhyme', 'Two words that mean the same', 'Two short sentences'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_24', question: 'Which is an oxymoron?', options: ['"Happy birthday"', '"Deafening silence"', '"Red rose"', '"Fast car"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_25', question: 'Who wrote "Jekyll and Hyde"?', options: ['Bram Stoker', 'Mary Shelley', 'Robert Louis Stevenson', 'Edgar Allan Poe'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_26', question: 'What is the main theme of "Jekyll and Hyde"?', options: ['Love', 'Dual nature of humanity', 'War', 'Poverty'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_27', question: 'Who wrote "Frankenstein"?', options: ['Mary Shelley', 'Charlotte Brontë', 'Emily Brontë', 'Jane Austen'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_28', question: 'The Gothic genre typically includes:', options: ['Romance and comedy', 'Mystery, horror, and the supernatural', 'Science and facts', 'Historical events only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_29', question: 'Dramatic irony is when:', options: ['Something is funny', 'The audience knows something characters don\'t', 'Characters argue', 'The ending is sad'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_30', question: 'Foreshadowing is:', options: ['Writing about the past', 'Hints about what will happen later', 'Describing shadows', 'Flashback'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_31', question: 'A protagonist is:', options: ['The villain', 'The main character', 'The narrator', 'A minor character'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_32', question: 'An antagonist is:', options: ['The hero', 'The character who opposes the protagonist', 'The narrator', 'The author'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_33', question: 'First person narrative uses:', options: ['"He" or "she"', '"I" or "we"', '"You"', '"They"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_34', question: 'Third person narrative uses:', options: ['"I" or "we"', '"You"', '"He", "she", or "they"', 'Only names'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_35', question: 'Who wrote "To Kill a Mockingbird"?', options: ['Harper Lee', 'John Steinbeck', 'F. Scott Fitzgerald', 'Ernest Hemingway'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_36', question: 'What is blank verse?', options: ['Poetry without rhyme but with meter', 'Prose', 'Free verse with no structure', 'Poetry with ABAB rhyme'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_37', question: 'A stanza is:', options: ['A line of poetry', 'A verse or group of lines in a poem', 'A rhyming word', 'The title of a poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_38', question: 'A couplet is:', options: ['One line', 'Two consecutive rhyming lines', 'Three lines', 'Four lines'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_39', question: 'What is enjambment?', options: ['End-stopped lines', 'Lines that run on to the next without pause', 'Rhyming pattern', 'Alliteration'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_40', question: 'Caesura is:', options: ['A pause within a line of poetry', 'The end of a poem', 'A rhyme scheme', 'A type of metaphor'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },

  // GRAMMAR & LANGUAGE (60 questions)
  { id: 'y9_eng_41', question: 'Which word is an adjective: "The beautiful garden"?', options: ['The', 'beautiful', 'garden', 'None'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_42', question: 'Which word is an adverb: "She ran quickly"?', options: ['She', 'ran', 'quickly', 'None'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_43', question: 'What is the verb in: "The dog barked loudly"?', options: ['dog', 'barked', 'loudly', 'The'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_44', question: 'Identify the noun: "Freedom is important"', options: ['Freedom', 'is', 'important', 'None'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_45', question: 'What type of noun is "happiness"?', options: ['Proper noun', 'Abstract noun', 'Collective noun', 'Concrete noun'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_46', question: 'What type of noun is "team"?', options: ['Proper noun', 'Abstract noun', 'Collective noun', 'Common noun'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_47', question: 'A proper noun should:', options: ['Be lowercase', 'Start with a capital letter', 'Be plural', 'Be an action'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_48', question: 'Which is a proper noun?', options: ['city', 'London', 'building', 'street'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_49', question: 'What is a pronoun?', options: ['A describing word', 'A word that replaces a noun', 'An action word', 'A connecting word'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_50', question: 'Which is a pronoun?', options: ['run', 'happy', 'she', 'quickly'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_51', question: 'A preposition shows:', options: ['Action', 'Description', 'Position or relationship', 'Time only'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_52', question: 'Which is a preposition?', options: ['and', 'under', 'very', 'quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_53', question: 'A conjunction connects:', options: ['Only sentences', 'Words, phrases, or clauses', 'Only nouns', 'Only verbs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_54', question: 'Which is a conjunction?', options: ['under', 'beautiful', 'because', 'slowly'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_55', question: 'Past tense of "run":', options: ['runned', 'ran', 'running', 'runs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_56', question: 'Past tense of "eat":', options: ['eated', 'ate', 'eating', 'eats'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_57', question: 'Present participle of "swim":', options: ['swam', 'swimming', 'swum', 'swims'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_58', question: 'Which sentence is in passive voice?', options: ['"The cat chased the mouse"', '"The mouse was chased by the cat"', '"The cat is chasing"', '"Chase the mouse"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_59', question: 'Active voice: subject ___ the action:', options: ['receives', 'performs', 'describes', 'avoids'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_60', question: 'Which is correct?', options: ['"Me and John went"', '"John and I went"', '"John and me went"', '"I and John went"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_61', question: 'Which is correct?', options: ['"Their going home"', '"There going home"', '"They\'re going home"', '"Theyre going home"'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_62', question: 'Which is correct?', options: ['"Its a nice day"', '"It\'s a nice day"', '"Its\' a nice day"', '"Its\'\' a nice day"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_63', question: 'Apostrophe for possession: "the boy\'s book" means:', options: ['Many boys, one book', 'One boy, his book', 'One boy, many books', 'Many boys, many books'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_64', question: '"The boys\' books" means:', options: ['One boy, one book', 'One boy, many books', 'Many boys, their books', 'No ownership'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_65', question: 'Which is a simple sentence?', options: ['"The dog barked"', '"The dog barked and ran"', '"Although it rained, we played"', '"The dog, which was brown, barked"'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_66', question: 'A compound sentence contains:', options: ['One clause', 'Two or more independent clauses', 'Only dependent clauses', 'No verbs'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_67', question: 'A complex sentence contains:', options: ['Only one clause', 'An independent and dependent clause', 'No conjunctions', 'Only simple words'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_68', question: 'Which is a complex sentence?', options: ['"I ran"', '"I ran and jumped"', '"Although I was tired, I ran"', '"I ran home"'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_69', question: 'A subordinate clause:', options: ['Can stand alone', 'Cannot stand alone as a sentence', 'Is always at the start', 'Has no verb'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_70', question: 'Identify the subordinate clause: "When it rains, I stay inside"', options: ['"When it rains"', '"I stay inside"', '"it rains"', 'No subordinate clause'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_71', question: 'A relative clause gives information about:', options: ['Time', 'A noun', 'An action', 'A place only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_72', question: 'Relative pronouns include:', options: ['and, but, or', 'who, which, that', 'I, you, he', 'in, on, under'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_73', question: 'Which sentence uses a relative clause?', options: ['"The dog barked"', '"The dog, which was brown, barked"', '"The dog barked loudly"', '"The brown dog barked"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_74', question: 'Semi-colon (;) is used to:', options: ['End a sentence', 'Join closely related independent clauses', 'Show possession', 'Ask a question'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_75', question: 'Colon (:) can introduce:', options: ['A question', 'A list or explanation', 'A new paragraph', 'A title only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_76', question: 'Which sentence is correct?', options: ['"I like: apples bananas oranges"', '"I like apples, bananas, and oranges"', '"I like apples bananas and oranges"', '"I like, apples, bananas, oranges"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_77', question: 'A dash (—) can be used for:', options: ['Ending sentences', 'Adding extra information or emphasis', 'Questions only', 'Lists only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_78', question: 'Parentheses ( ) are used for:', options: ['Main ideas', 'Additional or less important information', 'Questions', 'Emphasis'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_79', question: 'Subject-verb agreement: "The dogs ___ barking"', options: ['is', 'are', 'was', 'be'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_80', question: 'Subject-verb agreement: "Each student ___ a book"', options: ['have', 'has', 'having', 'are having'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_81', question: 'Comparative form of "good":', options: ['gooder', 'better', 'best', 'more good'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_82', question: 'Superlative form of "bad":', options: ['badder', 'baddest', 'worse', 'worst'], correctAnswer: 3, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_83', question: 'Comparative form of "beautiful":', options: ['beautifuler', 'more beautiful', 'beautifullest', 'most beautiful'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_84', question: 'Double negative is:', options: ['Correct grammar', 'Incorrect - cancels out meaning', 'Emphasis', 'A question form'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_85', question: 'Which is incorrect (double negative)?', options: ['"I don\'t have any"', '"I don\'t have none"', '"I have none"', '"I don\'t have anything"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_86', question: 'Formal language is used in:', options: ['Text messages to friends', 'Academic essays and professional letters', 'Casual conversations', 'Social media posts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_87', question: 'Informal language includes:', options: ['Complex vocabulary', 'Slang and contractions', 'Third person only', 'No personal pronouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_88', question: 'Standard English is:', options: ['Slang', 'Widely accepted formal version', 'Regional dialect', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_89', question: 'Modal verbs include:', options: ['run, jump, swim', 'can, could, should, would', 'happy, sad, angry', 'and, but, or'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_90', question: 'Modal verbs express:', options: ['Actions only', 'Possibility, permission, ability, obligation', 'Descriptions', 'Past tense only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_91', question: 'Imperative mood is used for:', options: ['Questions', 'Commands or instructions', 'Statements only', 'Wishes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_92', question: 'Which is imperative?', options: ['"Are you ready?"', '"Close the door"', '"The door is closed"', '"I closed the door"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_93', question: 'Subjunctive mood expresses:', options: ['Facts', 'Wishes, hypotheticals, demands', 'Questions', 'Commands'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_94', question: 'Which uses subjunctive?', options: ['"He is here"', '"If I were rich"', '"I am going"', '"She runs fast"'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_95', question: 'Homophone: words that:', options: ['Sound the same but have different meanings', 'Look the same', 'Mean the same', 'Rhyme'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_96', question: 'Which are homophones?', options: ['big/large', 'there/their/they\'re', 'happy/sad', 'run/walk'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_97', question: 'Synonym means:', options: ['Opposite meaning', 'Similar meaning', 'Sounds the same', 'Rhymes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_98', question: 'Synonym for "happy":', options: ['sad', 'joyful', 'angry', 'tired'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_99', question: 'Antonym means:', options: ['Similar meaning', 'Opposite meaning', 'Sounds the same', 'Same spelling'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_100', question: 'Antonym for "ancient":', options: ['old', 'historic', 'modern', 'vintage'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },

  // WRITING TECHNIQUES & NON-FICTION (50 questions)
  { id: 'y9_eng_101', question: 'A persuasive text aims to:', options: ['Entertain', 'Convince the reader', 'Inform only', 'Describe'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_102', question: 'Rhetorical question is asked to:', options: ['Get an answer', 'Make the reader think (no answer expected)', 'Confuse', 'Test knowledge'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_103', question: 'Which is a rhetorical question?', options: ['"What time is it?"', '"Isn\'t it obvious we need change?"', '"Where do you live?"', '"How old are you?"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_104', question: 'Emotive language uses words to:', options: ['State facts', 'Appeal to emotions', 'Show times', 'Give directions'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_105', question: 'Which uses emotive language?', options: ['"The temperature is 20°C"', '"Innocent children are suffering"', '"It is Tuesday"', '"The room is 5 meters wide"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_106', question: 'Rule of three means:', options: ['Writing three paragraphs', 'Using three points/examples for impact', 'Three sentences', 'Three pages'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_107', question: 'Anecdote is:', options: ['A statistic', 'A short personal story', 'A question', 'A command'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_108', question: 'Statistics and facts are used to:', options: ['Appeal to emotions', 'Provide evidence and credibility', 'Entertain', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_109', question: 'Direct address uses:', options: ['Third person', '"You" to speak to the reader', 'Past tense only', 'No pronouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_110', question: 'Imperative verbs in persuasive writing:', options: ['Ask questions', 'Give commands: "Buy", "Support", "Act"', 'Describe emotions', 'Show uncertainty'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_111', question: 'Counterargument means:', options: ['Agreeing completely', 'Presenting and addressing opposing views', 'Ignoring other opinions', 'Changing topic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_112', question: 'A leaflet is designed to:', options: ['Tell a story', 'Inform or persuade in brief format', 'Entertain with poetry', 'Provide detailed analysis'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_113', question: 'A newspaper article should include:', options: ['Only opinions', 'Headline, facts, quotes, structure', 'Only pictures', 'Rhyming words'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_114', question: 'A formal letter starts with:', options: ['"Hi"', '"Dear Sir/Madam" or name', '"Hey there"', '"Yo"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_115', question: 'A formal letter ends with:', options: ['"Bye"', '"Yours sincerely/faithfully"', '"See ya"', '"Cheers"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_116', question: '"Yours faithfully" is used when you:', options: ['Know the person\'s name', 'Don\'t know the person\'s name (Dear Sir/Madam)', 'Are writing to a friend', 'Are angry'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_117', question: '"Yours sincerely" is used when you:', options: ['Know the person\'s name', 'Don\'t know the person\'s name', 'Are writing to a friend', 'Are writing informally'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_118', question: 'A speech should include:', options: ['Only facts', 'Engaging opening, clear points, rhetorical devices', 'Only questions', 'Technical jargon'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_119', question: 'Biography is written in:', options: ['First person about yourself', 'Third person about someone else', 'Second person', 'No person'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_120', question: 'Autobiography is written in:', options: ['Third person about someone else', 'First person about yourself', 'Second person', 'No person'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_121', question: 'Travel writing aims to:', options: ['Persuade only', 'Describe places and experiences', 'Give instructions', 'Argue a point'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_122', question: 'A review should include:', options: ['Only praise', 'Balanced opinion with examples', 'Only criticism', 'No opinion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_123', question: 'An article for a magazine is usually:', options: ['Very formal and academic', 'Engaging with personal voice', 'Written in second person', 'Without paragraphs'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_124', question: 'Purpose of informative writing:', options: ['To persuade', 'To educate/inform', 'To entertain only', 'To argue'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_125', question: 'Purpose of descriptive writing:', options: ['To argue', 'To create vivid images using sensory details', 'To instruct', 'To ask questions'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_126', question: 'Sensory details include:', options: ['Only visual', 'Sight, sound, smell, taste, touch', 'Only sound', 'Only smell'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_127', question: 'Narrative writing tells:', options: ['Only facts', 'A story with plot and characters', 'Instructions', 'Arguments'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_128', question: 'A good paragraph should have:', options: ['One sentence', 'A topic sentence and supporting details', 'No structure', 'Only examples'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_129', question: 'Topic sentence is usually:', options: ['At the end', 'At the beginning of a paragraph', 'In the middle randomly', 'Not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_130', question: 'Connectives are used to:', options: ['End writing', 'Link ideas and sentences', 'Start every paragraph', 'Replace nouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_131', question: 'Which is a time connective?', options: ['However', 'Furthermore', 'Meanwhile', 'Because'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_132', question: 'Which is a contrasting connective?', options: ['Also', 'Furthermore', 'However', 'Firstly'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_133', question: 'Which adds information?', options: ['However', 'Moreover', 'Although', 'Unless'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_134', question: 'Chronological order means:', options: ['Random order', 'Time order', 'Alphabetical order', 'Importance order'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_135', question: 'Flashback in narrative:', options: ['Moves forward in time', 'Goes back to earlier events', 'Stays in present', 'Predicts future'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_136', question: 'Cliffhanger is used to:', options: ['End clearly', 'Create suspense at the end', 'Introduce characters', 'Describe setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_137', question: 'Circular structure means the ending:', options: ['Is completely different', 'Links back to the beginning', 'Is unclear', 'Is very long'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_138', question: 'Show don\'t tell means:', options: ['Use direct statements', 'Use descriptive details to imply meaning', 'Use short sentences', 'Use questions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_139', question: 'Which "shows" fear?', options: ['"He was scared"', '"His hands trembled and sweat dripped"', '"Fear happened"', '"He felt fear"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_140', question: 'Pathetic fallacy is:', options: ['Being overly emotional', 'Weather/nature reflecting mood/atmosphere', 'A mistake', 'A type of character'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_eng_141', question: 'Which shows pathetic fallacy?', options: ['"It was Tuesday"', '"The storm raged as his anger grew"', '"The tree is green"', '"She walked home"'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_142', question: 'Juxtaposition places ___ ideas together:', options: ['Similar', 'Contrasting', 'Identical', 'Unrelated'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_143', question: 'Imagery creates:', options: ['Characters', 'Vivid mental pictures', 'Plot', 'Dialogue'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_144', question: 'Symbolism is when an object represents:', options: ['Itself only', 'A deeper meaning or idea', 'A character', 'A setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_145', question: 'Tone is the writer\'s:', options: ['Handwriting', 'Attitude toward the subject', 'Name', 'Age'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_146', question: 'Mood is the ___ created for the reader:', options: ['Confusion', 'Atmosphere or feeling', 'Plot', 'Character'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_147', question: 'Dialogue is:', options: ['Description', 'Conversation between characters', 'Setting details', 'Author\'s opinion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_148', question: 'Dialogue is punctuated with:', options: ['Brackets', 'Speech marks/quotation marks', 'Asterisks', 'Underlines'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_149', question: 'New paragraph for dialogue when:', options: ['Never', 'New speaker', 'After 3 sentences', 'Randomly'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_150', question: 'Proofreading checks for:', options: ['New ideas', 'Spelling, grammar, punctuation errors', 'Different topics', 'Longer sentences'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // READING COMPREHENSION & ANALYSIS (50 questions)
  { id: 'y9_eng_151', question: 'Inference means:', options: ['Reading what\'s written', 'Reading between the lines', 'Summarizing', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_152', question: 'Explicit information is:', options: ['Hidden', 'Clearly stated in the text', 'Implied', 'Guessed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_153', question: 'Implicit information is:', options: ['Clearly stated', 'Suggested/implied, not directly stated', 'In the title', 'In bold'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_154', question: 'Context clues help you:', options: ['Spell words', 'Figure out unknown word meanings', 'Count words', 'Find the author'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_155', question: 'Main idea is:', options: ['A minor detail', 'The central point of a text', 'The first sentence', 'The longest sentence'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_156', question: 'Supporting details:', options: ['Are unrelated', 'Back up the main idea', 'Contradict the main idea', 'Are not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_157', question: 'Summary should be:', options: ['Longer than original', 'Brief overview of main points', 'Exact copy', 'Only your opinion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_158', question: 'Analysis means:', options: ['Just reading', 'Examining closely and explaining', 'Memorizing', 'Rewriting'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_159', question: 'When analyzing language, you look at:', options: ['Page numbers', 'Word choice, techniques, effects', 'Font type', 'Paper quality'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_160', question: 'When analyzing structure, you examine:', options: ['Only grammar', 'How the text is organized', 'Only punctuation', 'Only spelling'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_161', question: 'Author\'s purpose might be to:', options: ['Confuse readers', 'Inform, persuade, entertain, or argue', 'Make text long', 'Use big words'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_162', question: 'Target audience is:', options: ['The author', 'The intended readers', 'Publishers', 'Printers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_163', question: 'Fact is:', options: ['An opinion', 'Something that can be proven true', 'A guess', 'Always false'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_164', question: 'Opinion is:', options: ['Proven truth', 'A belief or judgment', 'Always correct', 'A fact'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_165', question: 'Which is a fact?', options: ['"Pizza is the best food"', '"Water boils at 100°C"', '"Summer is better than winter"', '"Red is prettier than blue"'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_166', question: 'Which is an opinion?', options: ['"The Earth orbits the Sun"', '"London is the capital of England"', '"Chocolate is delicious"', '"There are 7 days in a week"'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_167', question: 'Bias means:', options: ['Fair view', 'Prejudice favoring one side', 'No opinion', 'Multiple perspectives'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_168', question: 'Objective writing is:', options: ['Personal and emotional', 'Unbiased, based on facts', 'Full of opinions', 'Argumentative'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_169', question: 'Subjective writing is:', options: ['Unbiased facts only', 'Based on personal feelings/opinions', 'Scientific', 'Mathematical'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_170', question: 'Viewpoint is:', options: ['Page number', 'Perspective from which something is considered', 'Font size', 'Book title'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_171', question: 'First person viewpoint uses:', options: ['"He" or "she"', '"I" or "we"', '"You"', '"They" only'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_172', question: 'Third person limited viewpoint:', options: ['Knows everything about all characters', 'Follows one character\'s thoughts', 'Uses "I"', 'Has no characters'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_173', question: 'Third person omniscient knows:', options: ['Nothing', 'Everything about all characters', 'One character\'s thoughts', 'Only the setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_174', question: 'Theme is:', options: ['The setting', 'The underlying message or central idea', 'A character', 'The title'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_175', question: 'Common themes include:', options: ['Page numbers', 'Love, power, revenge, identity, conflict', 'Font types', 'Chapter titles'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_176', question: 'Setting includes:', options: ['Only place', 'Time and place', 'Only characters', 'Only plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_177', question: 'Character development shows:', options: ['No change', 'How characters change/grow', 'Physical appearance only', 'Author\'s name'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_178', question: 'A dynamic character:', options: ['Never changes', 'Changes and develops', 'Is unimportant', 'Has no personality'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_179', question: 'A static character:', options: ['Changes significantly', 'Stays the same throughout', 'Is the protagonist', 'Is always evil'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_180', question: 'Plot structure includes:', options: ['Only the ending', 'Exposition, rising action, climax, falling action, resolution', 'Only characters', 'Only setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_181', question: 'Exposition introduces:', options: ['The ending', 'Characters, setting, basic situation', 'The climax', 'The resolution'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_182', question: 'Rising action is:', options: ['After the climax', 'Events building tension toward climax', 'The introduction', 'The conclusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_183', question: 'Climax is:', options: ['The introduction', 'The turning point/highest tension', 'The resolution', 'The first event'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_184', question: 'Falling action:', options: ['Builds tension', 'Events after climax leading to resolution', 'Is the climax', 'Introduces characters'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_185', question: 'Resolution:', options: ['Starts the story', 'Concludes and resolves conflicts', 'Is the climax', 'Builds tension'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_186', question: 'Conflict in literature can be:', options: ['Only physical fights', 'Character vs character, self, nature, society', 'Only dialogue', 'Unimportant'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_187', question: 'Internal conflict is:', options: ['Between two characters', 'Within a character\'s mind', 'With nature', 'With society'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_188', question: 'External conflict is:', options: ['Within one character', 'Between character and outside force', 'Not possible', 'Always solved'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_189', question: 'Irony is when:', options: ['Everything goes as expected', 'Outcome is opposite of expectation', 'Characters agree', 'Setting changes'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_190', question: 'Situational irony:', options: ['What someone says vs means', 'What happens vs what\'s expected', 'Audience knows, character doesn\'t', 'No irony'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_191', question: 'Verbal irony:', options: ['What happens vs expected', 'Saying opposite of what you mean', 'Audience knows more', 'No words involved'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_192', question: 'Sarcasm is a form of:', options: ['Metaphor', 'Verbal irony', 'Simile', 'Alliteration'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_eng_193', question: 'When evaluating a text, you:', options: ['Just read it', 'Make judgments about quality and effectiveness', 'Copy it', 'Ignore it'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_194', question: 'Comparing texts means:', options: ['Reading one', 'Finding similarities and differences', 'Choosing your favorite', 'Ignoring one'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_195', question: 'Text structure can include:', options: ['Only paragraphs', 'Headings, subheadings, bullet points, chronological order', 'Only sentences', 'Only words'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_196', question: 'A headline\'s purpose is to:', options: ['Take up space', 'Grab attention and summarize', 'Confuse readers', 'Look pretty'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_197', question: 'Subheadings help to:', options: ['Make text longer', 'Organize information into sections', 'Confuse', 'Replace paragraphs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_198', question: 'Images/photos in non-fiction texts:', options: ['Are decoration only', 'Support and enhance written content', 'Replace all text', 'Are not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_199', question: 'Captions explain:', options: ['The author', 'What\'s in images/photos', 'The title', 'The date'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_eng_200', question: 'When quoting from a text, you should:', options: ['Change the words', 'Use exact words in quotation marks', 'Paraphrase everything', 'Make up quotes'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 }
];
