// Year 11 Science Trivia Questions
// Based on UK Year 11 Science Curriculum Framework (GCSE Final Year - Advanced)
// 200 comprehensive questions for GCSE exam preparation (Combined/Triple Science)

export const YEAR_11_SCIENCE_QUESTIONS = [
  // ADVANCED BIOLOGY (70 questions)
  { id: 'y11_sci_1', question: 'What is homeostasis?', options: ['Cell division', 'Maintaining constant internal environment', 'Growth', 'Reproduction'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_2', question: 'Negative feedback maintains:', options: ['Change', 'Stability', 'Growth', 'Decline'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_3', question: 'Thermoregulation is controlled by:', options: ['Liver', 'Hypothalamus', 'Heart', 'Lungs'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_4', question: 'When too hot, body responds by:', options: ['Shivering', 'Vasodilation and sweating', 'Vasoconstriction', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_5', question: 'When too cold, body responds by:', options: ['Sweating', 'Vasodilation', 'Vasoconstriction and shivering', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_6', question: 'Insulin is produced by:', options: ['Liver', 'Pancreas', 'Kidneys', 'Heart'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_7', question: 'Insulin causes blood glucose to:', options: ['Increase', 'Decrease', 'Stay same', 'Double'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_8', question: 'Glucagon causes blood glucose to:', options: ['Decrease', 'Increase', 'Stay same', 'Halve'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_9', question: 'Type 1 diabetes is caused by:', options: ['Diet', 'Pancreas not producing insulin', 'Exercise', 'Age'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_10', question: 'Type 2 diabetes involves:', options: ['No insulin', 'Insulin resistance', 'Too much insulin', 'Normal response'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_11', question: 'Kidneys produce urine to remove:', options: ['Oxygen', 'Urea and excess water/salts', 'Glucose', 'Proteins'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_12', question: 'ADH (antidiuretic hormone) is released when:', options: ['Too much water', 'Dehydrated', 'Normal', 'Sweating'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_13', question: 'ADH causes kidneys to:', options: ['Produce more urine', 'Reabsorb more water', 'Stop working', 'Release water'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_14', question: 'Nervous system uses:', options: ['Hormones', 'Electrical impulses', 'Blood', 'Diffusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_15', question: 'Endocrine system uses:', options: ['Nerves', 'Hormones in blood', 'Muscles', 'Bones'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_16', question: 'Nervous response is:', options: ['Slow, long-lasting', 'Fast, short-lived', 'No response', 'Permanent'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_17', question: 'Hormonal response is:', options: ['Fast, short', 'Slower, longer-lasting', 'Immediate', 'Instant'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_18', question: 'Reflex arc bypasses:', options: ['Spinal cord', 'Brain', 'Nerves', 'Muscles'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_19', question: 'Synapse is gap between:', options: ['Bones', 'Neurons', 'Organs', 'Cells'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_20', question: 'Neurotransmitters cross:', options: ['Blood', 'Synapse', 'Organs', 'Bones'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_21', question: 'Alleles are:', options: ['Cells', 'Different versions of same gene', 'Organs', 'Organisms'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_22', question: 'Homozygous means:', options: ['Different alleles', 'Same alleles', 'No alleles', 'Three alleles'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_23', question: 'Heterozygous means:', options: ['Same alleles', 'Different alleles', 'No alleles', 'Three alleles'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_24', question: 'If B is dominant, Bb phenotype is:', options: ['Recessive', 'Dominant', 'Mixed', 'None'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_25', question: 'Cross Bb × Bb. Offspring ratio?', options: ['1:1', '3:1', '1:2:1', '9:3:3:1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_26', question: 'Punnett square predicts:', options: ['Past', 'Offspring genotypes/phenotypes', 'Nothing', 'Weather'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_27', question: 'Family tree showing inheritance is:', options: ['Punnett square', 'Pedigree', 'Food chain', 'Pyramid'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_28', question: 'Sex chromosomes in females:', options: ['XY', 'XX', 'YY', 'XO'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_29', question: 'Sex chromosomes in males:', options: ['XX', 'XY', 'YY', 'XO'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_30', question: 'Probability of male offspring:', options: ['25%', '50%', '75%', '100%'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_31', question: 'Mutation is:', options: ['Normal', 'Change in DNA sequence', 'Growth', 'Death'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_32', question: 'Most mutations are:', options: ['Beneficial', 'Harmful or neutral', 'Always deadly', 'Always good'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_33', question: 'Evolution is:', options: ['Quick change', 'Gradual change in species over time', 'No change', 'Instant'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_34', question: 'Natural selection favors:', options: ['Weak', 'Best adapted organisms', 'All equally', 'None'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_35', question: 'Darwin proposed:', options: ['Creationism', 'Evolution by natural selection', 'No change', 'Instant creation'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_36', question: 'Evidence for evolution includes:', options: ['Nothing', 'Fossils, DNA, anatomy', 'Guesses', 'Opinions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_37', question: 'Speciation occurs when:', options: ['No change', 'Populations become reproductively isolated', 'Breeding continues', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_38', question: 'Antibiotic resistance is example of:', options: ['No evolution', 'Evolution by natural selection', 'Devolution', 'Magic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_39', question: 'Selective breeding involves:', options: ['Random mating', 'Choosing organisms with desired traits', 'No breeding', 'Wild breeding'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_40', question: 'Genetic engineering involves:', options: ['Natural breeding', 'Transferring genes between organisms', 'No change', 'Hoping'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_41', question: 'Cloning produces:', options: ['Different organisms', 'Genetically identical organisms', 'No organisms', 'Random organisms'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_42', question: 'Stem cells can:', options: ['Only be one type', 'Differentiate into many cell types', 'Never divide', 'Only die'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_43', question: 'Adult stem cells are:', options: ['Pluripotent', 'Multipotent (limited types)', 'Totipotent', 'Unipotent'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_44', question: 'Embryonic stem cells are:', options: ['Limited', 'Pluripotent (many types)', 'Cannot divide', 'Useless'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_45', question: 'Communicable diseases are:', options: ['Not infectious', 'Caused by pathogens, spread between people', 'Genetic', 'Non-transmissible'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_46', question: 'Non-communicable diseases are:', options: ['Infectious', 'Not caused by pathogens, not spread', 'Always fatal', 'Always mild'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_47', question: 'Bacteria are:', options: ['Viruses', 'Prokaryotic cells', 'Eukaryotic', 'Fungi'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_48', question: 'Viruses are:', options: ['Living cells', 'Non-living particles needing host', 'Bacteria', 'Fungi'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_49', question: 'Antibiotics work on:', options: ['Viruses', 'Bacteria', 'All pathogens', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_50', question: 'Antibiotics do NOT work on:', options: ['Bacteria', 'Viruses', 'Nothing', 'Everything'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_51', question: 'Phagocytes:', options: ['Produce antibodies', 'Engulf pathogens', 'Nothing', 'Are pathogens'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_52', question: 'Lymphocytes:', options: ['Engulf only', 'Produce antibodies', 'Nothing', 'Are pathogens'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_53', question: 'Antibodies are:', options: ['Pathogens', 'Proteins that bind to antigens', 'Cells', 'Viruses'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_54', question: 'Antigens are:', options: ['Antibodies', 'Proteins on pathogen surface', 'Blood cells', 'Organs'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_55', question: 'Vaccination provides:', options: ['Cure', 'Active immunity', 'Instant death', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_56', question: 'Vaccines contain:', options: ['Living disease', 'Dead/weakened pathogen or antigen', 'Antibodies only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_57', question: 'Herd immunity protects:', options: ['No one', 'Unvaccinated through high vaccination rate', 'Only vaccinated', 'Animals only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_58', question: 'Risk factors for heart disease include:', options: ['Exercise', 'Smoking, poor diet, inactivity', 'Healthy eating', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_59', question: 'Cancer is caused by:', options: ['Controlled cell division', 'Uncontrolled cell division', 'No cell division', 'One cell'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_60', question: 'Carcinogens are:', options: ['Harmless', 'Cancer-causing substances', 'Cures', 'Vitamins'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_61', question: 'Biodiversity is:', options: ['One species', 'Variety of life', 'No life', 'Only plants'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_62', question: 'Deforestation reduces:', options: ['CO₂', 'Biodiversity and increases CO₂', 'Nothing', 'Pollution'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_63', question: 'Eutrophication is caused by:', options: ['Clean water', 'Excess nutrients (fertilizers)', 'No nutrients', 'Oxygen'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_64', question: 'Biological control uses:', options: ['Pesticides', 'Natural predators', 'Chemicals', 'Fire'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_65', question: 'Trophic levels show:', options: ['Time', 'Feeding positions', 'Temperature', 'Location'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_66', question: 'Pyramids of biomass show:', options: ['Numbers', 'Mass at each level', 'Time', 'Energy only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_67', question: 'Carbon cycle involves:', options: ['Only CO₂', 'Photosynthesis, respiration, combustion', 'Only plants', 'Only animals'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_68', question: 'Water cycle involves:', options: ['Only rain', 'Evaporation, condensation, precipitation', 'Only ice', 'No movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_69', question: 'Decomposers recycle:', options: ['Nothing', 'Nutrients from dead organisms', 'Only CO₂', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_70', question: 'Compost is produced by:', options: ['Burning', 'Decomposition', 'Photosynthesis', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // ADVANCED CHEMISTRY (65 questions)
  { id: 'y11_sci_71', question: 'Covalent bond forms by:', options: ['Transfer', 'Sharing electrons', 'Losing protons', 'Gaining neutrons'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_72', question: 'Ionic bond forms by:', options: ['Sharing', 'Transfer of electrons', 'Sharing protons', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_73', question: 'Metallic bonding involves:', options: ['Sharing between two', 'Delocalized electrons in metal lattice', 'Transfer', 'No electrons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_74', question: 'Diamond structure:', options: ['Layers', 'Giant covalent lattice', 'Simple molecular', 'Metallic'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_75', question: 'Graphite conducts electricity because:', options: ['No electrons', 'Delocalized electrons', 'Ionic', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_76', question: 'Fullerenes are:', options: ['Elements', 'Molecules of carbon (C₆₀)', 'Compounds', 'Mixtures'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_77', question: 'Graphene is:', options: ['Thick layer', 'Single layer of graphite', 'Diamond', 'Fullerene'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_78', question: 'Nanoparticles have size:', options: ['1-100 mm', '1-100 nm', '1-100 m', '1-100 km'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_79', question: 'Polymers are:', options: ['Small molecules', 'Large molecules from repeating units', 'Elements', 'Atoms'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_80', question: 'Polymerization is:', options: ['Breaking down', 'Joining monomers to form polymer', 'Burning', 'Dissolving'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_81', question: 'Relative formula mass calculated by:', options: ['Counting atoms', 'Adding atomic masses', 'Subtracting', 'Dividing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_82', question: 'Mole is:', options: ['Animal', '6.02 × 10²³ particles', 'Unit of volume', 'Unit of time'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_83', question: 'Avogadro\'s constant is:', options: ['3.14', '6.02 × 10²³', '9.81', '1.66'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_84', question: 'Mass of 1 mole = ___g:', options: ['1', 'Relative formula mass', '100', '1000'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_85', question: 'Moles = mass / ___:', options: ['Volume', 'Relative formula mass', 'Time', 'Temperature'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_86', question: 'Concentration = moles / ___:', options: ['Mass', 'Volume (dm³)', 'Time', 'Temperature'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_87', question: 'Limiting reactant is:', options: ['In excess', 'Used up first', 'Not used', 'Catalyst'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_88', question: 'Percentage yield = (actual/theoretical) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_89', question: 'Atom economy measures:', options: ['Money', 'Efficiency of using reactants', 'Time', 'Temperature'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_90', question: 'High atom economy means:', options: ['Wasteful', 'Less waste/more sustainable', 'Expensive', 'Slow'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_91', question: 'Equilibrium is when:', options: ['All reacted', 'Forward rate = reverse rate', 'Nothing happens', 'One way only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_92', question: 'Dynamic equilibrium means:', options: ['Static', 'Reactions still occurring both ways', 'Stopped', 'One direction'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_93', question: 'Le Chatelier\'s principle: system opposes:', options: ['Everything', 'Changes imposed on it', 'Nothing', 'Equilibrium'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_94', question: 'Increase temperature favors:', options: ['Exothermic', 'Endothermic', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_95', question: 'Increase pressure favors:', options: ['More moles', 'Fewer moles of gas', 'No change', 'Solids'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_96', question: 'Haber process makes:', options: ['Oxygen', 'Ammonia (NH₃)', 'Water', 'CO₂'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_97', question: 'Haber process: N₂ + 3H₂ ⇌ ___:', options: ['2NH₃', 'NH₃', 'N₂H₆', 'H₃N'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_98', question: 'Crude oil is separated by:', options: ['Filtration', 'Fractional distillation', 'Evaporation', 'Chromatography'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_99', question: 'Fractions separated by:', options: ['Color', 'Boiling point', 'Density only', 'Smell'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_100', question: 'Alkanes general formula:', options: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnHn'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_101', question: 'Alkenes general formula:', options: ['CnH2n+2', 'CnH2n', 'CnH2n-2', 'CnHn'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_102', question: 'Alkanes are:', options: ['Unsaturated', 'Saturated', 'Aromatic', 'Ionic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_103', question: 'Alkenes are:', options: ['Saturated', 'Unsaturated (C=C)', 'No carbon', 'Ionic'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_104', question: 'Test for alkenes:', options: ['Limewater', 'Bromine water (decolorizes)', 'Blue litmus', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_105', question: 'Cracking breaks:', options: ['Small into large', 'Large hydrocarbons into smaller', 'Bonds in water', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_106', question: 'Cracking produces:', options: ['Only alkanes', 'Alkanes and alkenes', 'Only water', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_107', question: 'Catalytic cracking uses:', options: ['No catalyst', 'Catalyst at high temp', 'Low temp only', 'Water'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_108', question: 'Complete combustion produces:', options: ['CO + H₂', 'CO₂ + H₂O', 'C + O₂', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_109', question: 'Incomplete combustion produces:', options: ['Only CO₂', 'CO and/or C (soot)', 'Only water', 'Oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_110', question: 'Acid + metal oxide → ___:', options: ['Nothing', 'Salt + water', 'Gas', 'Metal'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_111', question: 'Acid + metal hydroxide → ___:', options: ['Nothing', 'Salt + water', 'Gas', 'Metal'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_112', question: 'Acid + metal → ___:', options: ['Nothing', 'Salt + hydrogen', 'Water', 'Oxygen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_113', question: 'Acid + carbonate → ___:', options: ['Nothing', 'Salt + water + CO₂', 'Oxygen', 'Hydrogen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_114', question: 'Strong acid is:', options: ['Partially ionized', 'Fully ionized', 'Not ionized', 'Neutral'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_115', question: 'Weak acid is:', options: ['Fully ionized', 'Partially ionized', 'Not ionized', 'Neutral'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_116', question: 'pH = 7 is:', options: ['Acidic', 'Alkaline', 'Neutral', 'Unknown'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_117', question: 'pH < 7 is:', options: ['Neutral', 'Alkaline', 'Acidic', 'Unknown'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_118', question: 'pH > 7 is:', options: ['Acidic', 'Neutral', 'Alkaline', 'Unknown'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_119', question: 'Electrolysis requires:', options: ['Solid ionic', 'Molten or dissolved ionic compound', 'Covalent', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_120', question: 'At cathode (negative):', options: ['Oxidation', 'Reduction (gain electrons)', 'No reaction', 'Explosion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_121', question: 'At anode (positive):', options: ['Reduction', 'Oxidation (lose electrons)', 'No reaction', 'Explosion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_122', question: 'Oxidation is:', options: ['Gain electrons', 'Loss of electrons', 'No change', 'Gain protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_123', question: 'Reduction is:', options: ['Loss electrons', 'Gain electrons', 'No change', 'Loss protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_124', question: 'OIL RIG stands for:', options: ['Nothing', 'Oxidation Is Loss, Reduction Is Gain (of electrons)', 'Random', 'Oil drilling'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_125', question: 'Reactivity series orders metals by:', options: ['Size', 'How reactive', 'Color', 'Cost'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_126', question: 'More reactive metal ___ less reactive from solution:', options: ['Cannot displace', 'Can displace', 'Ignores', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_127', question: 'Extraction method depends on:', options: ['Color', 'Metal reactivity', 'Smell', 'Taste'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_128', question: 'Very reactive metals extracted by:', options: ['Heating', 'Electrolysis', 'Filtering', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_129', question: 'Less reactive metals extracted by:', options: ['Electrolysis only', 'Reduction with carbon', 'Nothing', 'Dissolving'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_130', question: 'Life Cycle Assessment evaluates:', options: ['One stage', 'Environmental impact throughout life', 'Cost only', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_131', question: 'Corrosion of iron requires:', options: ['Nothing', 'Oxygen and water', 'Only oxygen', 'Only water'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_132', question: 'Galvanizing protects iron with:', options: ['Paint', 'Zinc coating', 'Oil', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_133', question: 'Alloys are usually ___ than pure metals:', options: ['Weaker', 'Harder/stronger', 'Softer', 'Same'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_134', question: 'Thermosetting polymers:', options: ['Melt when heated', 'Do not melt when heated', 'Dissolve', 'Evaporate'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_135', question: 'Thermosoftening polymers:', options: ['Do not melt', 'Melt when heated', 'Never change', 'Burn only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },

  // ADVANCED PHYSICS (65 questions)
  { id: 'y11_sci_136', question: 'Energy cannot be:', options: ['Transferred', 'Created or destroyed', 'Changed form', 'Measured'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_137', question: 'Kinetic energy = ½m___²:', options: ['a', 't', 'v', 'f'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_138', question: 'Gravitational potential energy = m × g × ___:', options: ['t', 'v', 'h', 'd'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_139', question: 'Elastic potential energy stored in:', options: ['Stationary objects', 'Stretched/compressed objects', 'Hot objects', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_140', question: 'Work done = force × ___:', options: ['Time', 'Mass', 'Distance moved in direction', 'Velocity'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_141', question: 'Power = work done / ___:', options: ['Force', 'Distance', 'Time', 'Mass'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_142', question: 'Power also = energy transferred / ___:', options: ['Force', 'Time', 'Distance', 'Mass'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_143', question: 'Efficiency = (useful energy out / total energy in) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_144', question: 'No device is 100% efficient because:', options: ['All energy useful', 'Some energy wasted as heat/sound', 'Perfect machines', 'Energy created'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_145', question: 'Sankey diagram shows:', options: ['Nothing', 'Energy transfers', 'Time', 'Distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_146', question: 'Non-renewable energy sources include:', options: ['Solar', 'Fossil fuels, nuclear', 'Wind', 'Tidal'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_147', question: 'Renewable energy sources include:', options: ['Coal', 'Solar, wind, hydro, tidal, biomass', 'Oil', 'Gas'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_148', question: 'Fossil fuels cause:', options: ['Clean air', 'Pollution and CO₂ emissions', 'No emissions', 'Oxygen release'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_149', question: 'Nuclear power does not produce:', options: ['Electricity', 'CO₂ emissions', 'Energy', 'Heat'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_150', question: 'Nuclear waste is:', options: ['Harmless', 'Radioactive and dangerous', 'Useful', 'Renewable'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_151', question: 'Specific heat capacity is energy needed to raise ___ by 1°C:', options: ['Any mass', '1kg', '1g', '10kg'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_152', question: 'Energy = mass × SHC × ___:', options: ['Time', 'Temperature change', 'Volume', 'Pressure'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_153', question: 'Heat transfer by conduction involves:', options: ['Fluid movement', 'Vibrating particles', 'Waves', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_154', question: 'Heat transfer by convection involves:', options: ['Vibrating particles', 'Fluid movement', 'Waves', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_155', question: 'Radiation transfers heat by:', options: ['Particles', 'Fluid', 'Infrared waves', 'Conduction'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_156', question: 'Black surfaces are ___ absorbers/emitters:', options: ['Poor', 'Good', 'No', 'Perfect reflectors'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_157', question: 'Shiny surfaces are ___ reflectors:', options: ['Poor', 'Good', 'No', 'Perfect absorbers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_158', question: 'Charge measured in:', options: ['Volts', 'Coulombs (C)', 'Amperes', 'Ohms'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_159', question: 'Charge = current × ___:', options: ['Voltage', 'Time', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_160', question: 'Potential difference = energy / ___:', options: ['Time', 'Charge', 'Current', 'Resistance'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_161', question: 'Ohm\'s Law: V = I × ___:', options: ['T', 'P', 'R', 'M'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_162', question: 'Power = voltage × ___:', options: ['Resistance', 'Current', 'Time', 'Charge'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_163', question: 'Power also = current² × ___:', options: ['Voltage', 'Resistance', 'Time', 'Charge'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_164', question: 'Energy transferred = power × ___:', options: ['Voltage', 'Current', 'Time', 'Resistance'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_165', question: 'Energy also = charge × ___:', options: ['Current', 'Resistance', 'Voltage', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_166', question: 'National Grid transmits at high:', options: ['Current', 'Voltage', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_167', question: 'High voltage transmission reduces:', options: ['Distance', 'Energy loss', 'Cost', 'Time'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_168', question: 'Transformers change:', options: ['Current only', 'Voltage', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_169', question: 'Step-up transformer:', options: ['Decreases voltage', 'Increases voltage', 'No change', 'Stops electricity'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_170', question: 'Step-down transformer:', options: ['Increases voltage', 'Decreases voltage', 'No change', 'Stops electricity'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_171', question: 'AC means:', options: ['Always Current', 'Alternating Current', 'Average Current', 'Actual Current'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_172', question: 'DC means:', options: ['Double Current', 'Direct Current', 'Dynamic Current', 'Decreasing Current'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_173', question: 'Mains electricity is:', options: ['DC', 'AC', 'No current', 'Static'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_174', question: 'UK mains voltage:', options: ['110V', '230V', '300V', '500V'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_175', question: 'UK mains frequency:', options: ['30 Hz', '50 Hz', '100 Hz', '230 Hz'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_176', question: 'Live wire is colored:', options: ['Blue', 'Brown', 'Green/yellow', 'Red'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_177', question: 'Neutral wire is colored:', options: ['Brown', 'Blue', 'Green/yellow', 'Red'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_178', question: 'Earth wire is colored:', options: ['Brown', 'Blue', 'Green/yellow', 'Red'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_179', question: 'Fuse prevents:', options: ['Nothing', 'Overheating/fire from excess current', 'Voltage', 'Light'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_180', question: 'Fuse should be rated ___ appliance current:', options: ['Well below', 'Just above', 'Much higher', 'Equal'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_181', question: 'Earth wire provides:', options: ['Power', 'Safety path for current', 'Voltage', 'Resistance'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_182', question: 'Double insulation means:', options: ['One layer', 'No metal exposed, no earth needed', 'Two earth wires', 'Two live wires'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_183', question: 'Radioactive decay is:', options: ['Predictable', 'Random', 'Controllable', 'Stoppable'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_184', question: 'Alpha particles are:', options: ['Electrons', 'Helium nuclei', 'Protons', 'Neutrons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_185', question: 'Beta particles are:', options: ['Protons', 'Electrons', 'Helium nuclei', 'Neutrons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_186', question: 'Gamma rays are:', options: ['Particles', 'Electromagnetic radiation', 'Atoms', 'Molecules'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_187', question: 'Most ionizing radiation:', options: ['Gamma', 'Alpha', 'Beta', 'None'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_188', question: 'Most penetrating radiation:', options: ['Alpha', 'Beta', 'Gamma', 'None'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_189', question: 'Alpha stopped by:', options: ['Nothing', 'Paper/skin', 'Aluminum', 'Lead'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_190', question: 'Beta stopped by:', options: ['Paper', 'Aluminum sheet', 'Nothing', 'Skin'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_191', question: 'Gamma reduced by:', options: ['Paper', 'Aluminum', 'Thick lead/concrete', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_192', question: 'Half-life is time for:', options: ['All to decay', 'Half of radioactive atoms to decay', 'No decay', 'Double'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_193', question: 'After one half-life, ___ remains:', options: ['All', 'Half', 'Quarter', 'None'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_sci_194', question: 'After two half-lives, ___ remains:', options: ['Half', 'Quarter', 'Eighth', 'None'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_195', question: 'Background radiation comes from:', options: ['Only nuclear plants', 'Cosmic rays, rocks, radon gas', 'Only humans', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_196', question: 'Nuclear fission is:', options: ['Joining nuclei', 'Splitting large nucleus', 'No change', 'Burning'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_197', question: 'Nuclear fusion is:', options: ['Splitting nuclei', 'Joining small nuclei', 'No change', 'Decay'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_198', question: 'Sun\'s energy from:', options: ['Fission', 'Fusion', 'Burning', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_sci_199', question: 'Chain reaction requires:', options: ['One neutron', 'Sustained neutron production', 'No neutrons', 'Electrons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_sci_200', question: 'Control rods in reactor:', options: ['Speed up', 'Absorb neutrons to control reaction', 'Provide fuel', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 }
];
