// Year 12 Science Trivia Questions
// Based on UK Year 12 Science Curriculum Framework (A-Level AS - Biology, Chemistry, Physics)
// 200 comprehensive questions covering A-Level AS Science

export const YEAR_12_SCIENCE_QUESTIONS = [
  // BIOLOGY (70 questions)
  { id: 'y12_sci_1', question: 'Prokaryotic cells lack:', options: ['DNA', 'Membrane-bound nucleus', 'Ribosomes', 'Cell membrane'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_2', question: 'Eukaryotic cells have:', options: ['No nucleus', 'Membrane-bound organelles', 'No DNA', 'No ribosomes'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_3', question: 'Mitochondria are site of:', options: ['Photosynthesis', 'Aerobic respiration', 'Protein synthesis', 'DNA replication'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_4', question: 'Chloroplasts are site of:', options: ['Respiration', 'Photosynthesis', 'Protein synthesis', 'Cell division'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_5', question: 'Ribosomes are site of:', options: ['DNA replication', 'Photosynthesis', 'Protein synthesis', 'Respiration'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_6', question: 'Golgi apparatus functions in:', options: ['Respiration', 'Modifying and packaging proteins', 'DNA storage', 'Photosynthesis'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_7', question: 'Rough ER has:', options: ['No ribosomes', 'Ribosomes attached', 'DNA', 'Chlorophyll'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_8', question: 'Smooth ER functions in:', options: ['Protein synthesis', 'Lipid synthesis', 'DNA replication', 'Photosynthesis'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_9', question: 'Lysosomes contain:', options: ['DNA', 'Digestive enzymes', 'Chlorophyll', 'Lipids'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_10', question: 'Cell membrane is:', options: ['Fully permeable', 'Selectively permeable', 'Impermeable', 'No barrier'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_11', question: 'Fluid mosaic model describes:', options: ['DNA', 'Cell membrane structure', 'Cytoplasm', 'Nucleus'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_12', question: 'Phospholipid bilayer has ___ heads:', options: ['Hydrophobic', 'Hydrophilic', 'No', 'Positive'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_13', question: 'Phospholipid tails are:', options: ['Hydrophilic', 'Hydrophobic', 'Charged', 'Water-loving'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_14', question: 'Diffusion is movement from ___ to ___ concentration:', options: ['Low, high', 'High, low', 'Equal, equal', 'No movement'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_15', question: 'Osmosis is diffusion of:', options: ['Solute', 'Water', 'Proteins', 'DNA'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_16', question: 'Active transport requires:', options: ['No energy', 'ATP', 'Only diffusion', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_17', question: 'Active transport moves substances ___ concentration gradient:', options: ['Down', 'Against', 'With', 'No direction'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_18', question: 'Facilitated diffusion uses:', options: ['ATP', 'Carrier/channel proteins', 'Only lipids', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_19', question: 'Endocytosis is:', options: ['Exporting', 'Taking in materials', 'Diffusion', 'Osmosis'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_20', question: 'Exocytosis is:', options: ['Taking in', 'Releasing materials', 'Diffusion', 'Osmosis'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_21', question: 'DNA structure is:', options: ['Single helix', 'Double helix', 'Triple helix', 'Linear'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_22', question: 'DNA bases: Adenine pairs with:', options: ['Cytosine', 'Thymine', 'Guanine', 'Uracil'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_23', question: 'DNA bases: Guanine pairs with:', options: ['Adenine', 'Thymine', 'Cytosine', 'Uracil'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_24', question: 'DNA replication is:', options: ['Conservative', 'Semi-conservative', 'Dispersive', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_25', question: 'DNA polymerase:', options: ['Breaks DNA', 'Builds new DNA strand', 'Destroys RNA', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_26', question: 'Transcription produces:', options: ['DNA', 'mRNA', 'Protein', 'Lipid'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_27', question: 'Translation produces:', options: ['DNA', 'RNA', 'Protein', 'Lipid'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_28', question: 'RNA contains ___ instead of thymine:', options: ['Adenine', 'Uracil', 'Cytosine', 'Guanine'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_29', question: 'Codon is:', options: ['One base', 'Three bases coding for amino acid', 'Protein', 'Lipid'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_30', question: 'tRNA brings:', options: ['DNA', 'Amino acids', 'Lipids', 'Glucose'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_31', question: 'Mutation is change in:', options: ['Cell', 'DNA sequence', 'Protein only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_32', question: 'Point mutation affects:', options: ['Whole chromosome', 'Single base', 'All DNA', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_33', question: 'Mitosis produces ___ daughter cells:', options: ['1', '2', '4', '8'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_34', question: 'Mitosis daughter cells are:', options: ['Different', 'Genetically identical', 'Haploid', 'Gametes'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_35', question: 'Meiosis produces ___ daughter cells:', options: ['2', '4', '8', '1'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_36', question: 'Meiosis daughter cells are:', options: ['Diploid', 'Haploid', 'Same as parent', 'Identical'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_37', question: 'Crossing over occurs in:', options: ['Mitosis', 'Meiosis', 'Neither', 'Both equally'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_38', question: 'Independent assortment occurs in:', options: ['Mitosis', 'Meiosis', 'Neither', 'DNA replication'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_39', question: 'Enzymes are:', options: ['Carbohydrates', 'Proteins (biological catalysts)', 'Lipids', 'Nucleic acids'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_40', question: 'Enzyme active site is:', options: ['Non-specific', 'Specific to substrate', 'Random', 'Universal'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_41', question: 'Lock and key model describes:', options: ['DNA', 'Enzyme-substrate specificity', 'Membrane', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_42', question: 'Induced fit model suggests active site:', options: ['Never changes', 'Changes to fit substrate', 'Is rigid', 'Breaks'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_43', question: 'Competitive inhibitor binds to:', options: ['Elsewhere', 'Active site', 'No site', 'All sites'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_44', question: 'Non-competitive inhibitor binds:', options: ['Active site', 'Elsewhere (allosteric site)', 'No site', 'Substrate'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_45', question: 'Increasing temperature generally ___ enzyme activity:', options: ['Decreases', 'Increases (to optimum)', 'No effect', 'Stops'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_46', question: 'Denaturing changes:', options: ['Substrate', 'Enzyme shape/active site', 'Product', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_47', question: 'ATP stands for:', options: ['Adenine Triphosphate', 'Adenosine Triphosphate', 'Adenine Diphosphate', 'Adenosine Diphosphate'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_48', question: 'ATP → ADP + Pi releases:', options: ['Nothing', 'Energy', 'Water', 'CO₂'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_49', question: 'Photosynthesis light-dependent reactions occur in:', options: ['Stroma', 'Thylakoid membrane', 'Cytoplasm', 'Mitochondria'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_50', question: 'Photosynthesis light-independent reactions (Calvin cycle) occur in:', options: ['Thylakoid', 'Stroma', 'Cytoplasm', 'Mitochondria'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_51', question: 'Photolysis splits:', options: ['CO₂', 'Water', 'Glucose', 'Oxygen'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_52', question: 'NADP is:', options: ['Enzyme', 'Electron carrier', 'Substrate', 'Product'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_53', question: 'Glycolysis occurs in:', options: ['Mitochondria', 'Cytoplasm', 'Nucleus', 'Chloroplast'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_54', question: 'Krebs cycle occurs in:', options: ['Cytoplasm', 'Mitochondrial matrix', 'Nucleus', 'Chloroplast'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_55', question: 'Oxidative phosphorylation occurs on:', options: ['Cytoplasm', 'Inner mitochondrial membrane', 'Nucleus', 'Outer membrane'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_56', question: 'NAD is:', options: ['Product', 'Electron carrier', 'Enzyme', 'Substrate'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_57', question: 'One glucose molecule yields approximately ___ ATP:', options: ['2', '32-38', '100', '5'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_58', question: 'Immunoglobulin is:', options: ['Enzyme', 'Antibody', 'Hormone', 'Carbohydrate'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_59', question: 'Antibodies are produced by:', options: ['Red blood cells', 'B lymphocytes/plasma cells', 'Platelets', 'Phagocytes'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_60', question: 'T lymphocytes mature in:', options: ['Bone marrow', 'Thymus', 'Liver', 'Spleen'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_61', question: 'Phagocytosis is performed by:', options: ['B cells', 'Phagocytes (e.g., macrophages)', 'T cells', 'Antibodies'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_62', question: 'Primary immune response is:', options: ['Fast', 'Slow first exposure', 'Immediate', 'Instant'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_63', question: 'Secondary immune response is:', options: ['Slow', 'Faster on re-exposure', 'Same speed', 'No response'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_64', question: 'Memory cells provide:', options: ['No immunity', 'Long-term immunity', 'Short immunity', 'No function'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_65', question: 'Gas exchange in lungs occurs across:', options: ['Bronchi', 'Alveolar epithelium', 'Trachea', 'Bronchioles'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_66', question: 'Ventilation is controlled by:', options: ['Heart', 'Medulla oblongata', 'Liver', 'Kidneys'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_67', question: 'Haemoglobin has ___ polypeptide chains:', options: ['2', '4', '6', '8'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_68', question: 'Bohr effect describes:', options: ['Temperature effect', 'CO₂ affecting O₂ binding', 'Pressure effect', 'Light effect'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_69', question: 'Heart has ___ chambers:', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_70', question: 'Cardiac cycle includes:', options: ['Only systole', 'Systole and diastole', 'Only diastole', 'No phases'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },

  // CHEMISTRY (65 questions)
  { id: 'y12_sci_71', question: 'Atomic number is number of:', options: ['Neutrons', 'Protons', 'Electrons in outer', 'Mass'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_72', question: 'Mass number is:', options: ['Protons', 'Neutrons', 'Protons + neutrons', 'Electrons'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_73', question: 'Isotopes have same ___ different ___:', options: ['Protons, neutrons', 'Electrons, protons', 'Neutrons, protons', 'Mass, charge'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_74', question: 'Relative atomic mass considers:', options: ['One isotope', 'Isotope abundance', 'Only mass number', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_75', question: 'Electron shells fill in order:', options: ['Random', '1s, 2s, 2p, 3s, 3p...', 'All at once', 'Backwards'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_76', question: 's orbital holds maximum ___ electrons:', options: ['1', '2', '6', '10'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_77', question: 'p orbital holds maximum ___ electrons:', options: ['2', '6', '10', '14'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_78', question: 'd orbital holds maximum ___ electrons:', options: ['2', '6', '10', '14'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_79', question: 'Ionic bonding involves:', options: ['Sharing', 'Transfer of electrons', 'No electrons', 'Protons'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_80', question: 'Covalent bonding involves:', options: ['Transfer', 'Sharing electrons', 'No electrons', 'Protons'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_81', question: 'Metallic bonding has:', options: ['Fixed electrons', 'Delocalized electrons', 'No electrons', 'Shared pairs'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_82', question: 'Electronegativity is tendency to:', options: ['Lose electrons', 'Attract bonding electrons', 'Gain protons', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_83', question: 'Polar covalent bond has:', options: ['Equal sharing', 'Unequal sharing', 'No sharing', 'Transfer'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_84', question: 'Dipole has:', options: ['No charge', 'Separation of charge', 'Positive only', 'Negative only'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_85', question: 'Hydrogen bonding occurs between:', options: ['Any atoms', 'H and N/O/F', 'Only H atoms', 'Metals'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_86', question: 'Van der Waals forces are:', options: ['Strong', 'Weak intermolecular', 'Ionic bonds', 'Covalent bonds'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_87', question: 'VSEPR theory predicts:', options: ['Mass', 'Molecular shape', 'Color', 'Charge'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_88', question: 'Oxidation is:', options: ['Gain electrons', 'Loss of electrons', 'No change', 'Gain protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_89', question: 'Reduction is:', options: ['Loss electrons', 'Gain electrons', 'No change', 'Loss protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_90', question: 'Oxidation number of element in standard state:', options: ['-1', '0', '+1', 'Variable'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_91', question: 'Oxidation number of oxygen usually:', options: ['+2', '0', '-2', '+1'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_92', question: 'Oxidation number of hydrogen usually:', options: ['-1', '0', '+1', '+2'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_93', question: 'Redox reaction involves:', options: ['Only oxidation', 'Both oxidation and reduction', 'Only reduction', 'Neither'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_94', question: 'Mole is:', options: ['Mass', '6.02 × 10²³ particles', 'Volume', 'Temperature'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_95', question: 'Molar mass is mass of ___ mole:', options: ['0.5', '1', '2', '10'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_96', question: 'Empirical formula shows:', options: ['Actual numbers', 'Simplest ratio', 'Structure', 'Shape'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_97', question: 'Molecular formula shows:', options: ['Simplest ratio', 'Actual number of atoms', 'Shape', 'Charge'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_98', question: 'Limiting reagent is:', options: ['In excess', 'Used up first', 'Not used', 'Catalyst'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_99', question: 'Percentage yield = (actual/theoretical) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_100', question: 'Atom economy = (mass of desired/total mass) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_101', question: 'Enthalpy change (ΔH) is:', options: ['Temperature change', 'Heat energy change', 'Volume change', 'Mass change'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_102', question: 'Exothermic reaction has ΔH:', options: ['Positive', 'Negative', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_103', question: 'Endothermic reaction has ΔH:', options: ['Negative', 'Positive', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_104', question: 'Bond breaking requires:', options: ['No energy', 'Energy (endothermic)', 'Releases energy', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_105', question: 'Bond making:', options: ['Requires energy', 'Releases energy (exothermic)', 'No energy change', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_106', question: 'Hess\'s Law states enthalpy change is independent of:', options: ['Temperature', 'Pathway', 'Pressure', 'Concentration'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_107', question: 'Standard enthalpy of formation is for:', options: ['Any reaction', '1 mole from elements', 'Combustion', 'Neutralization'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_108', question: 'Activation energy is:', options: ['Product energy', 'Minimum energy to react', 'Total energy', 'Zero'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_109', question: 'Catalyst:', options: ['Is used up', 'Lowers activation energy', 'Increases activation energy', 'Stops reaction'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_110', question: 'Rate of reaction depends on:', options: ['Color', 'Concentration, temperature, surface area', 'Nothing', 'Time only'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_111', question: 'Collision theory states reactions require:', options: ['No collisions', 'Effective collisions', 'Slow collisions', 'Any collisions'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_112', question: 'Maxwell-Boltzmann distribution shows:', options: ['Temperature only', 'Energy distribution of particles', 'Mass only', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_113', question: 'Dynamic equilibrium means:', options: ['No reaction', 'Forward rate = reverse rate', 'Only forward', 'Only reverse'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_114', question: 'Le Chatelier\'s principle: system opposes:', options: ['Everything', 'Changes imposed', 'Nothing', 'Equilibrium'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_115', question: 'Increase concentration favors:', options: ['No reaction', 'Using up added substance', 'Same direction', 'Stop'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_116', question: 'Increase temperature favors:', options: ['Exothermic', 'Endothermic', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_117', question: 'Increase pressure favors:', options: ['More moles gas', 'Fewer moles gas', 'No change', 'Liquids'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_118', question: 'Kc is equilibrium constant for:', options: ['Gases', 'Concentrations', 'Pressure', 'Temperature'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_119', question: 'Kp is equilibrium constant for:', options: ['Concentrations', 'Partial pressures', 'Temperature', 'Volume'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_120', question: 'Alkanes are:', options: ['Unsaturated', 'Saturated hydrocarbons', 'Aromatic', 'Alcohols'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_121', question: 'Alkenes contain:', options: ['Only single bonds', 'C=C double bond', 'Triple bond', 'No carbon'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_122', question: 'Alkenes undergo:', options: ['Substitution', 'Addition reactions', 'No reactions', 'Only combustion'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_123', question: 'Test for alkene uses:', options: ['Limewater', 'Bromine water', 'Litmus', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_124', question: 'Alkene + bromine water:', options: ['No change', 'Decolorizes', 'Turns red', 'Turns blue'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_125', question: 'Alcohols contain ___ functional group:', options: ['-COOH', '-OH', '-NH₂', '-CHO'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_126', question: 'Carboxylic acids contain ___ group:', options: ['-OH', '-COOH', '-CHO', '-CO'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_127', question: 'Primary alcohol oxidation produces:', options: ['Nothing', 'Aldehyde then acid', 'Ketone', 'Alkene'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_128', question: 'Secondary alcohol oxidation produces:', options: ['Aldehyde', 'Ketone', 'Acid', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_129', question: 'Tertiary alcohol oxidation produces:', options: ['Aldehyde', 'Ketone', 'Nothing (resistant)', 'Acid'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_130', question: 'Esterification is reaction between:', options: ['Alkane + water', 'Alcohol + carboxylic acid', 'Alkene + water', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_131', question: 'Polymers are:', options: ['Small molecules', 'Large molecules from monomers', 'Elements', 'Ions'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_132', question: 'Addition polymers form from:', options: ['Saturated compounds', 'Unsaturated monomers', 'Acids', 'Alcohols'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_133', question: 'Condensation polymers release:', options: ['Nothing', 'Small molecule (e.g., H₂O)', 'Large molecule', 'Gas only'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_134', question: 'Halogenoalkanes contain:', options: ['Only C and H', 'Halogen atom', 'Oxygen', 'Nitrogen'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_135', question: 'Nucleophilic substitution involves:', options: ['Positive species', 'Negative/neutral species donating electrons', 'Radicals', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },

  // PHYSICS (65 questions)
  { id: 'y12_sci_136', question: 'Scalar quantity has:', options: ['Magnitude and direction', 'Only magnitude', 'Only direction', 'Neither'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_137', question: 'Vector quantity has:', options: ['Only magnitude', 'Magnitude and direction', 'Only direction', 'Neither'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_138', question: 'Displacement is:', options: ['Scalar', 'Vector', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_139', question: 'Distance is:', options: ['Vector', 'Scalar', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_140', question: 'Velocity is:', options: ['Scalar', 'Vector', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_141', question: 'Speed is:', options: ['Vector', 'Scalar', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_142', question: 'Newton\'s First Law: object continues unless:', options: ['It stops', 'Resultant force acts', 'Time passes', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_143', question: 'Newton\'s Second Law: F = ___:', options: ['ma', 'mv', 'md', 'mt'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_144', question: 'Newton\'s Third Law: forces are ___ and ___:', options: ['Same direction, same', 'Equal, opposite', 'Different, same direction', 'Unrelated'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_145', question: 'Momentum = ___:', options: ['Mass × velocity', 'Mass × acceleration', 'Force × time', 'Force × distance'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_146', question: 'Impulse = ___:', options: ['Change in momentum', 'Change in velocity', 'Change in force', 'Change in mass'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_147', question: 'Impulse also = ___:', options: ['Mass × time', 'Force × time', 'Mass × velocity', 'Force × distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_148', question: 'Conservation of momentum applies in:', options: ['Open systems', 'Closed systems', 'Never', 'Sometimes'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_149', question: 'Elastic collision conserves:', options: ['Only momentum', 'Momentum and kinetic energy', 'Only KE', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_150', question: 'Inelastic collision conserves:', options: ['KE only', 'Momentum only', 'Both', 'Neither'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_151', question: 'Work done = ___:', options: ['Force × time', 'Force × distance', 'Mass × velocity', 'Power × distance'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_152', question: 'Kinetic energy = ___:', options: ['mv', 'mgh', '½mv²', 'Ft'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_153', question: 'Gravitational potential energy = ___:', options: ['½mv²', 'mgh', 'Ft', 'Fd'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_154', question: 'Power = ___:', options: ['Work / time', 'Force × distance', 'Energy × time', 'Mass × velocity'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_155', question: 'Power also = ___:', options: ['F × d', 'F × v', 'F × t', 'F × m'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_156', question: 'Efficiency = (useful output / total input) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_157', question: 'Hooke\'s Law: F = ___:', options: ['mx', 'kx', 'ma', 'mg'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_158', question: 'Elastic limit is point where:', options: ['Always elastic', 'Permanent deformation begins', 'Breaks', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_159', question: 'Young modulus = ___:', options: ['Stress / strain', 'Strain / stress', 'Force / area', 'Extension / length'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_160', question: 'Stress = ___:', options: ['Extension / length', 'Force / area', 'Strain × modulus', 'Force × area'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_161', question: 'Strain = ___:', options: ['Force / area', 'Extension / original length', 'Stress / modulus', 'Force × distance'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_162', question: 'Current measured in:', options: ['Volts', 'Amperes', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_163', question: 'Voltage measured in:', options: ['Amperes', 'Volts', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_164', question: 'Resistance measured in:', options: ['Amperes', 'Volts', 'Ohms', 'Watts'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_165', question: 'Ohm\'s Law: V = ___:', options: ['I/R', 'IR', 'I + R', 'I - R'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_166', question: 'Power = ___:', options: ['VI', 'V/I', 'V + I', 'V - I'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_167', question: 'Power also = ___:', options: ['V²R', 'I²R', 'VIR', 'V/I²'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_168', question: 'Energy = ___:', options: ['Power × time', 'Power / time', 'Voltage × current', 'Resistance × current'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_169', question: 'Charge = ___:', options: ['Current / time', 'Current × time', 'Voltage × time', 'Power / time'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_170', question: 'Series resistors: Total R = ___:', options: ['R₁ + R₂', '1/R₁ + 1/R₂', 'R₁ × R₂', 'R₁ / R₂'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_171', question: 'Parallel resistors: 1/R = ___:', options: ['R₁ + R₂', '1/R₁ + 1/R₂', 'R₁ × R₂', 'R₁ / R₂'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_172', question: 'Kirchhoff\'s First Law: sum of currents at junction:', options: ['Increases', 'Zero', 'Decreases', 'Doubles'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_173', question: 'Kirchhoff\'s Second Law: sum of voltages in loop:', options: ['Increases', 'Zero', 'Decreases', 'Doubles'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_174', question: 'EMF is:', options: ['Lost voltage', 'Voltage source provides', 'Resistance', 'Current'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_175', question: 'Internal resistance causes:', options: ['No loss', 'Voltage loss in source', 'Current increase', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_176', question: 'Terminal pd = EMF - ___:', options: ['External voltage', 'Voltage lost to internal r', 'Current', 'Power'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_177', question: 'Potential divider divides:', options: ['Current', 'Voltage', 'Resistance', 'Power'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_178', question: 'Wave speed = ___:', options: ['Frequency / wavelength', 'Frequency × wavelength', 'Amplitude × frequency', 'Wavelength / frequency'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_179', question: 'Transverse wave: oscillations ___ to direction:', options: ['Parallel', 'Perpendicular', 'Same', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_180', question: 'Longitudinal wave: oscillations ___ to direction:', options: ['Perpendicular', 'Parallel', 'Opposite', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_181', question: 'Refraction is:', options: ['Reflection', 'Bending due to speed change', 'Absorption', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_sci_182', question: 'Snell\'s Law: n₁sin θ₁ = ___:', options: ['n₂cos θ₂', 'n₂sin θ₂', 'n₁sin θ₂', 'n₂tan θ₂'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_183', question: 'Total internal reflection occurs when:', options: ['Always', 'Angle > critical angle', 'Angle < critical angle', 'Never'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_184', question: 'Diffraction is:', options: ['Reflection', 'Spreading through gap', 'Absorption', 'Refraction'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_185', question: 'Interference requires:', options: ['One wave', 'Coherent sources', 'No waves', 'Different frequencies'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_186', question: 'Constructive interference: waves are:', options: ['Out of phase', 'In phase', 'Different frequencies', 'Not overlapping'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_187', question: 'Destructive interference: waves are:', options: ['In phase', 'Out of phase (180°)', 'Same amplitude', 'Not overlapping'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_188', question: 'Path difference for constructive: ___:', options: ['Odd multiple λ/2', 'Whole number of λ', 'λ/4', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_189', question: 'Path difference for destructive: ___:', options: ['Whole λ', 'Odd multiple of λ/2', 'λ/4', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_190', question: 'Photoelectric effect: photons eject:', options: ['Protons', 'Electrons', 'Neutrons', 'Nuclei'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_191', question: 'Threshold frequency is:', options: ['Maximum', 'Minimum to eject electron', 'Average', 'Zero'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_192', question: 'Photon energy = ___:', options: ['hf', 'mc²', 'mgh', '½mv²'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_193', question: 'Stopping potential measures:', options: ['Frequency', 'Maximum KE of electrons', 'Intensity', 'Wavelength'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_194', question: 'Wave-particle duality means:', options: ['Only wave', 'Both wave and particle properties', 'Only particle', 'Neither'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_195', question: 'De Broglie wavelength: λ = ___:', options: ['h/p', 'p/h', 'hf', 'mc²'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_196', question: 'Quantum means:', options: ['Continuous', 'Discrete packet', 'Infinite', 'Zero'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_sci_197', question: 'Heisenberg uncertainty principle relates:', options: ['Position and momentum', 'Energy and mass', 'Frequency and wavelength', 'Speed and time'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_198', question: 'Electron diffraction demonstrates:', options: ['Only particle nature', 'Wave nature of electrons', 'No properties', 'Positive charge'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_199', question: 'Energy levels in atoms are:', options: ['Continuous', 'Quantized/discrete', 'Random', 'Infinite'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_sci_200', question: 'Emission spectrum shows:', options: ['All frequencies', 'Specific frequencies', 'No light', 'Only UV'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 }
];
