// Year 7 English Trivia Questions
// Based on UK Year 7 English Curriculum Framework (KS3)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_7_ENGLISH_QUESTIONS = [
  // READING & COMPREHENSION (60 questions)
  // Literary techniques and analysis
  { id: 'y7_eng_1', question: 'What is a simile?', options: ['Direct comparison', 'Comparison using like or as', 'Exaggeration', 'Human qualities to objects'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_2', question: 'What is a metaphor?', options: ['Comparison with like', 'Direct comparison saying one thing IS another', 'Sound words', 'Repetition'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_3', question: 'What is personification?', options: ['Describing people', 'Giving human qualities to non-human things', 'Using similes', 'Alliteration'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_4', question: 'Example of personification:', options: ['As cold as ice', 'The wind whispered', 'He is a lion', 'She runs fast'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_5', question: 'What is alliteration?', options: ['Rhyming', 'Repeating consonant sounds at word starts', 'Metaphors', 'Questions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_6', question: 'Example of alliteration:', options: ['The cat sat', 'Peter Piper picked peppers', 'Very happy', 'As brave as'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_7', question: 'What is onomatopoeia?', options: ['Long word', 'Words that sound like their meaning', 'Metaphor', 'Simile'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_8', question: 'Example of onomatopoeia:', options: ['Beautiful', 'Crash', 'Happy', 'Quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_9', question: 'What is hyperbole?', options: ['Understatement', 'Exaggeration for effect', 'Comparison', 'Question'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_10', question: 'Example of hyperbole:', options: ['She is kind', 'I told you a million times', 'He is tall', 'Very cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_11', question: 'What is imagery?', options: ['Pictures', 'Descriptive language creating mental images', 'Photos', 'Diagrams'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_12', question: 'What is a rhetorical question?', options: ['Normal question', 'Question asked for effect, not needing answer', 'Easy question', 'Statement'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_13', question: 'What is repetition used for?', options: ['Fill space', 'Emphasize ideas', 'Confuse', 'Make longer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_14', question: 'What is foreshadowing?', options: ['Looking back', 'Hints about what will happen later', 'The ending', 'Introduction'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_15', question: 'What is a flashback?', options: ['Future events', 'Scene from the past', 'Current scene', 'The ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Shakespeare and drama
  { id: 'y7_eng_16', question: 'Who wrote Romeo and Juliet?', options: ['Dickens', 'Shakespeare', 'Austen', 'Tolkien'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_17', question: 'What is a tragedy?', options: ['Happy story', 'Serious play with sad ending', 'Comedy', 'News'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_18', question: 'What is a comedy?', options: ['Sad play', 'Humorous play with happy ending', 'Tragic', 'Boring'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_19', question: 'What is dialogue?', options: ['Description', 'Conversation between characters', 'Narration', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_20', question: 'What are stage directions?', options: ['Dialogue', 'Instructions for actors/directors', 'Audience seats', 'Props'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_21', question: 'A soliloquy is:', options: ['Two people talking', 'Character speaking thoughts alone', 'Chorus', 'Prologue'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_22', question: 'An aside is:', options: ['Exit', 'Remark heard by audience, not other characters', 'Prologue', 'Epilogue'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_23', question: 'What is dramatic irony?', options: ['Audience knows something characters don\'t', 'Characters know everything', 'No irony', 'Sarcasm'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_24', question: 'What is a protagonist?', options: ['The villain', 'The main character', 'Minor character', 'The setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_25', question: 'What is an antagonist?', options: ['The hero', 'Character opposing main character', 'Narrator', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Poetry
  { id: 'y7_eng_26', question: 'What is a stanza?', options: ['A line', 'A verse/group of lines', 'The title', 'The rhyme'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_27', question: 'What is rhyme scheme?', options: ['Type of poem', 'Pattern of rhymes (ABAB)', 'Number of lines', 'Rhythm'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_28', question: 'ABAB rhyme scheme means:', options: ['No rhyme', 'Alternate line rhyme', 'Couplets', 'All rhyme'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_29', question: 'What is rhythm in poetry?', options: ['Meaning', 'Pattern of beats/stressed syllables', 'Rhyme', 'Length'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_30', question: 'What is a haiku?', options: ['5-line poem', 'Japanese 3-line poem (5-7-5 syllables)', '14-line poem', 'Rhyming couplet'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_31', question: 'What is a sonnet?', options: ['5-line', '14-line poem', '3-line', '20-line'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_32', question: 'What is free verse?', options: ['Strict rules', 'Poetry without regular rhyme/rhythm', 'Always rhymes', 'Only 4 lines'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_33', question: 'What is a limerick?', options: ['Sad poem', 'Humorous 5-line poem (AABBA)', 'Japanese', '14-line'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_34', question: 'What is enjambment?', options: ['End of line', 'Line running onto next without pause', 'Rhyme', 'Rhythm'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_35', question: 'What is a caesura?', options: ['End rhyme', 'Pause in middle of line', 'Stanza break', 'Rhythm'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },

  // Reading skills
  { id: 'y7_eng_36', question: 'What is inference?', options: ['Reading aloud', 'Reading between lines for hidden meaning', 'Summarizing', 'Predicting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_37', question: 'What is deduction?', options: ['Guessing', 'Using evidence to reach conclusion', 'Copying', 'Reading slowly'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_38', question: 'What is context?', options: ['Title', 'Surrounding words helping explain meaning', 'Author', 'Conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_39', question: 'What is a summary?', options: ['Copying all', 'Brief statement of main points', 'Adding details', 'Changing story'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_40', question: 'What is theme?', options: ['Title', 'Central idea/message', 'Plot', 'Characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_41', question: 'What is plot?', options: ['Setting', 'Sequence of events', 'Theme', 'Mood'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_42', question: 'What is setting?', options: ['Theme', 'Time and place', 'Characters', 'Plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_43', question: 'What is conflict?', options: ['Agreement', 'Problem/struggle', 'Solution', 'Ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_44', question: 'What is resolution?', options: ['Problem', 'How conflict is solved', 'Introduction', 'Climax'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_45', question: 'What is the climax?', options: ['Beginning', 'Turning point/most intense moment', 'Ending', 'Introduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_46', question: 'First-person narration uses:', options: ['He/she', 'I/we', 'You', 'They'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_47', question: 'Third-person narration uses:', options: ['I/we', 'He/she/they', 'You', 'Me'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_48', question: 'What is mood/atmosphere?', options: ['Author attitude', 'Feeling created for reader', 'Plot', 'Characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_49', question: 'What is tone?', options: ['Volume', 'Author\'s attitude conveyed', 'Length', 'Color'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_50', question: 'What is symbolism?', options: ['Math symbols', 'Objects representing deeper meanings', 'Letters', 'Numbers'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_51', question: 'What is character motivation?', options: ['How they move', 'Why they do what they do', 'Appearance', 'Location'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_52', question: 'What is character development?', options: ['Stays same', 'How character changes', 'Age', 'Appearance'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_53', question: 'What is a fact?', options: ['Opinion', 'Something provable', 'Belief', 'Guess'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_54', question: 'What is an opinion?', options: ['Proven truth', 'Personal belief/judgment', 'Fact', 'Data'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_55', question: 'Which is a fact?', options: ['Pizza is delicious', 'Water boils at 100°C', 'Summer is best', 'Red is pretty'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_56', question: 'What is bias?', options: ['Fairness', 'Showing prejudice for/against', 'Balance', 'Neutrality'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_57', question: 'What is emotive language?', options: ['Factual', 'Language to provoke emotion', 'Boring', 'Scientific'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_58', question: 'What is allusion?', options: ['Direct reference', 'Indirect reference to another work/event', 'Confusion', 'Metaphor'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_59', question: 'What is juxtaposition?', options: ['Same things together', 'Contrasting things placed together', 'Repetition', 'Rhyme'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_60', question: 'What is irony?', options: ['Expected outcome', 'Opposite of what\'s expected', 'Sarcasm only', 'Humor'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },

  // WRITING (60 questions)
  // Creative writing
  { id: 'y7_eng_61', question: 'Good story opening should:', options: ['Be boring', 'Hook reader immediately', 'Summarize everything', 'Be very long'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_62', question: 'Show don\'t tell means:', options: ['State emotions', 'Use actions/details to show', 'Be vague', 'Hide information'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_63', question: 'Describing settings should include:', options: ['Only names', 'Sensory details (5 senses)', 'Short words', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_64', question: 'Good character description includes:', options: ['Only name', 'Appearance, personality, actions', 'Nothing', 'Just age'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_65', question: 'Dialogue should:', options: ['Be boring', 'Show character, advance plot', 'Be ignored', 'Be very long'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_66', question: 'To build tension:', options: ['Rush', 'Delay information, hint at danger', 'Be boring', 'Reveal everything'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_67', question: 'A good ending should:', options: ['Be abrupt', 'Provide closure/resolution', 'Introduce new ideas', 'Be incomplete'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_68', question: 'Varied sentence length creates:', options: ['Boredom', 'Interest and rhythm', 'Confusion', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_69', question: 'What is pace?', options: ['Size', 'Speed story unfolds', 'Location', 'Characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_70', question: 'To create atmosphere use:', options: ['Random words', 'Descriptive language, mood words, imagery', 'Short sentences', 'No description'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // Non-fiction writing
  { id: 'y7_eng_71', question: 'What is audience?', options: ['Author', 'Who will read it', 'Title', 'Topic'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_72', question: 'What is purpose?', options: ['Title', 'Why writing (inform, persuade, entertain)', 'Ending', 'Length'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_73', question: 'To persuade means:', options: ['Inform', 'Convince of viewpoint', 'Entertain', 'Describe'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_74', question: 'To inform means:', options: ['Entertain', 'Provide facts/information', 'Make up stories', 'Persuade'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_75', question: 'To entertain means:', options: ['Give facts', 'Amuse/interest reader', 'Give instructions', 'Persuade'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_76', question: 'Formal writing uses:', options: ['Slang', 'Proper grammar, formal vocabulary', 'Casual language', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_77', question: 'Informal writing uses:', options: ['Very formal', 'Casual, conversational', 'Only Standard English', 'No contractions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_78', question: 'Persuasive techniques include:', options: ['Boring facts', 'Rhetorical questions, emotive language, repetition', 'Nothing', 'Random words'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_79', question: 'What is a counter-argument?', options: ['Agreement', 'Opposing viewpoint', 'Repeating', 'Conclusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_80', question: 'What is a recount?', options: ['Counting', 'Retelling events', 'Fiction', 'Poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_81', question: 'What is a report?', options: ['Fiction', 'Factual writing about topic', 'Story', 'Poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_82', question: 'What is an article?', options: ['Story', 'Non-fiction piece for publication', 'Poem', 'Play'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_83', question: 'What is a speech?', options: ['Written story', 'Spoken presentation', 'Poem', 'Letter'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_84', question: 'What is a letter format?', options: ['No structure', 'Address, greeting, body, closing, signature', 'Just text', 'Only greeting'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_85', question: 'What is a paragraph?', options: ['One sentence', 'Group of sentences about one idea', 'Whole text', 'Word'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_86', question: 'Start new paragraph when:', options: ['Every sentence', 'New topic, time, place, speaker', 'Never', 'Randomly'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_87', question: 'Topic sentence:', options: ['Ends paragraph', 'Introduces main idea', 'Random', 'Not needed'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_88', question: 'Connectives help:', options: ['Confuse', 'Link ideas and sentences', 'Make longer', 'Add pictures'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_89', question: 'Example of time connective:', options: ['However', 'Meanwhile', 'Because', 'Although'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_90', question: 'Example of cause connective:', options: ['Next', 'Because', 'Then', 'Later'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_91', question: 'Organizational devices include:', options: ['Only paragraphs', 'Headings, subheadings, bullet points', 'Only sentences', 'Only words'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_92', question: 'What is editing?', options: ['First draft', 'Checking/improving writing', 'Publishing', 'Ignoring mistakes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_93', question: 'What is proofreading?', options: ['Writing', 'Checking for errors', 'Planning', 'Brainstorming'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_94', question: 'When editing check:', options: ['Nothing', 'Spelling, grammar, punctuation, clarity', 'Only spelling', 'Only grammar'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_95', question: 'Tense should be:', options: ['Mixed randomly', 'Consistent throughout', 'Ignored', 'Changed often'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_96', question: 'Past tense example:', options: ['I walk', 'I walked', 'I will walk', 'I am walking'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_97', question: 'Present tense example:', options: ['I walked', 'I walk', 'I will walk', 'I had walked'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_98', question: 'Future tense example:', options: ['I walked', 'I walk', 'I will walk', 'I am'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_99', question: 'Varied vocabulary makes writing:', options: ['Boring', 'More interesting', 'Confusing', 'Longer only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_100', question: 'Thesaurus helps find:', options: ['Spelling', 'Synonyms and varied vocabulary', 'Grammar', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_101', question: 'What is cohesion?', options: ['Random ideas', 'How ideas link and flow', 'Long sentences', 'Short sentences'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_102', question: 'What is register?', options: ['List', 'Level of formality', 'List of names', 'Book'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_103', question: 'A strong conclusion should:', options: ['Introduce new ideas', 'Summarize and provide closure', 'Ask many questions', 'Be incomplete'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_104', question: 'What is drafting?', options: ['Final version', 'Writing early version', 'Ignoring task', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_105', question: 'Planning helps:', options: ['Waste time', 'Organize ideas before writing', 'Confuse', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_106', question: 'Introduction should:', options: ['End essay', 'Introduce topic and engage reader', 'Conclude', 'Be last'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_107', question: 'Main body paragraphs should:', options: ['Be random', 'Each cover one main point with evidence', 'Be very short', 'Have no structure'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_108', question: 'Evidence in writing:', options: ['Not needed', 'Supports your points', 'Confuses', 'Makes longer'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_109', question: 'Quotations should be:', options: ['Very long', 'Relevant and explained', 'Random', 'Avoided'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_110', question: 'What is analysis?', options: ['Summarizing', 'Examining closely and explaining', 'Copying', 'Ignoring'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_111', question: 'PEE/PEEL structure means:', options: ['Random', 'Point, Evidence, Explain (Link)', 'Only examples', 'No structure'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_112', question: 'What is a thesis statement?', options: ['Conclusion', 'Main argument stated upfront', 'Evidence', 'Example'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_113', question: 'Linking words help:', options: ['Confuse', 'Connect ideas smoothly', 'End essay', 'Start essay'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_114', question: 'Balanced argument shows:', options: ['One side only', 'Both/multiple viewpoints', 'No opinion', 'Random ideas'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_115', question: 'What is a discursive essay?', options: ['Story', 'Explores different viewpoints', 'Biography', 'Poem'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_116', question: 'Imperative verbs in instructions:', options: ['Suggest', 'Command (do this)', 'Question', 'Describe'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_117', question: 'Chronological order means:', options: ['Random', 'Time order', 'Alphabetical', 'Size order'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_118', question: 'Technical vocabulary should be:', options: ['Avoided', 'Used appropriately and explained', 'Used constantly', 'Random'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_119', question: 'Descriptive writing focuses on:', options: ['Facts only', 'Creating vivid picture', 'Arguments', 'Instructions'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_120', question: 'Narrative writing tells:', options: ['Facts', 'A story', 'Instructions', 'Arguments'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // GRAMMAR & PUNCTUATION (60 questions)
  { id: 'y7_eng_121', question: 'What is a noun?', options: ['Action', 'Person, place, thing, idea', 'Describing word', 'Joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_122', question: 'What is a verb?', options: ['Naming word', 'Action/state word', 'Describing word', 'Joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_123', question: 'What is an adjective?', options: ['Action', 'Describes noun', 'Joining word', 'Naming'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_124', question: 'What is an adverb?', options: ['Describes noun', 'Describes verb/adjective/adverb', 'Names', 'Joins'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_125', question: 'What is a pronoun?', options: ['Action', 'Replaces noun (he, she, it)', 'Describes', 'Joins'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_126', question: 'What is a preposition?', options: ['Action', 'Shows position/relationship (in, on, under)', 'Describes', 'Names'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_127', question: 'What is a conjunction?', options: ['Action', 'Joins words/clauses (and, but, because)', 'Describes', 'Names'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_128', question: 'Example of conjunction:', options: ['Happy', 'But', 'Quickly', 'Running'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_129', question: 'Coordinating conjunctions:', options: ['Because, although', 'And, but, or', 'When, if', 'That, which'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_130', question: 'Subordinating conjunctions:', options: ['And, but, or', 'Because, although, when, if', 'Only and', 'Only but'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_131', question: 'What is a clause?', options: ['Single word', 'Group of words with subject and verb', 'Random words', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_132', question: 'What is a main clause?', options: ['Cannot stand alone', 'Can stand alone as sentence', 'Only short', 'Only long'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_133', question: 'What is a subordinate clause?', options: ['Stands alone', 'Cannot stand alone, depends on main', 'Only questions', 'Only statements'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_134', question: 'Simple sentence has:', options: ['Two clauses', 'One main clause', 'Three clauses', 'No clause'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_135', question: 'Compound sentence has:', options: ['One clause', 'Two+ main clauses joined', 'No clauses', 'Subordinate only'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_136', question: 'Complex sentence has:', options: ['Only main', 'Main + subordinate clause(s)', 'No clauses', 'Only subordinate'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_137', question: 'Compound sentence example:', options: ['The cat slept.', 'I like tea, but she likes coffee.', 'Although tired, he worked.', 'Stop!'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_138', question: 'Complex sentence example:', options: ['She ran.', 'I ran and jumped.', 'Because it rained, we stayed inside.', 'Hello.'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_139', question: 'What is a colon used for?', options: ['End sentences', 'Introduce list/explanation', 'Show questions', 'Show excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_140', question: 'What is a semi-colon used for?', options: ['End sentences', 'Link related clauses', 'Show questions', 'Show excitement'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_141', question: 'Apostrophe shows:', options: ['Questions', 'Possession or omission', 'Excitement', 'Lists'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_142', question: '"The dog\'s bone" means:', options: ['Many dogs', 'Bone belongs to dog', 'Dogs are bones', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_143', question: '"Don\'t" is short for:', options: ['Do not', 'Did not', 'Does not', 'Doing not'], correctAnswer: 0, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_144', question: 'Which is correct?', options: ['Its raining', 'It\'s raining', 'Its\' raining', 'I\'ts raining'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_145', question: 'Plural possession: "The girls\' books" means:', options: ['One girl', 'Many girls own books', 'No girls', 'One book'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_146', question: 'Commas in lists separate:', options: ['Nothing', 'Items', 'Sentences', 'Paragraphs'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_147', question: 'Comma after introductory word:', options: ['Wrong', 'Correct (However, I disagree.)', 'Random', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_148', question: 'Parenthesis can use:', options: ['Only full stops', 'Brackets, dashes, or commas', 'Only capitals', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_149', question: 'What is ellipsis (...)?', options: ['Full stop', 'Shows omission/trailing off', 'Question mark', 'Comma'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_150', question: 'Quotation marks show:', options: ['Questions', 'Direct speech/quotations', 'Titles only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_151', question: 'Subject-verb agreement means:', options: ['Can be different', 'Subject and verb must match', 'Verbs don\'t matter', 'Subjects don\'t matter'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_152', question: 'Correct agreement:', options: ['She walk', 'She walks', 'They walks', 'I walks'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_153', question: 'What is active voice?', options: ['Subject receives action', 'Subject performs action', 'No subject', 'Past tense'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_154', question: 'What is passive voice?', options: ['Subject performs', 'Subject receives action', 'No verb', 'Future'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_155', question: 'Active voice example:', options: ['The ball was kicked', 'Tom kicked the ball', 'The ball is kicked', 'Kicked by Tom'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_156', question: 'Passive voice example:', options: ['She wrote letter', 'The letter was written by her', 'Writing letter', 'She writes'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_157', question: 'What is a modal verb?', options: ['Past tense', 'Shows possibility/obligation (might, must)', 'Present', 'Future'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_158', question: 'Example of modal verb:', options: ['Walk', 'Should', 'Happy', 'Quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_159', question: 'What is a relative clause?', options: ['Main sentence', 'Clause giving extra info about noun', 'Question', 'Command'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_160', question: 'Relative pronouns include:', options: ['And, but', 'Who, which, that, whose', 'I, you, he', 'In, on, under'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_161', question: 'Use "who" for:', options: ['Things', 'People', 'Places', 'Times'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_162', question: 'Use "which" for:', options: ['People', 'Things', 'Only animals', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_163', question: 'What is a determiner?', options: ['Action word', 'Introduces noun (the, a, an, this)', 'Adjective', 'Adverb'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_164', question: 'Example of determiner:', options: ['Jump', 'Blue', 'The', 'Quickly'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_165', question: 'Proper noun always starts with:', options: ['Lowercase', 'Capital letter', 'Number', 'Symbol'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_166', question: 'Common noun is:', options: ['Specific name', 'General name (dog, city)', 'Verb', 'Adjective'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_167', question: 'Collective noun is:', options: ['One item', 'Group (team, flock)', 'Verb', 'Adjective'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_168', question: 'Abstract noun refers to:', options: ['Physical objects', 'Ideas, concepts, feelings', 'Only animals', 'Only places'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_169', question: 'Concrete noun refers to:', options: ['Ideas only', 'Physical things you can sense', 'Feelings only', 'Concepts only'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_170', question: 'Synonym is:', options: ['Opposite word', 'Similar meaning word', 'Made-up word', 'Plural'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_171', question: 'Synonym for "happy":', options: ['Sad', 'Joyful', 'Angry', 'Tired'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_172', question: 'Antonym is:', options: ['Similar word', 'Opposite word', 'Rhyming word', 'Long word'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_173', question: 'Antonym for "hot":', options: ['Warm', 'Cold', 'Big', 'Small'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_174', question: 'Homophones are:', options: ['Same spelling', 'Sound same, different meanings/spellings', 'Opposites', 'Synonyms'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_175', question: 'Correct: "Can you ___ me?"', options: ['here', 'hear', 'hare', 'heir'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_176', question: 'Prefix "un-" means:', options: ['Again', 'Not/opposite', 'Before', 'After'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_177', question: 'Prefix "re-" means:', options: ['Not', 'Again', 'Before', 'Under'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_178', question: 'Suffix "-tion" creates:', options: ['Verb', 'Noun', 'Adjective', 'Adverb'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_179', question: 'Suffix "-ly" often creates:', options: ['Noun', 'Verb', 'Adverb', 'Pronoun'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_180', question: 'Standard English is:', options: ['Slang', 'Formal, grammatically correct', 'Regional dialect', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },

  // SPELLING & VOCABULARY (20 questions)
  { id: 'y7_eng_181', question: 'Correct spelling:', options: ['Necesary', 'Neccesary', 'Necessary', 'Neccessary'], correctAnswer: 2, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_182', question: 'Correct spelling:', options: ['Separate', 'Seperate', 'Separete', 'Seprate'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_183', question: 'Correct spelling:', options: ['Definately', 'Definitely', 'Definitly', 'Definetely'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_184', question: 'Correct spelling:', options: ['Accomodate', 'Accommodate', 'Acommodate', 'Acomodate'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_185', question: 'Silent letter in "knight":', options: ['n', 'i', 'k', 't'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_186', question: 'Silent letter in "Wednesday":', options: ['W', 'd', 'n', 'e'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_187', question: 'Correct: "___ bag is this?"', options: ['Whose', 'Who\'s', 'Whos', 'Who\'se'], correctAnswer: 0, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_188', question: 'Correct: "The decision is ___."', options: ['your\'s', 'yours', 'yours\'', 'your'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_189', question: 'Correct: "We ___ going tomorrow."', options: ['were', 'where', 'we\'re', 'wear'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_190', question: 'Correct: "___ very happy."', options: ['There', 'Their', 'They\'re', 'Thare'], correctAnswer: 2, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_191', question: 'Word families share:', options: ['Nothing', 'Same root/base word', 'Same length', 'Same first letter'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_192', question: 'Etymology means:', options: ['Study of insects', 'Study of word origins', 'Study of rocks', 'Study of numbers'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_193', question: 'Morphology studies:', options: ['Shapes', 'Word structure/formation', 'Animals', 'Plants'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_194', question: 'Root word of "unhappiness":', options: ['Unhappy', 'Happy', 'Happiness', 'Un'], correctAnswer: 1, difficulty: 'medium', xpReward: 30 },
  { id: 'y7_eng_195', question: 'Dictionary used for:', options: ['Grammar', 'Finding spelling/meaning', 'Synonyms only', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_196', question: 'Thesaurus used for:', options: ['Spelling', 'Finding synonyms/antonyms', 'Grammar', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_197', question: 'Words in dictionary arranged:', options: ['Randomly', 'Alphabetically', 'By size', 'By color'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_198', question: 'Context clues help:', options: ['Nothing', 'Work out unknown word meanings', 'Grammar', 'Spelling'], correctAnswer: 1, difficulty: 'easy', xpReward: 25 },
  { id: 'y7_eng_199', question: 'What is connotation?', options: ['Dictionary definition', 'Associated meanings/feelings', 'Spelling', 'Grammar'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 },
  { id: 'y7_eng_200', question: 'What is denotation?', options: ['Associated feelings', 'Literal/dictionary definition', 'Spelling', 'Grammar'], correctAnswer: 1, difficulty: 'hard', xpReward: 35 }
];
