/* AUTOGENERATED FILE - credentials moved to .env.local for security */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;
export const authDomain = import.meta.env.VITE_SUPABASE_AUTH_DOMAIN as string | undefined;