// Year 2 Science Trivia Questions
// Based on UK Year 2 Science Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_2_SCIENCE_QUESTIONS = [
  // WORKING SCIENTIFICALLY (15 questions)
  { id: 'y2_sci_1', question: 'What do scientists do when they want to find out something?', options: ['Guess', 'Ask questions and investigate', 'Copy others', 'Do nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_2', question: 'A prediction is:', options: ['A fact', 'A guess about what might happen', 'The answer', 'A type of animal'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_3', question: 'Which sense do we use to observe how something looks?', options: ['Touch', 'Smell', 'Sight', 'Hearing'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_4', question: 'Which sense tells us if something is rough or smooth?', options: ['Touch', 'Taste', 'Hearing', 'Sight'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_5', question: 'When we do a test, we are:', options: ['Playing a game', 'Investigating to find answers', 'Breaking things', 'Sleeping'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_6', question: 'Classifying means:', options: ['Breaking things', 'Grouping things that are similar', 'Hiding things', 'Throwing things away'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_7', question: 'Why do we record our results?', options: ['To forget them', 'To remember what we found out', 'To make noise', 'To waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_8', question: 'Which can we use to record results?', options: ['Drawings and charts', 'Only words', 'Nothing', 'Only pictures'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_9', question: 'A simple test helps us:', options: ['Find answers to questions', 'Make a mess', 'Waste time', 'Break things'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_10', question: 'When observing, we should use:', options: ['Only our eyes', 'All our senses safely', 'No senses', 'Only our ears'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_11', question: 'What does "investigate" mean?', options: ['To find out by testing', 'To guess', 'To copy', 'To ignore'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_12', question: 'A chart helps us:', options: ['Organize information', 'Make noise', 'Hide things', 'Break things'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_13', question: 'Why do scientists make predictions?', options: ['To guess what might happen', 'To break things', 'To hide results', 'To sleep'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_14', question: 'After an investigation, we should:', options: ['Forget about it', 'Explain what we found', 'Run away', 'Cry'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_15', question: 'Observing closely means:', options: ['Looking quickly', 'Looking carefully at details', 'Not looking', 'Closing eyes'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // LIVING THINGS & HABITATS (30 questions)
  // Living and Non-Living Things
  { id: 'y2_sci_16', question: 'Which of these is a living thing?', options: ['Rock', 'Tree', 'Chair', 'Cup'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_17', question: 'Living things can:', options: ['Never change', 'Grow and reproduce', 'Stay the same forever', 'Not move'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_18', question: 'Which is NOT a living thing?', options: ['Dog', 'Cat', 'Stone', 'Plant'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_19', question: 'What do all living things need?', options: ['Toys', 'Food, water, and air', 'Television', 'Cars'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_20', question: 'Something that was once alive but is not alive now is:', options: ['Living', 'Dead', 'Non-living', 'Growing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_21', question: 'A wooden chair is made from a tree. It is:', options: ['Living', 'Dead', 'Never been alive', 'Growing'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_22', question: 'A plastic toy has:', options: ['Been alive', 'Never been alive', 'Is alive', 'Is dead'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_23', question: 'Which shows a life process?', options: ['A car moving', 'A plant growing', 'A ball rolling', 'A rock sitting'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // Habitats
  { id: 'y2_sci_24', question: 'A habitat is:', options: ['A type of food', 'Where an animal or plant lives', 'A game', 'A color'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_25', question: 'Which animal lives in the ocean?', options: ['Lion', 'Elephant', 'Dolphin', 'Bear'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_26', question: 'Where would you find a polar bear?', options: ['Desert', 'Rainforest', 'Arctic', 'Garden'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_27', question: 'Which plant lives in a pond?', options: ['Cactus', 'Water lily', 'Oak tree', 'Rose'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_28', question: 'A desert habitat is:', options: ['Very wet', 'Very dry', 'Very cold', 'Underwater'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_29', question: 'Which animal would you find in a garden?', options: ['Shark', 'Whale', 'Snail', 'Polar bear'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_30', question: 'A rainforest is:', options: ['Very dry', 'Very wet with lots of trees', 'Very cold', 'Has no plants'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_31', question: 'Where do fish live?', options: ['On land', 'In water', 'In trees', 'Underground'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_32', question: 'A woodland habitat has lots of:', options: ['Water', 'Sand', 'Trees', 'Ice'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // Food Chains
  { id: 'y2_sci_33', question: 'A food chain shows:', options: ['What we eat for dinner', 'How energy passes from one living thing to another', 'Types of shops', 'Colors'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_34', question: 'In a food chain, plants are called:', options: ['Consumers', 'Producers', 'Predators', 'Prey'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_35', question: 'Animals that eat plants or other animals are called:', options: ['Producers', 'Consumers', 'Plants', 'Flowers'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_36', question: 'Simple food chain: Grass → Rabbit → ___. What comes next?', options: ['More grass', 'Fox', 'Sun', 'Water'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_37', question: 'What do all food chains start with?', options: ['Animals', 'A plant or the sun', 'Water', 'Soil'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_38', question: 'A caterpillar eats a leaf. The caterpillar is:', options: ['A producer', 'A consumer', 'Not alive', 'The sun'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_39', question: 'Which is a producer?', options: ['Lion', 'Grass', 'Fox', 'Owl'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // PLANTS (20 questions)
  { id: 'y2_sci_40', question: 'What do plants need to grow?', options: ['Light, water, and air', 'Only toys', 'Only soil', 'Only darkness'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_41', question: 'Which part of the plant absorbs water from the soil?', options: ['Leaf', 'Flower', 'Root', 'Stem'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_42', question: 'The stem of a plant:', options: ['Holds the plant up', 'Is not important', 'Only looks pretty', 'Makes noise'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_43', question: 'Leaves help plants:', options: ['Walk', 'Make food using sunlight', 'Talk', 'Sleep'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_44', question: 'What happens if a plant gets no water?', options: ['It grows bigger', 'It wilts and may die', 'It dances', 'It sings'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_45', question: 'What happens if a plant gets no light?', options: ['It grows better', 'It becomes weak and pale', 'It gets stronger', 'Nothing happens'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_46', question: 'Seeds need ___ to start growing:', options: ['Toys', 'Water and warmth', 'Television', 'Shoes'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_47', question: 'A plant growing from a seed is called:', options: ['Dying', 'Germination', 'Sleeping', 'Running'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_48', question: 'Which is a common garden plant?', options: ['Shark', 'Daisy', 'Car', 'Book'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_49', question: 'Which part of the plant makes seeds?', options: ['Root', 'Stem', 'Flower', 'Air'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_50', question: 'A sunflower turns to face:', options: ['The moon', 'The sun', 'The ground', 'Away from light'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_51', question: 'Trees are:', options: ['Not plants', 'Very large plants', 'Animals', 'Rocks'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_52', question: 'What do we call plants we grow for food?', options: ['Pets', 'Crops', 'Toys', 'Clothes'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_53', question: 'If we plant two seeds, one with water and one without, which grows?', options: ['The one without water', 'The one with water', 'Both the same', 'Neither'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_54', question: 'A plant kept in a dark cupboard will:', options: ['Grow normally', 'Become weak and yellow', 'Grow faster', 'Turn blue'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_55', question: 'We can record plant growth by:', options: ['Ignoring it', 'Measuring and drawing it', 'Destroying it', 'Hiding it'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_56', question: 'Which plant grows in water?', options: ['Cactus', 'Water lily', 'Desert rose', 'Pine tree'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_57', question: 'A bulb is:', options: ['A light', 'A type of seed storage', 'An animal', 'A color'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_58', question: 'What color are most leaves?', options: ['Red', 'Blue', 'Green', 'Purple'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_59', question: 'Plants give us:', options: ['Only problems', 'Oxygen, food, and materials', 'Nothing useful', 'Only toys'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // ANIMALS INCLUDING HUMANS (30 questions)
  // Animals
  { id: 'y2_sci_60', question: 'Which group does a frog belong to?', options: ['Mammals', 'Amphibians', 'Birds', 'Fish'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_61', question: 'Which animal is a mammal?', options: ['Snake', 'Butterfly', 'Dog', 'Goldfish'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_62', question: 'Birds have:', options: ['Fur', 'Feathers', 'Scales', 'Skin only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_63', question: 'Fish breathe using:', options: ['Lungs', 'Gills', 'Nose', 'Ears'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_64', question: 'Reptiles have:', options: ['Feathers', 'Fur', 'Scales', 'Nothing'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_65', question: 'Which is a reptile?', options: ['Cat', 'Lizard', 'Bird', 'Frog'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_66', question: 'Insects have ___ legs:', options: ['4', '6', '8', '10'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_67', question: 'Which is an insect?', options: ['Spider', 'Ant', 'Worm', 'Snail'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_68', question: 'What do animals need to survive?', options: ['Only toys', 'Food, water, air, and shelter', 'Only TV', 'Only games'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_69', question: 'A carnivore eats:', options: ['Only plants', 'Only meat', 'Both plants and meat', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_70', question: 'A herbivore eats:', options: ['Only plants', 'Only meat', 'Both', 'Nothing'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_71', question: 'An omnivore eats:', options: ['Only plants', 'Only meat', 'Both plants and meat', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_72', question: 'Which animal is a herbivore?', options: ['Lion', 'Rabbit', 'Shark', 'Eagle'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_73', question: 'Which animal is a carnivore?', options: ['Cow', 'Sheep', 'Lion', 'Horse'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_74', question: 'Animals that are active at night are:', options: ['Diurnal', 'Nocturnal', 'Sleeping', 'Dead'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },

  // Humans
  { id: 'y2_sci_75', question: 'What do humans need to stay healthy?', options: ['Only sweets', 'Good food, water, exercise, and sleep', 'Only TV', 'Only games'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_76', question: 'Exercise is important because:', options: ['It wastes time', 'It keeps us fit and healthy', 'It makes us tired only', 'It\'s not important'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_77', question: 'Eating vegetables and fruits is:', options: ['Bad for you', 'Good for you', 'Not needed', 'Only for animals'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_78', question: 'Why should we wash our hands?', options: ['To waste time', 'To remove germs and stay healthy', 'To get wet', 'Not important'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_79', question: 'Why do we need sleep?', options: ['To waste time', 'To rest and grow', 'It\'s not needed', 'Only for fun'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_80', question: 'Hygiene means:', options: ['Being dirty', 'Keeping clean and healthy', 'Playing games', 'Eating sweets'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_81', question: 'A balanced diet includes:', options: ['Only sweets', 'Only meat', 'Different types of healthy food', 'Only bread'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_82', question: 'Babies grow into:', options: ['Nothing', 'Children, then adults', 'Animals', 'Plants'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_83', question: 'As humans grow, they:', options: ['Get smaller', 'Get bigger and learn new things', 'Stay the same', 'Disappear'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_84', question: 'Why do we brush our teeth?', options: ['To waste time', 'To keep them clean and healthy', 'To make noise', 'Not important'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_85', question: 'How many senses do humans have?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_86', question: 'The five senses are:', options: ['All the same', 'Sight, hearing, touch, taste, smell', 'Only sight and hearing', 'Not real'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_87', question: 'Our skeleton:', options: ['Is not needed', 'Supports and protects our body', 'Only looks good', 'Makes us heavy'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_88', question: 'How many main food groups are there?', options: ['2', '3', '5', '10'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_89', question: 'Water is important because:', options: ['It\'s not important', 'Our bodies need it to work properly', 'Only for washing', 'Only for plants'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // MATERIALS (30 questions)
  // Uses of Materials
  { id: 'y2_sci_90', question: 'What is a window usually made from?', options: ['Wood', 'Glass', 'Fabric', 'Paper'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_91', question: 'Why is glass used for windows?', options: ['It\'s colorful', 'You can see through it', 'It\'s soft', 'It smells nice'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_92', question: 'What is a chair usually made from?', options: ['Water', 'Wood or plastic', 'Glass', 'Paper'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_93', question: 'A raincoat should be:', options: ['Soft', 'Waterproof', 'Transparent', 'Rough'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_94', question: 'What are clothes often made from?', options: ['Stone', 'Fabric', 'Glass', 'Metal'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_95', question: 'Pots and pans are often made of:', options: ['Paper', 'Metal', 'Fabric', 'Feathers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_96', question: 'Why is metal good for pots?', options: ['It\'s light', 'It conducts heat well', 'It\'s transparent', 'It floats'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_97', question: 'A book is made from:', options: ['Metal', 'Paper', 'Glass', 'Liquid'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // Properties of Materials
  { id: 'y2_sci_98', question: 'A hard material is:', options: ['Easy to scratch', 'Difficult to scratch or break', 'Always soft', 'Always wet'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_99', question: 'Which material is hard?', options: ['Cotton', 'Feather', 'Stone', 'Sponge'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_100', question: 'A soft material is:', options: ['Very hard', 'Easy to squash or bend', 'Always rough', 'Always cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_101', question: 'Which material is soft?', options: ['Stone', 'Metal', 'Cushion', 'Glass'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_102', question: 'Flexible means:', options: ['Cannot bend', 'Can bend easily', 'Very hard', 'Very hot'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_103', question: 'Which is flexible?', options: ['Stone', 'Rubber band', 'Brick', 'Glass'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_104', question: 'Waterproof means:', options: ['Absorbs water', 'Water cannot pass through', 'Always wet', 'Always dry'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_105', question: 'Which material is waterproof?', options: ['Sponge', 'Plastic', 'Paper towel', 'Fabric'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_106', question: 'Rough means:', options: ['Smooth to touch', 'Bumpy to touch', 'Wet', 'Cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_107', question: 'Which feels rough?', options: ['Silk', 'Sandpaper', 'Glass', 'Mirror'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_108', question: 'Smooth means:', options: ['Very bumpy', 'Even and flat to touch', 'Very hot', 'Very cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_109', question: 'Which feels smooth?', options: ['Tree bark', 'Gravel', 'Polished glass', 'Sandpaper'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_110', question: 'Transparent means:', options: ['Cannot see through', 'Can see through', 'Very hard', 'Very soft'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_111', question: 'Which is transparent?', options: ['Wood', 'Clear glass', 'Brick', 'Paper'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // Changing Materials
  { id: 'y2_sci_112', question: 'What happens when ice is heated?', options: ['It stays the same', 'It melts into water', 'It becomes harder', 'It disappears'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_113', question: 'What happens when water is frozen?', options: ['It becomes ice', 'It becomes steam', 'It stays liquid', 'It disappears'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_114', question: 'If we heat chocolate, it:', options: ['Gets harder', 'Melts', 'Stays the same', 'Grows'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_115', question: 'Bending a piece of paper is:', options: ['A permanent change', 'A reversible change', 'Impossible', 'Dangerous'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_116', question: 'Twisting a rubber band is:', options: ['A permanent change', 'A reversible change', 'Impossible', 'Breaking it'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_117', question: 'Burning wood is:', options: ['Reversible', 'Irreversible', 'Not a change', 'Easy to undo'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_118', question: 'Stretching a spring is usually:', options: ['Permanent', 'Reversible', 'Impossible', 'Dangerous'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_119', question: 'If water is heated a lot, it becomes:', options: ['Ice', 'Steam', 'Solid', 'Disappears completely'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },

  // EARTH & ENVIRONMENT (15 questions)
  { id: 'y2_sci_120', question: 'Why should we care for the environment?', options: ['It\'s not important', 'To keep Earth healthy for all living things', 'Only for fun', 'To waste time'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_121', question: 'Recycling means:', options: ['Throwing everything away', 'Using materials again', 'Burning waste', 'Hiding rubbish'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_122', question: 'Which can be recycled?', options: ['Food waste', 'Paper and plastic', 'Dirt', 'Water only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_123', question: 'Pollution is:', options: ['Good for Earth', 'Harmful to the environment', 'Natural', 'Not real'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_124', question: 'Littering is:', options: ['Good', 'Bad for the environment', 'Helpful', 'Natural'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_125', question: 'We should put rubbish:', options: ['On the ground', 'In the bin', 'In rivers', 'Anywhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_126', question: 'Reusing means:', options: ['Throwing away', 'Using something again', 'Burning it', 'Hiding it'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_127', question: 'Which helps the environment?', options: ['Littering', 'Wasting water', 'Planting trees', 'Polluting'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_128', question: 'Trees are important because they:', options: ['Look pretty only', 'Give us oxygen and homes for animals', 'Make noise', 'Are not useful'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_129', question: 'Saving water is:', options: ['Not important', 'Important for the environment', 'Impossible', 'Only for adults'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_130', question: 'An example of pollution is:', options: ['Clean air', 'Smoke from factories', 'Fresh water', 'Clean soil'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_131', question: 'Which is good for the environment?', options: ['Using lots of plastic bags', 'Using reusable bags', 'Wasting food', 'Littering'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_132', question: 'Composting is:', options: ['Throwing food away', 'Turning food waste into soil', 'Burning waste', 'Hiding waste'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_133', question: 'Why should we turn off lights when not needed?', options: ['No reason', 'To save energy', 'To be in the dark', 'To break them'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_134', question: 'Clean air is important for:', options: ['Nothing', 'All living things to breathe', 'Only plants', 'Only water'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // SEASONS & WEATHER (20 questions)
  { id: 'y2_sci_135', question: 'How many seasons are there?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_136', question: 'The four seasons are:', options: ['Hot, cold, wet, dry', 'Spring, summer, autumn, winter', 'Day, night, morning, evening', 'None of these'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_137', question: 'Which season is usually the coldest?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], correctAnswer: 3, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_138', question: 'Which season is usually the warmest?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_139', question: 'In spring:', options: ['Everything dies', 'Flowers bloom and baby animals are born', 'It snows a lot', 'Nothing happens'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_140', question: 'In autumn:', options: ['Leaves fall from trees', 'Everything grows', 'It\'s very hot', 'Nothing changes'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_141', question: 'In winter:', options: ['It\'s very hot', 'Days are shorter and it may snow', 'Flowers bloom', 'Trees grow'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_142', question: 'In summer:', options: ['It\'s cold', 'Days are longer and warmer', 'Trees lose leaves', 'It always snows'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_143', question: 'What weather symbol shows rain?', options: ['Sun', 'Cloud with raindrops', 'Snowflake', 'Lightning'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_144', question: 'What weather symbol shows sunshine?', options: ['Cloud', 'Sun', 'Raindrop', 'Wind lines'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_145', question: 'Which weather is good for flying a kite?', options: ['No wind', 'Windy', 'Rainy', 'Snowy'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_146', question: 'A thermometer measures:', options: ['Wind', 'Temperature', 'Rain', 'Time'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_147', question: 'Snow falls when:', options: ['It\'s very hot', 'It\'s very cold', 'It\'s very windy', 'It\'s very dry'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_148', question: 'Clouds are made of:', options: ['Cotton', 'Tiny water droplets', 'Smoke', 'Paper'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_149', question: 'Which season comes after winter?', options: ['Summer', 'Spring', 'Autumn', 'Winter again'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_150', question: 'Recording daily weather helps us:', options: ['Waste time', 'See patterns over time', 'Nothing', 'Get confused'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_151', question: 'Thunder and lightning happen during:', options: ['Sunny weather', 'A storm', 'Snow', 'Clear sky'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_152', question: 'Fog is:', options: ['Very clear', 'A thick cloud near the ground', 'Very hot', 'Very loud'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_153', question: 'Wind is:', options: ['Still air', 'Moving air', 'Water', 'Fire'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_154', question: 'A rainbow appears after:', options: ['Snow', 'Rain with sunshine', 'Fog', 'Night'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // LIGHT & SHADOWS (15 questions)
  { id: 'y2_sci_155', question: 'Which is a source of light?', options: ['Moon', 'Sun', 'Rock', 'Book'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_156', question: 'Light helps us:', options: ['Sleep', 'See things', 'Hear things', 'Smell things'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_157', question: 'When there is no light, it is:', options: ['Bright', 'Dark', 'Colorful', 'Loud'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_158', question: 'A shadow is made when:', options: ['Light passes through', 'An object blocks light', 'It rains', 'It\'s windy'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_159', question: 'Shadows are darkest when the light is:', options: ['Dim', 'Very bright', 'Gone', 'Colorful'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_160', question: 'Which makes light?', options: ['Stone', 'Lamp', 'Paper', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_161', question: 'The moon:', options: ['Makes its own light', 'Reflects light from the sun', 'Never has light', 'Is always dark'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_162', question: 'We should not look directly at:', options: ['Books', 'The sun', 'Shadows', 'Clouds'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_163', question: 'If you stand in front of a light, your shadow is:', options: ['In front of you', 'Behind you', 'Beside you', 'Above you'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_164', question: 'During the day, we get light from:', options: ['Stars', 'The sun', 'Moon', 'Fire only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_165', question: 'A torch is:', options: ['Not a light source', 'An artificial light source', 'Natural light', 'Not real'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_166', question: 'Natural light sources include:', options: ['Lamps', 'The sun and stars', 'Torches', 'Light bulbs'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_167', question: 'Artificial light sources include:', options: ['Sun', 'Stars', 'Lamps and bulbs', 'Moon'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_168', question: 'Your shadow is longest when the sun is:', options: ['High in the sky', 'Low in the sky', 'Behind clouds', 'Not there'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_sci_169', question: 'We need light to:', options: ['Sleep', 'See colors and shapes', 'Hear sounds', 'Taste food'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // SOUND (15 questions)
  { id: 'y2_sci_170', question: 'Sound is made by:', options: ['Light', 'Vibrations', 'Color', 'Smell'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_171', question: 'Which makes a loud sound?', options: ['Whisper', 'Drum', 'Feather dropping', 'Silence'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_172', question: 'Which makes a quiet sound?', options: ['Thunder', 'Jet plane', 'Whisper', 'Fireworks'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_173', question: 'We hear sounds with our:', options: ['Eyes', 'Ears', 'Nose', 'Hands'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_174', question: 'Which animal makes a "woof" sound?', options: ['Cat', 'Dog', 'Cow', 'Bird'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_175', question: 'A musical instrument makes:', options: ['Light', 'Sound', 'Smell', 'Taste'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_176', question: 'Banging a drum makes it:', options: ['Glow', 'Vibrate and make sound', 'Disappear', 'Melt'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_177', question: 'Which is a source of sound?', options: ['A rock sitting still', 'A ringing bell', 'A picture', 'Silence'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_178', question: 'Sounds can be:', options: ['Only loud', 'Only quiet', 'Loud, quiet, high, or low', 'Only one type'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_179', question: 'A high sound is like:', options: ['A drum', 'A whistle', 'Thunder', 'A bass guitar'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_180', question: 'A low sound is like:', options: ['A whistle', 'A squeaky toy', 'A drum', 'A bird chirping'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_181', question: 'We use our sense of hearing to:', options: ['See things', 'Detect sounds', 'Taste food', 'Smell flowers'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_182', question: 'Sounds travel through:', options: ['Nothing', 'Air and other materials', 'Only vacuum', 'Only space'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_sci_183', question: 'To make a guitar string sound, you:', options: ['Look at it', 'Pluck or strum it', 'Smell it', 'Ignore it'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_184', question: 'Silence means:', options: ['Very loud', 'No sound', 'Music', 'Talking'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // SCIENTIFIC VOCABULARY & REASONING (16 questions)
  { id: 'y2_sci_185', question: 'A "habitat" is:', options: ['A type of food', 'Where something lives', 'A sound', 'A color'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_186', question: 'A "material" is:', options: ['What something is made from', 'A type of animal', 'A season', 'A sound'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_187', question: '"Observe" means:', options: ['To ignore', 'To look carefully', 'To break', 'To hide'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_188', question: 'A "carnivore" eats:', options: ['Plants', 'Meat', 'Nothing', 'Rocks'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_189', question: 'A "herbivore" eats:', options: ['Meat', 'Plants', 'Nothing', 'Rocks'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_190', question: 'If we see a pattern, it means:', options: ['Everything is random', 'Something repeats or is similar', 'Nothing makes sense', 'We\'re wrong'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_191', question: 'Comparing means:', options: ['Ignoring differences', 'Looking at similarities and differences', 'Breaking things', 'Hiding things'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_192', question: 'An "investigation" is:', options: ['A game', 'A test to find out something', 'A story', 'A picture'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_193', question: 'If something is "waterproof", it:', options: ['Absorbs water', 'Keeps water out', 'Loves water', 'Is water'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_194', question: 'A "source" of light is:', options: ['Something that blocks light', 'Something that makes light', 'Darkness', 'A shadow'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_195', question: '"Temperature" tells us:', options: ['How loud something is', 'How hot or cold something is', 'How big something is', 'How old something is'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_196', question: '"Flexible" means:', options: ['Very hard', 'Can bend', 'Cannot move', 'Very cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_197', question: 'A "season" is:', options: ['A type of food', 'A time of year with certain weather', 'A game', 'An animal'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_198', question: 'When we "predict", we:', options: ['Look back at the past', 'Guess what might happen', 'Give up', 'Ignore everything'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_sci_199', question: '"Germination" is when:', options: ['A plant dies', 'A seed starts to grow', 'An animal sleeps', 'Water freezes'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_sci_200', question: 'An "experiment" helps us:', options: ['Break things', 'Test ideas and learn', 'Sleep', 'Watch TV'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 }
];
