// Year 10 Mathematics Trivia Questions
// Based on UK Year 10 Maths Curriculum Framework (GCSE Foundation & Higher)
// 200 comprehensive questions covering all GCSE topics

export const YEAR_10_MATHS_QUESTIONS = [
  // ALGEBRA (50 questions)
  { id: 'y10_math_1', question: 'Solve: 3x + 7 = 22', options: ['x = 3', 'x = 4', 'x = 5', 'x = 6'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_2', question: 'Solve: 5(x - 3) = 25', options: ['x = 5', 'x = 6', 'x = 7', 'x = 8'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_3', question: 'Solve: 2x + 5 = x + 12', options: ['x = 5', 'x = 6', 'x = 7', 'x = 8'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_4', question: 'Solve: x² = 49', options: ['x = 7', 'x = ±7', 'x = 49', 'x = 24.5'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_5', question: 'Solve: x² - 9 = 0', options: ['x = 3', 'x = ±3', 'x = 9', 'x = -3'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_6', question: 'Factorise: x² + 7x + 12', options: ['(x+3)(x+4)', '(x+2)(x+6)', '(x+1)(x+12)', '(x+3)(x+3)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_7', question: 'Factorise: x² - 5x + 6', options: ['(x-2)(x-3)', '(x-1)(x-6)', '(x+2)(x+3)', '(x-2)(x+3)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_8', question: 'Factorise: x² + 3x - 10', options: ['(x+5)(x-2)', '(x-5)(x+2)', '(x+10)(x-1)', '(x-10)(x+1)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_9', question: 'Factorise: x² - 16', options: ['(x-4)(x-4)', '(x+4)(x+4)', '(x+4)(x-4)', 'Cannot factorise'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_10', question: 'Expand: (x + 5)²', options: ['x² + 25', 'x² + 10x + 25', 'x² + 5x + 25', 'x² + 10x + 10'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_11', question: 'Expand: (x - 3)²', options: ['x² - 9', 'x² - 6x + 9', 'x² + 6x + 9', 'x² - 3x + 9'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_12', question: 'Expand: (2x + 3)(x - 4)', options: ['2x² - 5x - 12', '2x² + 5x - 12', '2x² - 8x - 12', '2x² - 5x + 12'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_13', question: 'Solve using quadratic formula: x² + 5x + 6 = 0', options: ['x = -2 or -3', 'x = 2 or 3', 'x = -1 or -6', 'x = 1 or 6'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_14', question: 'Solve: x² + 4x - 5 = 0', options: ['x = 1 or -5', 'x = -1 or 5', 'x = 1 or 5', 'x = -1 or -5'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_15', question: 'Solve: 2x² = 18', options: ['x = 3', 'x = ±3', 'x = 9', 'x = ±9'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_16', question: 'Solve inequality: 3x > 15', options: ['x > 5', 'x > 12', 'x > 18', 'x > 45'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_17', question: 'Solve inequality: 2x - 5 ≤ 11', options: ['x ≤ 3', 'x ≤ 8', 'x ≤ 16', 'x ≤ 6'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_18', question: 'Solve inequality: -2x < 10', options: ['x < -5', 'x > -5', 'x < 5', 'x > 5'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_19', question: 'Simplify: 3x² × 4x³', options: ['7x⁵', '12x⁵', '12x⁶', '7x⁶'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_20', question: 'Simplify: 15x⁵ ÷ 3x²', options: ['5x³', '5x⁷', '12x³', '18x³'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_21', question: 'Simplify: (2x³)⁴', options: ['8x⁷', '2x¹²', '16x¹²', '8x¹²'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_22', question: 'Make x the subject: y = 3x + 5', options: ['x = (y - 5)/3', 'x = (y + 5)/3', 'x = 3y - 5', 'x = y/3 - 5'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_23', question: 'Make x the subject: y = 2x - 7', options: ['x = (y - 7)/2', 'x = (y + 7)/2', 'x = 2y + 7', 'x = y/2 + 7'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_24', question: 'Make x the subject: y = x/4 + 3', options: ['x = 4y - 3', 'x = 4(y - 3)', 'x = 4y + 3', 'x = (y - 3)/4'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_25', question: 'Solve simultaneous: x + y = 10, x - y = 4. Find x:', options: ['x = 5', 'x = 6', 'x = 7', 'x = 8'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_26', question: 'Solve simultaneous: 2x + y = 14, x + y = 8. Find x:', options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_27', question: 'Solve simultaneous: 3x + 2y = 16, x + 2y = 8. Find x:', options: ['x = 2', 'x = 3', 'x = 4', 'x = 5'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_28', question: 'What is the nth term of: 5, 8, 11, 14...?', options: ['3n + 2', 'n + 5', '3n + 5', '5n'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_29', question: 'What is the nth term of: 7, 12, 17, 22...?', options: ['5n + 2', 'n + 7', '5n + 7', '7n'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_30', question: 'Find 50th term of: 4n + 3', options: ['203', '200', '197', '206'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_31', question: 'Simplify: √50', options: ['5√2', '2√5', '25', '10'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_32', question: 'Simplify: √72', options: ['6√2', '2√6', '8√9', '36'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_33', question: 'Simplify: √12 + √27', options: ['√39', '5√3', '3√5', '6√3'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_34', question: 'Expand and simplify: (x + 3)(x + 5)', options: ['x² + 8x + 15', 'x² + 15', 'x² + 8x + 8', '2x + 8'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_35', question: 'Expand: (2x - 1)(3x + 4)', options: ['6x² + 5x - 4', '6x² - 5x - 4', '5x² + 5x - 4', '6x² + 8x - 4'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_36', question: 'Factorise completely: 6x² + 9x', options: ['3x(2x + 3)', '3(2x² + 3x)', 'x(6x + 9)', '6x(x + 9)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_37', question: 'Factorise: 4x² - 25', options: ['(2x - 5)(2x + 5)', '(4x - 5)(x + 5)', '(2x - 5)²', 'Cannot factorise'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_38', question: 'Solve: (x + 2)(x - 5) = 0', options: ['x = -2 or 5', 'x = 2 or -5', 'x = -2 or -5', 'x = 2 or 5'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_39', question: 'Which graph represents y = x²?', options: ['Straight line', 'U-shaped curve (parabola)', 'Circle', 'Exponential curve'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_40', question: 'What is the turning point of y = x² - 4?', options: ['(0, -4)', '(0, 4)', '(-4, 0)', '(4, 0)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_41', question: 'Evaluate 2⁻³:', options: ['-6', '-8', '1/6', '1/8'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_42', question: 'Evaluate 3⁰:', options: ['0', '1', '3', 'Undefined'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_43', question: 'Simplify: a⁴ × a³', options: ['a⁷', 'a¹²', 'a', '2a⁷'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_44', question: 'Simplify: b⁸ ÷ b³', options: ['b⁵', 'b¹¹', 'b²⁴', 'b'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_45', question: 'Simplify: (c²)⁵', options: ['c⁷', 'c¹⁰', 'c³', '2c⁵'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_46', question: 'Write in standard form: 45,000', options: ['4.5 × 10³', '4.5 × 10⁴', '45 × 10³', '0.45 × 10⁵'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_47', question: 'Write in standard form: 0.0072', options: ['7.2 × 10⁻³', '7.2 × 10⁻²', '72 × 10⁻⁴', '0.72 × 10⁻²'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_48', question: 'Calculate: (2 × 10³) × (3 × 10⁴)', options: ['5 × 10⁷', '6 × 10⁷', '6 × 10¹²', '5 × 10¹²'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_49', question: 'Gradient of y = 4x - 7:', options: ['-7', '4', '4x', '11'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_50', question: 'Y-intercept of y = 3x + 8:', options: ['3', '8', '11', 'x'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // GEOMETRY & TRIGONOMETRY (60 questions)
  { id: 'y10_math_51', question: 'Pythagoras theorem: a² + b² = ___', options: ['c', 'c²', '2c', 'c³'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_52', question: 'If a = 3 and b = 4, find c using Pythagoras:', options: ['5', '7', '25', '12'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_53', question: 'If a = 5 and b = 12, find c:', options: ['13', '17', '60', '169'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_54', question: 'Is a triangle with sides 8, 15, 17 right-angled?', options: ['Yes', 'No', 'Cannot tell', 'Only if acute'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_55', question: 'SOH CAH TOA: Sin θ = Opposite / ___', options: ['Adjacent', 'Hypotenuse', 'Base', 'Height'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_56', question: 'Cos θ = ___ / Hypotenuse', options: ['Opposite', 'Adjacent', 'Sine', 'Tangent'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_57', question: 'Tan θ = Opposite / ___', options: ['Hypotenuse', 'Adjacent', 'Sine', 'Cosine'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_58', question: 'Sin 30° = ?', options: ['0', '0.5', '0.707', '0.866'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_59', question: 'Cos 60° = ?', options: ['0', '0.5', '0.707', '0.866'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_60', question: 'Tan 45° = ?', options: ['0', '0.5', '1', '√3'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_61', question: 'Sin 90° = ?', options: ['0', '0.5', '0.866', '1'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_62', question: 'Cos 0° = ?', options: ['0', '0.5', '1', 'Undefined'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_63', question: 'Area of triangle = ½ × base × ___', options: ['Width', 'Height', 'Hypotenuse', 'Perimeter'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_64', question: 'Area of triangle: base = 8cm, height = 5cm', options: ['13 cm²', '20 cm²', '40 cm²', '80 cm²'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_65', question: 'Area of circle = πr². If r = 7cm, area ≈ (π ≈ 3.14)?', options: ['44 cm²', '154 cm²', '22 cm²', '308 cm²'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_66', question: 'Circumference = 2πr. If r = 10cm, circumference ≈ (π ≈ 3.14)?', options: ['31.4 cm', '62.8 cm', '314 cm', '20 cm'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_67', question: 'Area of trapezium = ½(a + b)h. If a=6, b=10, h=4:', options: ['32', '64', '16', '80'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_68', question: 'Volume of cuboid = length × width × height. If 5×4×3:', options: ['12', '60', '120', '20'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_69', question: 'Volume of cylinder = πr²h. If r=3, h=10 (π≈3.14):', options: ['94.2', '282.6', '188.4', '376.8'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_70', question: 'Volume of prism = cross-sectional area × length. If area=20, length=8:', options: ['28', '160', '100', '2.5'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_71', question: 'Sum of interior angles of triangle:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_72', question: 'Sum of interior angles of quadrilateral:', options: ['180°', '270°', '360°', '540°'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_73', question: 'Sum of interior angles of pentagon:', options: ['360°', '450°', '540°', '720°'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_74', question: 'Sum of interior angles formula: (n-2) × 180°. For hexagon (n=6):', options: ['540°', '720°', '900°', '1080°'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_75', question: 'Each interior angle of regular hexagon:', options: ['90°', '108°', '120°', '135°'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_76', question: 'Sum of exterior angles of ANY polygon:', options: ['180°', '270°', '360°', 'Varies'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_77', question: 'Each exterior angle of regular octagon:', options: ['36°', '40°', '45°', '60°'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_78', question: 'Angle at center is ___ angle at circumference (same arc):', options: ['Half', 'Equal to', 'Twice', 'Three times'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_79', question: 'Angle in semicircle:', options: ['45°', '60°', '90°', '180°'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_80', question: 'Opposite angles in cyclic quadrilateral sum to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_81', question: 'Tangent to circle is ___ to radius:', options: ['Parallel', 'Perpendicular', 'Equal', 'Similar'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_82', question: 'Two tangents from external point are:', options: ['Different lengths', 'Equal length', 'Parallel', 'Perpendicular'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_83', question: 'Arc length = (θ/360) × 2πr. If θ=90°, r=8 (π≈3.14):', options: ['12.56', '25.12', '50.24', '6.28'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_84', question: 'Sector area = (θ/360) × πr². If θ=120°, r=6 (π≈3.14):', options: ['18.84', '37.68', '56.52', '113.04'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_85', question: 'Enlarge by scale factor 3. Side 4cm becomes:', options: ['7cm', '12cm', '1.33cm', '9cm'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_86', question: 'Scale factor 2. Area 10cm² becomes:', options: ['12cm²', '20cm²', '40cm²', '100cm²'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_87', question: 'Scale factor 3. Volume 5cm³ becomes:', options: ['8cm³', '15cm³', '45cm³', '135cm³'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_88', question: 'Reflect point (3, 5) in x-axis:', options: ['(3, -5)', '(-3, 5)', '(-3, -5)', '(5, 3)'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_89', question: 'Reflect point (4, -2) in y-axis:', options: ['(-4, -2)', '(4, 2)', '(-4, 2)', '(2, -4)'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_90', question: 'Translate (2, 3) by vector (5, -1):', options: ['(7, 2)', '(-3, 4)', '(7, 4)', '(2, 2)'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_91', question: 'Rotate (5, 0) 90° clockwise about origin:', options: ['(0, -5)', '(0, 5)', '(-5, 0)', '(5, 0)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_92', question: 'Surface area of cube with side 5cm:', options: ['25 cm²', '75 cm²', '125 cm²', '150 cm²'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_93', question: 'Volume of sphere = (4/3)πr³. If r=3 (π≈3.14):', options: ['28.26', '56.52', '113.04', '226.08'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_94', question: 'Surface area of sphere = 4πr². If r=5 (π≈3.14):', options: ['78.5', '157', '314', '523.3'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_95', question: 'Volume of cone = (1/3)πr²h. If r=3, h=4 (π≈3.14):', options: ['12.56', '25.12', '37.68', '75.36'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_96', question: 'Gradient formula: (y₂-y₁)/(x₂-x₁). Points (1,2) and (5,10):', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_97', question: 'Distance formula: √[(x₂-x₁)²+(y₂-y₁)²]. Distance (0,0) to (3,4):', options: ['3', '4', '5', '7'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_98', question: 'Midpoint of (2,4) and (8,10):', options: ['(5,7)', '(4,6)', '(6,8)', '(10,14)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_99', question: 'Parallel lines have ___ gradient:', options: ['Different', 'Same', 'Negative reciprocal', 'Zero'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_100', question: 'Perpendicular lines: m₁ × m₂ = ___', options: ['0', '1', '-1', '2'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_101', question: 'Line parallel to y = 3x + 2 has gradient:', options: ['2', '3', '-3', '1/3'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_102', question: 'Line perpendicular to y = 2x + 1 has gradient:', options: ['2', '-2', '1/2', '-1/2'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_103', question: 'Bearing from A to B is 135°. Bearing from B to A?', options: ['225°', '315°', '045°', '180°'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_104', question: 'Congruent shapes have:', options: ['Same shape only', 'Same size only', 'Same shape and size', 'Different shape'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_105', question: 'Similar shapes have:', options: ['Same shape, different size', 'Same size, different shape', 'Same shape and size', 'No relation'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_106', question: 'Vectors: (3,4) + (2,-1) = ?', options: ['(5,3)', '(1,5)', '(5,5)', '(6,-4)'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_107', question: 'Scalar multiplication: 3(2,5) = ?', options: ['(5,8)', '(6,15)', '(6,8)', '(3,10)'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_108', question: 'Magnitude of vector (3,4):', options: ['3', '4', '5', '7'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_109', question: 'Surface area of cylinder = 2πr² + 2πrh. If r=3, h=5 (π≈3.14):', options: ['94.2', '150.72', '282.6', '188.4'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_110', question: 'Sine rule: a/sinA = b/sinB = ___', options: ['c/sinC', 'c×sinC', 'sinC/c', 'c'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },

  // RATIO, PROPORTION & PERCENTAGES (40 questions)
  { id: 'y10_math_111', question: 'Simplify ratio 45:60', options: ['3:4', '9:12', '15:20', '1:2'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_112', question: 'Share ₦450 in ratio 2:3:4. Largest share?', options: ['₦100', '₦150', '₦200', '₦250'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_113', question: 'Divide ₦1,200 in ratio 3:5. Smaller share?', options: ['₦300', '₦400', '₦450', '₦500'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_114', question: 'If a:b = 2:3 and b:c = 4:5, find a:b:c:', options: ['2:3:5', '8:12:15', '2:4:5', '8:12:20'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_115', question: 'Direct proportion: y ∝ x. If y=12 when x=3, find y when x=7:', options: ['21', '24', '28', '36'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_116', question: 'Inverse proportion: y ∝ 1/x. If y=8 when x=3, find y when x=6:', options: ['2', '4', '12', '16'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_117', question: 'Increase ₦800 by 25%:', options: ['₦200', '₦825', '₦1,000', '₦1,025'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_118', question: 'Decrease ₦1,500 by 40%:', options: ['₦600', '₦900', '₦1,100', '₦1,460'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_119', question: 'What is 35% of ₦2,400?', options: ['₦720', '₦800', '₦840', '₦900'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_120', question: 'Express 3/8 as percentage:', options: ['33.3%', '37.5%', '38%', '40%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_121', question: 'What percentage is 72 out of 200?', options: ['30%', '32%', '36%', '40%'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_122', question: 'Percentage change: from 80 to 100', options: ['20%', '25%', '30%', '80%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_123', question: 'Percentage decrease: from 200 to 150', options: ['20%', '25%', '30%', '50%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_124', question: 'Reverse percentage: After 20% increase, price is ₦960. Original?', options: ['₦768', '₦800', '₦1,152', '₦1,200'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_125', question: 'Reverse percentage: After 30% decrease, price is ₦490. Original?', options: ['₦637', '₦700', '₦343', '₦637'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_126', question: 'Simple interest: P=₦5,000, R=8%, T=3 years. Interest?', options: ['₦1,200', '₦1,500', '₦2,000', '₦400'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_127', question: 'Compound interest formula: A = P(1 + r/100)ⁿ. P=₦1,000, r=10%, n=2:', options: ['₦1,100', '₦1,200', '₦1,210', '₦1,300'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_128', question: 'Best value: 500g for ₦400 or 750g for ₦570?', options: ['500g', '750g', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_129', question: 'Unit price: ₦720 for 12 items. Price per item?', options: ['₦60', '₦70', '₦72', '₦80'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_130', question: 'Profit = Selling price - Cost. Cost ₦600, sell ₦900. Profit?', options: ['₦200', '₦300', '₦400', '₦1,500'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_131', question: 'Profit % = (Profit/Cost) × 100. Cost ₦500, profit ₦150:', options: ['20%', '25%', '30%', '35%'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_132', question: 'Loss % = (Loss/Cost) × 100. Cost ₦800, sell ₦600:', options: ['20%', '25%', '30%', '33.3%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_133', question: 'Speed = Distance ÷ Time. Distance 240km, time 3 hours:', options: ['60 km/h', '70 km/h', '80 km/h', '90 km/h'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_134', question: 'Distance = Speed × Time. Speed 75 km/h, time 4 hours:', options: ['150 km', '200 km', '300 km', '400 km'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_135', question: 'Time = Distance ÷ Speed. Distance 420km, speed 70 km/h:', options: ['4 hours', '5 hours', '6 hours', '7 hours'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_136', question: 'Density = Mass ÷ Volume. Mass 800g, volume 100cm³:', options: ['4 g/cm³', '6 g/cm³', '8 g/cm³', '10 g/cm³'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_137', question: 'Convert 12 m/s to km/h:', options: ['12 km/h', '20 km/h', '43.2 km/h', '720 km/h'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_138', question: 'Map scale 1:50,000. 12cm represents?', options: ['6 km', '60 km', '600 m', '6,000 m'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_139', question: 'Currency: £1 = ₦950. Convert £80 to Naira:', options: ['₦11.88', '₦950', '₦76,000', '₦1,030'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_140', question: 'Currency: $1 = ₦850. Convert ₦17,000 to dollars:', options: ['$5', '$10', '$20', '$50'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_141', question: 'Compound % change: Increase 10% then increase 20%. Overall?', options: ['30%', '32%', '28%', '26%'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_142', question: 'Compound % change: Increase 50% then decrease 50%. Overall?', options: ['0%', '25% decrease', '25% increase', '50% decrease'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_143', question: 'Growth/Decay: N = N₀(1.05)ᵗ. N₀=100, t=2:', options: ['105', '110', '110.25', '120'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_144', question: 'Recipe for 6 people: 300g flour. For 15 people?', options: ['500g', '600g', '750g', '900g'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_145', question: '8 workers complete job in 12 days. How long for 6 workers?', options: ['9 days', '12 days', '16 days', '18 days'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_146', question: 'Petrol costs ₦600/L. How much for 35L?', options: ['₦17.14', '₦21,000', '₦635', '₦565'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_147', question: 'VAT at 15% on item costing ₦2,000. Total price?', options: ['₦2,015', '₦2,150', '₦2,300', '₦2,500'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_148', question: 'Discount 20% on ₦3,500. Final price?', options: ['₦2,800', '₦3,000', '₦3,400', '₦3,480'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_149', question: 'Area enlarges by scale factor 4. Original 25cm². New area?', options: ['29cm²', '100cm²', '400cm²', '1600cm²'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_150', question: 'Volume enlarges by scale factor 2. Original 50cm³. New volume?', options: ['100cm³', '200cm³', '400cm³', '800cm³'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },

  // STATISTICS & PROBABILITY (50 questions)
  { id: 'y10_math_151', question: 'Mean of 8, 12, 15, 20, 25:', options: ['12', '15', '16', '20'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_152', question: 'Median of 3, 7, 9, 12, 15, 18, 21:', options: ['9', '12', '15', '18'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_153', question: 'Mode of 5, 7, 7, 9, 9, 9, 11, 13:', options: ['5', '7', '9', '11'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_154', question: 'Range of 12, 18, 25, 32, 45:', options: ['12', '25', '33', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_155', question: 'Interquartile range (IQR) = Q3 - ___:', options: ['Q1', 'Q2', 'Median', 'Mean'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_156', question: 'For data: 5, 8, 10, 12, 15, 18, 20. Q2 (median) is:', options: ['10', '12', '13.5', '15'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_157', question: 'Which average is best with outliers?', options: ['Mean', 'Median', 'Mode', 'Range'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_158', question: 'Standard deviation measures:', options: ['Central value', 'Spread/dispersion', 'Highest value', 'Most common value'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_159', question: 'Probability scale goes from ___ to ___:', options: ['-1 to 1', '0 to 1', '0 to 100', '0 to ∞'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_160', question: 'P(certain event) = ?', options: ['0', '0.5', '1', 'Undefined'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_161', question: 'P(impossible event) = ?', options: ['0', '0.5', '1', '-1'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_162', question: 'P(A) + P(not A) = ?', options: ['0', '0.5', '1', '2'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_163', question: 'If P(A) = 0.3, then P(not A) = ?', options: ['0.3', '0.7', '1', '0'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_164', question: 'Two dice: P(sum = 7) = ?', options: ['1/12', '1/6', '1/9', '1/36'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_165', question: 'One die: P(even number) = ?', options: ['1/6', '1/3', '1/2', '2/3'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_166', question: 'Bag: 5 red, 3 blue, 2 green. P(blue) = ?', options: ['3/10', '3/5', '3/8', '1/3'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_167', question: 'Expected frequency = probability × trials. P=0.25, trials=80:', options: ['10', '20', '30', '40'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_168', question: 'Relative frequency = outcomes ÷ trials. 45 out of 150:', options: ['0.2', '0.3', '0.4', '0.5'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_169', question: 'Independent events: P(A and B) = P(A) × ___:', options: ['P(A)', 'P(B)', 'P(A or B)', '1'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_170', question: 'P(A) = 0.4, P(B) = 0.5 (independent). P(A and B) = ?', options: ['0.1', '0.2', '0.9', '0.45'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_171', question: 'Mutually exclusive events: P(A or B) = P(A) + ___:', options: ['P(B)', 'P(A and B)', 'P(not B)', '0'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_172', question: 'P(A) = 0.3, P(B) = 0.4 (mutually exclusive). P(A or B) = ?', options: ['0.1', '0.7', '0.12', '1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_173', question: 'Cumulative frequency shows:', options: ['Individual frequencies', 'Running total of frequencies', 'Probability', 'Mean'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_174', question: 'On cumulative frequency graph, median at:', options: ['Highest point', 'n/2', 'Q1', 'Q3'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_175', question: 'Histogram: frequency shown by bar ___:', options: ['Height', 'Area', 'Width', 'Position'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_176', question: 'Frequency density = frequency ÷ ___:', options: ['Total', 'Class width', 'Mean', 'Median'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_177', question: 'Box plot shows:', options: ['Only mean', 'Five-number summary', 'Only mode', 'Only range'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_178', question: 'Five-number summary includes:', options: ['Mean only', 'Min, Q1, median, Q3, max', 'Mode only', 'Range only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_179', question: 'Positive correlation means:', options: ['As x increases, y decreases', 'As x increases, y increases', 'No relationship', 'x and y equal'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_180', question: 'Negative correlation means:', options: ['As x increases, y increases', 'As x increases, y decreases', 'No relationship', 'Perfect relationship'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_181', question: 'No correlation means:', options: ['Strong relationship', 'Weak relationship', 'No clear relationship', 'Perfect relationship'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_182', question: 'Line of best fit should have:', options: ['All points on it', 'Roughly equal points either side', 'More points above', 'More points below'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_183', question: 'Stratified sampling ensures:', options: ['Random selection only', 'Proportional representation of groups', 'Large sample', 'Quick sampling'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_184', question: 'Sample of 100 from population: 60% female, 40% male. Stratified sample:', options: ['50 female, 50 male', '60 female, 40 male', '70 female, 30 male', 'All female'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_185', question: 'Biased sample:', options: ['Represents population fairly', 'Does not represent population fairly', 'Is very large', 'Is random'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_186', question: 'Time series graph shows:', options: ['Correlation', 'Data over time', 'Probability', 'Frequency'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_187', question: 'Moving average smooths out:', options: ['Errors', 'Fluctuations to show trend', 'Mean', 'Mode'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_188', question: 'Two-way table shows frequencies for:', options: ['One variable', 'Two variables', 'Three variables', 'No variables'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_189', question: 'Tree diagram shows:', options: ['One event', 'Sequential probabilities', 'Correlation', 'Frequency'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_190', question: 'Venn diagram shows:', options: ['Time series', 'Set relationships', 'Correlation', 'Mean'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_191', question: 'In Venn diagram, n(A ∪ B) represents:', options: ['Elements in A only', 'Elements in B only', 'Elements in A or B', 'Elements in neither'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_192', question: 'In Venn diagram, n(A ∩ B) represents:', options: ['Elements in A only', 'Elements in A and B', 'Elements in A or B', 'Elements in neither'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_193', question: 'Conditional probability P(A|B) means:', options: ['P(A and B)', 'P(A) given B has occurred', 'P(A or B)', 'P(not A)'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_194', question: 'For grouped data, estimate of mean uses:', options: ['Actual values', 'Midpoints of groups', 'Frequencies only', 'Mode'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_195', question: 'Which gives most accurate picture of data?', options: ['Mean only', 'Mean and range', 'Mean and standard deviation', 'Mode only'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_math_196', question: 'Outlier is a value that:', options: ['Is typical', 'Is significantly different from others', 'Is the mode', 'Is the mean'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_197', question: 'Sampling method where every nth person selected:', options: ['Random', 'Systematic', 'Stratified', 'Quota'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_198', question: 'Which is NOT a sampling method?', options: ['Random', 'Systematic', 'Biased', 'Stratified'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_math_199', question: 'Comparing data sets, consider:', options: ['Average only', 'Average and spread', 'Spread only', 'Neither'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_math_200', question: 'Stem and leaf diagram shows:', options: ['Only frequencies', 'Individual data values organized', 'Probability', 'Correlation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 }
];
