// Year 9 Science Trivia Questions
// Based on UK Year 9 Science Curriculum Framework (KS3 Level 3)
// 200 comprehensive questions covering Biology, Chemistry, and Physics

export const YEAR_9_SCIENCE_QUESTIONS = [
  // BIOLOGY (70 questions)
  { id: 'y9_sci_1', question: 'What is photosynthesis?', options: ['Animals eating', 'Plants making food using light', 'Plants breathing', 'Cell division'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_2', question: 'Photosynthesis equation: 6CO₂ + 6H₂O → ___ + 6O₂', options: ['C₆H₁₂O₆ (glucose)', 'CO₂', 'H₂O', 'N₂'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_3', question: 'Chlorophyll is found in:', options: ['Mitochondria', 'Nucleus', 'Chloroplasts', 'Cell membrane'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_4', question: 'What gas do plants take in during photosynthesis?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_5', question: 'What gas do plants release during photosynthesis?', options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Methane'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_6', question: 'Respiration releases:', options: ['Light', 'Energy from glucose', 'Water only', 'Soil'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_7', question: 'Aerobic respiration requires:', options: ['No oxygen', 'Oxygen', 'Only water', 'Only light'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_8', question: 'Aerobic respiration equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + ___ + energy', options: ['6H₂O', '6O₂', 'C₆H₁₂O₆', '6N₂'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_9', question: 'Anaerobic respiration occurs without:', options: ['Glucose', 'Water', 'Oxygen', 'Energy'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_10', question: 'In humans, anaerobic respiration produces:', options: ['Oxygen', 'Lactic acid', 'Carbon monoxide', 'Nitrogen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_11', question: 'The powerhouse of the cell is:', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Vacuole'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_12', question: 'The nucleus contains:', options: ['Water', 'Genetic material (DNA)', 'Food', 'Air'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_13', question: 'Cell membrane controls:', options: ['DNA replication', 'What enters and exits the cell', 'Photosynthesis', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_14', question: 'Cytoplasm is:', options: ['Jelly-like substance where reactions occur', 'The cell wall', 'Only in plant cells', 'The nucleus'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_15', question: 'Plant cells have ___ but animal cells don\'t:', options: ['Nucleus', 'Cell wall, chloroplasts, large vacuole', 'Cytoplasm', 'Cell membrane'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_16', question: 'DNA stands for:', options: ['Deoxyribonucleic Acid', 'Do Not Approach', 'Digital Network Access', 'Diverse Natural Activity'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_17', question: 'DNA structure is a:', options: ['Single helix', 'Double helix', 'Triangle', 'Square'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_18', question: 'Genes are sections of:', options: ['Protein', 'DNA', 'Water', 'Cells'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_19', question: 'Chromosomes are found in the:', options: ['Cytoplasm', 'Nucleus', 'Cell membrane', 'Chloroplast'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_20', question: 'Humans have ___ pairs of chromosomes:', options: ['21', '23', '46', '92'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_21', question: 'Mitosis produces ___ identical cells:', options: ['One', 'Two', 'Four', 'Eight'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_22', question: 'Meiosis produces ___ gametes (sex cells):', options: ['Two identical', 'Four non-identical', 'Eight', 'One'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_23', question: 'Gametes are:', options: ['Body cells', 'Sex cells (sperm and egg)', 'Blood cells', 'Nerve cells'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_24', question: 'Fertilization is when:', options: ['Cells divide', 'Sperm and egg fuse', 'Plants make food', 'Cells die'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_25', question: 'Dominant alleles are represented by:', options: ['Lowercase letters', 'Capital letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_26', question: 'Recessive alleles are represented by:', options: ['Capital letters', 'Lowercase letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_27', question: 'If alleles are Bb, the genotype is:', options: ['Homozygous dominant', 'Heterozygous', 'Homozygous recessive', 'Invalid'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_28', question: 'Genotype is:', options: ['Physical appearance', 'Genetic makeup', 'Behavior', 'Environment'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_29', question: 'Phenotype is:', options: ['Genetic makeup', 'Physical appearance', 'DNA sequence', 'Cell type'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_30', question: 'Natural selection means:', options: ['Humans choose traits', 'Organisms best adapted survive and reproduce', 'Random changes', 'All die equally'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_31', question: 'Who proposed the theory of evolution by natural selection?', options: ['Isaac Newton', 'Charles Darwin', 'Albert Einstein', 'Marie Curie'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_32', question: 'Adaptation is:', options: ['Random change', 'Characteristic helping survival in environment', 'Disease', 'Cell division'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_33', question: 'Variation within species is caused by:', options: ['Only genes', 'Only environment', 'Genes and environment', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_34', question: 'Food chains start with:', options: ['Carnivores', 'Herbivores', 'Producers (plants)', 'Decomposers'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_35', question: 'Producers make their own food through:', options: ['Eating', 'Photosynthesis', 'Respiration', 'Decomposition'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_36', question: 'Primary consumers are:', options: ['Producers', 'Herbivores', 'Carnivores eating carnivores', 'Decomposers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_37', question: 'Secondary consumers are:', options: ['Plants', 'Herbivores', 'Carnivores eating herbivores', 'Decomposers'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_38', question: 'Decomposers:', options: ['Make food', 'Eat plants', 'Break down dead organisms', 'Are predators'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_39', question: 'Biomass ___ at each trophic level:', options: ['Increases', 'Decreases', 'Stays same', 'Doubles'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_40', question: 'Energy transfer in food chains is about:', options: ['100%', '50%', '10%', '1%'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_41', question: 'Pyramid of numbers shows:', options: ['Energy', 'Number of organisms at each level', 'Biomass', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_42', question: 'The heart pumps:', options: ['Air', 'Blood', 'Food', 'Waste'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_43', question: 'Arteries carry blood:', options: ['To the heart', 'Away from the heart', 'Nowhere', 'Only to lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_44', question: 'Veins carry blood:', options: ['Away from heart', 'To the heart', 'Nowhere', 'Only to brain'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_45', question: 'Capillaries are:', options: ['Large vessels', 'Tiny vessels where exchange occurs', 'Only in lungs', 'Not blood vessels'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_46', question: 'Red blood cells carry:', options: ['White blood cells', 'Oxygen', 'Carbon dioxide only', 'Food'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_47', question: 'White blood cells fight:', options: ['Oxygen', 'Infections and disease', 'Red blood cells', 'Food'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_48', question: 'Platelets help with:', options: ['Oxygen transport', 'Fighting infection', 'Blood clotting', 'Digestion'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_49', question: 'Plasma is:', options: ['Red blood cells', 'White blood cells', 'Liquid part of blood', 'Platelets'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_50', question: 'Gas exchange in lungs occurs in:', options: ['Trachea', 'Bronchi', 'Alveoli', 'Diaphragm'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_51', question: 'Alveoli are adapted with:', options: ['Thick walls', 'Thin walls and large surface area', 'No blood supply', 'Bones'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_52', question: 'Breathing in is called:', options: ['Exhalation', 'Inhalation', 'Respiration', 'Perspiration'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_53', question: 'Breathing out is called:', options: ['Inhalation', 'Exhalation', 'Inspiration', 'Transpiration'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_54', question: 'The diaphragm is a:', options: ['Bone', 'Muscle', 'Blood vessel', 'Organ'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_55', question: 'Digestion starts in the:', options: ['Stomach', 'Mouth', 'Small intestine', 'Large intestine'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_56', question: 'Enzymes are:', options: ['Minerals', 'Biological catalysts', 'Vitamins', 'Carbohydrates'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_57', question: 'Amylase breaks down:', options: ['Proteins', 'Fats', 'Carbohydrates', 'Vitamins'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_58', question: 'Protease breaks down:', options: ['Proteins', 'Fats', 'Carbohydrates', 'Water'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_59', question: 'Lipase breaks down:', options: ['Proteins', 'Fats/lipids', 'Carbohydrates', 'Minerals'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_60', question: 'The stomach produces:', options: ['Insulin', 'Hydrochloric acid', 'Oxygen', 'Blood'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_61', question: 'Most absorption of nutrients occurs in the:', options: ['Mouth', 'Stomach', 'Small intestine', 'Large intestine'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_62', question: 'The small intestine is adapted with:', options: ['Thick walls', 'Villi for large surface area', 'No blood supply', 'Bones'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_63', question: 'Large intestine absorbs:', options: ['Nutrients', 'Oxygen', 'Water', 'Proteins'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_64', question: 'Bile is produced by the:', options: ['Pancreas', 'Liver', 'Stomach', 'Small intestine'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_65', question: 'Bile emulsifies:', options: ['Proteins', 'Carbohydrates', 'Fats', 'Vitamins'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_66', question: 'The skeletal system provides:', options: ['Only movement', 'Support, protection, movement, blood cell production', 'Only blood', 'Only oxygen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_67', question: 'Antagonistic muscles work in:', options: ['One direction', 'Opposite pairs', 'Groups of ten', 'Isolation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_68', question: 'Example of antagonistic pair:', options: ['Biceps and triceps', 'Two biceps', 'Heart and lungs', 'Bones'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_69', question: 'Synovial joints allow:', options: ['No movement', 'Movement', 'Blood flow', 'Digestion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_70', question: 'Ligaments connect:', options: ['Muscle to bone', 'Bone to bone', 'Organs', 'Nerves'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },

  // CHEMISTRY (65 questions)
  { id: 'y9_sci_71', question: 'An atom is:', options: ['Smallest particle of a compound', 'Smallest particle of an element', 'A molecule', 'A mixture'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_72', question: 'Atoms contain:', options: ['Only protons', 'Protons, neutrons, electrons', 'Only electrons', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_73', question: 'Protons have ___ charge:', options: ['Negative', 'Positive', 'Neutral', 'No charge'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_74', question: 'Electrons have ___ charge:', options: ['Positive', 'Negative', 'Neutral', 'No charge'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_75', question: 'Neutrons have ___ charge:', options: ['Positive', 'Negative', 'Neutral (no charge)', 'Double positive'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_76', question: 'Protons and neutrons are in the:', options: ['Electron shells', 'Nucleus', 'Outside the atom', 'Nowhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_77', question: 'Electrons orbit in:', options: ['The nucleus', 'Shells/energy levels', 'Straight lines', 'Random patterns'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_78', question: 'Atomic number tells you the number of:', options: ['Neutrons', 'Protons', 'Electrons in outer shell', 'Atoms'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_79', question: 'Mass number = protons + ___:', options: ['Electrons', 'Neutrons', 'Atoms', 'Molecules'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_80', question: 'Elements are made of ___ type of atom:', options: ['Many', 'One', 'No', 'Two'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_81', question: 'Compounds contain ___ elements chemically bonded:', options: ['One', 'Two or more', 'No', 'Only three'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_82', question: 'Mixtures contain ___ substances not chemically bonded:', options: ['One', 'Two or more', 'No', 'Only elements'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_83', question: 'H₂O is:', options: ['An element', 'A compound', 'A mixture', 'An atom'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_84', question: 'Air is:', options: ['An element', 'A compound', 'A mixture', 'A pure substance'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_85', question: 'The periodic table arranges elements by:', options: ['Color', 'Atomic number', 'Alphabetically', 'Size'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_86', question: 'Group 1 elements are called:', options: ['Noble gases', 'Alkali metals', 'Halogens', 'Transition metals'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_87', question: 'Group 7 elements are called:', options: ['Alkali metals', 'Noble gases', 'Halogens', 'Alkali earth metals'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_88', question: 'Group 0/8 elements are called:', options: ['Alkali metals', 'Halogens', 'Noble gases', 'Transition metals'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_89', question: 'Noble gases are:', options: ['Very reactive', 'Unreactive/inert', 'Explosive', 'Liquid'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_90', question: 'Alkali metals react with water to form:', options: ['Acids', 'Alkalis and hydrogen', 'Nothing', 'Salts only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_91', question: 'Metals are generally:', options: ['Dull and brittle', 'Shiny and malleable', 'Gases', 'Poor conductors'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_92', question: 'Non-metals are generally:', options: ['Good conductors', 'Poor conductors', 'Always solid', 'Magnetic'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_93', question: 'Ionic bonding involves:', options: ['Sharing electrons', 'Transfer of electrons', 'Neutrons', 'Protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_94', question: 'Covalent bonding involves:', options: ['Transfer of electrons', 'Sharing electrons', 'Losing protons', 'Gaining neutrons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_95', question: 'Ionic compounds form between:', options: ['Two metals', 'Metal and non-metal', 'Two non-metals', 'Noble gases'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_96', question: 'Covalent compounds form between:', options: ['Two metals', 'Metal and non-metal', 'Non-metals', 'Noble gases only'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_97', question: 'Metals lose electrons to form ___ ions:', options: ['Negative', 'Positive', 'Neutral', 'No ions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_98', question: 'Non-metals gain electrons to form ___ ions:', options: ['Positive', 'Negative', 'Neutral', 'No ions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_99', question: 'pH scale ranges from:', options: ['1-10', '0-14', '1-100', '0-7'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_100', question: 'Acids have pH:', options: ['Less than 7', 'Equal to 7', 'More than 7', 'Always 14'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_101', question: 'Alkalis have pH:', options: ['Less than 7', 'Equal to 7', 'More than 7', 'Always 0'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_102', question: 'Neutral solutions have pH:', options: ['0', '7', '14', '1'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_103', question: 'Universal indicator shows pH by:', options: ['Smell', 'Taste', 'Color', 'Sound'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_104', question: 'Litmus turns ___ in acid:', options: ['Blue', 'Red', 'Green', 'Yellow'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_105', question: 'Litmus turns ___ in alkali:', options: ['Red', 'Blue', 'Green', 'Yellow'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_106', question: 'Neutralization: acid + alkali →', options: ['More acid', 'Salt + water', 'Gas only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_107', question: 'Acid + metal →', options: ['Nothing', 'Salt + hydrogen', 'Water', 'Oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_108', question: 'Acid + carbonate →', options: ['Nothing', 'Salt + water + carbon dioxide', 'Oxygen', 'Hydrogen'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_109', question: 'Exothermic reactions:', options: ['Take in heat', 'Give out heat', 'No temperature change', 'Only occur in labs'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_110', question: 'Endothermic reactions:', options: ['Give out heat', 'Take in heat', 'No temperature change', 'Explode'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_111', question: 'Combustion is:', options: ['Endothermic', 'Exothermic', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_112', question: 'Thermal decomposition needs:', options: ['Cold', 'Heat', 'Light only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_113', question: 'Oxidation is:', options: ['Loss of oxygen', 'Gain of oxygen', 'Gain of electrons', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_114', question: 'Reduction is:', options: ['Gain of oxygen', 'Loss of oxygen', 'Loss of electrons', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_115', question: 'Reactivity series orders metals by:', options: ['Alphabetically', 'How reactive they are', 'Size', 'Color'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_116', question: 'More reactive metals ___ less reactive from compounds:', options: ['Cannot displace', 'Can displace', 'Ignore', 'Bond with'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_117', question: 'Conservation of mass means:', options: ['Mass increases', 'Mass is conserved in reactions', 'Mass decreases', 'Mass disappears'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_118', question: 'In a closed system, total mass ___ during reactions:', options: ['Increases', 'Decreases', 'Stays the same', 'Doubles'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_119', question: 'A catalyst:', options: ['Is used up', 'Speeds up reactions without being used up', 'Slows reactions', 'Makes products'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_120', question: 'Rate of reaction can be increased by:', options: ['Cooling', 'Increasing temperature, concentration, surface area', 'Removing reactants', 'Adding water'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_121', question: 'Increasing surface area ___ rate of reaction:', options: ['Decreases', 'Increases', 'No effect', 'Stops'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_122', question: 'Increasing temperature ___ particle movement:', options: ['Decreases', 'Stops', 'Increases', 'No effect'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_123', question: 'Word equation: Methane + Oxygen → ___ + Water', options: ['Hydrogen', 'Carbon dioxide', 'Nitrogen', 'Oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_124', question: 'Symbol equation balancing follows:', options: ['Random rules', 'Conservation of mass (same atoms each side)', 'No rules', 'Alphabetical order'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_125', question: 'Crude oil is a mixture of:', options: ['Water', 'Hydrocarbons', 'Metals', 'Salts'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_126', question: 'Hydrocarbons contain only:', options: ['Hydrogen', 'Carbon', 'Hydrogen and carbon', 'Oxygen'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_127', question: 'Fractional distillation separates crude oil by:', options: ['Color', 'Boiling points', 'Smell', 'Density only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_128', question: 'Complete combustion of hydrocarbons produces:', options: ['CO₂ + H₂O', 'CO + H₂', 'C + O₂', 'Nothing'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_129', question: 'Incomplete combustion can produce:', options: ['Only CO₂', 'Carbon monoxide (CO) and/or carbon (soot)', 'Only water', 'Oxygen'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_130', question: 'Carbon monoxide is:', options: ['Harmless', 'Toxic', 'Useful fuel', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_131', question: 'Greenhouse gases include:', options: ['Oxygen', 'Carbon dioxide, methane', 'Nitrogen', 'Hydrogen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_132', question: 'Greenhouse effect causes:', options: ['Cooling', 'Global warming', 'No temperature change', 'Ice age'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_133', question: 'The three states of matter are:', options: ['Hot, warm, cold', 'Solid, liquid, gas', 'Big, medium, small', 'Heavy, light, medium'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_134', question: 'In solids, particles:', options: ['Move freely', 'Vibrate in fixed positions', 'Don\'t exist', 'Float away'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_135', question: 'In liquids, particles:', options: ['Are fixed', 'Move around each other', 'Don\'t touch', 'Are far apart'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },

  // PHYSICS (65 questions)
  { id: 'y9_sci_136', question: 'Force is measured in:', options: ['Meters', 'Newtons (N)', 'Kilograms', 'Joules'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_137', question: 'Mass is measured in:', options: ['Newtons', 'Kilograms (kg)', 'Meters', 'Seconds'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_138', question: 'Weight is:', options: ['Same as mass', 'Force due to gravity', 'Always 10N', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_139', question: 'Weight = mass × ___:', options: ['Time', 'Distance', 'Gravitational field strength', 'Speed'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_140', question: 'On Earth, gravitational field strength is about:', options: ['5 N/kg', '10 N/kg', '15 N/kg', '100 N/kg'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_141', question: 'Balanced forces cause:', options: ['Acceleration', 'No change in motion', 'Deceleration', 'Explosion'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_142', question: 'Unbalanced forces cause:', options: ['No change', 'Change in motion (acceleration)', 'Nothing', 'Balance'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_143', question: 'Newton\'s First Law: An object stays at rest or in motion unless:', options: ['It wants to change', 'Acted on by an unbalanced force', 'It gets tired', 'Never'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_144', question: 'Newton\'s Second Law: Force = mass × ___:', options: ['Time', 'Distance', 'Acceleration', 'Velocity'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_145', question: 'Newton\'s Third Law: For every action, there is an equal and opposite ___:', options: ['Mass', 'Reaction', 'Distance', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_146', question: 'Speed = distance ÷ ___:', options: ['Mass', 'Force', 'Time', 'Acceleration'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_147', question: 'If distance = 100m and time = 20s, speed =', options: ['5 m/s', '10 m/s', '20 m/s', '2000 m/s'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_148', question: 'Velocity includes:', options: ['Only speed', 'Speed and direction', 'Only direction', 'Only distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_149', question: 'Acceleration = change in velocity ÷ ___:', options: ['Distance', 'Mass', 'Time', 'Force'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_150', question: 'Acceleration is measured in:', options: ['m/s', 'm/s²', 'kg', 'N'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_151', question: 'Distance-time graph: flat line means:', options: ['Moving fast', 'Stationary', 'Accelerating', 'Decelerating'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_152', question: 'Distance-time graph: straight diagonal line means:', options: ['Stationary', 'Constant speed', 'Accelerating', 'Stopping'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_153', question: 'Distance-time graph: curved line means:', options: ['Constant speed', 'Stationary', 'Changing speed (acceleration)', 'Nothing'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_154', question: 'Gradient of distance-time graph gives:', options: ['Distance', 'Time', 'Speed', 'Acceleration'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_155', question: 'Stopping distance = thinking distance + ___:', options: ['Speed', 'Braking distance', 'Time', 'Mass'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_156', question: 'Thinking distance increases with:', options: ['Better brakes', 'Slower speed', 'Faster reaction time/speed', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_157', question: 'Braking distance increases with:', options: ['Lower speed', 'Wet roads, worn brakes, higher speed', 'Better conditions', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_158', question: 'Friction is a force that:', options: ['Helps motion', 'Opposes motion', 'Has no effect', 'Increases speed'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_159', question: 'Air resistance is a type of:', options: ['Gravity', 'Friction', 'Magnetism', 'Electricity'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_160', question: 'Terminal velocity is when:', options: ['Object stops', 'Forces are balanced so constant speed', 'Object accelerates', 'Object explodes'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_161', question: 'Momentum = mass × ___:', options: ['Acceleration', 'Time', 'Velocity', 'Force'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_162', question: 'In a collision, total momentum is:', options: ['Lost', 'Conserved', 'Doubled', 'Halved'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_163', question: 'Work done = force × ___:', options: ['Time', 'Mass', 'Distance moved in direction of force', 'Velocity'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_164', question: 'Work done is measured in:', options: ['Newtons', 'Watts', 'Joules', 'Kilograms'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_165', question: 'Energy is measured in:', options: ['Newtons', 'Watts', 'Joules', 'Meters'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_166', question: 'Kinetic energy is energy of:', options: ['Position', 'Movement', 'Heat', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_167', question: 'Gravitational potential energy is energy of:', options: ['Movement', 'Position/height', 'Heat', 'Electricity'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_168', question: 'KE = ½ × mass × ___²:', options: ['Time', 'Distance', 'Velocity', 'Force'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_169', question: 'GPE = mass × gravitational field strength × ___:', options: ['Time', 'Velocity', 'Height', 'Distance'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_170', question: 'Law of conservation of energy:', options: ['Energy is created', 'Energy is destroyed', 'Energy is conserved (can\'t be created/destroyed)', 'Energy doubles'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_171', question: 'Energy is transferred, not:', options: ['Moved', 'Used', 'Created or destroyed', 'Changed'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_172', question: 'Power = work done ÷ ___:', options: ['Force', 'Distance', 'Time', 'Mass'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_173', question: 'Power is measured in:', options: ['Joules', 'Newtons', 'Watts', 'Kilograms'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_174', question: 'Efficiency = (useful energy out ÷ total energy in) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_175', question: 'No machine is 100% efficient because:', options: ['All energy is useful', 'Some energy is wasted (heat, sound)', 'Machines are perfect', 'Energy is created'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_176', question: 'Pressure = force ÷ ___:', options: ['Time', 'Mass', 'Area', 'Distance'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_177', question: 'Pressure is measured in:', options: ['Newtons', 'Pascals (Pa)', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_178', question: 'Increasing area ___ pressure:', options: ['Increases', 'Decreases', 'No effect', 'Doubles'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_179', question: 'Moments = force × ___:', options: ['Time', 'Perpendicular distance from pivot', 'Mass', 'Velocity'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_180', question: 'Principle of moments: balanced when clockwise moments = ___ moments:', options: ['No', 'Anticlockwise', 'All', 'Zero'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y9_sci_181', question: 'Current is measured in:', options: ['Volts', 'Amperes (A)', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_182', question: 'Current is measured using:', options: ['Voltmeter', 'Ammeter', 'Thermometer', 'Barometer'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_183', question: 'Ammeter is connected in:', options: ['Parallel', 'Series', 'Either', 'Not connected'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_184', question: 'Voltage is measured in:', options: ['Amperes', 'Volts (V)', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_185', question: 'Voltage is measured using:', options: ['Ammeter', 'Voltmeter', 'Thermometer', 'Ruler'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_186', question: 'Voltmeter is connected in:', options: ['Series', 'Parallel', 'Either', 'Not connected'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_187', question: 'Resistance is measured in:', options: ['Amperes', 'Volts', 'Ohms (Ω)', 'Watts'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_188', question: 'Ohm\'s Law: V = I × ___:', options: ['T', 'P', 'R', 'M'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_189', question: 'If V = 12V and I = 3A, then R =', options: ['4Ω', '9Ω', '15Ω', '36Ω'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_190', question: 'Series circuits have ___ path:', options: ['Multiple', 'One', 'No', 'Infinite'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_191', question: 'In series circuits, current is:', options: ['Different everywhere', 'The same everywhere', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_192', question: 'Parallel circuits have ___ paths:', options: ['One', 'Multiple', 'No', 'Zero'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_193', question: 'In parallel circuits, voltage across each branch is:', options: ['Different', 'The same', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_194', question: 'Static electricity is caused by:', options: ['Movement of electrons', 'Friction transferring electrons', 'Heat', 'Light'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y9_sci_195', question: 'Like charges (same charge):', options: ['Attract', 'Repel', 'No effect', 'Bond'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_196', question: 'Opposite charges:', options: ['Repel', 'Attract', 'No effect', 'Explode'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_197', question: 'Magnets have ___ poles:', options: ['One', 'Two (North and South)', 'Three', 'Four'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_198', question: 'Like magnetic poles:', options: ['Attract', 'Repel', 'No effect', 'Bond'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_199', question: 'Opposite magnetic poles:', options: ['Repel', 'Attract', 'No effect', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y9_sci_200', question: 'Electromagnets use ___ to create magnetic field:', options: ['Permanent magnets only', 'Electric current through coil', 'Gravity', 'Heat'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 }
];
