// Year 12 English Trivia Questions
// Based on UK Year 12 English Curriculum Framework (A-Level AS Literature & Language)
// 200 comprehensive questions covering A-Level English

export const YEAR_12_ENGLISH_QUESTIONS = [
  // LITERARY CRITICISM & THEORY (50 questions)
  { id: 'y12_eng_1', question: 'Who wrote "The Metamorphosis"?', options: ['James Joyce', 'Franz Kafka', 'Albert Camus', 'Samuel Beckett'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_2', question: 'Modernist literature is characterized by:', options: ['Linear narratives', 'Fragmentation and stream of consciousness', 'Realism', 'Romance'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_3', question: 'Postmodernism challenges:', options: ['Nothing', 'Grand narratives and absolute truths', 'All literature', 'Poetry only'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_4', question: 'Marxist criticism focuses on:', options: ['Psychology', 'Class, economics, power structures', 'Gender', 'Language only'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_5', question: 'Feminist criticism examines:', options: ['Economics', 'Gender roles and representation', 'Only male authors', 'Plot only'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_6', question: 'Psychoanalytic criticism derives from:', options: ['Marx', 'Freud', 'Darwin', 'Newton'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_7', question: 'New Historicism considers:', options: ['Only text', 'Text within historical context', 'Only history', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_8', question: 'Structuralism focuses on:', options: ['Individual meaning', 'Underlying structures and systems', 'Surface details', 'Plot only'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_9', question: 'Post-structuralism argues meaning is:', options: ['Fixed', 'Unstable and fluid', 'Obvious', 'Universal'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_10', question: 'Derrida is associated with:', options: ['Feminism', 'Deconstruction', 'Marxism', 'Realism'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_11', question: 'Reader-response theory emphasizes:', options: ['Author intent', 'Reader creating meaning', 'Historical context', 'Plot summary'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_12', question: 'Intertextuality refers to:', options: ['One text only', 'Relationships between texts', 'No connections', 'Plot'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_13', question: 'Canon refers to:', options: ['Any books', 'Accepted important literary works', 'Only modern texts', 'Only poetry'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_14', question: 'Death of the author theory suggests:', options: ['Author is everything', 'Author intent is irrelevant to interpretation', 'No authors exist', 'Authors should die'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_15', question: 'Mimesis means:', options: ['Creation', 'Imitation of reality', 'Fantasy', 'Rejection'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_16', question: 'Catharsis in tragedy causes:', options: ['Boredom', 'Emotional purging/release', 'Anger', 'Confusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_17', question: 'Aristotle\'s Poetics discusses:', options: ['Novels', 'Drama and epic poetry', 'Only comedy', 'Only sonnets'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_18', question: 'Gothic literature features:', options: ['Realism', 'Supernatural, mystery, horror', 'Comedy', 'Romance only'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_19', question: 'Romanticism emphasized:', options: ['Reason', 'Emotion, nature, individualism', 'Industry', 'Science'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_20', question: 'Victorian literature often addressed:', options: ['Nothing', 'Social issues, morality, industrialization', 'Only love', 'Only war'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_21', question: 'Bildungsroman is:', options: ['War novel', 'Coming-of-age novel', 'Detective novel', 'Science fiction'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_22', question: 'Epistolary novel uses:', options: ['Dialogue', 'Letters/documents', 'Poetry', 'No words'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_23', question: 'Picaresque novel features:', options: ['One location', 'Rogue protagonist on episodic adventures', 'No plot', 'Only dialogue'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_24', question: 'Stream of consciousness portrays:', options: ['Dialogue', 'Character\'s thoughts flowing', 'Description only', 'Plot summary'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_25', question: 'Free indirect discourse blends:', options: ['Nothing', 'Narrator and character perspectives', 'Only narration', 'Only dialogue'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_26', question: 'Omniscient narrator knows:', options: ['Nothing', 'Everything about all characters', 'One character only', 'Only plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_27', question: 'Limited third person reveals:', options: ['Everything', 'One character\'s perspective', 'No perspectives', 'All equally'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_28', question: 'Unreliable narrator:', options: ['Tells truth', 'May mislead reader', 'Knows everything', 'Is objective'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_29', question: 'Frame narrative has:', options: ['One story', 'Story within story', 'No structure', 'Only dialogue'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_30', question: 'In medias res begins:', options: ['At start', 'In middle of action', 'At end', 'Nowhere'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_31', question: 'Flashback reveals:', options: ['Future', 'Past events', 'Present only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_32', question: 'Foreshadowing hints at:', options: ['Past', 'Future events', 'Nothing', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_33', question: 'Dramatic irony occurs when:', options: ['Something is funny', 'Audience knows more than characters', 'No one knows anything', 'Characters know all'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_34', question: 'Situational irony is when:', options: ['Expected happens', 'Opposite of expected happens', 'Nothing happens', 'Same happens'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_35', question: 'Verbal irony says:', options: ['What is meant', 'Opposite of what is meant', 'Nothing', 'Everything'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_36', question: 'Allegory has:', options: ['Only literal meaning', 'Symbolic underlying meaning', 'No meaning', 'Random meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_37', question: 'Archetype is:', options: ['Unique character', 'Universal symbol/character type', 'Modern invention', 'Plot device'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_38', question: 'Tragic hero has:', options: ['No flaws', 'Fatal flaw leading to downfall', 'Perfect life', 'No conflict'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_39', question: 'Hamartia is:', options: ['Strength', 'Tragic flaw', 'Success', 'Beginning'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_40', question: 'Hubris is excessive:', options: ['Humility', 'Pride', 'Fear', 'Joy'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_41', question: 'Nemesis is:', options: ['Friend', 'Deserved fate/downfall', 'Beginning', 'Success'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_42', question: 'Peripeteia is:', options: ['Introduction', 'Sudden reversal', 'Resolution', 'No change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_43', question: 'Anagnorisis is moment of:', options: ['Ignorance', 'Recognition/discovery', 'Death', 'Beginning'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_44', question: 'Deus ex machina is:', options: ['Natural resolution', 'Contrived sudden solution', 'Gradual change', 'Character development'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_45', question: 'Bathos is:', options: ['Elevated language', 'Anticlimatic descent to trivial', 'Rising tension', 'Comedy'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_46', question: 'Pathos evokes:', options: ['Logic', 'Pity/emotion', 'Anger', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_47', question: 'Ethos appeals to:', options: ['Emotion', 'Credibility/character', 'Logic', 'Fear'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_48', question: 'Logos appeals to:', options: ['Emotion', 'Logic/reason', 'Credibility', 'Fear'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_49', question: 'Verisimilitude means:', options: ['Fantasy', 'Appearance of truth/realism', 'Impossible events', 'Magic'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_50', question: 'Metafiction is:', options: ['Traditional narrative', 'Fiction aware it\'s fiction', 'Non-fiction', 'Biography'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },

  // POETRY ANALYSIS (50 questions)
  { id: 'y12_eng_51', question: 'Metaphysical poetry features:', options: ['Simple images', 'Complex conceits and paradoxes', 'No imagery', 'Only nature'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_52', question: 'John Donne is known for:', options: ['Romantic poetry', 'Metaphysical poetry', 'Epic poetry', 'Haiku'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_53', question: 'Conceit is:', options: ['Simple comparison', 'Extended elaborate metaphor', 'Rhyme scheme', 'Meter'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_54', question: 'Enjambment is when line:', options: ['Ends with punctuation', 'Runs onto next without pause', 'Is short', 'Rhymes'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_55', question: 'End-stopped line has:', options: ['No punctuation', 'Punctuation at end', 'Middle pause', 'No meaning'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_56', question: 'Caesura is:', options: ['Line break', 'Pause within line', 'Rhyme', 'Meter'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_57', question: 'Volta in sonnet is:', options: ['Rhyme', 'Turn/shift in argument', 'Meter', 'First line'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_58', question: 'Petrarchan sonnet structure:', options: ['3 quatrains + couplet', 'Octave + sestet', '14 couplets', 'No structure'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_59', question: 'Shakespearean sonnet structure:', options: ['Octave + sestet', '3 quatrains + couplet', '7 couplets', 'No structure'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_60', question: 'Iambic pentameter has ___ syllables:', options: ['8', '10', '12', '14'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_61', question: 'Iamb is ___ followed by ___:', options: ['Stressed, unstressed', 'Unstressed, stressed', 'Two stressed', 'Two unstressed'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_62', question: 'Trochee is ___ followed by ___:', options: ['Unstressed, stressed', 'Stressed, unstressed', 'Two stressed', 'Two unstressed'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_63', question: 'Spondee is:', options: ['Unstressed, stressed', 'Two stressed syllables', 'Two unstressed', 'Three syllables'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_64', question: 'Anapest is:', options: ['One stressed', 'Two unstressed + stressed', 'Three stressed', 'No pattern'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_65', question: 'Dactylic meter has:', options: ['Unstressed + stressed', 'Stressed + two unstressed', 'All stressed', 'No pattern'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_66', question: 'Free verse has:', options: ['Strict rhyme', 'No regular rhyme/meter', 'Fixed form', 'Always rhymes'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_67', question: 'Blank verse has:', options: ['Rhyme', 'Meter but no rhyme', 'No meter', 'No structure'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_68', question: 'Heroic couplet is:', options: ['Any two lines', 'Rhyming pair of iambic pentameter', 'Three lines', 'No rhyme'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_69', question: 'Ballad stanza typically has ___ lines:', options: ['2', '4', '6', '8'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_70', question: 'Villanelle has ___ lines:', options: ['14', '17', '19', '21'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_71', question: 'Terza rima uses rhyme scheme:', options: ['AABB', 'ABA BCB CDC', 'ABAB', 'ABBA'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_72', question: 'Ottava rima stanza has ___ lines:', options: ['6', '8', '10', '12'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_73', question: 'Spenserian stanza has ___ lines:', options: ['7', '8', '9', '10'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_74', question: 'Ode is:', options: ['Short simple poem', 'Lengthy lyric poem', 'Narrative poem', 'Epic'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_75', question: 'Elegy is poem of:', options: ['Joy', 'Mourning/loss', 'Love', 'Nature'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_76', question: 'Pastoral poetry focuses on:', options: ['City life', 'Rural/shepherd life', 'War', 'Industry'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_77', question: 'Epic poem is:', options: ['Short', 'Long narrative of heroic deeds', 'Lyric', 'Sonnet'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_78', question: 'Lyric poetry expresses:', options: ['Story', 'Personal emotions/thoughts', 'Epic battles', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_79', question: 'Dramatic monologue features:', options: ['Multiple speakers', 'Single speaker revealing character', 'No speaker', 'Narrator only'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_80', question: 'Apostrophe addresses:', options: ['Nothing', 'Absent person/abstract idea', 'Audience only', 'Self'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_81', question: 'Personification gives ___ qualities:', options: ['Animal', 'Human', 'Object', 'Abstract'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_82', question: 'Extended metaphor develops:', options: ['One line', 'Throughout poem', 'Not at all', 'Only title'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_83', question: 'Oxymoron combines:', options: ['Similar words', 'Contradictory terms', 'Rhyming words', 'Long words'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_84', question: 'Paradox seems:', options: ['Simple', 'Contradictory but true', 'False', 'Obvious'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_85', question: 'Synecdoche uses:', options: ['Whole for whole', 'Part for whole or vice versa', 'Nothing', 'Everything'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_86', question: 'Metonymy uses:', options: ['Direct name', 'Associated term to represent something', 'Nothing', 'Everything'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_87', question: 'Hyperbole is:', options: ['Understatement', 'Exaggeration', 'Literal', 'Quiet'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_88', question: 'Litotes is:', options: ['Exaggeration', 'Understatement via negative', 'Direct statement', 'Loud'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_89', question: 'Euphemism is:', options: ['Harsh language', 'Mild expression for harsh reality', 'Direct language', 'Slang'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_90', question: 'Dysphemism is:', options: ['Polite', 'Harsh expression', 'Neutral', 'Mild'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_91', question: 'Alliteration repeats ___ sounds:', options: ['Vowel', 'Initial consonant', 'Final', 'Middle'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_92', question: 'Assonance repeats ___ sounds:', options: ['Consonant', 'Vowel', 'All', 'None'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_93', question: 'Consonance repeats ___ sounds:', options: ['Vowel', 'Consonant', 'All', 'None'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_94', question: 'Sibilance uses ___ sounds:', options: ['B/P', 'S/SH', 'T/D', 'M/N'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_95', question: 'Plosive sounds are:', options: ['Soft', 'Explosive (b, p, d, t)', 'Silent', 'Long'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_96', question: 'Anaphora repeats at:', options: ['End', 'Beginning of successive clauses', 'Middle', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_97', question: 'Epistrophe repeats at:', options: ['Beginning', 'End of successive clauses', 'Middle', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_98', question: 'Chiasmus has ___ structure:', options: ['Linear', 'Reversed parallel (ABBA)', 'Random', 'None'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_99', question: 'Zeugma uses one word to modify:', options: ['One thing', 'Two+ things differently', 'Nothing', 'Everything equally'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_100', question: 'Pathetic fallacy attributes human emotions to:', options: ['Humans', 'Nature/weather', 'Animals', 'Objects'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },

  // PROSE ANALYSIS (50 questions)
  { id: 'y12_eng_101', question: 'Who wrote "1984"?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_102', question: 'Who wrote "Brave New World"?', options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'William Golding'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_103', question: 'Who wrote "The Great Gatsby"?', options: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_104', question: 'Who wrote "To Kill a Mockingbird"?', options: ['Harper Lee', 'Toni Morrison', 'Maya Angelou', 'Alice Walker'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_105', question: 'Who wrote "Wuthering Heights"?', options: ['Charlotte Brontë', 'Emily Brontë', 'Anne Brontë', 'Jane Austen'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_106', question: 'Who wrote "Jane Eyre"?', options: ['Emily Brontë', 'Charlotte Brontë', 'Anne Brontë', 'George Eliot'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_107', question: 'Who wrote "Pride and Prejudice"?', options: ['Jane Austen', 'Charlotte Brontë', 'George Eliot', 'Virginia Woolf'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_108', question: 'Who wrote "Frankenstein"?', options: ['Bram Stoker', 'Mary Shelley', 'Edgar Allan Poe', 'H.P. Lovecraft'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_109', question: 'Who wrote "Dracula"?', options: ['Mary Shelley', 'Bram Stoker', 'Oscar Wilde', 'Robert Louis Stevenson'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_110', question: 'Who wrote "The Picture of Dorian Gray"?', options: ['Bram Stoker', 'Robert Louis Stevenson', 'Oscar Wilde', 'H.G. Wells'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_111', question: 'Who wrote "Heart of Darkness"?', options: ['Joseph Conrad', 'E.M. Forster', 'Rudyard Kipling', 'H. Rider Haggard'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_112', question: 'Who wrote "Mrs Dalloway"?', options: ['James Joyce', 'Virginia Woolf', 'D.H. Lawrence', 'E.M. Forster'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_113', question: 'Who wrote "Ulysses"?', options: ['Virginia Woolf', 'James Joyce', 'T.S. Eliot', 'Ezra Pound'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_114', question: 'Who wrote "The Waste Land"?', options: ['Ezra Pound', 'T.S. Eliot', 'W.B. Yeats', 'W.H. Auden'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_115', question: 'Who wrote "Waiting for Godot"?', options: ['Harold Pinter', 'Samuel Beckett', 'Tom Stoppard', 'Edward Albee'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_116', question: 'Who wrote "The Handmaid\'s Tale"?', options: ['Margaret Atwood', 'Toni Morrison', 'Angela Carter', 'Doris Lessing'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_117', question: 'Who wrote "Things Fall Apart"?', options: ['Wole Soyinka', 'Chinua Achebe', 'Ngũgĩ wa Thiong\'o', 'Ben Okri'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_118', question: 'Who wrote "Beloved"?', options: ['Maya Angelou', 'Toni Morrison', 'Alice Walker', 'Zora Neale Hurston'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_119', question: 'Who wrote "One Hundred Years of Solitude"?', options: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Pablo Neruda'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_120', question: 'Who wrote "The Catcher in the Rye"?', options: ['Jack Kerouac', 'J.D. Salinger', 'William S. Burroughs', 'Allen Ginsberg'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_121', question: 'Narrative perspective affects:', options: ['Nothing', 'Reader\'s understanding and sympathy', 'Only plot', 'Only setting'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_122', question: 'Setting can symbolize:', options: ['Nothing', 'Character states/themes', 'Only location', 'Only time'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_123', question: 'Characterization can be:', options: ['Only direct', 'Direct or indirect', 'Absent', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_124', question: 'Round characters are:', options: ['Flat', 'Complex and multi-dimensional', 'Simple', 'One-trait'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_125', question: 'Flat characters are:', options: ['Complex', 'One-dimensional', 'Realistic', 'Detailed'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_126', question: 'Dynamic characters:', options: ['Never change', 'Undergo development', 'Are static', 'Are boring'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_127', question: 'Static characters:', options: ['Change significantly', 'Remain unchanged', 'Develop', 'Are protagonists'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_128', question: 'Stock characters are:', options: ['Unique', 'Stereotypical recurring types', 'Complex', 'Realistic'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_129', question: 'Foil character:', options: ['Is same as protagonist', 'Contrasts to highlight traits', 'Is villain', 'Is narrator'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_130', question: 'Conflict can be:', options: ['Only external', 'Internal or external', 'Only internal', 'Absent'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_131', question: 'Rising action leads to:', options: ['Introduction', 'Climax', 'Resolution', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_132', question: 'Climax is point of:', options: ['Introduction', 'Highest tension', 'Resolution', 'Beginning'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_133', question: 'Falling action occurs:', options: ['Before climax', 'After climax', 'At beginning', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_134', question: 'Resolution/denouement:', options: ['Introduces conflict', 'Resolves conflict', 'Creates tension', 'Is climax'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_135', question: 'Exposition provides:', options: ['Climax', 'Background information', 'Resolution', 'Conflict only'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_136', question: 'Theme is:', options: ['Plot', 'Central idea/message', 'Character', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_137', question: 'Motif is:', options: ['One occurrence', 'Recurring element', 'Character', 'Plot'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_138', question: 'Symbol represents:', options: ['Itself only', 'Deeper meaning', 'Nothing', 'Surface'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_139', question: 'Tone reflects:', options: ['Plot', 'Author\'s attitude', 'Setting', 'Character names'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_140', question: 'Mood creates:', options: ['Plot', 'Atmosphere for reader', 'Characters', 'Setting only'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_141', question: 'Pacing controls:', options: ['Characters', 'Speed of narrative', 'Setting', 'Theme'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_142', question: 'Dialogue reveals:', options: ['Nothing', 'Character and advances plot', 'Only time', 'Only place'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_143', question: 'Show don\'t tell uses:', options: ['Direct statements', 'Details to imply', 'Summary', 'Explanation'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_144', question: 'Suspense creates:', options: ['Resolution', 'Tension and uncertainty', 'Boredom', 'Confusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_145', question: 'Anticlimax is:', options: ['Exciting peak', 'Disappointing after buildup', 'Beginning', 'Climax'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_146', question: 'Cliffhanger creates:', options: ['Resolution', 'Suspense at end', 'Introduction', 'Boredom'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_147', question: 'Red herring is:', options: ['Main clue', 'Misleading clue', 'Resolution', 'Truth'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_148', question: 'Juxtaposition places ___ together:', options: ['Similar things', 'Contrasting things', 'Same things', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_149', question: 'Circular structure:', options: ['Is linear', 'Ends where it began', 'Has no structure', 'Is random'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_150', question: 'Non-linear narrative:', options: ['Follows chronology', 'Disrupts chronological order', 'Has no time', 'Is always past'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },

  // LANGUAGE & LINGUISTICS (50 questions)
  { id: 'y12_eng_151', question: 'Phonology studies:', options: ['Meaning', 'Sound systems', 'Grammar', 'Words'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_152', question: 'Morphology studies:', options: ['Sounds', 'Word structure', 'Sentences', 'Meaning'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_153', question: 'Syntax studies:', options: ['Sounds', 'Words', 'Sentence structure', 'Meaning'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_154', question: 'Semantics studies:', options: ['Sounds', 'Grammar', 'Meaning', 'Use'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_155', question: 'Pragmatics studies:', options: ['Sounds', 'Grammar', 'Language in context/use', 'Words'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_156', question: 'Phoneme is:', options: ['Letter', 'Smallest unit of sound', 'Word', 'Sentence'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_157', question: 'Morpheme is:', options: ['Sound', 'Smallest unit of meaning', 'Sentence', 'Paragraph'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_158', question: 'Free morpheme:', options: ['Cannot stand alone', 'Can stand alone', 'Is always short', 'Is always long'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_159', question: 'Bound morpheme:', options: ['Stands alone', 'Must attach to another', 'Is always long', 'Is a sentence'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_160', question: 'Affix includes:', options: ['Only roots', 'Prefixes and suffixes', 'Only free morphemes', 'Sentences'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_161', question: 'Lexicon is:', options: ['Grammar', 'Vocabulary/mental dictionary', 'Pronunciation', 'Syntax'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_162', question: 'Lexical field is group of words related by:', options: ['Sound', 'Meaning/topic', 'Grammar', 'Length'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_163', question: 'Collocation is words that:', options: ['Never appear together', 'Frequently appear together', 'Are opposites', 'Rhyme'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_164', question: 'Polysemy is when word has:', options: ['One meaning', 'Multiple related meanings', 'No meaning', 'Opposite meaning'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_165', question: 'Homonym words:', options: ['Sound same, mean different', 'Sound different, mean same', 'Are identical', 'Don\'t exist'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_166', question: 'Synonym means:', options: ['Opposite', 'Similar meaning', 'Same sound', 'No relation'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_167', question: 'Antonym means:', options: ['Similar', 'Opposite meaning', 'Same sound', 'No relation'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_eng_168', question: 'Denotation is:', options: ['Associated meaning', 'Literal dictionary meaning', 'Emotional meaning', 'No meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_169', question: 'Connotation is:', options: ['Literal meaning', 'Associated/emotional meaning', 'No meaning', 'Dictionary meaning'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_170', question: 'Register refers to:', options: ['Volume', 'Level of formality', 'Speed', 'Pitch'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_171', question: 'Idiolect is:', options: ['Group language', 'Individual\'s unique language use', 'Formal language', 'Written language'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_172', question: 'Sociolect is:', options: ['Individual language', 'Social group\'s language variety', 'Formal language', 'Animal language'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_173', question: 'Dialect is:', options: ['Standard language', 'Regional language variety', 'Formal language', 'Written language'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_174', question: 'Standard English is:', options: ['Slang', 'Widely accepted prestige variety', 'Regional', 'Informal'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_175', question: 'Code-switching is:', options: ['Writing in code', 'Alternating between languages/varieties', 'Formal only', 'Never switching'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_176', question: 'Discourse is:', options: ['One word', 'Extended communication', 'Silence', 'Sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_177', question: 'Discourse markers signal:', options: ['Nothing', 'Relationships between utterances', 'Only questions', 'Only statements'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_178', question: 'Turn-taking is feature of:', options: ['Written language', 'Conversation', 'Grammar', 'Vocabulary'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_179', question: 'Adjacency pairs are:', options: ['Random utterances', 'Related conversational exchanges', 'Monologues', 'Silence'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_180', question: 'Phatic communication serves:', options: ['Information', 'Social function', 'Commands', 'Questions'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_181', question: 'Prestige variety is:', options: ['Stigmatized', 'Socially valued', 'Informal', 'Rare'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_182', question: 'Covert prestige is:', options: ['Open high status', 'Hidden value in non-standard forms', 'No value', 'Official prestige'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_183', question: 'Lingua franca is:', options: ['Native language', 'Common language for communication', 'Dead language', 'First language'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_184', question: 'Pidgin is:', options: ['Full language', 'Simplified contact language', 'Native language', 'Written language'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_185', question: 'Creole is:', options: ['Pidgin', 'Fully developed from pidgin', 'Dialect', 'Standard language'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_186', question: 'Language acquisition is:', options: ['Learning as adult', 'Natural childhood learning', 'Formal study', 'Forgetting'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_187', question: 'Language learning is:', options: ['Natural acquisition', 'Conscious study', 'Childhood only', 'Impossible'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_188', question: 'Prescriptivism:', options: ['Describes usage', 'Prescribes rules', 'No rules', 'Accepts all'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_189', question: 'Descriptivism:', options: ['Prescribes rules', 'Describes actual usage', 'Judges correctness', 'Rejects change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_190', question: 'Language change is:', options: ['Impossible', 'Inevitable', 'Always bad', 'Never happens'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_191', question: 'Semantic change is change in:', options: ['Sound', 'Meaning', 'Grammar', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_192', question: 'Amelioration is:', options: ['Meaning worsens', 'Meaning improves', 'No change', 'Sound change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_193', question: 'Pejoration is:', options: ['Meaning improves', 'Meaning worsens', 'No change', 'Grammar change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_194', question: 'Broadening is:', options: ['Meaning narrows', 'Meaning expands', 'No change', 'Sound change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_195', question: 'Narrowing is:', options: ['Meaning expands', 'Meaning becomes more specific', 'No change', 'Grammar change'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_eng_196', question: 'Neologism is:', options: ['Old word', 'New word', 'Grammar rule', 'Sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_197', question: 'Archaism is:', options: ['New word', 'Old/outdated word', 'Modern term', 'Slang'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_198', question: 'Borrowing is:', options: ['Creating new words', 'Taking words from other languages', 'Deleting words', 'Grammar'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_199', question: 'Compounding creates words by:', options: ['One morpheme', 'Combining existing words', 'Borrowing', 'Shortening'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_eng_200', question: 'Clipping is:', options: ['Lengthening', 'Shortening words', 'Creating new', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 }
];
