// Year 11 Mathematics Trivia Questions
// Based on UK Year 11 Maths Curriculum Framework (GCSE Higher Tier)
// 200 comprehensive questions covering advanced GCSE topics for exam preparation

export const YEAR_11_MATHS_QUESTIONS = [
  // ADVANCED ALGEBRA (50 questions)
  { id: 'y11_math_1', question: 'Solve: x² + 6x + 8 = 0', options: ['x = -2 or -4', 'x = 2 or 4', 'x = -2 or 4', 'x = 2 or -4'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_2', question: 'Solve: x² - 7x + 12 = 0', options: ['x = 3 or 4', 'x = -3 or -4', 'x = 3 or -4', 'x = -3 or 4'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_3', question: 'Solve using formula: 2x² + 5x - 3 = 0. x = ?', options: ['x = 0.5 or -3', 'x = -0.5 or 3', 'x = 1 or -3', 'x = -1 or 3'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_4', question: 'Complete the square: x² + 8x + 7 = 0 becomes (x + 4)² = ?', options: ['7', '9', '11', '16'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_5', question: 'Factorise: x² - 9', options: ['(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', 'Cannot factorise'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_6', question: 'Factorise: 4x² - 9', options: ['(2x-3)(2x+3)', '(4x-3)(x+3)', '(2x-3)²', '(x-3)(4x+3)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_7', question: 'Factorise: x² - 6x + 9', options: ['(x-3)(x+3)', '(x-3)²', '(x+3)²', '(x-9)(x+1)'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_8', question: 'Expand: (2x + 3)²', options: ['4x² + 9', '4x² + 12x + 9', '4x² + 6x + 9', '2x² + 12x + 9'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_9', question: 'Expand: (3x - 2)(2x + 5)', options: ['6x² + 11x - 10', '6x² - 11x - 10', '6x² + 11x + 10', '5x² + 11x - 10'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_10', question: 'Solve inequality: x² - 5x + 6 < 0', options: ['x < 2', '2 < x < 3', 'x > 3', 'x < 2 or x > 3'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_11', question: 'Solve simultaneous: 2x + 3y = 13, 3x - y = 3. Find y:', options: ['y = 1', 'y = 2', 'y = 3', 'y = 4'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_12', question: 'Solve simultaneous: x + y = 5, xy = 6. Find x:', options: ['x = 2 or 3', 'x = 1 or 6', 'x = -2 or -3', 'x = 2 or -3'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_13', question: 'Rearrange to make r the subject: V = πr²h', options: ['r = V/πh', 'r = √(V/πh)', 'r = V/√(πh)', 'r = πh/V'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_14', question: 'Make x the subject: y = (3x + 2)/4', options: ['x = 4y - 2/3', 'x = (4y - 2)/3', 'x = (4y + 2)/3', 'x = 4y/3 - 2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_15', question: 'Simplify: (x³)⁴ ÷ x⁵', options: ['x⁷', 'x¹²', 'x⁶⁰', 'x⁸'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_16', question: 'Simplify: (2a²b³)³', options: ['6a⁶b⁹', '8a⁶b⁹', '8a⁵b⁶', '2a⁶b⁹'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_17', question: 'Evaluate: 27^(2/3)', options: ['3', '6', '9', '18'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_18', question: 'Evaluate: 16^(-1/2)', options: ['-8', '-4', '1/4', '1/8'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_19', question: 'Simplify: √75', options: ['5√3', '3√5', '15', '25√3'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_20', question: 'Simplify: √48 - √12', options: ['√36', '2√3', '4√3 - 2√3 = 2√3', '6'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_21', question: 'Rationalize: 1/√3', options: ['√3', '√3/3', '3/√3', '1/3'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_22', question: 'Rationalize: 6/(2+√3)', options: ['12 - 6√3', '3(2-√3)', '6(2-√3)', '12 + 6√3'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_23', question: 'Nth term of quadratic sequence 3, 8, 15, 24...?', options: ['n² + 2', 'n² + 2n', '2n² + n', 'n² + 2n - 1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_24', question: 'Find turning point of y = x² - 4x + 1', options: ['(2, -3)', '(2, 3)', '(-2, -3)', '(4, 1)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_25', question: 'Where does y = x² - 3x - 4 cross x-axis?', options: ['x = -1, 4', 'x = 1, -4', 'x = -1, -4', 'x = 1, 4'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_26', question: 'Solve graphically where y = x² and y = 2x + 3 intersect:', options: ['x = -1 or 3', 'x = 1 or -3', 'x = -1 or -3', 'x = 1 or 3'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_27', question: 'Function f(x) = 2x + 3. Find f⁻¹(x):', options: ['x/2 - 3', '(x - 3)/2', '2x - 3', 'x - 3/2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_28', question: 'If f(x) = x² and g(x) = 2x + 1, find fg(x):', options: ['2x² + 1', '(2x + 1)²', '2x² + x', 'x² + 2x + 1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_29', question: 'Domain of f(x) = 1/(x-2) is:', options: ['All real numbers', 'x ≠ 2', 'x > 2', 'x < 2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_30', question: 'Range of f(x) = x² (x ∈ ℝ) is:', options: ['All real numbers', 'y ≥ 0', 'y > 0', 'y ≤ 0'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_31', question: 'Expand and simplify: (x + 2)(x - 3)(x + 1)', options: ['x³ + 7x - 6', 'x³ - 7x - 6', 'x³ - 7x + 6', 'x³ - 5x - 6'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_32', question: 'Solve: |2x - 3| = 5', options: ['x = 4', 'x = -1', 'x = 4 or -1', 'x = 1 or -4'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_33', question: 'Prove algebraically: (n+1)² - n² = 2n + 1. First expand (n+1)²:', options: ['n² + 1', 'n² + 2n + 1', 'n² + n + 1', '2n² + 1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_34', question: 'Growth formula: P = P₀(1.05)ᵗ. What is growth rate?', options: ['1%', '5%', '10%', '50%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_35', question: 'Decay formula: N = 1000(0.9)ᵗ. After 1 year, N = ?', options: ['100', '900', '990', '910'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_36', question: 'Solve inequality: 2x - 5 > 3x + 2', options: ['x > -7', 'x < -7', 'x > 7', 'x < 7'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_37', question: 'Solve: -3 < 2x + 1 ≤ 7', options: ['-2 < x ≤ 3', '-1 < x ≤ 4', '-2 ≤ x < 3', '-1 ≤ x < 4'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_38', question: 'Graph of y = -x² has what shape?', options: ['U-shape opening up', 'Upside-down U (∩)', 'Straight line', 'Circle'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_39', question: 'Graph of y = 1/x has asymptotes at:', options: ['x = 0 only', 'y = 0 only', 'x = 0 and y = 0', 'No asymptotes'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_40', question: 'Write in form a(x + p)² + q: x² + 6x + 5', options: ['(x + 3)² - 4', '(x + 3)² + 4', '(x - 3)² - 4', '(x + 6)² + 5'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_41', question: 'Factorise: 2x² + 7x + 3', options: ['(2x + 1)(x + 3)', '(2x + 3)(x + 1)', '(x + 1)(2x + 3)', '(2x + 1)(x + 3)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_42', question: 'Simplify: (x² - 4)/(x + 2)', options: ['x - 2', 'x + 2', 'x² - 2', '(x - 2)/(x + 2)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_43', question: 'Add fractions: 2/(x+1) + 3/(x-1)', options: ['5/(2x)', '(5x - 1)/[(x+1)(x-1)]', '(5x + 1)/(x² - 1)', '5/(x² - 1)'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_44', question: 'Differentiation gives:', options: ['Area under curve', 'Gradient/rate of change', 'Total distance', 'Average value'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_45', question: 'If y = x³, dy/dx = ?', options: ['x²', '3x²', '3x³', 'x⁴'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_46', question: 'If y = 5x⁴, dy/dx = ?', options: ['5x³', '20x³', '5x⁵', '20x⁴'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_47', question: 'Gradient of y = 2x² + 3x at x = 2:', options: ['7', '10', '11', '14'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_48', question: 'Stationary point when dy/dx = ?', options: ['-1', '0', '1', 'Undefined'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_49', question: 'Maximum point has d²y/dx² that is:', options: ['Positive', 'Negative', 'Zero', 'Undefined'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_50', question: 'Minimum point has d²y/dx² that is:', options: ['Negative', 'Zero', 'Positive', 'Undefined'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },

  // ADVANCED GEOMETRY & TRIGONOMETRY (60 questions)
  { id: 'y11_math_51', question: 'Sin²θ + Cos²θ = ?', options: ['0', '1', '2', 'Tan²θ'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_52', question: 'If Sin θ = 3/5, find Cos θ (acute angle):', options: ['4/5', '3/4', '5/3', '5/4'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_53', question: 'Tan θ = Sin θ / ?', options: ['Tan θ', 'Cos θ', '1', 'Sin θ'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_54', question: 'Sin 30° = ?', options: ['1/2', '√3/2', '1', '0'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_55', question: 'Cos 60° = ?', options: ['1/2', '√3/2', '1', '0'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_56', question: 'Tan 60° = ?', options: ['1', '√3', '1/√3', '2'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_57', question: 'Sine rule: a/Sin A = b/Sin B = ?', options: ['c/Cos C', 'c/Sin C', 'c/Tan C', '2R'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_58', question: 'Cosine rule: a² = b² + c² - ?', options: ['2bc Cos A', 'bc Cos A', '2bc Sin A', 'bc Sin A'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_59', question: 'Area of triangle = (1/2)ab Sin C. If a=6, b=8, C=30°:', options: ['12', '24', '48', '6'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_60', question: 'In triangle, sides 7, 8, 9. Find largest angle using cosine rule:', options: ['Opposite side 7', 'Opposite side 8', 'Opposite side 9', 'All equal'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_61', question: 'Graph of y = Sin x has period:', options: ['90°', '180°', '360°', '720°'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_62', question: 'Graph of y = Cos x has amplitude:', options: ['0.5', '1', '2', 'π'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_63', question: 'Solve: Sin x = 0.5 for 0° ≤ x ≤ 360°', options: ['30° only', '150° only', '30° and 150°', '30° and 210°'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_64', question: 'Solve: Cos x = -1 for 0° ≤ x ≤ 360°', options: ['0°', '90°', '180°', '270°'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_65', question: 'Solve: Tan x = 1 for 0° ≤ x ≤ 360°', options: ['45° only', '45° and 135°', '45° and 225°', '135° and 315°'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_66', question: 'Vector (3, 4) has magnitude:', options: ['3', '4', '5', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_67', question: 'Vector a = (2, 3), vector b = (1, -1). Find a + b:', options: ['(3, 2)', '(1, 4)', '(3, 4)', '(2, 2)'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_68', question: 'Vector from A(1, 2) to B(4, 6) is:', options: ['(3, 4)', '(5, 8)', '(3, 8)', '(4, 3)'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_69', question: 'Scalar multiplication: 3(2, -1) = ?', options: ['(5, 2)', '(6, -3)', '(6, 3)', '(2, -3)'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_70', question: 'Circle equation: (x - a)² + (y - b)² = r². Center is:', options: ['(0, 0)', '(a, b)', '(r, 0)', '(0, r)'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_71', question: 'Circle: x² + y² = 25 has radius:', options: ['5', '25', '10', '50'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_72', question: 'Circle: (x - 3)² + (y + 2)² = 16 has center:', options: ['(3, -2)', '(-3, 2)', '(3, 2)', '(-3, -2)'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_73', question: 'Equation of tangent to circle has gradient ___ to radius:', options: ['Same as', 'Parallel', 'Perpendicular', 'Equal'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_74', question: 'Arc length = (θ/360) × 2πr. θ=60°, r=12 (π≈3.14):', options: ['6.28', '12.56', '18.84', '25.12'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_75', question: 'Sector area = (θ/360) × πr². θ=90°, r=8 (π≈3.14):', options: ['25.12', '50.24', '100.48', '200.96'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_76', question: 'Angle subtended at center is ___ angle at circumference:', options: ['Half', 'Equal to', 'Twice', 'Three times'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_77', question: 'Angles in same segment are:', options: ['Different', 'Equal', 'Complementary', 'Supplementary'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_78', question: 'Angle in semicircle is:', options: ['45°', '60°', '90°', '180°'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_79', question: 'Opposite angles in cyclic quadrilateral sum to:', options: ['90°', '180°', '270°', '360°'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_80', question: 'Alternate segment theorem: angle between tangent and chord equals:', options: ['Angle in alternate segment', 'Angle at center', '90°', '180°'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_81', question: 'Volume of sphere = (4/3)πr³. r=6 (π≈3.14):', options: ['452.16', '904.32', '226.08', '678.24'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_82', question: 'Surface area of sphere = 4πr². r=5 (π≈3.14):', options: ['78.5', '157', '314', '628'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_83', question: 'Volume of cone = (1/3)πr²h. r=4, h=9 (π≈3.14):', options: ['75.36', '150.72', '226.08', '37.68'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_84', question: 'Curved surface area of cone = πrl. r=3, l=5 (π≈3.14):', options: ['15.7', '23.55', '47.1', '78.5'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_85', question: 'Volume of pyramid = (1/3) × base area × height. Base=36, h=5:', options: ['60', '180', '120', '36'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_86', question: 'Similar shapes: if length scale factor = 3, area scale factor = ?', options: ['3', '6', '9', '27'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_87', question: 'Similar shapes: if length scale factor = 2, volume scale factor = ?', options: ['2', '4', '6', '8'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_88', question: 'Enlarge triangle area 20cm² by scale factor 4. New area?', options: ['80cm²', '160cm²', '240cm²', '320cm²'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_89', question: 'Congruent triangles have:', options: ['Same shape only', 'Same size only', 'Same shape and size', 'Nothing in common'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_90', question: 'SSS stands for:', options: ['Side-Side-Side', 'Same-Same-Same', 'Similar-Similar-Similar', 'Square-Square-Square'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_91', question: 'Pythagoras in 3D: diagonal of cuboid a×b×c = ?', options: ['√(a² + b²)', '√(a² + b² + c²)', 'a + b + c', '√(abc)'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_92', question: 'Bearing from A to B is 135°. Bearing from B to A?', options: ['45°', '225°', '315°', '135°'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_93', question: 'Transform point (4, 5) by matrix [[0, -1], [1, 0]]:', options: ['(-5, 4)', '(5, -4)', '(4, -5)', '(-4, 5)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_94', question: 'Rotation 90° anticlockwise about origin is matrix:', options: ['[[0, 1], [-1, 0]]', '[[0, -1], [1, 0]]', '[[1, 0], [0, 1]]', '[[-1, 0], [0, -1]]'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_95', question: 'Reflection in y-axis is matrix:', options: ['[[1, 0], [0, 1]]', '[[-1, 0], [0, 1]]', '[[1, 0], [0, -1]]', '[[-1, 0], [0, -1]]'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_96', question: 'Determinant of [[2, 3], [1, 4]] = ?', options: ['5', '8', '11', '-1'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_97', question: 'If determinant = 0, transformation causes:', options: ['Enlargement', 'Reduction to line/point', 'Reflection', 'Rotation'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_98', question: 'Distance formula in 3D from (0,0,0) to (3,4,12):', options: ['5', '12', '13', '19'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_99', question: 'Locus of points equidistant from two points is:', options: ['Circle', 'Perpendicular bisector', 'Parallel line', 'Arc'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_100', question: 'Locus of points 5cm from a point is:', options: ['Line', 'Circle radius 5cm', 'Square', 'Triangle'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_101', question: 'Graph transformation: y = f(x) + 3 shifts:', options: ['Left 3', 'Right 3', 'Up 3', 'Down 3'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_102', question: 'Graph transformation: y = f(x - 2) shifts:', options: ['Left 2', 'Right 2', 'Up 2', 'Down 2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_103', question: 'Graph transformation: y = 2f(x) is:', options: ['Horizontal stretch factor 2', 'Vertical stretch factor 2', 'Shift up 2', 'Shift right 2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_104', question: 'Graph transformation: y = f(2x) is:', options: ['Vertical stretch factor 2', 'Horizontal stretch factor 1/2', 'Shift left 2', 'Shift up 2'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_105', question: 'Graph transformation: y = -f(x) is reflection in:', options: ['x-axis', 'y-axis', 'y=x', 'Origin'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_106', question: 'Graph transformation: y = f(-x) is reflection in:', options: ['x-axis', 'y-axis', 'y=x', 'Origin'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_107', question: 'Gradient between (1, 3) and (5, 11) is:', options: ['2', '3', '4', '8'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_108', question: 'Perpendicular to y = 3x + 2 has gradient:', options: ['3', '-3', '1/3', '-1/3'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_109', question: 'Equation of line through (2, 5) with gradient 3:', options: ['y = 3x - 1', 'y = 3x + 1', 'y = 3x - 5', 'y = 3x + 5'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_110', question: 'y-intercept of line 2x + 3y = 12:', options: ['2', '3', '4', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },

  // RATIO, PROPORTION & APPLICATIONS (40 questions)
  { id: 'y11_math_111', question: 'Direct proportion: y ∝ x². If y = 20 when x = 2, find y when x = 5:', options: ['50', '100', '125', '250'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_112', question: 'Inverse proportion: y ∝ 1/x². If y = 4 when x = 2, find y when x = 4:', options: ['0.5', '1', '2', '16'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_113', question: 'Compound interest: ₦5000 at 6% for 2 years. Total?', options: ['₦5,600', '₦5,618', '₦5,630', '₦6,000'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_114', question: 'Depreciation: Car worth ₦2,000,000 loses 15% per year. After 1 year?', options: ['₦1,700,000', '₦1,750,000', '₦1,800,000', '₦1,850,000'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_115', question: 'Reverse percentage: After 20% VAT, price is ₦1,200. Original?', options: ['₦960', '₦1,000', '₦1,080', '₦1,440'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_116', question: 'Multiplier for 12% increase:', options: ['0.12', '0.88', '1.12', '1.88'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_117', question: 'Multiplier for 30% decrease:', options: ['0.3', '0.7', '1.3', '1.7'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_118', question: 'Compound percentage: Increase 10% then 20%. Overall?', options: ['30%', '32%', '28%', '30.2%'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_119', question: 'Map scale 1:25,000. 8cm represents?', options: ['200m', '2km', '20km', '200km'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_120', question: 'Speed-time graph: area under gives:', options: ['Speed', 'Acceleration', 'Distance', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_121', question: 'Distance-time graph: gradient gives:', options: ['Distance', 'Time', 'Speed', 'Acceleration'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_122', question: 'Density = mass / volume. Mass 800g, density 4g/cm³. Volume?', options: ['200cm³', '320cm³', '3200cm³', '20cm³'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_123', question: 'Pressure = force / area. Force 200N, area 4m². Pressure?', options: ['50 Pa', '800 Pa', '196 Pa', '204 Pa'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_124', question: 'Best buy: 400g for ₦320 or 600g for ₦450?', options: ['400g', '600g', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_125', question: 'Currency conversion: £1 = ₦950. Convert ₦3,800 to pounds:', options: ['£3', '£4', '£5', '£40'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_126', question: 'Simple interest: I = PRT/100. P=₦2000, R=5%, T=3 years:', options: ['₦150', '₦200', '₦300', '₦350'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_127', question: 'Compound interest formula: A = P(1 + r/100)ⁿ. What is n?', options: ['Principal', 'Rate', 'Time period', 'Amount'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_128', question: 'Growth factor for 8% increase:', options: ['0.08', '0.92', '1.08', '1.8'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_129', question: 'Exponential growth: N = 100 × 1.5ᵗ. When t=2, N=?', options: ['150', '200', '225', '300'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_130', question: 'Ratio 2:3:5. Total = 200. Largest share?', options: ['40', '60', '80', '100'], correctAnswer: 3, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_131', question: 'Divide ₦3,600 in ratio 5:7. Smaller share?', options: ['₦1,200', '₦1,500', '₦2,100', '₦2,400'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_132', question: 'If 8 workers take 12 days, how long for 6 workers?', options: ['9 days', '12 days', '14 days', '16 days'], correctAnswer: 3, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_133', question: 'Speed = distance / time. Average speed if 60km in 1.5 hours?', options: ['40 km/h', '45 km/h', '50 km/h', '90 km/h'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_134', question: 'Convert 25 m/s to km/h:', options: ['25 km/h', '50 km/h', '90 km/h', '1500 km/h'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_135', question: 'Profit % = (profit/cost) × 100. Cost ₦400, sell ₦500. Profit %?', options: ['20%', '25%', '30%', '80%'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_136', question: 'Loss % = (loss/cost) × 100. Cost ₦1200, sell ₦900. Loss %?', options: ['20%', '25%', '30%', '33.3%'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_137', question: 'Mark-up 40% on cost ₦500. Selling price?', options: ['₦540', '₦600', '₦700', '₦900'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_138', question: 'Discount 20% on ₦5,000. Sale price?', options: ['₦1,000', '₦4,000', '₦4,500', '₦4,800'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_139', question: 'Population growth 3% per year. Formula for year n:', options: ['P(1.03)ⁿ', 'P(0.03)ⁿ', 'P + 0.03n', 'P(1.3)ⁿ'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_140', question: 'Decay formula: N = N₀(1/2)^(t/h). h is:', options: ['Initial amount', 'Final amount', 'Half-life', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_141', question: 'Standard form: 5.6 × 10⁻⁴ as decimal:', options: ['0.00056', '0.0056', '0.056', '5600'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_142', question: 'Calculate: (4 × 10⁵) ÷ (2 × 10²)', options: ['2 × 10³', '2 × 10⁷', '8 × 10³', '8 × 10⁷'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_143', question: 'Upper bound for 50 (to nearest 10):', options: ['50', '54.9', '55', '59.9'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_144', question: 'Lower bound for 7.2 (to 1 d.p.):', options: ['7.1', '7.15', '7.2', '7.25'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_145', question: 'Round 2.847 to 2 significant figures:', options: ['2.8', '2.85', '2.9', '3.0'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_146', question: 'Estimate √200:', options: ['10', '14', '20', '100'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_147', question: 'Truncate 5.786 to 2 decimal places:', options: ['5.78', '5.79', '5.8', '6'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_148', question: 'Error interval for 40kg (to nearest kg):', options: ['39 ≤ x < 40', '39.5 ≤ x < 40.5', '39 < x < 41', '40 ≤ x < 41'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_149', question: 'Percentage error if true value 50, measured 48:', options: ['2%', '4%', '8%', '96%'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_150', question: 'Absolute error = |measured - true|. If measured 25, true 23:', options: ['1', '2', '23', '48'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },

  // STATISTICS & PROBABILITY (50 questions)
  { id: 'y11_math_151', question: 'For grouped data, modal class is class with:', options: ['Lowest frequency', 'Highest frequency', 'Middle frequency', 'No frequency'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_152', question: 'Estimate mean from grouped data using:', options: ['Actual values', 'Midpoints', 'Upper bounds', 'Lower bounds'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_153', question: 'In histogram, frequency = frequency density × ___:', options: ['Total', 'Class width', 'Mean', 'Median'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_154', question: 'Cumulative frequency graph: median at total frequency / ?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_155', question: 'On cumulative frequency graph, Q1 at n / ?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_156', question: 'Interquartile range = Q3 - ___:', options: ['Q1', 'Q2', 'Minimum', 'Maximum'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_157', question: 'Outlier if value > Q3 + ___ × IQR:', options: ['1', '1.5', '2', '3'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_158', question: 'Outlier if value < Q1 - ___ × IQR:', options: ['1', '1.5', '2', '3'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_159', question: 'Box plot shows:', options: ['Only mean', 'Five-number summary', 'Only mode', 'Only range'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_160', question: 'Five-number summary is:', options: ['Mean, mode, median, range, IQR', 'Min, Q1, median, Q3, max', 'Mean ± 2SD', 'Only quartiles'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_161', question: 'Comparing distributions: consider center and ___:', options: ['Color', 'Spread', 'Name', 'Units'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_162', question: 'Which average best resists outliers?', options: ['Mean', 'Median', 'Mode', 'Range'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_163', question: 'Standard deviation measures:', options: ['Center', 'Spread from mean', 'Maximum', 'Minimum'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_164', question: 'Small standard deviation means data is:', options: ['Widely spread', 'Clustered near mean', 'Random', 'Bimodal'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_165', question: 'Correlation coefficient r ranges from:', options: ['0 to 1', '0 to 100', '-1 to 1', '-∞ to ∞'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_166', question: 'r = 1 means:', options: ['No correlation', 'Perfect positive correlation', 'Perfect negative correlation', 'Weak correlation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_167', question: 'r = -1 means:', options: ['No correlation', 'Perfect positive correlation', 'Perfect negative correlation', 'Weak correlation'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_168', question: 'r ≈ 0 means:', options: ['Perfect correlation', 'No linear correlation', 'Positive correlation', 'Negative correlation'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_169', question: 'Spearman\'s rank correlation uses:', options: ['Actual values', 'Ranks of data', 'Means', 'Modes'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_170', question: 'Regression line y = a + bx. b is:', options: ['y-intercept', 'Gradient', 'Mean', 'Median'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_171', question: 'Interpolation is:', options: ['Predicting within data range', 'Predicting beyond data range', 'Finding mean', 'Finding mode'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_172', question: 'Extrapolation is:', options: ['Predicting within data range', 'Predicting beyond data range', 'Finding mean', 'Finding mode'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_173', question: 'Tree diagram shows:', options: ['One event', 'Sequential probabilities', 'Correlation', 'Frequency'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_174', question: 'On tree diagram, multiply along ___:', options: ['Rows', 'Branches', 'Columns', 'Nowhere'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_175', question: 'For independent events: P(A and B) = P(A) × ___:', options: ['P(A)', 'P(B)', 'P(A or B)', '1'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_176', question: 'For mutually exclusive: P(A or B) = P(A) + ___:', options: ['P(A)', 'P(B)', 'P(A and B)', '0'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_177', question: 'For ANY events: P(A or B) = P(A) + P(B) - ___:', options: ['0', 'P(A and B)', '1', 'P(A)P(B)'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_178', question: 'Conditional probability P(A|B) = P(A and B) / ___:', options: ['P(A)', 'P(B)', 'P(A or B)', '1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_179', question: 'Venn diagram: n(A ∪ B) = n(A) + n(B) - ___:', options: ['n(A ∩ B)', 'n(total)', '0', 'n(A)'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_180', question: 'In Venn diagram, n(A ∩ B) represents:', options: ['Elements in A only', 'Elements in B only', 'Elements in both A and B', 'Elements in neither'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_181', question: 'Expected value = Σ(value × probability). For die, E(X) = ?', options: ['1', '3.5', '6', '21'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_182', question: 'Probability distribution: ΣP(X) must equal:', options: ['0', '0.5', '1', 'Variable'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_183', question: 'Sampling: population size 1000, sample 100. Sampling fraction?', options: ['1/100', '1/10', '1/1000', '10'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_184', question: 'Stratified sample: population has 60% female, 40% male. Sample 50:', options: ['25F, 25M', '30F, 20M', '20F, 30M', '35F, 15M'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_185', question: 'Systematic sampling selects every ___ person:', options: ['First', 'nth', 'Random', 'Last'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_186', question: 'Quota sampling ensures:', options: ['Random selection', 'Certain number from each group', 'Everyone selected', 'No one selected'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_187', question: 'Opportunity sampling uses:', options: ['Random selection', 'Convenient available people', 'Systematic approach', 'Stratified method'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_188', question: 'Sampling bias occurs when sample:', options: ['Represents population well', 'Does not represent population', 'Is large', 'Is random'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_189', question: 'Time series shows data over:', options: ['Space', 'Time', 'Categories', 'Groups'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_190', question: 'Moving average smooths out:', options: ['Errors', 'Seasonal variation', 'Mean', 'Mode'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_191', question: 'Trend is:', options: ['Short-term change', 'Long-term pattern', 'Random variation', 'Error'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y11_math_192', question: 'Quality control chart shows:', options: ['Cost', 'Whether process is in control', 'Profit', 'Sales'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y11_math_193', question: 'Hypothesis testing checks if:', options: ['Data is correct', 'Result is due to chance or real effect', 'Sample is large', 'Mean exists'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_194', question: 'Null hypothesis typically states:', options: ['There is an effect', 'There is no effect/difference', 'Sample is biased', 'Data is wrong'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_195', question: 'Alternative hypothesis states:', options: ['No effect', 'There is an effect/difference', 'Sample is perfect', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_196', question: 'Significance level 0.05 means:', options: ['50% confidence', '95% confidence', '5% confidence', '0.5% confidence'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_197', question: 'P-value < 0.05 means:', options: ['Accept null hypothesis', 'Reject null hypothesis', 'No conclusion', 'Repeat test'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_198', question: 'Type I error is:', options: ['Correct decision', 'Rejecting true null hypothesis', 'Accepting false null hypothesis', 'No error'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_199', question: 'Chi-squared test is used for:', options: ['Means', 'Association in categorical data', 'Correlation', 'Regression'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y11_math_200', question: 'Normal distribution is:', options: ['Skewed', 'Symmetric bell-shaped', 'Uniform', 'Bimodal'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 }
];
