// Year 10 Science Trivia Questions
// Based on UK Year 10 Science Curriculum Framework (GCSE Combined/Triple Science)
// 200 comprehensive questions covering Biology, Chemistry, and Physics

export const YEAR_10_SCIENCE_QUESTIONS = [
  // BIOLOGY (70 questions)
  { id: 'y10_sci_1', question: 'What is a cell?', options: ['Tissue', 'Basic unit of life', 'Organ', 'System'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_2', question: 'Plant cells have ___ but animal cells don\'t:', options: ['Nucleus', 'Cell wall, chloroplasts, large vacuole', 'Cytoplasm', 'Mitochondria'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_3', question: 'Nucleus contains:', options: ['Water', 'Genetic material (DNA)', 'Food', 'Air'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_4', question: 'Mitochondria are for:', options: ['Photosynthesis', 'Aerobic respiration', 'Storage', 'Support'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_5', question: 'Chloroplasts are for:', options: ['Respiration', 'Photosynthesis', 'Storage', 'Support'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_6', question: 'Cell membrane controls:', options: ['DNA', 'What enters/exits cell', 'Photosynthesis', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_7', question: 'Photosynthesis equation: 6CO₂ + 6H₂O → ___ + 6O₂', options: ['C₆H₁₂O₆', 'CO₂', 'H₂O', 'O₂'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_8', question: 'Photosynthesis requires:', options: ['Darkness', 'Light, CO₂, water, chlorophyll', 'Only water', 'Only oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_9', question: 'Photosynthesis produces:', options: ['CO₂', 'Glucose and oxygen', 'Only water', 'Nitrogen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_10', question: 'Aerobic respiration equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + ___ + energy', options: ['6H₂O', '6O₂', '6N₂', 'C₆H₁₂O₆'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_11', question: 'Aerobic respiration requires:', options: ['No oxygen', 'Oxygen', 'Only glucose', 'Only light'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_12', question: 'Anaerobic respiration in humans produces:', options: ['Oxygen', 'Lactic acid', 'Water', 'Glucose'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_13', question: 'Anaerobic respiration in yeast produces:', options: ['Oxygen', 'Ethanol and CO₂', 'Lactic acid', 'Water'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_14', question: 'DNA stands for:', options: ['Deoxyribonucleic Acid', 'Digital Network', 'Data Access', 'Diverse Natural'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_15', question: 'DNA structure is:', options: ['Single helix', 'Double helix', 'Triangle', 'Square'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_16', question: 'DNA bases pair: A with ___, C with ___:', options: ['T, G', 'C, G', 'G, T', 'A, C'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_17', question: 'Genes are sections of:', options: ['Protein', 'DNA', 'Water', 'Cells'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_18', question: 'Chromosomes are found in:', options: ['Cytoplasm', 'Nucleus', 'Cell membrane', 'Chloroplast'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_19', question: 'Humans have ___ pairs of chromosomes:', options: ['21', '23', '46', '92'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_20', question: 'Mitosis produces ___ cells:', options: ['1', '2 identical', '4', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_21', question: 'Mitosis is for:', options: ['Sexual reproduction', 'Growth and repair', 'Making gametes', 'Digestion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_22', question: 'Meiosis produces ___ cells:', options: ['2 identical', '4 non-identical gametes', '8', '1'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_23', question: 'Meiosis is for:', options: ['Growth', 'Making sex cells', 'Repair', 'Digestion'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_24', question: 'Gametes have ___ set of chromosomes:', options: ['Full (diploid)', 'Half (haploid)', 'Double', 'No'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_25', question: 'Fertilization joins:', options: ['Two body cells', 'Sperm and egg', 'Two chromosomes', 'Two organs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_26', question: 'Dominant alleles shown by:', options: ['Lowercase', 'Capital letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_27', question: 'Recessive alleles shown by:', options: ['Capital', 'Lowercase letters', 'Numbers', 'Symbols'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_28', question: 'Genotype Bb is:', options: ['Homozygous dominant', 'Heterozygous', 'Homozygous recessive', 'Invalid'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_29', question: 'Genotype is:', options: ['Physical appearance', 'Genetic makeup', 'Behavior', 'Environment'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_30', question: 'Phenotype is:', options: ['Genetic makeup', 'Observable characteristics', 'DNA sequence', 'Cell type'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_31', question: 'Natural selection means:', options: ['Humans choose', 'Best adapted survive and reproduce', 'Random', 'All die equally'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_32', question: 'Who proposed evolution by natural selection?', options: ['Newton', 'Charles Darwin', 'Einstein', 'Curie'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_33', question: 'Adaptation helps:', options: ['Nothing', 'Survival in environment', 'Reproduction only', 'Death'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_34', question: 'Variation caused by:', options: ['Only genes', 'Only environment', 'Genes and environment', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_35', question: 'Food chains start with:', options: ['Carnivores', 'Producers (plants)', 'Herbivores', 'Decomposers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_36', question: 'Producers make food by:', options: ['Eating', 'Photosynthesis', 'Respiration', 'Decomposition'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_37', question: 'Primary consumers are:', options: ['Plants', 'Herbivores', 'Carnivores', 'Decomposers'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_38', question: 'Decomposers:', options: ['Make food', 'Eat plants', 'Break down dead organisms', 'Are predators'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_39', question: 'Biomass ___ along food chain:', options: ['Increases', 'Decreases', 'Stays same', 'Doubles'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_40', question: 'Energy efficiency in food chain about:', options: ['100%', '50%', '10%', '1%'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_41', question: 'Enzymes are:', options: ['Minerals', 'Biological catalysts', 'Vitamins', 'Carbohydrates'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_42', question: 'Enzymes are made of:', options: ['Lipids', 'Carbohydrates', 'Proteins', 'Nucleic acids'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_43', question: 'Enzyme specificity due to:', options: ['Size', 'Active site shape', 'Color', 'Mass'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_44', question: 'Amylase breaks down:', options: ['Proteins', 'Fats', 'Starch', 'Vitamins'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_45', question: 'Protease breaks down:', options: ['Proteins', 'Fats', 'Carbohydrates', 'Water'], correctAnswer: 0, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_46', question: 'Lipase breaks down:', options: ['Proteins', 'Fats/lipids', 'Carbohydrates', 'Minerals'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_47', question: 'Optimum pH for stomach enzymes:', options: ['pH 7', 'pH 2 (acidic)', 'pH 8', 'pH 14'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_48', question: 'Optimum pH for small intestine enzymes:', options: ['pH 2', 'pH 8 (alkaline)', 'pH 1', 'pH 14'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_49', question: 'High temperature denatures enzymes by:', options: ['Making faster', 'Changing active site shape', 'Making more', 'No effect'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_50', question: 'Red blood cells carry:', options: ['White cells', 'Oxygen', 'Only CO₂', 'Food'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_51', question: 'White blood cells fight:', options: ['Oxygen', 'Infections', 'Red cells', 'Food'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_52', question: 'Platelets help:', options: ['Oxygen transport', 'Fighting infection', 'Blood clotting', 'Digestion'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_53', question: 'Plasma is:', options: ['Red cells', 'White cells', 'Liquid part of blood', 'Platelets'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_54', question: 'Arteries carry blood:', options: ['To heart', 'Away from heart', 'Nowhere', 'Only to lungs'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_55', question: 'Veins carry blood:', options: ['Away from heart', 'To heart', 'Nowhere', 'Only to brain'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_56', question: 'Capillaries are:', options: ['Large vessels', 'Tiny vessels for exchange', 'Only in lungs', 'Not blood vessels'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_57', question: 'Arteries have ___ walls than veins:', options: ['Thinner', 'Thicker and more muscular', 'Same', 'No'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_58', question: 'Veins have:', options: ['No valves', 'Valves', 'Very thick walls', 'No blood'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_59', question: 'Gas exchange in lungs occurs in:', options: ['Trachea', 'Bronchi', 'Alveoli', 'Diaphragm'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_60', question: 'Alveoli adapted with:', options: ['Thick walls', 'Thin walls and large surface area', 'No blood supply', 'Bones'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_61', question: 'Small intestine absorbs:', options: ['Oxygen', 'Nutrients', 'Only water', 'Blood'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_62', question: 'Villi increase:', options: ['Thickness', 'Surface area for absorption', 'Length only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_63', question: 'Large intestine absorbs:', options: ['Nutrients', 'Oxygen', 'Water', 'Proteins'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_64', question: 'Bile produced by:', options: ['Pancreas', 'Liver', 'Stomach', 'Small intestine'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_65', question: 'Bile emulsifies:', options: ['Proteins', 'Carbohydrates', 'Fats', 'Vitamins'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_66', question: 'Communicable diseases are:', options: ['Not infectious', 'Infectious/can spread', 'Genetic only', 'Not harmful'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_67', question: 'Pathogens are:', options: ['Helpful organisms', 'Disease-causing organisms', 'Nutrients', 'Cells'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_68', question: 'Types of pathogens include:', options: ['Only bacteria', 'Bacteria, viruses, fungi, protists', 'Only viruses', 'Only fungi'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_69', question: 'Antibiotics kill:', options: ['Viruses', 'Bacteria', 'Both', 'Neither'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_70', question: 'Vaccination provides:', options: ['Cure', 'Active immunity', 'Instant cure', 'No protection'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },

  // CHEMISTRY (65 questions)
  { id: 'y10_sci_71', question: 'Atom is:', options: ['Smallest particle of compound', 'Smallest particle of element', 'Molecule', 'Mixture'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_72', question: 'Atoms contain:', options: ['Only protons', 'Protons, neutrons, electrons', 'Only electrons', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_73', question: 'Protons have ___ charge:', options: ['Negative', 'Positive', 'Neutral', 'No charge'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_74', question: 'Electrons have ___ charge:', options: ['Positive', 'Negative', 'Neutral', 'No charge'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_75', question: 'Neutrons have ___ charge:', options: ['Positive', 'Negative', 'Neutral (no charge)', 'Double positive'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_76', question: 'Protons and neutrons in:', options: ['Electron shells', 'Nucleus', 'Outside atom', 'Nowhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_77', question: 'Electrons orbit in:', options: ['Nucleus', 'Shells/energy levels', 'Straight lines', 'Random'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_78', question: 'Atomic number =number of:', options: ['Neutrons', 'Protons', 'Electrons in outer', 'Molecules'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_79', question: 'Mass number = protons + ___:', options: ['Electrons', 'Neutrons', 'Atoms', 'Molecules'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_80', question: 'Elements made of ___ type atom:', options: ['Many', 'One', 'No', 'Two'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_81', question: 'Compounds contain ___ elements chemically bonded:', options: ['One', 'Two or more', 'No', 'Only 3'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_82', question: 'Mixtures contain ___ substances not bonded:', options: ['One', 'Two or more', 'No', 'Only elements'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_83', question: 'Periodic table arranges elements by:', options: ['Color', 'Atomic number', 'Alphabetically', 'Size'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_84', question: 'Group 1 elements:', options: ['Noble gases', 'Alkali metals', 'Halogens', 'Transition'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_85', question: 'Group 7 elements:', options: ['Alkali metals', 'Noble gases', 'Halogens', 'Alkali earth'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_86', question: 'Group 0/8 elements:', options: ['Alkali metals', 'Halogens', 'Noble gases', 'Transition'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_87', question: 'Noble gases are:', options: ['Very reactive', 'Unreactive/inert', 'Explosive', 'Liquid'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_88', question: 'Alkali metals react with water to form:', options: ['Acids', 'Alkalis and hydrogen', 'Nothing', 'Salts only'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_89', question: 'Ionic bonding involves:', options: ['Sharing electrons', 'Transfer of electrons', 'Neutrons', 'Protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_90', question: 'Covalent bonding involves:', options: ['Transfer', 'Sharing electrons', 'Losing protons', 'Gaining neutrons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_91', question: 'Ionic compounds form between:', options: ['Two metals', 'Metal and non-metal', 'Two non-metals', 'Noble gases'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_92', question: 'Covalent compounds form between:', options: ['Two metals', 'Metal and non-metal', 'Non-metals', 'Noble gases only'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_93', question: 'Metals lose electrons to form ___ ions:', options: ['Negative', 'Positive', 'Neutral', 'No ions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_94', question: 'Non-metals gain electrons to form ___ ions:', options: ['Positive', 'Negative', 'Neutral', 'No ions'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_95', question: 'Ionic compounds have ___ melting points:', options: ['Low', 'High', 'No', 'Variable'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_96', question: 'Simple covalent molecules have ___ melting points:', options: ['High', 'Low', 'No', 'Very high'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_97', question: 'pH scale ranges from:', options: ['1-10', '0-14', '1-100', '0-7'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_98', question: 'Acids have pH:', options: ['Less than 7', 'Equal to 7', 'More than 7', 'Always 14'], correctAnswer: 0, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_99', question: 'Alkalis have pH:', options: ['Less than 7', 'Equal to 7', 'More than 7', 'Always 0'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_100', question: 'Neutral pH is:', options: ['0', '7', '14', '1'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_101', question: 'Neutralization: acid + alkali →', options: ['More acid', 'Salt + water', 'Gas only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_102', question: 'Acid + metal →', options: ['Nothing', 'Salt + hydrogen', 'Water', 'Oxygen'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_103', question: 'Acid + carbonate →', options: ['Nothing', 'Salt + water + CO₂', 'Oxygen', 'Hydrogen'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_104', question: 'Exothermic reactions:', options: ['Take in heat', 'Give out heat', 'No temperature change', 'Only in labs'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_105', question: 'Endothermic reactions:', options: ['Give out heat', 'Take in heat', 'No temperature change', 'Explode'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_106', question: 'Combustion is:', options: ['Endothermic', 'Exothermic', 'Neither', 'Both'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_107', question: 'Oxidation is:', options: ['Loss of oxygen', 'Gain of oxygen/loss of electrons', 'No change', 'Gain of protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_108', question: 'Reduction is:', options: ['Gain of oxygen', 'Loss of oxygen/gain of electrons', 'No change', 'Loss of protons'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_109', question: 'Conservation of mass means:', options: ['Mass increases', 'Mass conserved in reactions', 'Mass decreases', 'Mass disappears'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_110', question: 'Catalyst:', options: ['Is used up', 'Speeds up reaction without being used', 'Slows reactions', 'Makes products'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_111', question: 'Rate of reaction increases with:', options: ['Cooling', 'Temperature, concentration, surface area', 'Removing reactants', 'Adding water'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_112', question: 'Increasing temperature ___ particle collisions:', options: ['Decreases', 'Increases frequency and energy', 'Stops', 'No effect'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_113', question: 'Electrolysis is:', options: ['Using heat', 'Using electricity to break compounds', 'Mixing', 'Dissolving'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_114', question: 'At cathode (negative electrode):', options: ['Oxidation', 'Reduction', 'No reaction', 'Explosion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_115', question: 'At anode (positive electrode):', options: ['Reduction', 'Oxidation', 'No reaction', 'Explosion'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_116', question: 'Relative formula mass found by:', options: ['Counting atoms', 'Adding atomic masses of all atoms', 'Multiplying', 'Dividing'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_117', question: 'Mole is:', options: ['Small animal', '6.02 × 10²³ particles', 'Unit of volume', 'Unit of time'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_118', question: 'Avogadro\'s number is:', options: ['6.02 × 10²³', '3.14', '9.81', '1.66'], correctAnswer: 0, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_119', question: 'Concentration = amount ÷ ___:', options: ['Mass', 'Volume', 'Time', 'Temperature'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_120', question: 'Crude oil is mixture of:', options: ['Water', 'Hydrocarbons', 'Metals', 'Salts'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_121', question: 'Hydrocarbons contain only:', options: ['Hydrogen', 'Carbon', 'Hydrogen and carbon', 'Oxygen'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_122', question: 'Fractional distillation separates by:', options: ['Color', 'Boiling points', 'Smell', 'Density only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_123', question: 'Complete combustion produces:', options: ['CO + H₂', 'CO₂ + H₂O', 'C + O₂', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_124', question: 'Incomplete combustion can produce:', options: ['Only CO₂', 'Carbon monoxide (CO) and/or soot', 'Only water', 'Oxygen'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_125', question: 'Carbon monoxide is:', options: ['Harmless', 'Toxic', 'Useful fuel', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_126', question: 'Greenhouse gases include:', options: ['Oxygen', 'CO₂, methane', 'Nitrogen', 'Hydrogen'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_127', question: 'Greenhouse effect causes:', options: ['Cooling', 'Global warming', 'No change', 'Ice age'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_128', question: 'Metals generally:', options: ['Dull, brittle', 'Shiny, malleable, good conductors', 'Gases', 'Poor conductors'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_129', question: 'Reactivity series orders metals by:', options: ['Alphabetically', 'How reactive', 'Size', 'Color'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_130', question: 'More reactive metal ___ less reactive from compounds:', options: ['Cannot displace', 'Can displace', 'Ignores', 'Bonds with'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_131', question: 'Metals extracted from:', options: ['Thin air', 'Ores (rocks containing metal compounds)', 'Water', 'Soil only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_132', question: 'Aluminium extracted by:', options: ['Heating', 'Electrolysis', 'Dissolving', 'Filtering'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_133', question: 'Iron ore reduced in blast furnace using:', options: ['Water', 'Carbon/coke', 'Air', 'Salt'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_134', question: 'Alloy is:', options: ['Pure metal', 'Mixture of metals (or metal + non-metal)', 'Compound', 'Gas'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_135', question: 'Alloys are often ___ than pure metals:', options: ['Weaker', 'Harder/stronger', 'Softer', 'Same'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },

  // PHYSICS (65 questions)
  { id: 'y10_sci_136', question: 'Force measured in:', options: ['Meters', 'Newtons (N)', 'Kilograms', 'Joules'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_137', question: 'Mass measured in:', options: ['Newtons', 'Kilograms (kg)', 'Meters', 'Seconds'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_138', question: 'Weight is:', options: ['Same as mass', 'Force due to gravity', 'Always 10N', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_139', question: 'Weight = mass × ___:', options: ['Time', 'Distance', 'Gravitational field strength', 'Speed'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_140', question: 'On Earth, g ≈ ___ N/kg:', options: ['5', '10', '15', '100'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_141', question: 'Newton\'s First Law: object stays at rest/motion unless:', options: ['It wants to', 'Unbalanced force acts', 'It tires', 'Never'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_142', question: 'Newton\'s Second Law: F = m × ___:', options: ['t', 'd', 'a', 'v'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_143', question: 'Newton\'s Third Law: action has equal and opposite ___:', options: ['Mass', 'Reaction', 'Distance', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_144', question: 'Speed = distance ÷ ___:', options: ['Mass', 'Force', 'Time', 'Acceleration'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_145', question: 'Velocity includes:', options: ['Only speed', 'Speed and direction', 'Only direction', 'Only distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_146', question: 'Acceleration = change in velocity ÷ ___:', options: ['Distance', 'Mass', 'Time', 'Force'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_147', question: 'Acceleration measured in:', options: ['m/s', 'm/s²', 'kg', 'N'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_148', question: 'Distance-time graph: flat line means:', options: ['Moving fast', 'Stationary', 'Accelerating', 'Decelerating'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_149', question: 'Distance-time graph: straight diagonal means:', options: ['Stationary', 'Constant speed', 'Accelerating', 'Stopping'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_150', question: 'Distance-time graph: curved line means:', options: ['Constant speed', 'Stationary', 'Changing speed (acceleration)', 'Nothing'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_151', question: 'Gradient of distance-time graph:', options: ['Distance', 'Time', 'Speed', 'Acceleration'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_152', question: 'Velocity-time graph: gradient gives:', options: ['Speed', 'Distance', 'Acceleration', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_153', question: 'Velocity-time graph: area under gives:', options: ['Speed', 'Acceleration', 'Distance', 'Time'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_154', question: 'Stopping distance = thinking distance + ___:', options: ['Speed', 'Braking distance', 'Time', 'Mass'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_155', question: 'Thinking distance increases with:', options: ['Better brakes', 'Slower speed', 'Faster speed/slower reaction', 'Nothing'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_156', question: 'Braking distance increases with:', options: ['Lower speed', 'Higher speed, wet roads, worn brakes', 'Better conditions', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_157', question: 'Momentum = mass × ___:', options: ['Acceleration', 'Time', 'Velocity', 'Force'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_158', question: 'In collision, total momentum:', options: ['Lost', 'Conserved', 'Doubled', 'Halved'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_159', question: 'Work done = force × ___:', options: ['Time', 'Mass', 'Distance moved in direction of force', 'Velocity'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_160', question: 'Work done measured in:', options: ['Newtons', 'Watts', 'Joules', 'Kilograms'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_161', question: 'Energy measured in:', options: ['Newtons', 'Watts', 'Joules', 'Meters'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_162', question: 'Kinetic energy = ½ × mass × ___²:', options: ['Time', 'Distance', 'Velocity', 'Force'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_163', question: 'Gravitational potential energy = m × g × ___:', options: ['Time', 'Velocity', 'Height', 'Distance'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_164', question: 'Law of conservation of energy:', options: ['Energy created', 'Energy destroyed', 'Energy conserved (can\'t be created/destroyed)', 'Energy doubles'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_165', question: 'Power = work done ÷ ___:', options: ['Force', 'Distance', 'Time', 'Mass'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_166', question: 'Power measured in:', options: ['Joules', 'Newtons', 'Watts', 'Kilograms'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_167', question: 'Efficiency = (useful energy out ÷ total energy in) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_168', question: 'No machine 100% efficient because:', options: ['All useful', 'Some wasted (heat, sound)', 'Perfect', 'Energy created'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_169', question: 'Current measured in:', options: ['Volts', 'Amperes (A)', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_170', question: 'Voltage/potential difference measured in:', options: ['Amperes', 'Volts (V)', 'Ohms', 'Watts'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_171', question: 'Resistance measured in:', options: ['Amperes', 'Volts', 'Ohms (Ω)', 'Watts'], correctAnswer: 2, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_172', question: 'Ohm\'s Law: V = I × ___:', options: ['T', 'P', 'R', 'M'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_173', question: 'Series circuits: current is:', options: ['Different everywhere', 'Same everywhere', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_174', question: 'Parallel circuits: voltage is:', options: ['Different across branches', 'Same across each branch', 'Zero', 'Infinite'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_175', question: 'Power = voltage × ___:', options: ['Resistance', 'Current', 'Time', 'Distance'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_176', question: 'Energy transferred = power × ___:', options: ['Voltage', 'Current', 'Time', 'Resistance'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_177', question: 'Like charges:', options: ['Attract', 'Repel', 'No effect', 'Bond'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_178', question: 'Opposite charges:', options: ['Repel', 'Attract', 'No effect', 'Explode'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_179', question: 'Like magnetic poles:', options: ['Attract', 'Repel', 'No effect', 'Bond'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_180', question: 'Opposite magnetic poles:', options: ['Repel', 'Attract', 'No effect', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 30 },
  { id: 'y10_sci_181', question: 'Electromagnets use ___ to create field:', options: ['Permanent magnets', 'Electric current through coil', 'Gravity', 'Heat'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_182', question: 'Density = mass ÷ ___:', options: ['Time', 'Volume', 'Force', 'Distance'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_183', question: 'Pressure = force ÷ ___:', options: ['Time', 'Mass', 'Area', 'Distance'], correctAnswer: 2, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_184', question: 'Pressure measured in:', options: ['Newtons', 'Pascals (Pa)', 'Joules', 'Watts'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_185', question: 'Hooke\'s Law: extension ∝ ___:', options: ['Mass', 'Force (within limit)', 'Time', 'Temperature'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_186', question: 'Spring constant measured in:', options: ['N', 'N/m', 'kg', 'J'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_187', question: 'Moments = force × ___:', options: ['Time', 'Perpendicular distance from pivot', 'Mass', 'Velocity'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_188', question: 'Balanced when clockwise moments = ___ moments:', options: ['No', 'Anticlockwise', 'All', 'Zero'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_189', question: 'Wave speed = frequency × ___:', options: ['Time', 'Amplitude', 'Wavelength', 'Energy'], correctAnswer: 2, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_190', question: 'Transverse waves: oscillations ___ to direction:', options: ['Parallel', 'Perpendicular', 'Same', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_191', question: 'Longitudinal waves: oscillations ___ to direction:', options: ['Perpendicular', 'Parallel', 'Opposite', 'Random'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_192', question: 'Sound waves are:', options: ['Transverse', 'Longitudinal', 'Electromagnetic', 'Light'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_193', question: 'Light waves are:', options: ['Longitudinal', 'Transverse', 'Sound', 'Water only'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_194', question: 'Electromagnetic spectrum includes:', options: ['Only light', 'Radio, micro, infrared, visible, UV, X-ray, gamma', 'Only sound', 'Only heat'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_195', question: 'All EM waves travel at ___ in vacuum:', options: ['Different speeds', 'Speed of light (3×10⁸ m/s)', 'Speed of sound', 'Zero'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_196', question: 'Radioactivity is:', options: ['Safe', 'Emission of radiation from unstable nuclei', 'Light', 'Sound'], correctAnswer: 1, difficulty: 'medium', xpReward: 35 },
  { id: 'y10_sci_197', question: 'Alpha particles are:', options: ['Electrons', 'Helium nuclei', 'Protons', 'Neutrons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_198', question: 'Beta particles are:', options: ['Protons', 'Electrons', 'Helium nuclei', 'Neutrons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_199', question: 'Gamma rays are:', options: ['Particles', 'Electromagnetic radiation', 'Electrons', 'Protons'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 },
  { id: 'y10_sci_200', question: 'Half-life is time for ___ of radioactive atoms to decay:', options: ['All', 'Half', 'Quarter', 'None'], correctAnswer: 1, difficulty: 'hard', xpReward: 40 }
];
