// Year 2 Mathematics Trivia Questions
// Based on UK Year 2 Maths Curriculum Framework
// 200 comprehensive questions covering all curriculum areas

export const YEAR_2_MATHS_QUESTIONS = [
  // COUNTING & NUMBER SENSE (30 questions)
  // Counting Skills
  { id: 'y2_math_1', question: 'Count in 2s: 2, 4, 6, 8, ___', options: ['9', '10', '11', '12'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_2', question: 'Count in 5s: 5, 10, 15, 20, ___', options: ['22', '23', '25', '30'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_3', question: 'Count in 10s: 10, 20, 30, 40, ___', options: ['45', '50', '55', '60'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_4', question: 'Count backwards from 50: 50, 49, 48, ___', options: ['46', '47', '49', '51'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_5', question: 'What number comes after 99?', options: ['98', '100', '101', '110'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_6', question: 'Count in 3s: 3, 6, 9, ___', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_7', question: 'What number is 10 more than 45?', options: ['35', '46', '50', '55'], correctAnswer: 3, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_8', question: 'What number is 10 less than 63?', options: ['53', '62', '64', '73'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_9', question: 'Count in 2s from 15: 15, 17, 19, ___', options: ['20', '21', '22', '23'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_10', question: 'Count in 5s from 25: 25, 30, 35, ___', options: ['36', '38', '40', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_11', question: 'Which number is between 67 and 69?', options: ['66', '67', '68', '70'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_12', question: 'Count backwards in 10s from 80: 80, 70, 60, ___', options: ['40', '50', '55', '59'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_13', question: 'What pattern do you see? 10, 20, 30, 40...', options: ['Counting in 5s', 'Counting in 10s', 'Counting in 2s', 'No pattern'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_14', question: 'Estimate: About how many apples? 🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎', options: ['About 5', 'About 10', 'About 20', 'About 50'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_15', question: 'On a number line, what comes after 56?', options: ['55', '57', '58', '60'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  
  // Place Value
  { id: 'y2_math_16', question: 'In the number 47, what does the 4 represent?', options: ['4 ones', '4 tens', '4 hundreds', '40'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_17', question: 'In the number 82, what does the 2 represent?', options: ['2 tens', '2 ones', '20', '2 hundreds'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_18', question: 'What is 6 tens and 3 ones?', options: ['36', '63', '603', '306'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_19', question: 'What is 5 tens and 0 ones?', options: ['5', '50', '500', '505'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_20', question: 'Partition 34 into tens and ones:', options: ['3 and 4', '30 and 4', '3 and 40', '34 and 0'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_21', question: 'What does the zero represent in 70?', options: ['Nothing', '0 ones', '0 tens', '7'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_22', question: 'Which number has 8 tens and 5 ones?', options: ['58', '85', '805', '508'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_23', question: 'What is another way to write 40 + 7?', options: ['407', '74', '47', '470'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_24', question: 'How many tens are in 90?', options: ['0', '9', '90', '900'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_25', question: 'What is 3 tens and 6 ones?', options: ['63', '36', '306', '633'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_26', question: 'Count in 2s backwards: 20, 18, 16, ___', options: ['12', '13', '14', '15'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_27', question: 'Complete the sequence: 45, 50, 55, 60, ___', options: ['61', '63', '65', '70'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_28', question: 'What number is missing? 72, 74, ___, 78', options: ['73', '75', '76', '77'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_29', question: 'Count in 10s from 33: 33, 43, 53, ___', options: ['54', '60', '63', '73'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_30', question: 'What is the value of the digit 7 in 75?', options: ['7', '70', '75', '700'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },

  // READING & WRITING NUMBERS (10 questions)
  { id: 'y2_math_31', question: 'How do you write the number "fifty-three"?', options: ['35', '53', '503', '530'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_32', question: 'What is 68 in words?', options: ['Six eight', 'Sixty eight', 'Eighty six', 'Six hundred eight'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_33', question: 'How do you write "ninety-two"?', options: ['29', '92', '902', '920'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_34', question: 'What number is "forty-one"?', options: ['14', '40', '41', '401'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_35', question: 'Write 100 in words:', options: ['Ten', 'One hundred', 'One thousand', 'One zero zero'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_36', question: 'What is "seventy-seven" as a number?', options: ['7', '70', '77', '777'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_37', question: 'How many tens blocks and ones blocks represent 84?', options: ['4 tens, 8 ones', '8 tens, 4 ones', '84 tens, 0 ones', '0 tens, 84 ones'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_38', question: 'On a number line from 0-100, where would 50 be?', options: ['At the start', 'In the middle', 'At the end', 'Near the start'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_39', question: 'What is "eighty" as a number?', options: ['8', '18', '80', '800'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_40', question: 'Write 25 in words:', options: ['Two five', 'Twenty five', 'Two hundred five', 'Fifty two'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // ORDERING & COMPARING NUMBERS (15 questions)
  { id: 'y2_math_41', question: 'Put in order from smallest to largest: 45, 23, 67', options: ['45, 23, 67', '23, 45, 67', '67, 45, 23', '23, 67, 45'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_42', question: 'Which is greater: 56 or 65?', options: ['56', '65', 'They are equal', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_43', question: 'Which symbol is correct? 42 ___ 38', options: ['<', '>', '=', 'None'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_44', question: 'Which is smaller: 71 or 17?', options: ['71', '17', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_45', question: '89 ___ 98. Which symbol fits?', options: ['>', '<', '=', '+'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_46', question: 'What is the missing number? 30, 40, ___, 60', options: ['45', '50', '55', '70'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_47', question: 'Order from largest to smallest: 12, 21, 2', options: ['12, 21, 2', '2, 12, 21', '21, 12, 2', '21, 2, 12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_48', question: 'What is the 3rd number in this sequence? 1st: 10, 2nd: 20, 3rd: ___', options: ['25', '30', '35', '40'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_49', question: 'Which ordinal number comes after 5th?', options: ['4th', '5th', '6th', '7th'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_50', question: 'Is 54 < 45?', options: ['Yes', 'No', 'Sometimes', 'Equal'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_51', question: 'Which number comes between 78 and 80?', options: ['77', '78', '79', '81'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_52', question: 'Complete: 33 = ___', options: ['30 + 3', '3 + 3', '30 + 30', '3 + 30'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_53', question: 'What is the 10th ordinal number?', options: ['9th', '10th', '11th', 'Ten'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_54', question: 'Put in order: 99, 9, 90', options: ['9, 90, 99', '99, 90, 9', '90, 9, 99', '9, 99, 90'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_55', question: 'Which is the greatest number: 46, 64, 40?', options: ['46', '64', '40', 'All equal'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // MORE THAN & LESS THAN (10 questions)
  { id: 'y2_math_56', question: 'What is 1 more than 59?', options: ['58', '60', '69', '50'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_57', question: 'What is 1 less than 40?', options: ['30', '39', '41', '49'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_58', question: 'What is 10 more than 73?', options: ['63', '74', '83', '93'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_59', question: 'What is 10 less than 95?', options: ['85', '84', '94', '105'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_60', question: 'Find 5 more than 48:', options: ['43', '48', '53', '58'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_61', question: 'Find 5 less than 62:', options: ['52', '57', '62', '67'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_62', question: 'Which is 10 more than 36?', options: ['26', '37', '46', '56'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_63', question: 'Which is 20 more than 30?', options: ['10', '40', '50', '60'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_64', question: 'What is 2 less than 81?', options: ['78', '79', '80', '83'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_65', question: 'What is 3 more than 87?', options: ['84', '87', '90', '97'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },

  // ADDITION (25 questions)
  { id: 'y2_math_66', question: 'What is 23 + 15?', options: ['35', '37', '38', '39'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_67', question: 'What is 45 + 32?', options: ['75', '76', '77', '78'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_68', question: 'What is 56 + 3?', options: ['53', '56', '59', '86'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_69', question: 'What is 28 + 7?', options: ['34', '35', '36', '37'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_70', question: 'What is 64 + 24?', options: ['84', '86', '88', '90'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_71', question: 'Add: 30 + 40', options: ['60', '70', '80', '90'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_72', question: 'What is 12 + 8?', options: ['18', '19', '20', '21'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_73', question: 'Add: 35 + 5', options: ['30', '35', '40', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_74', question: 'What is 51 + 28?', options: ['77', '78', '79', '80'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_75', question: 'What is 44 + 15?', options: ['57', '58', '59', '60'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_76', question: 'If I have 23 marbles and get 14 more, how many do I have?', options: ['36', '37', '38', '39'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_77', question: 'What is 60 + 30?', options: ['80', '90', '100', '110'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_78', question: 'Add: 17 + 22', options: ['37', '38', '39', '40'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_79', question: 'What is 49 + 11?', options: ['58', '59', '60', '61'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_80', question: 'What is 38 + 6?', options: ['42', '43', '44', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_81', question: 'Using a number line to add 25 + 10, you move:', options: ['Left 10', 'Right 10', 'Up 10', 'Down 10'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_82', question: 'In a part-whole model, if the whole is 50 and one part is 30, what is the other part?', options: ['10', '15', '20', '25'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_83', question: 'What is 27 + 13?', options: ['38', '39', '40', '41'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_84', question: 'Add: 55 + 25', options: ['75', '78', '80', '85'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_85', question: 'What is 31 + 9?', options: ['38', '39', '40', '41'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_86', question: 'There are 42 children in Year 1 and 36 in Year 2. How many altogether?', options: ['76', '77', '78', '79'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_87', question: 'What is 50 + 50?', options: ['90', '95', '100', '105'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_88', question: 'Add: 18 + 21', options: ['37', '38', '39', '40'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_89', question: 'What is 66 + 4?', options: ['68', '69', '70', '71'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_90', question: 'What is 43 + 27?', options: ['68', '69', '70', '71'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },

  // SUBTRACTION (25 questions)
  { id: 'y2_math_91', question: 'What is 45 - 12?', options: ['31', '32', '33', '34'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_92', question: 'What is 67 - 5?', options: ['60', '61', '62', '63'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_93', question: 'What is 58 - 23?', options: ['33', '34', '35', '36'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_94', question: 'What is 80 - 30?', options: ['40', '45', '50', '60'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_95', question: 'What is 36 - 9?', options: ['25', '26', '27', '28'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_96', question: 'Subtract: 74 - 32', options: ['40', '41', '42', '43'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_97', question: 'What is 91 - 8?', options: ['81', '82', '83', '84'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_98', question: 'What is 55 - 15?', options: ['35', '40', '45', '50'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_99', question: 'What is 62 - 7?', options: ['53', '54', '55', '56'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_100', question: 'What is 88 - 44?', options: ['42', '43', '44', '45'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_101', question: 'If I have 50 sweets and eat 12, how many are left?', options: ['36', '37', '38', '39'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_102', question: 'What is 70 - 25?', options: ['40', '45', '50', '55'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_103', question: 'What is 39 - 14?', options: ['23', '24', '25', '26'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_104', question: 'What is 100 - 35?', options: ['60', '63', '65', '70'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_105', question: 'Subtract: 47 - 6', options: ['39', '40', '41', '42'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_106', question: 'What is the difference between 65 and 30?', options: ['30', '35', '40', '45'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_107', question: 'Count back 20 from 75:', options: ['50', '55', '60', '65'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_108', question: 'What is 56 - 21?', options: ['33', '34', '35', '36'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_109', question: 'What is 83 - 9?', options: ['72', '73', '74', '75'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_110', question: 'There were 64 birds. 22 flew away. How many are left?', options: ['40', '41', '42', '43'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_111', question: 'What is 90 - 45?', options: ['40', '43', '45', '50'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_112', question: 'What is 52 - 11?', options: ['39', '40', '41', '42'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_113', question: 'What is 77 - 33?', options: ['42', '43', '44', '45'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_114', question: 'What is 48 - 18?', options: ['28', '29', '30', '31'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_115', question: 'Solve: 95 - 50 + 10 = ___', options: ['45', '50', '55', '60'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },

  // MULTIPLICATION & DIVISION (25 questions)
  { id: 'y2_math_116', question: '2 + 2 + 2 + 2 + 2 is the same as:', options: ['2 × 3', '2 × 4', '2 × 5', '5 × 5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_117', question: 'What is 2 × 5?', options: ['7', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_118', question: 'What is 5 × 3?', options: ['8', '12', '15', '18'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_119', question: 'What is 10 × 4?', options: ['14', '20', '30', '40'], correctAnswer: 3, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_120', question: 'What is double 8?', options: ['10', '12', '14', '16'], correctAnswer: 3, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_121', question: 'What is double 15?', options: ['20', '25', '30', '35'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_122', question: 'Count in 2s five times: 2, 4, 6, 8, ___', options: ['9', '10', '12', '14'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_123', question: 'What is 2 × 10?', options: ['12', '15', '20', '25'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_124', question: 'If I have 3 groups of 5 apples, how many apples in total?', options: ['8', '12', '15', '18'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_125', question: 'What is 5 × 6?', options: ['25', '28', '30', '35'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_126', question: 'Share 10 sweets equally between 2 children. How many each?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_127', question: 'Share 20 marbles equally between 5 children. How many each?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_128', question: 'What is 10 ÷ 2?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_129', question: 'What is half of 20?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_130', question: 'What is half of 16?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_131', question: 'How many groups of 5 are in 15?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_132', question: 'What is 2 × 7?', options: ['12', '14', '16', '18'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_133', question: 'An array has 2 rows of 6. How many items total?', options: ['8', '10', '12', '14'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_134', question: 'What is 5 × 10?', options: ['15', '40', '50', '55'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_135', question: 'What is 10 × 10?', options: ['20', '50', '100', '110'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_136', question: 'What is double 12?', options: ['20', '22', '24', '26'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_137', question: 'Share 12 pencils equally between 2 friends. How many each?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_138', question: 'What is 2 × 9?', options: ['16', '17', '18', '19'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_139', question: 'What is 5 × 8?', options: ['35', '38', '40', '45'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_140', question: 'What is half of 50?', options: ['20', '22', '25', '30'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // FRACTIONS (15 questions)
  { id: 'y2_math_141', question: 'What is half (½) of 10?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_142', question: 'What is a quarter (¼) of 12?', options: ['2', '3', '4', '6'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_143', question: 'If a pizza is cut into 4 equal parts, what fraction is each part?', options: ['½', '⅓', '¼', '⅕'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_144', question: 'What is ½ of 20?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_145', question: 'If a shape is divided into 3 equal parts, each part is:', options: ['½', '⅓', '¼', '⅕'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_146', question: 'How many quarters make one whole?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_147', question: 'What is ⅓ of 9?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_148', question: 'What is ¼ of 8?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_149', question: 'Which is bigger: ½ or ¼?', options: ['½', '¼', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_150', question: 'If I eat ½ of 6 cookies, how many did I eat?', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_151', question: 'What is ⅓ of 15?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_152', question: 'How many halves make one whole?', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_153', question: 'What is ¼ of 20?', options: ['4', '5', '6', '8'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_154', question: 'If a chocolate bar has 8 pieces and you eat ½, how many pieces did you eat?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_155', question: 'Which is smaller: ⅓ or ½?', options: ['⅓', '½', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },

  // MONEY (15 questions)
  { id: 'y2_math_156', question: 'How many 1p coins make 10p?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_157', question: 'What is 5p + 5p?', options: ['8p', '9p', '10p', '15p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_158', question: 'How many 2p coins make 10p?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_159', question: 'What is 10p + 20p?', options: ['20p', '25p', '30p', '35p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_160', question: 'If a pencil costs 15p and you pay with 20p, how much change?', options: ['3p', '4p', '5p', '6p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_161', question: 'What is 50p + 50p?', options: ['80p', '90p', '£1', '£1.50'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_162', question: 'How many 5p coins make 20p?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_163', question: 'What is 25p + 25p?', options: ['40p', '45p', '50p', '55p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_164', question: 'If an apple costs 30p and you give 50p, how much change?', options: ['10p', '15p', '20p', '25p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_165', question: 'How many pence in £1?', options: ['10', '50', '100', '200'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_166', question: 'What is 40p + 35p?', options: ['65p', '70p', '75p', '80p'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_167', question: 'How many 10p coins make £1?', options: ['5', '8', '10', '12'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_168', question: 'If a toy costs 45p and you pay with £1, how much change?', options: ['45p', '50p', '55p', '60p'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_169', question: 'What is 20p + 15p + 10p?', options: ['40p', '42p', '45p', '50p'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_170', question: 'Which coin is worth more: 20p or 50p?', options: ['20p', '50p', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },

  // MEASUREMENT (20 questions)
  // Length & Height
  { id: 'y2_math_171', question: 'Which unit is used to measure length?', options: ['Litres', 'Centimetres', 'Kilograms', 'Minutes'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_172', question: 'Which is longer: 50cm or 1m?', options: ['50cm', '1m', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_173', question: 'How many centimetres in 1 metre?', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_174', question: 'Which is taller: 2m or 150cm?', options: ['2m', '150cm', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_175', question: 'A pencil is about 15___ long:', options: ['metres', 'centimetres', 'kilometres', 'millimetres'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  
  // Mass/Weight
  { id: 'y2_math_176', question: 'Which unit measures weight?', options: ['Litres', 'Centimetres', 'Kilograms', 'Hours'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_177', question: 'Which is heavier: 1kg or 500g?', options: ['1kg', '500g', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_178', question: 'How many grams in 1 kilogram?', options: ['10', '100', '500', '1000'], correctAnswer: 3, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_179', question: 'A bag of sugar weighs about 1___:', options: ['gram', 'kilogram', 'tonne', 'litre'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_180', question: 'Which is lighter: 200g or 2kg?', options: ['200g', '2kg', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  
  // Capacity
  { id: 'y2_math_181', question: 'Which unit measures capacity?', options: ['Litres', 'Centimetres', 'Kilograms', 'Hours'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_182', question: 'How many millilitres in 1 litre?', options: ['10', '100', '500', '1000'], correctAnswer: 3, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_183', question: 'Which holds more: 1 litre or 500ml?', options: ['1 litre', '500ml', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_184', question: 'A cup holds about 250___:', options: ['litres', 'millilitres', 'kilograms', 'grams'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_185', question: 'Which container holds more: 2 litres or 1500ml?', options: ['2 litres', '1500ml', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },
  
  // Temperature
  { id: 'y2_math_186', question: 'What do we use to measure temperature?', options: ['Ruler', 'Scales', 'Thermometer', 'Clock'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_187', question: 'Water freezes at:', options: ['0°C', '10°C', '50°C', '100°C'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_188', question: 'Which is hotter: 25°C or 10°C?', options: ['25°C', '10°C', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_189', question: 'On a hot summer day, the temperature might be:', options: ['0°C', '10°C', '25°C', '-5°C'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_190', question: 'Which is colder: 5°C or 15°C?', options: ['5°C', '15°C', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },

  // TIME (15 questions)
  { id: 'y2_math_191', question: 'When the hour hand points to 3 and minute hand to 12, what time is it?', options: ['12 o\'clock', '3 o\'clock', '6 o\'clock', '9 o\'clock'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_192', question: 'When the minute hand points to 6, it shows:', options: ['Quarter past', 'Half past', 'Quarter to', 'O\'clock'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_193', question: 'What time is half past 4?', options: ['4:15', '4:30', '4:45', '5:00'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_194', question: 'Quarter past 2 is the same as:', options: ['2:15', '2:30', '2:45', '3:00'], correctAnswer: 0, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_195', question: 'Quarter to 5 is the same as:', options: ['4:15', '4:30', '4:45', '5:15'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_196', question: 'How many days in a week?', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_197', question: 'How many months in a year?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_198', question: 'Which is longer: 1 hour or 30 minutes?', options: ['1 hour', '30 minutes', 'Same', 'Cannot tell'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_199', question: 'What comes after Tuesday?', options: ['Monday', 'Wednesday', 'Thursday', 'Friday'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_200', question: 'How many weeks in a year?', options: ['48', '50', '52', '54'], correctAnswer: 2, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_math_201', question: 'If it is 3 o\'clock now, what time will it be in 2 hours?', options: ['4 o\'clock', '5 o\'clock', '6 o\'clock', '1 o\'clock'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_202', question: 'What month comes after May?', options: ['April', 'June', 'July', 'August'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_203', question: 'The short hand on a clock shows:', options: ['Minutes', 'Hours', 'Seconds', 'Days'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_204', question: 'How many hours in a day?', options: ['12', '20', '24', '30'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_205', question: 'How many minutes in half an hour?', options: ['15', '20', '30', '60'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // GEOMETRY - SHAPE & POSITION (15 questions)
  { id: 'y2_math_206', question: 'A square has ___ equal sides:', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_207', question: 'How many sides does a pentagon have?', options: ['4', '5', '6', '7'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_208', question: 'How many sides does a hexagon have?', options: ['4', '5', '6', '7'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_209', question: 'What 3D shape is a ball?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_210', question: 'What 3D shape is a box?', options: ['Cube', 'Sphere', 'Cylinder', 'Cone'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_211', question: 'A rectangle has ___ corners:', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_212', question: 'A quarter turn is:', options: ['45 degrees', '90 degrees', '180 degrees', '360 degrees'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_math_213', question: 'A half turn is:', options: ['90 degrees', '180 degrees', '270 degrees', '360 degrees'], correctAnswer: 1, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_math_214', question: 'A full turn is:', options: ['90 degrees', '180 degrees', '270 degrees', '360 degrees'], correctAnswer: 3, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_math_215', question: 'If you face forward and do a quarter turn right, you face:', options: ['Left', 'Right', 'Backward', 'Forward'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_216', question: 'If you face forward and do a half turn, you face:', options: ['Left', 'Right', 'Backward', 'Forward'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_217', question: 'The opposite of left is:', options: ['Up', 'Down', 'Right', 'Forward'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_218', question: 'If something is above you, it is:', options: ['Higher up', 'Lower down', 'Beside you', 'Behind you'], correctAnswer: 0, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_219', question: 'A triangle has ___ vertices (corners):', options: ['2', '3', '4', '5'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_220', question: 'Which shape has no straight sides?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // STATISTICS (10 questions)
  { id: 'y2_math_221', question: 'A tally chart uses marks to:', options: ['Draw pictures', 'Count things', 'Tell time', 'Measure'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_222', question: 'In a pictogram, if 🍎 = 2 apples, how many apples do 🍎🍎🍎 represent?', options: ['3', '4', '5', '6'], correctAnswer: 3, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_223', question: 'A block graph shows information using:', options: ['Pictures', 'Blocks', 'Lines', 'Numbers only'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_224', question: 'If the block for cats goes up to 8 and dogs to 5, there are ___ more cats:', options: ['2', '3', '4', '13'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_225', question: 'What does sorting information help us do?', options: ['Make a mess', 'Organize and compare data', 'Waste time', 'Break things'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_226', question: 'In a survey of favourite colours, if 12 chose blue and 8 chose red, which is more popular?', options: ['Red', 'Blue', 'Same', 'Cannot tell'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_227', question: 'If |||| represents 4, what does |||| |||| represent?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_228', question: 'A pictogram uses ___ to show data:', options: ['Numbers only', 'Pictures or symbols', 'Words only', 'Letters'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_229', question: 'If more children like dogs than cats, the bar for dogs is:', options: ['Shorter', 'Taller', 'Same', 'Missing'], correctAnswer: 1, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_230', question: 'What type of graph uses bars to show information?', options: ['Pictogram', 'Tally chart', 'Block graph', 'Pie chart'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },

  // REASONING & PROBLEM SOLVING (10 questions)
  { id: 'y2_math_231', question: 'I have 15. I need 23. How many more do I need?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_232', question: 'What is missing? 5 + ___ = 12', options: ['5', '6', '7', '8'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_233', question: 'I have 30p. I buy a sweet for 15p. How much do I have left?', options: ['10p', '12p', '15p', '20p'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_234', question: '20 - ___ = 12. What is missing?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'easy', xpReward: 15 },
  { id: 'y2_math_235', question: 'How many different ways can you make 10? (e.g., 5+5, 6+4...)', options: ['3 ways', '5 ways', 'Many ways', 'Only 1 way'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_236', question: 'If 15 + 10 = 25, then 25 - 10 = ___', options: ['10', '15', '20', '25'], correctAnswer: 1, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_237', question: 'There are 24 children. Half go outside. How many go outside?', options: ['10', '11', '12', '13'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_238', question: 'If I have £1 and spend 60p, how much is left?', options: ['30p', '35p', '40p', '50p'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 },
  { id: 'y2_math_239', question: 'What number is 5 more than 18 and 5 less than 28?', options: ['20', '21', '22', '23'], correctAnswer: 3, difficulty: 'hard', xpReward: 25 },
  { id: 'y2_math_240', question: 'If ___ + 17 = 25, what is the missing number?', options: ['6', '7', '8', '9'], correctAnswer: 2, difficulty: 'medium', xpReward: 20 }
];
