// Year 12 Mathematics Trivia Questions
// Based on UK Year 12 Maths Curriculum Framework (A-Level AS - Pure, Mechanics, Statistics)
// 200 comprehensive questions covering A-Level AS Mathematics

export const YEAR_12_MATHS_QUESTIONS = [
  // PURE MATHEMATICS - CALCULUS (50 questions)
  { id: 'y12_math_1', question: 'Differentiate: y = x³', options: ['x²', '3x²', '3x³', 'x⁴/4'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_2', question: 'Differentiate: y = 5x⁴', options: ['5x³', '20x³', '5x⁵', '20x⁴'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_3', question: 'Differentiate: y = x⁻²', options: ['-2x⁻³', '-2x⁻¹', '-x⁻³', '2x⁻³'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_4', question: 'Differentiate: y = √x', options: ['1/(2√x)', '2√x', '√x/2', 'x/(2√x)'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_5', question: 'Chain rule: dy/dx = dy/du × ___', options: ['dx/du', 'du/dx', 'dy/dx', 'dx/dy'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_6', question: 'Differentiate: y = (2x + 3)⁴', options: ['8(2x + 3)³', '4(2x + 3)³', '8(2x + 3)⁴', '2(2x + 3)³'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_7', question: 'Product rule: d/dx[uv] = u(dv/dx) + ___', options: ['v(du/dx)', 'du/dv', 'dv/du', 'u × v'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_8', question: 'Differentiate: y = x²sin(x) using product rule:', options: ['2xsin(x) + x²cos(x)', 'x²cos(x)', '2xsin(x)', '2xcos(x)'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_9', question: 'Quotient rule: d/dx[u/v] = [v(du/dx) - u(dv/dx)] / ___', options: ['v', 'v²', 'u²', 'uv'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_10', question: 'Find dy/dx when y = eˣ:', options: ['xeˣ⁻¹', 'eˣ', 'eˣ⁻¹', 'ln(x)'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_11', question: 'Find dy/dx when y = ln(x):', options: ['x', '1/x', 'ln(x)/x', 'eˣ'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_12', question: 'Find dy/dx when y = sin(x):', options: ['-cos(x)', 'cos(x)', '-sin(x)', 'tan(x)'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_13', question: 'Find dy/dx when y = cos(x):', options: ['sin(x)', '-sin(x)', 'cos(x)', '-cos(x)'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_14', question: 'Find dy/dx when y = tan(x):', options: ['sec²(x)', '-sec²(x)', 'cos²(x)', 'sin²(x)'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_15', question: 'Stationary point when dy/dx = ___:', options: ['-1', '0', '1', 'Undefined'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_16', question: 'Maximum when d²y/dx² is:', options: ['Positive', 'Negative', 'Zero', 'Undefined'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_17', question: 'Minimum when d²y/dx² is:', options: ['Negative', 'Zero', 'Positive', 'Undefined'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_18', question: 'Point of inflection when d²y/dx² = ___:', options: ['-1', '0', '1', 'Maximum'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_19', question: 'Integrate: ∫x² dx', options: ['x³/3 + c', '2x + c', 'x³ + c', 'x²/2 + c'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_20', question: 'Integrate: ∫4x³ dx', options: ['12x² + c', 'x⁴ + c', '4x⁴ + c', 'x⁴/4 + c'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_21', question: 'Integrate: ∫(3x² + 2x) dx', options: ['x³ + x² + c', '6x + 2 + c', '3x³ + 2x² + c', 'x³ + 2x + c'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_22', question: 'Integrate: ∫eˣ dx', options: ['xeˣ + c', 'eˣ + c', 'eˣ/x + c', 'ln(x) + c'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_23', question: 'Integrate: ∫1/x dx', options: ['ln(x) + c', 'x⁻¹ + c', '1/x² + c', 'eˣ + c'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_24', question: 'Integrate: ∫sin(x) dx', options: ['cos(x) + c', '-cos(x) + c', 'sin(x) + c', '-sin(x) + c'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_25', question: 'Integrate: ∫cos(x) dx', options: ['-sin(x) + c', 'sin(x) + c', 'cos(x) + c', '-cos(x) + c'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_26', question: 'Definite integral ∫₀² x dx equals:', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_27', question: 'Area under curve found by:', options: ['Differentiation', 'Integration', 'Factorization', 'Substitution'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_28', question: 'Trapezium rule estimates:', options: ['Derivatives', 'Area under curve', 'Turning points', 'Gradients'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_29', question: 'What is e approximately equal to?', options: ['2.718', '3.142', '1.414', '1.732'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_30', question: 'ln(e) = ___:', options: ['0', '1', 'e', 'Undefined'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_31', question: 'e⁰ = ___:', options: ['0', '1', 'e', 'Undefined'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_32', question: 'ln(1) = ___:', options: ['0', '1', 'e', 'Undefined'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_33', question: 'Laws of logs: ln(a) + ln(b) = ___:', options: ['ln(a + b)', 'ln(ab)', 'ln(a/b)', 'ln(a - b)'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_34', question: 'Laws of logs: ln(a) - ln(b) = ___:', options: ['ln(a - b)', 'ln(ab)', 'ln(a/b)', 'ln(b/a)'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_35', question: 'Laws of logs: ln(aⁿ) = ___:', options: ['n × ln(a)', 'ln(a) + n', 'ln(a)/n', 'ln(n) × a'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_36', question: 'Solve: eˣ = 5', options: ['x = 5', 'x = e⁵', 'x = ln(5)', 'x = log(5)'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_37', question: 'Implicit differentiation: x² + y² = 25. Find dy/dx:', options: ['-x/y', '-y/x', 'x/y', 'y/x'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_38', question: 'Parametric equations: x = t², y = 2t. Find dy/dx:', options: ['1/t', 't', '2/t', '1/(2t)'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_39', question: 'Small changes formula: δy ≈ (dy/dx) × ___:', options: ['δx', 'dx', 'x', 'y'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_40', question: 'Rate of change of volume of sphere: dV/dt = 4πr² × ___:', options: ['dr/dt', 'dθ/dt', 'dt/dr', 'r'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_41', question: 'Increasing function has dy/dx:', options: ['< 0', '> 0', '= 0', 'Undefined'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_42', question: 'Decreasing function has dy/dx:', options: ['> 0', '= 0', '< 0', 'Undefined'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_43', question: 'Concave up (convex) when d²y/dx²:', options: ['< 0', '= 0', '> 0', 'Undefined'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_44', question: 'Concave down when d²y/dx²:', options: ['> 0', '= 0', '< 0', 'Undefined'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_45', question: 'Integration by substitution: ∫f(g(x))g\'(x)dx = ∫f(u)du where u = ___:', options: ['x', 'g(x)', 'f(x)', 'dx'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_46', question: 'Integration by parts: ∫u(dv/dx)dx = uv - ___:', options: ['∫v(du/dx)dx', '∫u(du/dx)dx', '∫v(dv/dx)dx', 'uv'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_47', question: 'Volume of revolution about x-axis: V = π∫___:', options: ['y dx', 'y² dx', 'x² dx', 'xy dx'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_48', question: 'Maclaurin series for eˣ starts:', options: ['1 + x + x²/2 + ...', 'x + x²/2 + ...', '1 - x + x² - ...', 'x - x²/2 + ...'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_49', question: 'Gradient of tangent = gradient of curve at ___:', options: ['Any point', 'Point of contact', 'Origin', 'Asymptote'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_50', question: 'Gradient of normal = -1 / ___:', options: ['x', 'y', 'Gradient of tangent', 'Gradient of curve'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },

  // PURE MATHEMATICS - ALGEBRA & FUNCTIONS (50 questions)
  { id: 'y12_math_51', question: 'Discriminant b² - 4ac > 0 means:', options: ['No real roots', 'One repeated root', 'Two distinct real roots', 'Complex roots'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_52', question: 'Discriminant b² - 4ac = 0 means:', options: ['Two distinct roots', 'One repeated root', 'No real roots', 'Three roots'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_53', question: 'Discriminant b² - 4ac < 0 means:', options: ['Two real roots', 'One root', 'No real roots', 'Infinite roots'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_54', question: 'Sum of roots of ax² + bx + c = 0:', options: ['b/a', '-b/a', 'c/a', '-c/a'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_55', question: 'Product of roots of ax² + bx + c = 0:', options: ['b/a', '-b/a', 'c/a', '-c/a'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_56', question: 'Factor theorem: (x - a) is factor if f(a) = ___:', options: ['-1', '0', '1', 'a'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_57', question: 'Remainder theorem: f(x) ÷ (x - a) gives remainder f(___):', options: ['0', 'x', 'a', '1'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_58', question: 'Binomial expansion: (1 + x)ⁿ = 1 + nx + ___:', options: ['nx²', 'n(n-1)x²/2', 'n²x²', 'x²/2'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_59', question: 'Binomial expansion valid when:', options: ['|x| < 1', '|x| > 1', 'x = 1', 'All x'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_60', question: 'ⁿCᵣ = n! / ___:', options: ['r!(n-r)!', 'r!n!', '(n-r)!', 'n-r'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_61', question: 'Pascal\'s triangle row 4:', options: ['1 3 3 1', '1 4 6 4 1', '1 5 10 10 5 1', '1 2 1'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_62', question: 'Function f(x) = x². Domain is:', options: ['x > 0', 'x ≥ 0', 'All real x', 'x ≠ 0'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_63', question: 'Function f(x) = √x. Domain is:', options: ['All real x', 'x > 0', 'x ≥ 0', 'x ≠ 0'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_64', question: 'Function f(x) = 1/x. Domain is:', options: ['All real x', 'x > 0', 'x ≠ 0', 'x ≥ 0'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_65', question: 'Function f(x) = x². Range is:', options: ['All real y', 'y ≥ 0', 'y > 0', 'y ≠ 0'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_66', question: 'Composite function fg(x) means:', options: ['f(x) + g(x)', 'f(x) × g(x)', 'f(g(x))', 'g(f(x))'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_67', question: 'Inverse function f⁻¹(f(x)) = ___:', options: ['0', '1', 'x', 'f(x)'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_68', question: 'To find f⁻¹: make ___ the subject:', options: ['y', 'x', 'f', 'f⁻¹'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_69', question: 'One-to-one function has:', options: ['Many x for one y', 'One x for one y', 'One x for many y', 'No relationship'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_70', question: 'Many-to-one function has:', options: ['One x for one y', 'Many x for one y', 'One x for many y', 'Many x for many y'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_71', question: 'Modulus |x| means:', options: ['Always negative', 'Distance from zero', 'Double x', 'x + 1'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_72', question: '|-5| = ___:', options: ['-5', '0', '5', '10'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_73', question: 'Graph of y = |x| has shape:', options: ['Parabola', 'V-shape', 'Straight line', 'Circle'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_74', question: 'Transform y = f(x) to y = f(x) + a:', options: ['Shift left a', 'Shift right a', 'Shift up a', 'Shift down a'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_75', question: 'Transform y = f(x) to y = f(x + a):', options: ['Shift left a', 'Shift right a', 'Shift up a', 'Shift down a'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_76', question: 'Transform y = f(x) to y = af(x):', options: ['Vertical stretch factor a', 'Horizontal stretch factor a', 'Shift up a', 'Shift left a'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_77', question: 'Transform y = f(x) to y = f(ax):', options: ['Vertical stretch factor a', 'Horizontal stretch factor 1/a', 'Shift right a', 'Shift up a'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_78', question: 'Transform y = f(x) to y = -f(x):', options: ['Reflect in x-axis', 'Reflect in y-axis', 'Reflect in y = x', 'No change'], correctAnswer: 0, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_79', question: 'Transform y = f(x) to y = f(-x):', options: ['Reflect in x-axis', 'Reflect in y-axis', 'Reflect in y = x', 'No change'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_80', question: 'Polynomial of degree n has at most ___ roots:', options: ['n-1', 'n', 'n+1', '2n'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_81', question: 'Polynomial of degree n has at most ___ turning points:', options: ['n', 'n-1', 'n-2', 'n+1'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_82', question: 'Asymptote is line that curve:', options: ['Crosses', 'Approaches but never touches', 'Touches once', 'Is perpendicular to'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_83', question: 'Vertical asymptote of y = 1/(x-2) is:', options: ['x = 0', 'x = 1', 'x = 2', 'y = 0'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_84', question: 'Horizontal asymptote of y = 1/x is:', options: ['x = 0', 'y = 0', 'y = 1', 'x = 1'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_85', question: 'Rational function is ratio of:', options: ['Polynomials', 'Exponentials', 'Logarithms', 'Trigonometric'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_86', question: 'Partial fractions: (3x+5)/[(x+1)(x+2)] = A/(x+1) + ___:', options: ['B/(x+2)', 'B(x+2)', 'B', 'B/(x+1)'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_87', question: 'Arithmetic sequence: a, a+d, a+2d, ... nth term = ___:', options: ['a + nd', 'a + (n-1)d', 'an + d', 'ad + n'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_88', question: 'Arithmetic series sum: Sₙ = n/2[2a + ___]:', options: ['d', '(n-1)d', 'nd', 'n'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_89', question: 'Geometric sequence: a, ar, ar², ... nth term = ___:', options: ['arⁿ', 'arⁿ⁻¹', 'aⁿr', 'a + rⁿ'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_90', question: 'Geometric series sum: Sₙ = a(1-rⁿ) / ___:', options: ['r', '1-r', 'n', 'r-1'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_91', question: 'Infinite geometric series converges when:', options: ['|r| > 1', '|r| < 1', '|r| = 1', 'r > 0'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_92', question: 'Sum to infinity: S∞ = a / ___:', options: ['r', '1-r', 'r-1', '1+r'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_93', question: 'Proof by contradiction assumes:', options: ['Statement is true', 'Statement is false', 'Nothing', 'Statement is unknown'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_94', question: 'Proof by induction proves for:', options: ['One case', 'All positive integers', 'Negative integers', 'Real numbers'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_95', question: 'Quadratic inequality x² - 5x + 6 < 0. Solution:', options: ['x < 2 or x > 3', '2 < x < 3', 'x < 2', 'x > 3'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_96', question: 'Algebraic division: x³ ÷ (x-1) gives quotient of degree:', options: ['1', '2', '3', '0'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_97', question: 'Simultaneous equations: one linear, one quadratic has at most ___ solutions:', options: ['1', '2', '3', '4'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_98', question: 'Complex number i² = ___:', options: ['1', '-1', 'i', '0'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_99', question: 'Complex conjugate of 3 + 4i is:', options: ['3 - 4i', '-3 + 4i', '-3 - 4i', '4 + 3i'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_100', question: 'Argand diagram plots:', options: ['Real vs imaginary parts', 'x vs y', 'Time vs position', 'Velocity vs time'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },

  // MECHANICS (50 questions)
  { id: 'y12_math_101', question: 'Displacement is:', options: ['Total distance', 'Distance in particular direction', 'Speed', 'Acceleration'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_102', question: 'Velocity is:', options: ['Speed', 'Speed with direction', 'Acceleration', 'Distance'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_103', question: 'Acceleration = change in velocity / ___:', options: ['Distance', 'Time', 'Mass', 'Force'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_104', question: 'SUVAT equation: v = u + ___:', options: ['as', 'at', 'a/t', 'a²t'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_105', question: 'SUVAT equation: s = ut + ___:', options: ['at', '½at²', 'at²', '2at'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_106', question: 'SUVAT equation: v² = u² + ___:', options: ['as', '2as', 'a²s', 'a/s'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_107', question: 'SUVAT equation: s = (u+v)t / ___:', options: ['1', '2', '3', 'a'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_108', question: 'Constant acceleration under gravity g ≈ ___ m/s²:', options: ['9.8', '10', '9.81', 'All correct'], correctAnswer: 3, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_109', question: 'Projectile motion: horizontal velocity is:', options: ['Constant', 'Increasing', 'Decreasing', 'Zero'], correctAnswer: 0, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_110', question: 'Projectile motion: vertical acceleration is:', options: ['Zero', 'g downward', 'g upward', 'Variable'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_111', question: 'Newton\'s First Law: object continues in motion unless:', options: ['It stops', 'Force acts on it', 'It accelerates', 'Time passes'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_112', question: 'Newton\'s Second Law: F = m × ___:', options: ['v', 'a', 's', 't'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_113', question: 'Newton\'s Third Law: action and reaction are:', options: ['Same direction', 'Equal and opposite', 'Unrelated', 'Variable'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_114', question: 'Weight = mass × ___:', options: ['Velocity', 'g', 'Acceleration', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_115', question: 'Friction opposes:', options: ['Weight', 'Motion', 'Normal force', 'Gravity'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_116', question: 'Normal reaction acts:', options: ['Parallel to surface', 'Perpendicular to surface', 'Downward', 'Horizontally'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_117', question: 'Tension acts:', options: ['In compression', 'Along string/rope', 'Perpendicular to rope', 'Downward'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_118', question: 'Resolving forces: component in direction θ = F × ___:', options: ['sin(θ)', 'cos(θ)', 'tan(θ)', 'θ'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_119', question: 'Resolving forces: component perpendicular to direction = F × ___:', options: ['cos(θ)', 'sin(θ)', 'tan(θ)', '1'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_120', question: 'Equilibrium when resultant force = ___:', options: ['-1', '0', '1', 'mg'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_121', question: 'Momentum = mass × ___:', options: ['Acceleration', 'Velocity', 'Force', 'Time'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_122', question: 'Momentum is conserved in:', options: ['Open systems', 'Closed systems', 'Never', 'Always'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_123', question: 'Impulse = change in ___:', options: ['Velocity', 'Momentum', 'Force', 'Energy'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_124', question: 'Impulse = Force × ___:', options: ['Distance', 'Time', 'Mass', 'Velocity'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_125', question: 'Elastic collision conserves:', options: ['Only momentum', 'Momentum and kinetic energy', 'Only kinetic energy', 'Nothing'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_126', question: 'Inelastic collision conserves:', options: ['Momentum only', 'Kinetic energy only', 'Both', 'Neither'], correctAnswer: 0, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_127', question: 'Work done = Force × ___:', options: ['Time', 'Distance in direction of force', 'Mass', 'Velocity'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_128', question: 'Work done measured in:', options: ['Newtons', 'Joules', 'Watts', 'kg m/s'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_129', question: 'Kinetic energy = ½m___²:', options: ['a', 's', 'v', 't'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_130', question: 'Gravitational potential energy = m × g × ___:', options: ['v', 'h', 't', 'a'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_131', question: 'Power = work done / ___:', options: ['Force', 'Distance', 'Time', 'Mass'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_132', question: 'Power = Force × ___:', options: ['Distance', 'Velocity', 'Time', 'Acceleration'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_133', question: 'Power measured in:', options: ['Joules', 'Newtons', 'Watts', 'kg m/s'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_134', question: 'Efficiency = (useful output / total input) × ___:', options: ['10', '50', '100', '1000'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_135', question: 'On velocity-time graph, gradient gives:', options: ['Distance', 'Velocity', 'Acceleration', 'Time'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_136', question: 'On velocity-time graph, area under gives:', options: ['Velocity', 'Acceleration', 'Displacement', 'Force'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_137', question: 'On displacement-time graph, gradient gives:', options: ['Displacement', 'Velocity', 'Acceleration', 'Force'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_138', question: 'Terminal velocity occurs when:', options: ['Speed is zero', 'Acceleration is zero', 'Force is maximum', 'Mass is zero'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_139', question: 'Air resistance increases with:', options: ['Decreasing speed', 'Increasing speed', 'Mass', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_140', question: 'Connected particles: same ___ if inextensible string:', options: ['Mass', 'Force', 'Acceleration', 'Velocity'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_141', question: 'Pulleys change:', options: ['Force magnitude', 'Force direction', 'Mass', 'Energy'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_142', question: 'Smooth surface means:', options: ['Friction present', 'No friction', 'Rough', 'Sticky'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_143', question: 'Rough surface has:', options: ['No friction', 'Friction', 'No contact', 'No forces'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_144', question: 'Coefficient of friction μ: F ≤ μ × ___:', options: ['Weight', 'Normal reaction', 'Velocity', 'Acceleration'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_145', question: 'Particle model assumes:', options: ['Size matters', 'Point mass, no rotation', 'Large object', 'Complex shape'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_146', question: 'Rigid body:', options: ['Changes shape', 'Does not deform', 'Flexible', 'Liquid'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_147', question: 'Light object has:', options: ['Large mass', 'Negligible mass', 'Variable mass', 'Infinite mass'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_148', question: 'Inextensible string:', options: ['Can stretch', 'Cannot stretch', 'Breaks easily', 'Is elastic'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_149', question: 'Peg/hinge allows:', options: ['No movement', 'Rotation about point', 'Translation only', 'No forces'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_150', question: 'Vector quantity has:', options: ['Only magnitude', 'Magnitude and direction', 'Only direction', 'Neither'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },

  // STATISTICS (50 questions)
  { id: 'y12_math_151', question: 'Population is:', options: ['Sample', 'Entire group being studied', 'Part of group', 'Average'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_152', question: 'Sample is:', options: ['Whole population', 'Part of population', 'Average', 'Mode'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_153', question: 'Random sample ensures:', options: ['Bias', 'Every member has equal chance', 'Only some selected', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_154', question: 'Stratified sampling maintains:', options: ['Randomness only', 'Proportions of subgroups', 'Size only', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_155', question: 'Systematic sampling selects every:', options: ['Random member', 'nth member', 'Other member', 'Fifth member'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_156', question: 'Quota sampling:', options: ['Random', 'Non-random meeting quotas', 'Systematic', 'Census'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_157', question: 'Census samples:', options: ['Part of population', 'Entire population', 'Random selection', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_158', question: 'Mean from frequency table: Σfx / ___:', options: ['n', 'Σf', 'x', 'f'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_159', question: 'Median position in n values:', options: ['n/2', '(n+1)/2', 'n', 'n-1'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_160', question: 'Lower quartile Q1 at position:', options: ['n/4', '(n+1)/4', 'n/2', '3n/4'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_161', question: 'Upper quartile Q3 at position:', options: ['n/4', '(n+1)/2', '3(n+1)/4', 'n'], correctAnswer: 2, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_162', question: 'Interquartile range IQR = Q3 - ___:', options: ['Q2', 'Q1', 'Median', 'Mean'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_163', question: 'Standard deviation measures:', options: ['Center', 'Spread from mean', 'Maximum', 'Minimum'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_164', question: 'Variance = ___²:', options: ['Mean', 'Standard deviation', 'Range', 'IQR'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_165', question: 'Outlier if > Q3 + ___ × IQR:', options: ['1', '1.5', '2', '3'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_166', question: 'Outlier if < Q1 - ___ × IQR:', options: ['1', '1.5', '2', '3'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_167', question: 'Box plot shows:', options: ['Mean only', 'Five number summary', 'Mode only', 'All data'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_168', question: 'Histogram bar area represents:', options: ['Height', 'Frequency', 'Width', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_169', question: 'Frequency density = frequency / ___:', options: ['Total', 'Class width', 'Mean', 'n'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_170', question: 'Cumulative frequency gives:', options: ['Individual frequencies', 'Running total', 'Average', 'Mode'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_171', question: 'Probability P(A) ranges from:', options: ['0 to 100', '-1 to 1', '0 to 1', '1 to 10'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_172', question: 'P(A) + P(A\') = ___:', options: ['0', '0.5', '1', '2'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_173', question: 'P(A or B) = P(A) + P(B) - ___:', options: ['0', 'P(A and B)', '1', 'P(A)P(B)'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_174', question: 'Mutually exclusive: P(A and B) = ___:', options: ['1', 'P(A)', 'P(B)', '0'], correctAnswer: 3, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_175', question: 'Independent events: P(A and B) = P(A) × ___:', options: ['P(A)', 'P(B)', 'P(A or B)', '1'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_176', question: 'Conditional probability: P(A|B) = P(A and B) / ___:', options: ['P(A)', 'P(B)', 'P(A or B)', '1'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_177', question: 'Tree diagram multiply along:', options: ['Rows', 'Branches', 'Columns', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_178', question: 'Venn diagram: P(A ∪ B) represents:', options: ['A and B', 'A or B', 'Neither', 'Only A'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_179', question: 'Discrete random variable takes:', options: ['Continuous values', 'Distinct separate values', 'Any value', 'No values'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_180', question: 'Continuous random variable takes:', options: ['Discrete values', 'Any value in range', 'Integer values', 'No values'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_181', question: 'Probability distribution: ΣP(X = x) = ___:', options: ['0', '0.5', '1', 'Variable'], correctAnswer: 2, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_182', question: 'Expected value E(X) = ___:', options: ['Mode', 'Σ[x × P(X=x)]', 'Median', 'Maximum'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_183', question: 'Variance Var(X) = E(X²) - ___:', options: ['E(X)', '[E(X)]²', 'E(X²)', '0'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_184', question: 'Binomial distribution models:', options: ['Continuous data', 'Fixed number of trials', 'Infinite trials', 'No trials'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_185', question: 'Binomial B(n, p): n is:', options: ['Probability', 'Number of trials', 'Success count', 'Mean'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_186', question: 'Binomial B(n, p): p is:', options: ['Number of trials', 'Probability of success', 'Mean', 'Variance'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_187', question: 'Binomial: P(X = r) = ⁿCᵣ × pʳ × ___:', options: ['qʳ', 'qⁿ⁻ʳ', 'pⁿ⁻ʳ', '(1-p)'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_188', question: 'Binomial mean = ___:', options: ['n', 'p', 'np', 'npq'], correctAnswer: 2, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_189', question: 'Binomial variance = ___:', options: ['np', 'npq', 'n', 'p'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_190', question: 'Normal distribution is:', options: ['Skewed', 'Symmetric bell-shaped', 'Uniform', 'Bimodal'], correctAnswer: 1, difficulty: 'easy', xpReward: 40 },
  { id: 'y12_math_191', question: 'Normal distribution notation: X ~ N(μ, ___²):', options: ['μ', 'σ', 'n', 'x'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_192', question: 'Standard normal distribution: Z ~ N(0, ___²):', options: ['0', '1', '2', 'μ'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_193', question: 'Standardizing: Z = (X - μ) / ___:', options: ['μ', 'σ', 'n', 'x'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_194', question: 'Normal approximation to binomial when np and nq both ___:', options: ['< 5', '> 5', '= 5', '< 10'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_195', question: 'Continuity correction: P(X = 5) becomes P(4.5 < X < ___):', options: ['5', '5.5', '6', '4'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_196', question: 'Hypothesis testing checks if:', options: ['Data is right', 'Result is significant', 'Mean exists', 'Sample is large'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_197', question: 'Null hypothesis H₀ states:', options: ['Change occurred', 'No change/difference', 'Data is wrong', 'Sample is biased'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_198', question: 'Alternative hypothesis H₁ states:', options: ['No change', 'Change/difference exists', 'Same as H₀', 'Nothing'], correctAnswer: 1, difficulty: 'medium', xpReward: 45 },
  { id: 'y12_math_199', question: 'Significance level 5% means:', options: ['50% confidence', '95% confidence', '5% confidence', '100% confidence'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 },
  { id: 'y12_math_200', question: 'Reject H₀ if p-value < ___:', options: ['Mean', 'Significance level', 'Standard deviation', '1'], correctAnswer: 1, difficulty: 'hard', xpReward: 50 }
];
