// Year 6 English Trivia Questions
// Based on UK Year 6 English Curriculum Framework
// 200 comprehensive questions covering all curriculum areas (SATs preparation level)

export const YEAR_6_ENGLISH_QUESTIONS = [
  // READING & COMPREHENSION (80 questions)
  // Advanced comprehension skills
  { id: 'y6_eng_1', question: 'What is inference?', options: ['Reading aloud', 'Reading between the lines to understand hidden meaning', 'Summarizing', 'Predicting'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_2', question: 'What is deduction?', options: ['Guessing', 'Using evidence to reach a conclusion', 'Copying text', 'Reading slowly'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_3', question: 'What does "retrieve" mean in comprehension?', options: ['Make up information', 'Find and extract information from text', 'Summarize', 'Predict'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_4', question: 'What is a protagonist?', options: ['The villain', 'The main character', 'A minor character', 'The narrator'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_5', question: 'What is an antagonist?', options: ['The hero', 'The character opposing the main character', 'The narrator', 'A setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_6', question: 'What are character traits?', options: ['Physical appearance only', 'Personality qualities and characteristics', 'Actions only', 'Dialogue only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_7', question: 'How can you infer character feelings?', options: ['Guess randomly', 'Use actions, dialogue, and context', 'Only read descriptions', 'Ignore the text'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_8', question: 'What is the climax of a story?', options: ['The beginning', 'The turning point or most intense moment', 'The ending', 'The introduction'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_9', question: 'What is resolution in a narrative?', options: ['The problem', 'How the conflict is solved', 'The setting', 'The characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_10', question: 'What is foreshadowing?', options: ['Looking back', 'Hints about future events', 'Describing the past', 'The ending'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  
  // Literary devices
  { id: 'y6_eng_11', question: 'What is a simile?', options: ['Direct comparison', 'Comparison using like or as', 'Exaggeration', 'Repetition'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_12', question: 'Example of simile:', options: ['He is a lion', 'He roars like a lion', 'The lion roared', 'His roar'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_13', question: 'What is a metaphor?', options: ['Comparison using like', 'Direct comparison saying one thing IS another', 'Exaggeration', 'Repetition'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_14', question: 'Example of metaphor:', options: ['As cold as ice', 'The classroom was a zoo', 'She sings like an angel', 'Very cold'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_15', question: 'What is personification?', options: ['Describing people', 'Giving human qualities to non-human things', 'Making things personal', 'Using pronouns'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_16', question: 'Example of personification:', options: ['The big tree', 'The tree danced in the wind', 'A green tree', 'Trees are tall'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_17', question: 'What is hyperbole?', options: ['Understatement', 'Exaggeration for effect', 'Literal truth', 'Comparison'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_18', question: 'Example of hyperbole:', options: ['She is kind', 'I\'ve told you a million times', 'He is tall', 'The sun is bright'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_19', question: 'What is alliteration?', options: ['Rhyming words', 'Repeating consonant sounds at word starts', 'Long words', 'Silent letters'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_20', question: 'Example of alliteration:', options: ['The cat sat', 'Sally sells sea shells', 'A big dog', 'Very happy'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_21', question: 'What is onomatopoeia?', options: ['A long word', 'Words that sound like their meaning', 'Rhyming', 'Metaphor'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_22', question: 'Example of onomatopoeia:', options: ['Beautiful', 'Crash', 'Slowly', 'Happy'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_23', question: 'What is imagery?', options: ['Pictures', 'Descriptive language creating mental images', 'Photographs', 'Diagrams'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_24', question: 'What is symbolism?', options: ['Using symbols in maths', 'Objects/colors representing deeper meanings', 'Writing symbols', 'Mathematical signs'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_25', question: 'What is mood in literature?', options: ['The author\'s attitude', 'The atmosphere or feeling created', 'The plot', 'The characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // Text types and features
  { id: 'y6_eng_26', question: 'What is narrative writing?', options: ['Giving instructions', 'Telling a story', 'Explaining facts', 'Persuading'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_27', question: 'What is persuasive writing?', options: ['Telling stories', 'Convincing readers of a viewpoint', 'Giving facts', 'Describing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_28', question: 'What is expository writing?', options: ['Telling stories', 'Persuading', 'Explaining and informing', 'Entertaining'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_29', question: 'What is a biography?', options: ['Fiction story', 'Account of someone\'s life', 'Your own life story', 'A poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_30', question: 'What is an autobiography?', options: ['Someone else\'s life', 'Your own life story', 'Fiction', 'A textbook'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_31', question: 'What is a recount?', options: ['Counting again', 'Retelling events that happened', 'Fiction story', 'Poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_32', question: 'What is a report?', options: ['Fiction', 'Factual writing about a topic', 'Story', 'Poem'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_33', question: 'What is an explanation text?', options: ['Tells a story', 'Describes how/why things happen', 'Persuades', 'Entertains'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_34', question: 'What is the purpose of a newspaper article?', options: ['Entertain only', 'Inform about events', 'Give instructions', 'Tell fiction'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_35', question: 'What is a discussion text?', options: ['Fiction story', 'Presents different viewpoints on an issue', 'Biography', 'Recount'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // Vocabulary
  { id: 'y6_eng_36', question: 'What is a synonym?', options: ['Opposite word', 'Word with similar meaning', 'Made-up word', 'Plural'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_37', question: 'Synonym for "brave":', options: ['Scared', 'Courageous', 'Weak', 'Tiny'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_38', question: 'What is an antonym?', options: ['Similar word', 'Opposite word', 'Rhyming word', 'Long word'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_39', question: 'Antonym for "difficult":', options: ['Hard', 'Easy', 'Challenging', 'Tough'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_40', question: 'What is context?', options: ['The title', 'Surrounding words helping explain meaning', 'The author', 'The conclusion'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_41', question: 'What are homophones?', options: ['Same spelling', 'Sound the same, different meanings/spellings', 'Opposites', 'Synonyms'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_42', question: 'Which is correct? "The game is over ___."', options: ['there', 'their', 'they\'re', 'thare'], correctAnswer: 0, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_43', question: 'Which is correct? "Can you ___ the music?"', options: ['here', 'hear', 'hare', 'heir'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_44', question: 'What is etymology?', options: ['Study of insects', 'Study of word origins', 'Study of grammar', 'Study of poetry'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_45', question: 'What is morphology?', options: ['Study of shapes', 'Study of word structure and formation', 'Study of stories', 'Study of sounds'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },

  // Poetry
  { id: 'y6_eng_46', question: 'What is a stanza?', options: ['A line', 'A verse or group of lines', 'The title', 'The rhyme'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_47', question: 'What is rhyme scheme?', options: ['Type of poem', 'Pattern of rhymes', 'Number of lines', 'Author name'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_48', question: 'Rhyme scheme AABB means:', options: ['No rhyme', 'Couplets (lines 1-2, 3-4 rhyme)', 'Alternate rhyme', 'All lines rhyme'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_49', question: 'Rhyme scheme ABAB means:', options: ['No rhyme', 'Couplets', 'Alternate line rhyme', 'All same'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_50', question: 'What is rhythm in poetry?', options: ['The meaning', 'The pattern of beats and sounds', 'The rhyme', 'The title'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_51', question: 'What is free verse?', options: ['Poetry with strict rules', 'Poetry without regular rhyme/rhythm', 'Always rhymes', 'Only 4 lines'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_52', question: 'What is a haiku?', options: ['5-line poem', 'Japanese 3-line poem (5-7-5 syllables)', '14-line poem', 'Rhyming couplet'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_53', question: 'What is a limerick?', options: ['Sad poem', 'Humorous 5-line poem with AABBA rhyme', 'Japanese poem', '14-line poem'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_54', question: 'What is a sonnet?', options: ['5-line poem', '14-line poem', '3-line poem', '20-line poem'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_55', question: 'What is a ballad?', options: ['Short poem', 'Narrative poem telling a story', 'Non-rhyming', 'About nature only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // Reading strategies
  { id: 'y6_eng_56', question: 'What is skimming?', options: ['Reading every word', 'Quickly reading for main ideas', 'Reading aloud', 'Re-reading'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_57', question: 'What is scanning?', options: ['Reading everything', 'Searching for specific information', 'Reading slowly', 'Summarizing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_58', question: 'What is a prediction?', options: ['Guessing randomly', 'Using clues to anticipate what happens next', 'Summarizing', 'Copying'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_59', question: 'What is summarizing?', options: ['Copying everything', 'Briefly stating main points', 'Adding details', 'Changing the story'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_60', question: 'What is a fact?', options: ['An opinion', 'Something that can be proven true', 'A belief', 'A guess'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_61', question: 'What is an opinion?', options: ['Proven truth', 'Personal belief or judgment', 'A fact', 'Statistical data'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_62', question: 'Which is a fact?', options: ['Pizza is delicious', 'Water boils at 100°C', 'Summer is the best season', 'Red is pretty'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_63', question: 'Which is an opinion?', options: ['Nigeria has 36 states', 'The capital is Abuja', 'Lagos is the best city', 'Earth orbits the Sun'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_64', question: 'What is the author\'s purpose in a persuasive text?', options: ['Entertain', 'Convince/persuade', 'Inform only', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_65', question: 'What is theme?', options: ['The title', 'The central idea or message', 'The plot', 'The characters'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_66', question: 'What is plot?', options: ['The setting', 'The sequence of events', 'The theme', 'The mood'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_67', question: 'What is setting?', options: ['The theme', 'Time and place of events', 'The characters', 'The plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_68', question: 'What is conflict in a story?', options: ['Agreement', 'The problem or struggle', 'The solution', 'The ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_69', question: 'First-person narration uses:', options: ['He/she', 'I/we', 'You', 'They'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_70', question: 'Third-person narration uses:', options: ['I/we', 'He/she/they', 'You', 'Me'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_71', question: 'What is dialogue?', options: ['Description', 'Conversation between characters', 'Narration', 'Setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_72', question: 'What is direct speech?', options: ['Reported speech', 'Exact words spoken in quotes', 'Summary', 'Paraphrase'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_73', question: 'What is reported speech?', options: ['Exact words in quotes', 'Paraphrased/indirect speech', 'Dialogue', 'Direct quote'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_74', question: 'What is a flashback?', options: ['Future events', 'Scene from the past', 'The ending', 'Current events'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_75', question: 'What is a cliffhanger?', options: ['Boring ending', 'Suspenseful ending leaving questions', 'Happy ending', 'Clear resolution'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_76', question: 'What is tension in writing?', options: ['Relaxation', 'Excitement/suspense', 'Boredom', 'Clarity'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_77', question: 'What is pace in writing?', options: ['Size', 'Speed at which story unfolds', 'Location', 'Characters'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_78', question: 'What is point of view?', options: ['The plot', 'Perspective from which story is told', 'The setting', 'The ending'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_79', question: 'What is a moral?', options: ['A character', 'The lesson/message of a story', 'The setting', 'The plot'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_80', question: 'What does "explicit" information mean?', options: ['Hidden', 'Clearly stated', 'Implied', 'Confusing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },

  // WRITING - COMPOSITION (40 questions)
  { id: 'y6_eng_81', question: 'What is audience?', options: ['The author', 'Who will read your writing', 'The title', 'The topic'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_82', question: 'What is purpose in writing?', options: ['The title', 'Why you are writing (inform, persuade, entertain)', 'The ending', 'The length'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_83', question: 'Formal writing is used for:', options: ['Text messages', 'Official letters, reports, essays', 'Chatting', 'Notes to friends'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_84', question: 'Informal writing is used for:', options: ['Business letters', 'Friendly emails, texts', 'School reports', 'Official documents'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_85', question: 'What is a paragraph?', options: ['One sentence', 'Group of sentences about one idea', 'The whole text', 'A title'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_86', question: 'When should you start a new paragraph?', options: ['Every sentence', 'New topic, time, place, or speaker', 'Never', 'Randomly'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_87', question: 'What is a topic sentence?', options: ['Last sentence', 'Introduces main idea of paragraph', 'Random sentence', 'The title'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_88', question: 'What is cohesion?', options: ['Random ideas', 'How ideas link and flow smoothly', 'Long sentences', 'Short sentences'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_89', question: 'What are connectives?', options: ['Punctuation', 'Words linking ideas/sentences', 'Adjectives', 'Verbs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_90', question: 'Example of time connective:', options: ['However', 'Meanwhile', 'Because', 'Although'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_91', question: 'Example of cause connective:', options: ['Then', 'Because', 'Next', 'Also'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_92', question: 'What is drafting?', options: ['Final version', 'Creating an early version', 'Ignoring task', 'Publishing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_93', question: 'What is editing?', options: ['Writing first draft', 'Checking and improving writing', 'Publishing', 'Ignoring mistakes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_94', question: 'What is proofreading?', options: ['Writing', 'Checking for spelling/grammar errors', 'Planning', 'Brainstorming'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_95', question: 'What should you check when editing?', options: ['Nothing', 'Spelling, grammar, punctuation, clarity', 'Only spelling', 'Only grammar'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_96', question: 'What is tone?', options: ['Volume', 'Attitude/feeling conveyed', 'Length', 'Font'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_97', question: 'Organizational devices include:', options: ['Only paragraphs', 'Headings, subheadings, bullet points', 'Only sentences', 'Only words'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_98', question: 'Headings are used to:', options: ['Confuse readers', 'Organize text into sections', 'Make text longer', 'Remove information'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_99', question: 'Bullet points help to:', options: ['Hide information', 'Present lists clearly', 'Make text messy', 'Confuse'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_100', question: 'What is tense consistency?', options: ['Changing tense randomly', 'Keeping same tense throughout', 'Ignoring tense', 'Using only present'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_101', question: 'Past tense example:', options: ['I walk', 'I walked', 'I will walk', 'I am walking'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_102', question: 'Present tense example:', options: ['I walked', 'I walk', 'I will walk', 'I had walked'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_103', question: 'Future tense example:', options: ['I walked', 'I walk', 'I will walk', 'I was walking'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_104', question: 'What is a précis?', options: ['Expanding text', 'Concise summary of main points', 'Copying everything', 'Random writing'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_105', question: 'When describing settings, use:', options: ['Only names', 'Sensory details (sight, sound, smell, touch, taste)', 'Short words', 'No details'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_106', question: 'Good character description includes:', options: ['Only name', 'Appearance, personality, actions', 'Nothing', 'Just age'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_107', question: 'Dialogue shows:', options: ['Nothing', 'Character and advances plot', 'Only speech', 'The setting'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_108', question: '"Show, don\'t tell" means:', options: ['Tell everything', 'Use actions/details to show emotions', 'Hide information', 'Be vague'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_109', question: 'What creates atmosphere?', options: ['Random words', 'Descriptive language, mood words, imagery', 'Short sentences', 'No description'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_110', question: 'To build suspense:', options: ['Reveal everything quickly', 'Delay information, use tension, hint at danger', 'Be boring', 'Rush the ending'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_111', question: 'A strong opening should:', options: ['Be boring', 'Hook the reader immediately', 'Summarize everything', 'Be very long'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_112', question: 'A strong conclusion should:', options: ['Introduce new ideas', 'Summarize and provide closure', 'Ask many questions', 'Be incomplete'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_113', question: 'Varied sentence length creates:', options: ['Boredom', 'Interest and rhythm', 'Confusion', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_114', question: 'What is voice in writing?', options: ['Speaking aloud', 'The writer\'s unique style', 'Volume', 'Tone of voice'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_115', question: 'Persuasive techniques include:', options: ['Boring facts', 'Rhetorical questions, emotive language, repetition', 'No techniques', 'Random words'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_116', question: 'What is a rhetorical question?', options: ['Normal question', 'Question asked for effect, not answer', 'Answered question', 'Statement'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_117', question: 'Emotive language:', options: ['Factual only', 'Appeals to emotions', 'Boring', 'Scientific'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_118', question: 'What is a counter-argument?', options: ['Agreement', 'Opposing viewpoint', 'Repeating same point', 'Conclusion'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_119', question: 'Varied vocabulary makes writing:', options: ['Boring', 'More interesting and precise', 'Confusing', 'Longer only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_120', question: 'What is a thesaurus useful for?', options: ['Spelling', 'Finding synonyms and varied vocabulary', 'Grammar', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // GRAMMAR, VOCABULARY & PUNCTUATION (60 questions)
  { id: 'y6_eng_121', question: 'What is a noun?', options: ['Action word', 'Person, place, thing, or idea', 'Describing word', 'Joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_122', question: 'What is a verb?', options: ['Naming word', 'Action or state word', 'Describing word', 'Joining word'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_123', question: 'What is an adjective?', options: ['Action word', 'Describes a noun', 'Joining word', 'Naming word'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_124', question: 'What is an adverb?', options: ['Describes noun', 'Describes verb, adjective, or adverb', 'Names things', 'Joins clauses'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_125', question: 'What is a pronoun?', options: ['Action word', 'Replaces a noun (he, she, it, they)', 'Describes', 'Joins'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_126', question: 'What is a preposition?', options: ['Action word', 'Shows position/relationship (in, on, under)', 'Describes', 'Names'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_127', question: 'What is a conjunction?', options: ['Action word', 'Joins words/clauses (and, but, because)', 'Describes', 'Names'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_128', question: 'What is a determiner?', options: ['Action word', 'Introduces noun (the, a, an, this)', 'Describes action', 'Joins'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_129', question: 'What is a modal verb?', options: ['Past tense', 'Shows possibility/obligation (might, could, must)', 'Present tense', 'Future only'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_130', question: 'Example of modal verb:', options: ['Walk', 'Should', 'Happy', 'Quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_131', question: 'What is the subjunctive mood?', options: ['Happy mood', 'Formal way expressing wishes/hypotheses (If I were...)', 'Past tense', 'Question'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_132', question: 'Correct subjunctive: "If I ___ rich..."', options: ['was', 'were', 'am', 'is'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_133', question: 'What is active voice?', options: ['Subject receives action', 'Subject performs action', 'No subject', 'Past tense'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_134', question: 'What is passive voice?', options: ['Subject performs action', 'Subject receives action', 'No verb', 'Future tense'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_135', question: 'Active voice example:', options: ['The ball was kicked by Tom', 'Tom kicked the ball', 'The ball is kicked', 'Kicked by Tom'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_136', question: 'Passive voice example:', options: ['She wrote the letter', 'The letter was written by her', 'Writing the letter', 'She writes'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_137', question: 'What is a relative clause?', options: ['Main sentence', 'Clause giving extra info about noun', 'Question', 'Command'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_138', question: 'Relative pronoun examples:', options: ['And, but', 'Who, which, that, whose', 'I, you, he', 'In, on, under'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_139', question: '"The book which I read was good." Relative clause:', options: ['The book', 'which I read', 'was good', 'I read'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_140', question: 'Use "who" for:', options: ['Things', 'People', 'Places', 'Times'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_141', question: 'Use "which" for:', options: ['People', 'Things', 'Only animals', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_142', question: 'What is parenthesis?', options: ['Main sentence', 'Extra information added (brackets, dashes, commas)', 'Question', 'Statement'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_143', question: 'Parenthesis with brackets: "The dog (a terrier) barked." Can remove:', options: ['The dog', '(a terrier)', 'barked', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_144', question: 'Parenthesis with dashes example:', options: ['The cat sat', 'The cat – very old – slept', 'What?', 'Stop!'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_145', question: 'What is a colon used for?', options: ['End sentences', 'Introduce list or explanation', 'Show questions', 'Show excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_146', question: 'Colon example: "I need: pencils, pens, paper." The colon:', options: ['Ends sentence', 'Introduces the list', 'Shows question', 'Shows excitement'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_147', question: 'What is a semi-colon used for?', options: ['End sentences', 'Link related clauses; separate complex lists', 'Show questions', 'Show excitement'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_148', question: 'Semi-colon example:', options: ['What?', 'I like apples; she likes oranges.', 'Stop!', 'Hello.'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_149', question: 'What is a hyphen used for?', options: ['End sentences', 'Join words/prefixes (re-enter, forty-five)', 'Show questions', 'Lists'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_150', question: 'Hyphen example:', options: ['Hello', 'Twenty-one', 'What?', 'Stop!'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_151', question: 'What is a dash used for?', options: ['Same as hyphen', 'Longer, shows break/parenthesis', 'Question mark', 'Full stop'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_152', question: 'Apostrophe for possession: "The dog\'s bone" means:', options: ['Many dogs', 'Bone belongs to dog', 'Dogs are bones', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_153', question: 'Apostrophe for omission: "Can\'t" means:', options: ['Can', 'Cannot', 'Will not', 'Could not'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_154', question: 'Which is correct?', options: ['Its raining', 'It\'s raining', 'Its\' raining', 'I\'ts raining'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_155', question: 'Plural possession: "The girls\' books" means:', options: ['One girl', 'Many girls', 'No girls', 'One book'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_156', question: 'Which shows singular possession?', options: ['The dogs bone', 'The dog\'s bone', 'The dogs\' bone', 'The dogs\'s bone'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_157', question: 'Commas in lists separate:', options: ['Nothing', 'Items', 'Sentences', 'Paragraphs'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_158', question: 'Commas for clarity: "Let\'s eat, Grandma!" vs "Let\'s eat Grandma!" Which is safe?', options: ['Second', 'First', 'Both same', 'Neither'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_159', question: 'What is subject-verb agreement?', options: ['Don\'t need to match', 'Subject and verb must agree in number', 'Only use singular', 'Only use plural'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_160', question: 'Correct agreement:', options: ['She walk', 'She walks', 'They walks', 'I walks'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_161', question: 'What is a clause?', options: ['Single word', 'Group of words with subject and verb', 'Random words', 'Punctuation'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_162', question: 'What is a main clause?', options: ['Cannot stand alone', 'Can stand alone as complete sentence', 'Only short', 'Only long'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_163', question: 'What is a subordinate clause?', options: ['Stands alone', 'Cannot stand alone; depends on main clause', 'Only questions', 'Only statements'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_164', question: 'Simple sentence has:', options: ['Two clauses', 'One main clause', 'Three clauses', 'No clause'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_165', question: 'Compound sentence has:', options: ['One clause', 'Two or more main clauses joined', 'No clauses', 'Subordinate only'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_166', question: 'Complex sentence has:', options: ['Only main clause', 'Main clause + subordinate clause(s)', 'No clauses', 'Only subordinate'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_167', question: 'Compound sentence example:', options: ['The cat slept.', 'I like tea, but she likes coffee.', 'Although tired, he worked.', 'Stop!'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_168', question: 'Complex sentence example:', options: ['She ran.', 'I ran and jumped.', 'Because it rained, we stayed inside.', 'Hello.'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_169', question: 'Expanded noun phrase example:', options: ['Dog', 'The big, fierce, angry dog', 'Run', 'Quickly'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_170', question: 'Standard English is:', options: ['Slang', 'Formal, grammatically correct English', 'Regional dialect', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_171', question: 'Formal register uses:', options: ['Slang, contractions', 'Proper grammar, no contractions, formal vocabulary', 'Casual language', 'Text speak'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_172', question: 'Informal register uses:', options: ['Very formal language', 'Casual, conversational language', 'Only Standard English', 'No contractions'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_173', question: 'Synonyms for "said":', options: ['Walked, ran', 'Whispered, shouted, exclaimed', 'Happy, sad', 'Big, small'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_174', question: 'What is ellipsis (...)?', options: ['Full stop', 'Shows omission or trailing off', 'Question mark', 'Comma'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_175', question: 'Prefix "un-" means:', options: ['Again', 'Not/opposite', 'Before', 'After'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_176', question: 'Prefix "re-" means:', options: ['Not', 'Again', 'Before', 'Under'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_177', question: 'Suffix "-tion" creates:', options: ['Verb', 'Noun', 'Adjective', 'Adverb'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_178', question: 'Suffix "-ly" often creates:', options: ['Noun', 'Verb', 'Adverb', 'Pronoun'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_179', question: 'What is direct address?', options: ['Mailing address', 'Speaking to someone by name', 'Email address', 'Indirect speech'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_180', question: 'Direct address example:', options: ['He is nice', 'Sarah, please come here.', 'The dog barked', 'I walked'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },

  // SPELLING & ASSESSMENT (20 questions)
  { id: 'y6_eng_181', question: 'Which letter is silent in "scissors"?', options: ['s', 'c', 'i', 'r'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_182', question: 'Which letter is silent in "Wednesday"?', options: ['W', 'd', 'n', 'e'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_183', question: 'Correct spelling:', options: ['Necesary', 'Neccesary', 'Necessary', 'Neccessary'], correctAnswer: 2, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_184', question: 'Correct spelling:', options: ['Separate', 'Seperate', 'Separete', 'Seprate'], correctAnswer: 0, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_185', question: 'Correct spelling:', options: ['Definately', 'Definitely', 'Definitly', 'Definetely'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_186', question: 'Correct spelling:', options: ['Accomodate', 'Accommodate', 'Acommodate', 'Acomodate'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_187', question: 'Correct spelling:', options: ['Conscous', 'Conscious', 'Consious', 'Concious'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_188', question: 'Which is correct? "___ bag is this?"', options: ['Whose', 'Who\'s', 'Whos', 'Who\'se'], correctAnswer: 0, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_189', question: 'Which is correct? "The decision is ___."', options: ['your\'s', 'yours', 'yours\'', 'your'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_190', question: 'Which is correct? "We ___ going tomorrow."', options: ['were', 'where', 'we\'re', 'wear'], correctAnswer: 2, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_191', question: 'Root word of "disagreement":', options: ['Disagree', 'Agree', 'Agreement', 'Dis'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_192', question: 'Etymology means:', options: ['Study of insects', 'Study of word origins', 'Study of rocks', 'Study of numbers'], correctAnswer: 1, difficulty: 'medium', xpReward: 25 },
  { id: 'y6_eng_193', question: 'Morphology studies:', options: ['Shapes', 'Word structure and formation', 'Animals', 'Plants'], correctAnswer: 1, difficulty: 'hard', xpReward: 30 },
  { id: 'y6_eng_194', question: 'Word families share:', options: ['Nothing', 'Same root/base word', 'Same length', 'Same first letter'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_195', question: 'Which are in same word family?', options: ['Cat, dog, bird', 'Happy, happiness, unhappy', 'Red, blue, green', 'Run, sit, jump'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_196', question: 'SATs test:', options: ['Only spelling', 'Reading, grammar, writing skills', 'Only maths', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_197', question: 'Reading comprehension tests check:', options: ['Handwriting', 'Understanding and interpretation', 'Spelling', 'Speaking'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_198', question: 'Grammar tests check:', options: ['Only spelling', 'Word types, sentence structure, punctuation', 'Only reading', 'Only writing'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_199', question: 'Writing tasks assess:', options: ['Only spelling', 'Composition, vocabulary, grammar, punctuation', 'Only handwriting', 'Only reading'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 },
  { id: 'y6_eng_200', question: 'Effective revision involves:', options: ['Last-minute cramming', 'Regular practice, reviewing mistakes, varied activities', 'Only reading', 'Ignoring weaknesses'], correctAnswer: 1, difficulty: 'easy', xpReward: 20 }
];
