// Year 1 Science Trivia Questions
// Based on TUTORNEST — YEAR 1 SCIENCE CURRICULUM FRAMEWORK (UK)
// 200 comprehensive questions covering all curriculum areas

export const YEAR_1_SCIENCE_QUESTIONS = [
  // WORKING SCIENTIFICALLY (FOUNDATIONS) (15 questions)
  { id: 'y1_sci_1', question: 'What do scientists do when they want to learn something?', options: ['Guess', 'Ask questions', 'Give up', 'Sleep'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_2', question: 'When we watch something carefully, we are:', options: ['Sleeping', 'Observing', 'Running', 'Eating'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_3', question: 'We can sort objects by putting things that are the same:', options: ['Far apart', 'Together', 'In the bin', 'Anywhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_4', question: 'Why is it important to use science equipment safely?', options: ['To go faster', 'To avoid getting hurt', 'To make noise', 'To break things'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_5', question: 'How can we record what we find in science?', options: ['Forget it', 'Draw pictures and make charts', 'Hide it', 'Throw it away'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_6', question: 'What does it mean to compare two things?', options: ['Make them the same', 'Look at how they are similar and different', 'Throw them away', 'Count them'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_7', question: 'A good science question starts with words like:', options: ['The end', 'What, why, how', 'Goodbye', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_8', question: 'When we group objects, we put together things that:', options: ['Are different', 'Are the same in some way', 'Are broken', 'Are big'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_9', question: 'What tool helps us see things that are very small?', options: ['Telescope', 'Magnifying glass', 'Ruler', 'Thermometer'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_10', question: 'When something changes, we should:', options: ['Ignore it', 'Notice and describe it', 'Hide it', 'Break it'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_11', question: 'A simple science chart helps us:', options: ['Sleep', 'Record and show our findings', 'Play games', 'Eat lunch'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_12', question: 'Labels on drawings tell us:', options: ['Nothing', 'What each part is', 'A story', 'A joke'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_13', question: 'When we talk about what we notice, we are:', options: ['Being quiet', 'Sharing our observations', 'Sleeping', 'Running'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_14', question: 'What does "investigate" mean in science?', options: ['Sleep', 'Find out more about something', 'Give up', 'Eat'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_15', question: 'Using our senses helps us:', options: ['Sleep better', 'Observe and learn about the world', 'Run faster', 'Eat more'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // PLANTS - Identifying Plants (12 questions)
  { id: 'y1_sci_16', question: 'Which of these is a common garden plant?', options: ['Car', 'Rose', 'Chair', 'Book'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_17', question: 'What part of the plant grows underground?', options: ['Flower', 'Leaves', 'Roots', 'Petals'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_18', question: 'The part of a plant that holds it up is called the:', options: ['Root', 'Stem', 'Flower', 'Seed'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_19', question: 'Leaves on a plant help it to:', options: ['Walk', 'Make food from sunlight', 'Sing', 'Sleep'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_20', question: 'The colourful part of a plant is usually the:', options: ['Root', 'Stem', 'Flower', 'Soil'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_21', question: 'Which of these is a tree?', options: ['Grass', 'Oak', 'Daisy', 'Carrot'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_22', question: 'A daisy is a type of:', options: ['Animal', 'Wild plant', 'Rock', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_23', question: 'Trees are plants that have:', options: ['Wings', 'Trunks and branches', 'Wheels', 'Eyes'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_24', question: 'Which part of a plant makes seeds?', options: ['Roots', 'Stem', 'Flower', 'Leaves'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_25', question: 'Grass is a type of:', options: ['Animal', 'Plant', 'Rock', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_26', question: 'What do we call the green parts on a plant?', options: ['Flowers', 'Leaves', 'Roots', 'Seeds'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_27', question: 'A sunflower gets its name because:', options: ['It grows at night', 'Its flower looks like the sun', 'It is cold', 'It lives in water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // PLANTS - Growing Plants (13 questions)
  { id: 'y1_sci_28', question: 'What do plants need to grow?', options: ['Only darkness', 'Water, light, and warmth', 'Only ice', 'Only air'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_29', question: 'If a plant has no water, it will:', options: ['Grow bigger', 'Wilt and die', 'Turn into a tree', 'Fly away'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_30', question: 'Plants use light from the:', options: ['Moon only', 'Sun', 'Stars only', 'Lights indoors only'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_31', question: 'A seed needs water, warmth, and light to:', options: ['Stay a seed forever', 'Germinate and grow', 'Turn into a rock', 'Disappear'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_32', question: 'When we plant a seed, we should:', options: ['Throw it away', 'Put it in soil and water it', 'Eat it', 'Hide it'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_33', question: 'A bulb is:', options: ['A type of seed that grows underground', 'A type of animal', 'A type of rock', 'A type of water'], correctAnswer: 0, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_34', question: 'What happens to a seed over time if we care for it?', options: ['Nothing', 'It grows into a plant', 'It turns into water', 'It becomes a stone'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_35', question: 'A healthy plant has:', options: ['Brown, droopy leaves', 'Green, strong leaves', 'No leaves', 'Dead stems'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_36', question: 'Why do plants need warmth?', options: ['To freeze', 'To help them grow', 'To sleep', 'To die'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_37', question: 'If you don\'t give a plant enough light, it might:', options: ['Grow very tall quickly', 'Become weak and pale', 'Turn blue', 'Fly'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_38', question: 'Soil helps plants by:', options: ['Making noise', 'Giving them support and nutrients', 'Keeping them wet all the time', 'Blocking the sun'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_39', question: 'What is the first part of a plant to grow from a seed?', options: ['Flower', 'Root', 'Leaves', 'Trunk'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_40', question: 'Caring for a plant means:', options: ['Ignoring it', 'Watering it and giving it light', 'Kicking it', 'Hiding it in a dark cupboard'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // ANIMALS INCLUDING HUMANS - Animals (20 questions)
  { id: 'y1_sci_41', question: 'Which of these is an animal?', options: ['Tree', 'Dog', 'Rock', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_42', question: 'Mammals are animals that:', options: ['Lay eggs', 'Have fur or hair and feed milk to babies', 'Live in water only', 'Have no legs'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_43', question: 'Which animal is a mammal?', options: ['Goldfish', 'Snake', 'Cat', 'Chicken'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_44', question: 'Birds have:', options: ['Fur', 'Feathers and wings', 'Scales', 'No body covering'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_45', question: 'Which of these is a bird?', options: ['Rabbit', 'Robin', 'Frog', 'Spider'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_46', question: 'Fish live in:', options: ['Trees', 'Water', 'Deserts', 'Sky'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_47', question: 'A goldfish is a:', options: ['Mammal', 'Bird', 'Fish', 'Reptile'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_48', question: 'Reptiles have:', options: ['Feathers', 'Fur', 'Scales', 'No covering'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_49', question: 'Which animal is a reptile?', options: ['Dog', 'Snake', 'Sparrow', 'Dolphin'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_50', question: 'How many legs does a dog have?', options: ['2', '3', '4', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_51', question: 'A habitat is:', options: ['An animal\'s home', 'A type of food', 'A colour', 'A season'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_52', question: 'Where would you find a fish living?', options: ['In a tree', 'In a pond or ocean', 'In the sky', 'In a cave'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_53', question: 'A bird uses its wings to:', options: ['Swim', 'Fly', 'Dig', 'Sleep'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_54', question: 'Which body part helps a fish swim?', options: ['Wings', 'Fins and tail', 'Legs', 'Arms'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_55', question: 'A cat has:', options: ['No legs', 'Two legs', 'Four legs', 'Six legs'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_56', question: 'Animals need food and water to:', options: ['Fly', 'Stay alive and healthy', 'Turn into plants', 'Disappear'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_57', question: 'A rabbit is a:', options: ['Fish', 'Mammal', 'Reptile', 'Rock'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_58', question: 'Which animal can fly?', options: ['Elephant', 'Bird', 'Snake', 'Fish'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_59', question: 'Animals that eat only plants are called:', options: ['Carnivores', 'Herbivores', 'Omnivores', 'Reptiles'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_60', question: 'Which sense do animals use to hear?', options: ['Eyes', 'Nose', 'Ears', 'Tongue'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },

  // ANIMALS INCLUDING HUMANS - Humans (15 questions)
  { id: 'y1_sci_61', question: 'How many senses do humans have?', options: ['3', '4', '5', '6'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_62', question: 'We use our eyes to:', options: ['Hear', 'See', 'Smell', 'Taste'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_63', question: 'We use our ears to:', options: ['See', 'Hear', 'Taste', 'Touch'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_64', question: 'We use our nose to:', options: ['See', 'Hear', 'Smell', 'Touch'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_65', question: 'We use our tongue to:', options: ['See', 'Hear', 'Taste', 'Smell'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_66', question: 'We use our skin to:', options: ['Taste', 'See', 'Touch and feel', 'Hear'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_67', question: 'What part of your body helps you bend your arm?', options: ['Knee', 'Elbow', 'Ankle', 'Wrist'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_68', question: 'Your head is connected to your body by your:', options: ['Arm', 'Leg', 'Neck', 'Foot'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_69', question: 'We walk and run using our:', options: ['Arms', 'Legs', 'Head', 'Stomach'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_70', question: 'Why is it important to wash your hands?', options: ['To get them wet', 'To remove germs and stay healthy', 'To waste water', 'To make them dirty'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_71', question: 'How much sleep do children need each night?', options: ['1 hour', '3 hours', 'About 10-12 hours', '20 hours'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_72', question: 'Eating fruits and vegetables helps us:', options: ['Get sick', 'Stay healthy and strong', 'Feel tired', 'Grow weaker'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_73', question: 'Exercise is good because it:', options: ['Makes us weaker', 'Keeps our body strong and healthy', 'Makes us sick', 'Wastes time'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_74', question: 'We should brush our teeth:', options: ['Never', 'Twice a day', 'Once a month', 'Once a year'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_75', question: 'Which body part helps you think?', options: ['Foot', 'Brain', 'Knee', 'Elbow'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // MATERIALS - Everyday Materials (15 questions)
  { id: 'y1_sci_76', question: 'A table is usually made of:', options: ['Water', 'Wood', 'Air', 'Clouds'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_77', question: 'Which material is hard?', options: ['Cotton', 'Metal', 'Paper', 'Sponge'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_78', question: 'Which material is soft?', options: ['Rock', 'Glass', 'Fabric', 'Metal'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_79', question: 'A window is made of:', options: ['Plastic', 'Wood', 'Glass', 'Fabric'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_80', question: 'A plastic bottle is made of:', options: ['Metal', 'Plastic', 'Wood', 'Glass'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_81', question: 'Which material is shiny?', options: ['Cardboard', 'Metal', 'Wood', 'Sponge'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_82', question: 'Which material is dull (not shiny)?', options: ['Mirror', 'Cardboard', 'Silver spoon', 'Gold ring'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_83', question: 'Your T-shirt is made of:', options: ['Glass', 'Metal', 'Fabric', 'Stone'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_84', question: 'A spoon can be made of:', options: ['Water', 'Metal', 'Air', 'Light'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_85', question: 'Which word describes glass?', options: ['Soft', 'Bendy', 'Hard and transparent', 'Fluffy'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_86', question: 'Wood comes from:', options: ['Rocks', 'Trees', 'Water', 'Air'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_87', question: 'Which material can be see-through?', options: ['Wood', 'Metal', 'Glass', 'Stone'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_88', question: 'A rubber ball is:', options: ['Hard and stiff', 'Soft and bouncy', 'Sharp', 'Transparent'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_89', question: 'Sorting materials means:', options: ['Mixing them all up', 'Grouping them by their properties', 'Throwing them away', 'Hiding them'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_90', question: 'A pencil can be made of wood and:', options: ['Water', 'Graphite', 'Air', 'Light'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },

  // MATERIALS - Uses of Materials (10 questions)
  { id: 'y1_sci_91', question: 'Why is glass used for windows?', options: ['It is soft', 'We can see through it', 'It is heavy', 'It is bendy'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_92', question: 'Why is metal used for spoons?', options: ['It is very soft', 'It is strong and doesn\'t break easily', 'It is see-through', 'It floats'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_93', question: 'Why is fabric used for clothes?', options: ['It is hard', 'It is soft and comfortable', 'It is see-through', 'It is heavy'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_94', question: 'A raincoat is waterproof. This means:', options: ['Water goes through it', 'Water cannot go through it', 'It dissolves in water', 'It is made of water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_95', question: 'A sponge is absorbent. This means:', options: ['It pushes water away', 'It soaks up water', 'It is hard', 'It is shiny'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_96', question: 'Why is plastic used for bottles?', options: ['It is soft and breaks', 'It is light and doesn\'t break easily', 'It is very heavy', 'It melts in water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_97', question: 'A towel is made from absorbent material because:', options: ['We want it to push water away', 'We want it to soak up water', 'We want it to be hard', 'We want it to be shiny'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_98', question: 'Why is wood good for building furniture?', options: ['It is soft and bendy', 'It is strong and can be shaped', 'It is see-through', 'It is very light'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_99', question: 'An umbrella is waterproof to:', options: ['Let rain through', 'Keep us dry from rain', 'Soak up water', 'Get very wet'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_100', question: 'Which material would be best for a cooking pot?', options: ['Paper', 'Metal', 'Cotton', 'Sponge'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },

  // SEASONS & WEATHER - Seasons (12 questions)
  { id: 'y1_sci_101', question: 'How many seasons are there in a year?', options: ['2', '3', '4', '5'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_102', question: 'The four seasons are:', options: ['Winter, Summer, Autumn, Spring', 'Monday, Tuesday, Wednesday, Thursday', 'Red, Blue, Green, Yellow', 'North, South, East, West'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_103', question: 'In which season do leaves fall from trees?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_104', question: 'Which season is usually the coldest?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], correctAnswer: 3, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_105', question: 'Which season is usually the warmest?', options: ['Winter', 'Summer', 'Autumn', 'Spring'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_106', question: 'In which season do flowers start to bloom?', options: ['Winter', 'Spring', 'Autumn', 'Never'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_107', question: 'What do we wear in winter to keep warm?', options: ['T-shirt and shorts', 'Swimming costume', 'Coat, hat, and gloves', 'Nothing'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_108', question: 'What might you do in summer?', options: ['Build a snowman', 'Go to the beach', 'Rake autumn leaves', 'Plant spring flowers'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_109', question: 'Trees lose their leaves in:', options: ['Spring', 'Summer', 'Autumn', 'Never'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_110', question: 'The season after winter is:', options: ['Autumn', 'Summer', 'Spring', 'Winter again'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_111', question: 'Days are longest in:', options: ['Winter', 'Summer', 'Autumn', 'They are always the same'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_112', question: 'In which season might you see snow?', options: ['Summer', 'Spring', 'Winter', 'Never'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },

  // SEASONS & WEATHER - Weather (13 questions)
  { id: 'y1_sci_113', question: 'What is weather?', options: ['The time of day', 'What it is like outside', 'A type of food', 'A season'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_114', question: 'When water falls from clouds, it is called:', options: ['Wind', 'Sunshine', 'Rain', 'Thunder'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_115', question: 'What do we call frozen rain?', options: ['Wind', 'Snow', 'Sunshine', 'Fog'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_116', question: 'When the air moves, we call it:', options: ['Rain', 'Wind', 'Snow', 'Clouds'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_117', question: 'On a sunny day, we can see the:', options: ['Moon', 'Sun', 'Stars', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_118', question: 'Clouds are made of tiny drops of:', options: ['Ice cream', 'Water', 'Sand', 'Rock'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_119', question: 'What should we wear on a rainy day?', options: ['Sunglasses and shorts', 'A raincoat or umbrella', 'Nothing', 'Winter coat'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_120', question: 'A weather diary helps us:', options: ['Forget the weather', 'Record what the weather is like each day', 'Play games', 'Sleep'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_121', question: 'We can use symbols to show:', options: ['Our names', 'Different types of weather', 'Our age', 'Our friends'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_122', question: 'What is a rainbow?', options: ['A type of cloud', 'Coloured light in the sky after rain', 'A type of wind', 'A type of snow'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_123', question: 'A thermometer measures:', options: ['Time', 'Temperature', 'Wind', 'Rain'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_124', question: 'When it is cloudy, the sun is:', options: ['Gone forever', 'Hidden behind clouds', 'Broken', 'Sleeping'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_125', question: 'Thunder is the sound made during a:', options: ['Sunny day', 'Storm', 'Rainbow', 'Snowy day'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // EARTH & SPACE (INTRODUCTORY) (15 questions)
  { id: 'y1_sci_126', question: 'The bright star we see during the day is called the:', options: ['Moon', 'Sun', 'Earth', 'Mars'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_127', question: 'We live on planet:', options: ['Mars', 'Moon', 'Earth', 'Sun'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_128', question: 'The Moon can be seen in the:', options: ['Day only', 'Night sky', 'Never', 'Only in winter'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_129', question: 'When it is daytime, we can see the:', options: ['Moon only', 'Sun', 'Stars only', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_130', question: 'When it is night-time, the Sun:', options: ['Disappears forever', 'Is still there but we can\'t see it', 'Turns into the Moon', 'Falls down'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_131', question: 'Day happens when:', options: ['Our part of Earth faces away from the Sun', 'Our part of Earth faces the Sun', 'The Moon is out', 'It is cold'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_132', question: 'Night happens when:', options: ['Our part of Earth faces the Sun', 'Our part of Earth faces away from the Sun', 'The Sun goes to sleep', 'The Moon comes'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_133', question: 'The Sun gives us:', options: ['Darkness and cold', 'Light and warmth', 'Only cold', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_134', question: 'Should we look directly at the Sun?', options: ['Yes, it is safe', 'No, it can hurt our eyes', 'Yes, it helps us see', 'Only sometimes'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_135', question: 'The Moon is:', options: ['A star', 'A planet', 'A natural satellite of Earth', 'The Sun'], correctAnswer: 2, difficulty: 'hard', xpReward: 20 },
  { id: 'y1_sci_136', question: 'Stars twinkle in the:', options: ['Daytime', 'Night sky', 'Never', 'Only in summer'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_137', question: 'The Sun is important because:', options: ['It gives us light and helps plants grow', 'It is pretty', 'It is small', 'It is cold'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_138', question: 'At night, it is dark because:', options: ['The Sun is facing our part of Earth', 'The Sun is not facing our part of Earth', 'There is no Sun', 'The Moon blocks the Sun'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_139', question: 'How long does it take for day and night to happen?', options: ['1 hour', '12 hours', '24 hours', '1 week'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_140', question: 'The Moon does not make its own light. It reflects light from the:', options: ['Earth', 'Stars', 'Sun', 'Clouds'], correctAnswer: 2, difficulty: 'hard', xpReward: 20 },

  // LIGHT & DARK (15 questions)
  { id: 'y1_sci_141', question: 'Light helps us:', options: ['Sleep', 'See things', 'Hear sounds', 'Smell'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_142', question: 'When there is no light, it is:', options: ['Bright', 'Dark', 'Loud', 'Quiet'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_143', question: 'Which of these gives light?', options: ['A rock', 'A lamp', 'A book', 'A chair'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_144', question: 'The Sun is a source of:', options: ['Darkness', 'Light', 'Sound', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_145', question: 'A torch gives out:', options: ['Water', 'Light', 'Food', 'Wind'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_146', question: 'During the day, the main source of light is the:', options: ['Moon', 'Stars', 'Sun', 'Lamp'], correctAnswer: 2, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_147', question: 'At night, we can use these to see:', options: ['Nothing', 'Lamps, candles, torches', 'Only our hands', 'Trees'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_148', question: 'When it is dark, it is harder to:', options: ['Sleep', 'See things', 'Close our eyes', 'Think'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_149', question: 'A candle gives out:', options: ['Darkness', 'Light', 'Cold', 'Wind'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_150', question: 'To stay safe in the dark, we should:', options: ['Run around quickly', 'Use a light or hold an adult\'s hand', 'Close our eyes', 'Hide'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_151', question: 'Light travels in:', options: ['Circles', 'Straight lines', 'Zigzags', 'Spirals'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_152', question: 'We see things when light:', options: ['Disappears', 'Bounces off them into our eyes', 'Stays still', 'Turns into sound'], correctAnswer: 1, difficulty: 'hard', xpReward: 20 },
  { id: 'y1_sci_153', question: 'Reflective clothing helps us stay safe because:', options: ['It is pretty', 'It reflects light so we can be seen', 'It keeps us warm', 'It is soft'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_154', question: 'Which object does NOT give its own light?', options: ['The Sun', 'A lamp', 'The Moon', 'A candle'], correctAnswer: 2, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_155', question: 'A shadow is formed when:', options: ['Light passes through everything', 'An object blocks light', 'It is daytime', 'We close our eyes'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },

  // SOUND (INTRODUCTORY) (12 questions)
  { id: 'y1_sci_156', question: 'We hear sounds with our:', options: ['Eyes', 'Ears', 'Nose', 'Hands'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_157', question: 'A loud sound is:', options: ['Very quiet', 'Very noisy', 'Silent', 'Invisible'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_158', question: 'A quiet sound is:', options: ['Very loud', 'Soft and gentle', 'Always scary', 'Always happy'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_159', question: 'Which of these makes a sound?', options: ['A drum', 'A picture', 'Silence', 'Darkness'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_160', question: 'A bell makes a sound when you:', options: ['Look at it', 'Ring it', 'Smell it', 'Hide it'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_161', question: 'Musical instruments make:', options: ['Light', 'Sounds', 'Food', 'Water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_162', question: 'The opposite of loud is:', options: ['Bright', 'Quiet', 'Fast', 'Big'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_163', question: 'Sounds are made when things:', options: ['Stay completely still', 'Vibrate or move', 'Disappear', 'Sleep'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_164', question: 'We can make sounds by:', options: ['Being silent', 'Clapping, singing, tapping', 'Sleeping', 'Staying still'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_165', question: 'Which animal makes a "moo" sound?', options: ['Dog', 'Cow', 'Cat', 'Bird'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_166', question: 'When you pluck a guitar string, it:', options: ['Stays still', 'Vibrates and makes sound', 'Breaks', 'Disappears'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_167', question: 'Sounds travel through:', options: ['Nothing', 'Air', 'Only water', 'Only space'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },

  // HEALTH & LIVING THINGS (15 questions)
  { id: 'y1_sci_168', question: 'Which food group includes apples and bananas?', options: ['Vegetables', 'Fruits', 'Meat', 'Dairy'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_169', question: 'Which of these is a vegetable?', options: ['Apple', 'Carrot', 'Bread', 'Milk'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_170', question: 'Eating a variety of foods helps us:', options: ['Get sick', 'Stay healthy and strong', 'Feel tired', 'Grow weaker'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_171', question: 'Exercise means:', options: ['Sleeping all day', 'Moving our body and being active', 'Eating sweets', 'Watching TV'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_172', question: 'Running, jumping, and playing help us:', options: ['Get weak', 'Stay fit and healthy', 'Feel sad', 'Get sick'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_173', question: 'We should wash our hands before:', options: ['Going to sleep', 'Eating', 'Playing', 'Running'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_174', question: 'Brushing our teeth keeps them:', options: ['Dirty', 'Clean and healthy', 'Weak', 'Gone'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_175', question: 'Water is important because:', options: ['It makes us sick', 'It keeps our body hydrated', 'It is colourful', 'It is sweet'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_176', question: 'What should we do if we feel unwell?', options: ['Ignore it', 'Tell an adult', 'Run around', 'Eat sweets'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_177', question: 'Wearing a helmet when cycling helps:', options: ['Make us faster', 'Protect our head', 'Make us look funny', 'Nothing'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_178', question: 'To stay safe near roads, we should:', options: ['Run into the road', 'Hold an adult\'s hand and look both ways', 'Close our eyes', 'Play in the road'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_179', question: 'Living things can:', options: ['Grow, eat, and move', 'Never change', 'Live without air', 'Live without water'], correctAnswer: 0, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_180', question: 'Non-living things do NOT:', options: ['Grow or eat', 'Exist', 'Have a shape', 'Have a colour'], correctAnswer: 0, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_181', question: 'Is a rock living or non-living?', options: ['Living', 'Non-living', 'Sometimes living', 'It depends'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_182', question: 'Is a tree living or non-living?', options: ['Non-living', 'Living', 'Sometimes living', 'Never living'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // SCIENTIFIC VOCABULARY (10 questions)
  { id: 'y1_sci_183', question: 'What does "observe" mean?', options: ['To sleep', 'To watch carefully', 'To run', 'To eat'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_184', question: 'What does "sort" mean?', options: ['Mix everything up', 'Put things into groups', 'Throw away', 'Break things'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_185', question: 'What does "compare" mean?', options: ['Ignore things', 'Look at how things are similar and different', 'Break things', 'Hide things'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_186', question: 'What does "predict" mean?', options: ['Look backwards', 'Guess what will happen next', 'Give up', 'Forget'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_187', question: 'What does "measure" mean?', options: ['Guess the size', 'Find out the size or amount', 'Break something', 'Colour something'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_188', question: '"Transparent" means:', options: ['Cannot see through', 'Can see through', 'Very hard', 'Very soft'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_189', question: '"Waterproof" means:', options: ['Soaks up water', 'Water cannot go through', 'Dissolves in water', 'Made of water'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_190', question: 'What does "classify" mean?', options: ['Make a mess', 'Group things by their features', 'Throw things away', 'Hide things'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_191', question: 'A "habitat" is:', options: ['A type of food', 'Where an animal lives', 'A type of plant', 'A season'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_192', question: '"Senses" help us:', options: ['Sleep', 'Learn about the world around us', 'Fly', 'Swim'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },

  // SCIENCE INVESTIGATIONS & ACTIVITIES (8 questions)
  { id: 'y1_sci_193', question: 'In a science experiment, we should:', options: ['Guess and not test', 'Try things out and observe what happens', 'Give up quickly', 'Not pay attention'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_194', question: 'A prediction is:', options: ['What already happened', 'What we think will happen', 'What never happens', 'What we ate'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_195', question: 'When we do an experiment, we should record:', options: ['Nothing', 'What we observe and find out', 'Only our name', 'Random things'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_196', question: 'Sorting objects by size means putting:', options: ['Big and small together', 'Big ones together and small ones together', 'Everything in a pile', 'Nothing anywhere'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_197', question: 'A simple table helps us:', options: ['Sleep', 'Organize and show our results', 'Play', 'Eat'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_198', question: 'What question could we investigate? "What happens to ice when..."', options: ['We forget it', 'It gets warm', 'We hide it', 'We paint it'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 },
  { id: 'y1_sci_199', question: 'When things change, a good scientist:', options: ['Ignores it', 'Observes and records the change', 'Gives up', 'Forgets about it'], correctAnswer: 1, difficulty: 'easy', xpReward: 10 },
  { id: 'y1_sci_200', question: 'Patterns in science are things that:', options: ['Never happen', 'Happen again and again', 'Happen once', 'Are random'], correctAnswer: 1, difficulty: 'medium', xpReward: 15 }
];
